### ISSUE TITLE
定位问题

### ISSUE THREAD

**Issue by NodeList** [qiuxiang/react-native-amap3d#1]
安卓权限已获取，无法获取到当前定位信息，locationEnabled已设置为true，onLocation事件，nativeEvent的值为 0。

**Comment by qiuxiang** [comment]
那是因为 Key 的问题，高德地图 SDK 需要正确的配置 Key 才能进行定位，详见
 http://lbs.amap.com/api/android-sdk/guide/create-project/get-key。

**Comment by NodeList** [comment]
果然，我记得修改过了key，不知道什么时候覆盖了。感谢。(′⌒`)

**Comment by fanyongbing** [comment]
定位点会自己乱动，这是什么情况？wifi，4G都会 @qiuxiang

**Comment by qiuxiang** [comment]
这是 sdk 的问题，之前用高德地图的时候就发现了，因为基于 wifi 和 基站的定位是不准的，误差大概在 50 米左右，nativeEvent 里有返回定位精度。

如果需要更精准的定位，只能是 GPS，也就是在开阔的室外才行，精度大概在3米左右，基本就不会出现定位漂移的问题。
