### ISSUE TITLE
老哥，xcode提示AMapFoundationKit/AMapFoundationKit.h找不到，frameworks下面的libPods-xxx.a也找不到，，我看你的例子中frameworks找得到，都是按照你的步骤来的，RN版本是0.44.3

### ISSUE THREAD

**Issue by webLiu** [qiuxiang/react-native-amap3d#10]
老哥，xcode提示AMapFoundationKit/AMapFoundationKit.h找不到，frameworks下面的libPods-xxx.a也找不到，红色的，我看你的例子中frameworks找得到，都是按照你的步骤来的，RN版本是0.44.3，请问我哪里弄错了

**Comment by qiuxiang** [comment]
你的 Podfile 怎么写的？

**Comment by webLiu** [comment]
platform :ios, '8.0'

target ‘Map’ do
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspaces => [
    'jschelpers_legacy',
  ]
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'
end

**Comment by webLiu** [comment]
![6ed63a8e-a74b-4b65-b590-b81bad27ea59](https://user-images.githubusercontent.com/12458173/28238957-5995e3d4-6992-11e7-8d65-942638ffe25f.png)
![422b644d-a3c2-47a5-a901-e7836314f1b5](https://user-images.githubusercontent.com/12458173/28238958-599aa716-6992-11e7-8163-9f84af96d1fa.png)

**Comment by qiuxiang** [comment]
RN 0.45 以下 Podfile 要写成
```ruby
platform :ios, '8.0'

target 'Map' do
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/'
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'
end
```

**Comment by webLiu** [comment]
改过了，但是还是没有生成libPods-xxx.a文件，那个AMapFoundationKit/AMapFoundationKit.h还是找不到，求老哥帮忙看看T_T。请问老哥你现在新建项目，pod install不会报我这个错误嘛？

**Comment by qiuxiang** [comment]
不会，而且新建的项目应该是 RN 0.46 才对

**Comment by webLiu** [comment]
额，那我新建一个0.46项目看看，因为0.45在ios上面跑不起来，所以还是用的0.44，在网上也没有找到解决这个问题的办法，请问老哥为什么RN0.45 ios跑不起来

**Comment by qiuxiang** [comment]
0.45 我也是测试过的，并没有跑不起来

**Comment by webLiu** [comment]
0.46可以引入AMapFoundationKit/AMapFoundationKit.h，但是0.45和0.46新建的项目跑不起来，老哥请问这是怎么回事，百度上面解决办法都是换回0.44.3版本，我也是醉了

**Comment by qiuxiang** [comment]
跑不起来是什么个情况？

**Comment by webLiu** [comment]
就是RN0.45，需要下载boost编译，不然ios run不起来，boost被墙了，很好奇老哥你为啥可以跑起来

**Comment by qiuxiang** [comment]
哦，我记起来了，确实有这么回事，有几个依赖要下载，我当时也出问题，不过不是 boost 而是另一个。用代理就可以了。

**Comment by webLiu** [comment]
老哥可以加个联系方式吗，现在跑不起来有点麻烦0.46版本，一运行报了50多个错误，现在公司有个新项目需要用到地图，很急T_T

**Comment by qiuxiang** [comment]
你可以用邮箱联系我，但我也不是特别有时间

**Comment by webLiu** [comment]
下载替换boost，已经可以了

**Comment by webLiu** [comment]
老哥你好，我新建了一个0.46项目，然后在ios下  pod install，结果还是那个错误
![abaf9ef8-40f3-4ef5-8691-5ee3d30cd8be](https://user-images.githubusercontent.com/12458173/28240687-9a37742c-69b8-11e7-9690-ed6c6f656020.png)

**Comment by qiuxiang** [comment]
<img width="1392" alt="screen shot 2017-07-16 at 12 13 35 am" src="https://user-images.githubusercontent.com/1709072/28240879-efa12d38-69bb-11e7-8320-e23aa79a027e.png">

你的 Pods target 下面的 Pods 有 AMap3DMap 和 AMapFoundation 吗

**Comment by webLiu** [comment]
![image](https://user-images.githubusercontent.com/12458173/28241201-8ee332fa-69c2-11e7-9ff8-835a00e7cc6b.png)

**Comment by webLiu** [comment]
我这里也有，但是还是not found
![image](https://user-images.githubusercontent.com/12458173/28241237-2faa955c-69c3-11e7-800d-f4d54aac38ed.png)

**Comment by qiuxiang** [comment]
那我就没办法了，太奇怪了，同样是 pod 安装的依赖，看起来 react-native 没问题，但 AMap3D 却无法使用。

我也新建项目测试过，并没有问题。估计你需要自己看看 Build Settings 到底有什么地方没设置正确。

**Comment by webLiu** [comment]
请问可以 手动配置吗？Build Settings要设置哪里我也不知道额，唉

**Comment by webLiu** [comment]
老哥麻烦发一份0.45以上集成你这个插件的项目给我可以不，我对比一下，我邮箱1125075101@qq.com,谢谢

**Comment by qiuxiang** [comment]
当然可以手动配置，参考 https://lbs.amap.com/api/ios-sdk/guide/create-project/manual-configuration
只是因为太麻烦，我自己都没试过。

**Comment by qiuxiang** [comment]
我直接发在这里吧，[RNAMap3D.zip](https://github.com/qiuxiang/react-native-amap3d/files/1150502/RNAMap3D.zip)。

为了减少文件体积，我把 Pods 目录和 node_modules 删掉了，你解压后，重新 npm i 和 pod install。

**Comment by webLiu** [comment]
好的，谢谢

**Comment by webLiu** [comment]
醉了，你发给我的RN项目就可以找到<AMapFoundationKit/AMapFoundationKit.h>，运行起来地图也可以看到，我新建的app咋就不行额

**Comment by qiuxiang** [comment]
我就是 pod install 就可以了。

一方面，你可能要再新建项目试试；另一方面，为了找到问题所在，如果你需要核查下 Build Settings。

**Comment by hhahh2011** [comment]
我想你应该是执行了 react-native link 这个指令了，这个指令会给你的项目添加额外的header 的查找目录，所以你这里查找不到，你要到你主项目目标里面 删除 才可以。
![image](https://user-images.githubusercontent.com/3818363/28257380-f7959636-6afc-11e7-9450-8b1d05b79972.png)

**Comment by ym1058117490** [comment]
react-native run-ios时报错
node_modules/react-native-amap3d/ios/AMapView.h:1:9: fatal error: 'MAMapKit/MAMapKit.h' file not found
#import <MAMapKit/MAMapKit.h>
        ^
1 error generated.

**Comment by qiuxiang** [comment]
@ym1058117490 没有正确配置吧

**Comment by qiuxiang** [comment]
经测试，对于 iOS 项目，如果运行了 `react-native link react-native-amap3d` 肯定会现上述错误。

其实我之前就有预感。。对 iOS 项目进行 link 很可能会导致编译出错，因为通过 `pod install` 已经成功安装了依赖，react-native link 会添加错误的引用。由于我没有实际去测试和说明而坑了大家。。

于是对于因为 link 而导致 iOS 项目编译失败，解决办法是 `react-native unlink react-native-amap3d`。

**Comment by SongZhaoJie** [comment]
@webLiu   哥们你解决没有呀，我也遇到了这个问题
