### ISSUE TITLE
最新RN0.50.2集成失败 'MAMapKit/MAMapKit.h' file not found

### ISSUE THREAD

**Issue by yuzhongyouqing** [qiuxiang/react-native-amap3d#101]
集成安卓没有问题，集成成功
集成IOS老是出现  'MAMapKit/MAMapKit.h' file not found 头文件找不到

我根据官网推送的pod 文件集成高德地图的
希望作者可以提供帮助一下!

AMapView.h文件出错

#import <MAMapKit/MAMapKit.h> //此处报错
@interface AMapView : MAMapView

@property(nonatomic, copy) RCTBubblingEventBlock onLocation;
@property(nonatomic, copy) RCTBubblingEventBlock onPress;
@property(nonatomic, copy) RCTBubblingEventBlock onLongPress;
@property(nonatomic, copy) RCTBubblingEventBlock onStatusChange;
@property(nonatomic, copy) RCTBubblingEventBlock onStatusChangeComplete;

@property(nonatomic) BOOL loaded;
@property(nonatomic) MACoordinateRegion initialRegion;

@end

**Comment by qiuxiang** [comment]
肯是配置问题，自己先确定下步骤

**Comment by Kerence** [comment]
原因是没有找到MAMapkit.framework
解决方法是把MAMapKit.framework下载下来拖到项目目录文件夹（防止丢失）
然后打开AMap3D.xcoderpoj项目，Build Settings->Framework Search Paths 把MAMapKit.framework所在目录加进去就可以了

**Comment by st4allen** [comment]
@yuzhongyouqing 遇到类似的问题，安卓没问题iOS找不到头文件。有可能是使用react-native link的时候将iOS也link了。

<img width="268" alt="screen shot 2017-11-15 at 10 30 25 am" src="https://user-images.githubusercontent.com/26893249/32831322-3811f204-c9f8-11e7-9139-66fb74ba3238.png">

将pod外引入的3个文件移除再试试。

<img width="269" alt="screen shot 2017-11-15 at 10 18 09 am" src="https://user-images.githubusercontent.com/26893249/32831366-59f160ee-c9f8-11e7-9e67-026d46cf4513.png">

**Comment by qiuxiang** [comment]
可以明确地说，用了 cocoapods，是不能 react-native link 的。另一方面，如果非要用 react-natve link，高德地图 SDK 本身对系统库的依赖还是要手动配置，这是没办法集成到这个项目里的（如果有，那就是我孤陋寡闻了）。

关于这个问题，之前已经讨论太多了。
