### ISSUE TITLE
请问iOS端的定位结果中可以返回移动速度么

### ISSUE THREAD

**Issue by ismjt** [qiuxiang/react-native-amap3d#102]
请问iOS端的定位结果中可以返回移动速度么？如果可以，需要怎么添加

**Comment by qiuxiang** [comment]
看文档是有速度的，我之后加上去看看

**Comment by ismjt** [comment]
@qiuxiang 果然不熟悉iOS开发就算看了文档也是没法自己加=_=   还是静候大神推更新吧
