### ISSUE TITLE
建议更新iOS使用教程

### ISSUE THREAD

**Issue by xuepx** [qiuxiang/react-native-amap3d#104]
在一个工程下，iOS和Android可同时使用
具体的
1. 安装

`npm i react-native-amap3d`

2. 备份ios/YOUR_ TARGET/project.pbxpro文件
3. react-native link react-native-amap3d
4. 回复之前备份的ios/YOUR_ TARGET/project.pbxpro文件
5. 在 ios 目录下新建文件 Podfile(如readme), 然后运行：

`$ pod install`

**Comment by qiuxiang** [comment]
link 的影响应该是开发者自己清楚并处理，我会考虑另外写一份更详细的安装文档
