### ISSUE TITLE
iOS 地图定位和小蓝点问题

### ISSUE THREAD

**Issue by etouyang** [qiuxiang/react-native-amap3d#105]
跑的例子中的demo,打开定位后,发现不显示蓝点地图不刷新;
真机断点调试, 走了onLocation事件, 并且console打印出了正确的经纬度;
但是地图就是没有刷新,仍旧在北京,而且小蓝点没有显示

**Comment by xuepx** [comment]
小蓝点在手机定位位置，没有看到代码里有依据用户位置自动移动的部分，调整你的Mapview初始位置在你所在地附近试试。

**Comment by qiuxiang** [comment]
打开定位不会移动定位点，但如定位成功，蓝点肯定是会有的

**Comment by etouyang** [comment]
正解,蓝点存在, 太远了...

**Comment by kevinchensd** [comment]
我的定位图标显示为：蓝色的纸飞机图标，而不是想要的小蓝点，这个怎么处理？
