### ISSUE TITLE
MapView.js中onStatusChangeComplete会返回什么数据？

### ISSUE THREAD

**Issue by zust-hh** [qiuxiang/react-native-amap3d#109]
`onStatusChangeComplete={
            (data) => {
              let point = JSON.stringify(data);
              alert(point)
            }
          }`
我写了一个这样的东西，报json.stringify cannot serialize cyclic structures错误，我想在每一次移动后获取当前中心的经纬度，请问怎么办

**Comment by zust-hh** [comment]
请您回复我一下吧。。。。

**Comment by qiuxiang** [comment]
`onStatusChangeComplete={ ({ nativeEvent }) => console.log(nativeEvent) }`

**Comment by xuepx** [comment]
mapView.onStatusChangeComplete(
{
            "zoomLevel": SOMELEVEL,
            "tilt": SOMETILT,
            "rotation": SOMEROTATION,
            "latitude": SOMELATITUDE,
            "longitude":SOMELONG,
            "latitudeDelta":SOMELATITDELTA,
           "longitudeDelta":SOMELONGDELTA
 });
