### ISSUE TITLE
有两点的导航功能？

### ISSUE THREAD

**Issue by zhubaobao** [qiuxiang/react-native-amap3d#11]

**Comment by qiuxiang** [comment]
目前没有

**Comment by zhangweihu** [comment]
大概什么时候可以有呢？请问

**Comment by qiuxiang** [comment]
导航功能的实现还挺花时间的，目前我的项目没有这个需求，短期内不太有时间做这个功能。

**Comment by zhangweihu** [comment]
@qiuxiang 好的谢谢您的回复！

**Comment by fanyongbing** [comment]
单独的定位方法什么时候实现啊  坐等中

**Comment by qiuxiang** [comment]
@fanyongbing 短期内也不太有时间。

**Comment by dragoneight** [comment]
@qiuxiang  请问是否可以加入关键字检索POI方法呢，通过POI搜索，完成找餐馆、找景点、找厕所等等的功能。只是提个意见 :)

**Comment by qiuxiang** [comment]
@dragoneight 有想过，但其实高德地图已经提供了[Web服务 API](https://lbs.amap.com/api/webservice/summary/)，实在没有理由再从 native 做接口封装。

**Comment by qiuxiang** [comment]
基本的导航功能已实现，只是，还不够完善
