### ISSUE TITLE
离线地图能否支持导入地图包的方式来加载

### ISSUE THREAD

**Issue by fangkyi03** [qiuxiang/react-native-amap3d#110]
离线地图能否支持导入地图包的方式来加载 因为我这边全程内网 但是可以支持把地图包放本地内网服务器上面 但是不能支持连接外网 所以想问一下 在这种完全无法联网的情况下 如何解决这个问题

**Comment by qiuxiang** [comment]
这已经不是一般问题了，还是自己想办法吧，我在实现离线地图接口的时候有看到过设置下载链接的接口，但怎么用就不确定了。
