### ISSUE TITLE
marker 中的信息窗体显示位置

### ISSUE THREAD

**Issue by ibmsoft** [qiuxiang/react-native-amap3d#111]
在android 平台上 marker 中的信息窗体默认显示在图标的上面，有什么方法能让弹出的信息窗体显示在最底部？

**Comment by qiuxiang** [comment]
是有个 offset 接口可以设置 InfoWindow 相对 Marker 的位置，但现在还没有实现这个接口，如果是自定义 View 的话，应该可以用 RN 的布局功能调整自定义 InfoWindow 的位置。

**Comment by ibmsoft** [comment]
感谢你的及时回复，我试了不行,参考demo中的，设置后，弹出窗体不知道跑哪里了
    customInfoWindow: {
        // zIndex:1000000,
        position:'absolute',
        bottom: 0,
        left:0,
        right:0,
        backgroundColor: '#8bc34a',
        // padding: 10,
        borderRadius: 10,
        // elevation: 4,
        borderWidth: 2,
        borderColor: '#689F38',
 
    },

**Comment by qiuxiang** [comment]
最好不要用 `position:'absolute'`

**Comment by qiuxiang** [comment]
你可以看看 examples 是怎么写的 https://github.com/qiuxiang/react-native-amap3d/blob/master/example/src/examples/marker.js

**Comment by ibmsoft** [comment]
各种方式都试了，还是不行

**Comment by qiuxiang** [comment]
examples 里的示例总不会有问题吧

**Comment by ibmsoft** [comment]
example 里没有问题，我就是想实现弹出窗口自定义位置，比如显示在最下面

**Comment by qiuxiang** [comment]
如果你是要固定在 MapView 的某个位置，而不随地图的拖动而移动，那么就不应该用 InfoWindow

**Comment by kevinchensd** [comment]
可以尝试写一个独立的块，固定位置的，在Marker的onpress事件中，触发显示这个块，并传入marker的引用；
