### ISSUE TITLE
lockedToScreen和lockedScreenPoint

### ISSUE THREAD

**Issue by etouyang** [qiuxiang/react-native-amap3d#112]
业务场景需要做成微信一样的marker标注点不动; 上面两个童鞋提的issues我也看了
使用onStatusChange事件可以获取到实时位置,但是赋值给marker后,虽然marker在动,但是非常卡顿;
官方的ios demo中,设置lockedToScreen以及lockedScreenPoint可以保证marker锁定在屏幕上,我改了一下你的ios源码,发现始终无效,没有发现你源码中哪里有问题,想请问一下,是哪个设置导致这两个属性失效了

**Comment by qiuxiang** [comment]
我之后写一个 demo 看看

**Comment by qiuxiang** [comment]
我试了，确实有问题，只是要等有时间了才能继续研究
