### ISSUE TITLE
通过State重新渲染地图点位后，老的点位不会清除掉，并且点位会随着地图拖动而移动

### ISSUE THREAD

**Issue by blackkey520** [qiuxiang/react-native-amap3d#116]
"react": "16.0.0",
"react-native": "0.50.4",
"react-native-amap3d": "^0.8.0",
更新到最新版本后，通过state重新渲染地图上的点位，老的点位不会被清除掉。新加的点位会随着地图的移动而移动。
之前我提过类似的bug，之前解决了。但是现在又出现了。
[这是链接](https://github.com/qiuxiang/react-native-amap3d/issues/25) 
代码如下

 ` import React, {Component} from 'react'
import {StyleSheet, Image, View} from 'react-native'
import {MapView, Marker} from 'react-native-amap3d'

export default class MarkerExample extends Component {
  static navigationOptions = {
    title: '添加标记',
  }

  state = {
    list: [1, 2, 3, 4, 5, 6],
  }

  _renderImageMarker = () =>
    <View style={styles.customIcon}>
      <Image style={styles.customIcon} source={require('../../images/flag.png')}/>
    </View>

  _update = () => this.setState({list: [11, 12, 13, 14, 15, 16]})

  render() {
    return <MapView style={StyleSheet.absoluteFill} onPress={this._update}>
      {this.state.list.map(item => <Marker
          key={item}
          icon={this._renderImageMarker}
          title={'Marker' + item}
          coordinate={{
            latitude: 39.906901 + (item * 0.01),
            longitude: 116.397972 + (item * 0.01),
          }}
        />
      )}
    </MapView>
  }
}

const styles = StyleSheet.create({
  customIcon: {
    width: 40,
    height: 40,
  },
})`

**Comment by qiuxiang** [comment]
我看了，似乎是 ReactView 的实现细节有变，稍微改了下代码，现在，新增和删除没问题了，但还是不能完全解决拖动的问题。

**Comment by only4ly** [comment]
这个bug我也遇到了。。。
请问解决了嘛

**Comment by qiuxiang** [comment]
暂时没时间，或许这个周末有时间看看，但我不能保证就能解决，自定义 View 的实现本身就是一个 hack，慎用。

**Comment by only4ly** [comment]
ios平台下出现setState 之后 marker无法删除的情况，同样的代码android端正常工作。。。。
麻烦大佬能不能看看，没有使用自定义icon

**Comment by qiuxiang** [comment]
无法删除的问题，我有修正过，只是还没发布新版本
