### ISSUE TITLE
nodeHandle.getHostNode()

### ISSUE THREAD

**Issue by godeadasdf** [qiuxiang/react-native-amap3d#118]
反复快速进出带有marker的界面时，就会概率性复现此问题
![screenshot_20171201-103628](https://user-images.githubusercontent.com/13552859/33465607-c5802c68-d683-11e7-9fdd-42b37e330bbb.png)

**Comment by qiuxiang** [comment]
你的 Marker 是用了自定义 View 吗？

**Comment by godeadasdf** [comment]
没有额外的自定义就是直接使用了库中原有的

**Comment by qiuxiang** [comment]
可以肯定的是，只有设置了 `Marker#icon` 才可能调用 `_sendCommand`。这是用于更新自定义 View 的方法。
