### ISSUE TITLE
大佬求助，0.44.3 Android 编译失败

### ISSUE THREAD

**Issue by ittianyu** [qiuxiang/react-native-amap3d#12]
```
* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86/libRoadLineRebuildAPI.so
	File1: C:\Users\86839\.gradle\caches\modules-2\files-2.1\com.amap.api\3dmap\5.2.1\6e52e58811a7d3f04a23cd8233a505f79008c481\3dmap-5.2.1.jar
	File2: K:\source_code\ReactNative\pointers\node_modules\react-native-amap3d\android\build\intermediates\bundles\default\jni
```

**Comment by qiuxiang** [comment]
这里错误是 `lib/x86/libRoadLineRebuildAPI.so` 重复了，我之前也遇到过，但不记得是因为什么了，甚至不记得怎么解决了。。

首先你要想，是什么导致同时引入了两个文件呢，然后，尝试 clean 项目，删掉 node_modules/react-native-amap3d 里面的 build。

**Comment by ittianyu** [comment]
清理和删除几次了没用，新建项目也一样，大佬，我好绝望，下了你的demo也是一样的结果

**Comment by qiuxiang** [comment]
example 也不能运行吗？

**Comment by ittianyu** [comment]
我把你的 java 和 kt 文件放到 app 模块下后，竟然就通过了，还有这种操作？

**Comment by qiuxiang** [comment]
但这并没有解决问题，搜索 “Duplicate files copied” 结果还挺多的，但也只是提了解决办法，而没有找到一个完整的解释，为什么会出现这个问题。

**Comment by qiuxiang** [comment]
手机操作一不小心手抖就关掉了。。

之前有人提的一个 PR https://github.com/qiuxiang/react-native-amap3d/pull/4/files#diff-15f694d688fe6360b46c5b8399a7eca8

其中 pickFirst 似乎是为了解决这个问题的，但是
 PR 提出者并没有做出解释。

**Comment by ittianyu** [comment]
大佬能再加个属性或方法吗，做国际化用

Android、iOS 2D 地图 SDK 支持展示国内英文地图。
Android 可参考：setMapLanguage(java.lang.String language)  方法设置地图显示的语言
iOS 可参考： MAMapView 类的  枚举参数：MAMapLanguageEn  设置地图显示的语言

**Comment by qiuxiang** [comment]
应该没什么问题，我去看看文档

**Comment by ittianyu** [comment]
好的，非常感谢

**Comment by ittianyu** [comment]
用 demo 测试了一下，加上之后就编译通过了
```
    packagingOptions {
        pickFirst('lib/*/libRoadLineRebuildAPI.so')
        pickFirst('lib/*/libGNaviUtils.so')
        pickFirst('lib/*/libGNaviData.so')
        pickFirst('lib/*/libGNaviMap.so')
        pickFirst('lib/*/libGNaviMapex.so')
        pickFirst('lib/*/libGNaviSearch.so')
    }
```

**Comment by qiuxiang** [comment]
我在搜索“Duplicate files copied”的时候别人是有提到用 picFirst，我很想知道 gradle 为什么会重复复制这些 .so，但我这里没有再出现过这个问题。

**Comment by ittianyu** [comment]
gradle 版本不一样，你看你用的是 3.5，我用的 3.3，也试了一下 4.0，都是报错，你换个版本试试

**Comment by ittianyu** [comment]
另外我发现 AMap3DPackage有 Java 和 kotlin 版本，而且还在同一个包下，个人觉得最好名字区别一下，理论上应该是类冲突了。

**Comment by qiuxiang** [comment]
对的，是冲突了，但不影响 kt 的编译，我也不想留这个文件的，因为这个问题：https://github.com/qiuxiang/react-native-amap3d/issues/3#issuecomment-313073250

**Comment by qiuxiang** [comment]
你上面提到的国际化支持，我看了文档，只有 2D 地图才支持，3D 地图并不支持。

**Comment by ittianyu** [comment]
好的，感谢
