### ISSUE TITLE
rn0.49.5 ios 编译报错

### ISSUE THREAD

**Issue by gongwenyi** [qiuxiang/react-native-amap3d#121]
rn0.49.5
部署方式使用手动部署
执行了link，iOS编译报错
<img width="1150" alt="qq20171204-234532 2x" src="https://user-images.githubusercontent.com/12042294/33561411-8d09621a-d94d-11e7-8a36-7d894b3f2056.png">

**Comment by qiuxiang** [comment]
既然你都说运行了 link，而且是用了 cocoapods 的情况下，那肯定会出错呀

**Comment by gongwenyi** [comment]
我没有使用cocoapods，是按照高德地图文档手动部署的

**Comment by xuepx** [comment]
1yarn add
2git commit
3react-native link
4恢复ios里的文件到commit前
5pod install
6xcode打开iOS添加pod项目，还有一个-lreact-native-amap3d的编译选项（好像还有一些配置，总之处理完这个xcode的bug）
7这样iOS和安卓都可以了

发自我的 iPhone SE

**Comment by qiuxiang** [comment]
如果是自己配置的话，基本是要你自己解决了，因为我没有做过手动配置。基本上，会遇到的都是编译相关的问题，比如上面提示 no such of file，就应该确认路径是不是正确。
