### ISSUE TITLE
demo的定位有问题

### ISSUE THREAD

**Issue by jokunhe** [qiuxiang/react-native-amap3d#122]
直接下载demo  ,开启定位后定位不正确，到非洲去了。同时自己的项目也定位不准确。望指点

**Comment by qiuxiang** [comment]
确定高德 Key 配置没有问题？

**Comment by qiuxiang** [comment]
你是说这个项目的 example？

**Comment by xuepx** [comment]
是不是安卓，直接定位到经纬度0了，我真机测试有这个问题，不知道是哪的问题，定位有时为0。自己写的移动判断了是否为0，但是定位按钮就...

发自我的 iPhone SE

**Comment by jokunhe** [comment]
是的  就是这个项目的 example    我自己项目 用了这个库也是这样  会定位到国外

**Comment by Xuchunyan** [comment]
跟楼上一样的问题，定位不对

**Comment by qiuxiang** [comment]
如果用其他的定位模块呢？能不能获取到正确的定位？这个问题也没什么好讨论的了，这个库的接口调用肯定是没问题的，无非权限、Kek 的问题。

Key 的问题应该以 logcat 为准，如果 Key 不匹配，会有 error log 的，而不是看起来没问题就真的没问题。

**Comment by ys5678** [comment]
我也是用的这个demo，启用定位没有反应，用onLocation这个事件，可以打印出数据，但是地图没有变

**Comment by qiuxiang** [comment]
@ys5678 `onStatusChangeComplete `

**Comment by ys5678** [comment]
@qiuxiang 你好，我没表达清楚，我的意思是获取定位的API，不是用mapVIew的onStatusChangeComplete事件。高德地图有定位SDK，其实我是想问你封装了这个没？

**Comment by qiuxiang** [comment]
地图 SDK 只有被动的定位事件，如果需要更完整的定位功能，需要另外引入定位 SDK 并加以封装，因为已经有人在做了，在这个项目我暂时没有打算这么做。
