### ISSUE TITLE
android打包报错Java空指针

### ISSUE THREAD

**Issue by DIVIBEAR** [qiuxiang/react-native-amap3d#124]
android打包后出现
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
WARNING [Project: :app] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING: Project react-native-amap3d: provided dependencies can only be jars. com.facebook.react:react-native:aar:0.50.3 is an Android Library.
WARNING: Project react-native-amap3d: provided dependencies can only be jars. com.facebook.react:react-native:aar:0.50.3 is an Android Library.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-amap3d'.
> java.lang.NullPointerException (no error message)

**Comment by qiuxiang** [comment]
这些错误信息没什么参考价值呀

**Comment by DIVIBEAR** [comment]
我按照README.md方法一步步操作下来，然后运行安卓，react是16的，com.android.tools.build:gradle:1.2.3的，还需要什么信息我可以提供。

**Comment by qiuxiang** [comment]
官方默认的 com.android.tools.build:gradle:2.2.3 版本已经很低了，你的居然是 1.2.3？

**Comment by DIVIBEAR** [comment]
部分机型安卓5.0+不支持2.2.3，只能通过降低gradle来解决。

**Comment by qiuxiang** [comment]
com.android.tools.build:gradle 和具体的 Android 设备有什么关系 = =
