### ISSUE TITLE
setState改变后Marker不生效（数组减少）

### ISSUE THREAD

**Issue by jnzw1986** [qiuxiang/react-native-amap3d#125]
render() {
    return <View style={styles.body}>
      <MapView ref={ref => this.mapView = ref} style={styles.body}>

          {
              this.state.dataSource.map((item,i)=>this.renderExpenseItem(item,i))
          }

      </MapView>
</View>
  }

renderExpenseItem(dataItem , i) {
        key=`${i}${Date.now()}`
        var keyvalue =  `${i}${Date.now()}`
        console.log("_keyvalue=="+`${keyvalue}`);
        return <Marker
                key = {keyvalue}
              title='自定义 View'
              icon={() =>
                <View style={styles.customMarker}>
                  <Text style={styles.markerText}>{`${i}`+ "_title"}</Text>
                </View>
              }
              coordinate={dataItem}
            />
    }

  _changeNilAction = () => {
      this.setState({
          dataSource:[]
      })
  }

**Comment by qiuxiang** [comment]
这个问题我已经注意到了，和 #119 一个问题，之前解决过，现在不晓得是 RN 和 SDK 哪个升级导致的，我得过段时间有时间了才能好好研究怎么解决。

目前 `Marker#icon` 慎用。

**Comment by jnzw1986** [comment]
如果有更新，烦劳第一时间通知下，多谢。。
