### ISSUE TITLE
定位问题

### ISSUE THREAD

**Issue by wq13718048209** [qiuxiang/react-native-amap3d#126]
rn版本 0.50.4
错误是按照你提示的定位代码,然后地图显示出来了,后台打印的坐标一直是0,0. 一直定位不到自己的正确位置.

<MapView
                    style={StyleSheet.absoluteFill}
                    locationEnabled
                    locationInterval={10000}
                    distanceFilter={10}
                    onLocation={({nativeEvent}) =>
                        console.log(`${nativeEvent.latitude}, ${nativeEvent.longitude}`)}
                />

只是写了一个定位,其他什么都没写

**Comment by qiuxiang** [comment]
关于定位的问题，我觉得没什么好讨论的了，无非就是高德 Key 的匹配还有权限的问题，自己看 logcat。

**Comment by wq13718048209** [comment]
作者你好,我就是按照你的步骤一步一步集成的,然后地图一打开显示是北京,然后我点击那个定位按钮就去了非洲了. 高德地图那边我也是按着步骤来的,这个key匹配不上是什么原因呢?在AS上的logcat我也看了啊 什么错误都没有报,主要是我这边好几个朋友都用了你这个,都是同样的错误,都去了非洲,返回的坐标是0,0

**Comment by wq13718048209** [comment]
非常感谢 ,问题已经解决. 还有就是我可以拉您进我们的rn群吗 我们这个群很多小伙伴都是网上开源作品的作者,其中有很多也在用您这个组件.是个非常活跃的RN讨论群

**Comment by qiuxiang** [comment]
@wq13718048209 不怎么喜欢 QQ 群或微信群

**Comment by wq13718048209** [comment]
那好吧, 群里面都只是讨论技术. 还请教您一个问题, 如果用您这个组件,写一个app,是显示周围的停车场,然后选择后可以导航到那个停车场,可以办到吗?

**Comment by qiuxiang** [comment]
显示周围的点肯定可以做到，这个库的导航还没有足够完善，建议调用其他地图 app 来完成导航。
