### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by wq13718048209** [qiuxiang/react-native-amap3d#128]
Error:Execution failed for task ':app:prepareBigcarReactNativeAmap3dUnspecifiedLibrary'.
> Could not expand ZIP 'E:\xuexi\bigcar\node_modules\react-native-amap3d\android\build\outputs\aar\react-native-amap3d-release.aar'.
一直报这样的错误,请问该怎么办?

**Comment by qiuxiang** [comment]
`cd android && ./gradlew clean` 试试

**Comment by wq13718048209** [comment]
好的谢谢
