### ISSUE TITLE
报错 No type or protocol named 'MAMultiPointOverlayRendererDelegate'

### ISSUE THREAD

**Issue by jxintang** [qiuxiang/react-native-amap3d#129]
RN 版本 0.45.0
报错平台 iOS

我是通过pod install进行部署的，为什么会在AmapMultiPoint里面报错  
No type or protocol named 'MAMultiPointOverlayRendererDelegate'

![image](https://user-images.githubusercontent.com/5434292/33866166-fb4256dc-df2f-11e7-8117-c63ece31019d.png)
MAMultiPointOverlayRendererDelegate这个分明是高德本身的sdk，为什么会有这个报错

**Comment by qiuxiang** [comment]
确认没有 link，以防万一运行一下 `react-native unlink react-native-amap3d`。

可以肯定是配置问题，尝试在新项目里测试一遍。

**Comment by jxintang** [comment]
unlink试过了，之前并没有link过
找到原因了，进行了pod update就可以了，怀疑是地图的sdk没有更新导致的
