### ISSUE TITLE
自定义marker出错

### ISSUE THREAD

**Issue by zust-hh** [qiuxiang/react-native-amap3d#130]
RN版本：0.51

我想要在marker上显示一个数字，原生的方法不支持，于是我就自定义marker的icon
`icon={() =>
                <View style={styles.customMarker}>

                  <Image source={require('../public/images/marker.png')} style={{width:30,height:30}}/>

                  <Text style={styles.markerText}>{index + 1}</Text>

                </View>

              }`
报错 width and height must > 0，这个View应该是有大小的呀，不知道怎么错的，求解答
或者告知我一个方法可以在marker上显示一个数字，谢谢

**Comment by qiuxiang** [comment]
看 example：https://github.com/qiuxiang/react-native-amap3d/blob/master/example/src/examples/marker.js#L76

自定义 View 慎用。

**Comment by zust-hh** [comment]
我看了example，example是可以实现的，但是他只能是平常的View，里面不能放Image，我想要一个image怎么办，那个image参数，是干什么的？传一个什么样的字符串？相对路径我试了不可以

**Comment by qiuxiang** [comment]
肯定是可以放 Image 的。

image 就是原生的图片，对于自定义 Marker 我个人是用 image 而不是 icon，因为更可靠，icon 的实现有已知的 bug。

**Comment by xuepx** [comment]
没有用image，用到了faicon
<Marker icon={()=>( <View style={styles.pins}> <FaIcon name='map-pin' style={[styles.dots, {color: 'green'}]}/> <Text>{idx + 1}#</Text> </View> )} title={`${idx}#`} coordinate={marker} />
没问题

发自我的 iPhone SE

**Comment by zust-hh** [comment]
@xuepx 您好，你用的这个FaIcon是什么组件里的

**Comment by qiuxiang** [comment]
除非能提供重现的方法，不然这个 issue 关掉了

**Comment by zhllucky** [comment]
@qiuxiang 你好  只要加了Text标签进去后就报错
`
icon={() =>
         <View style={styles.item}>
                  <Image style={styles.imgStyle} source={require('./images/mess.png')} />
                  {/* <Text style={{color: '#fff', height: 30, width: 30}}>40</Text> */}
                </View>
              }`

注释了Text这样就可以

**Comment by qiuxiang** [comment]
@zhllucky 什么样的错误？

**Comment by zhllucky** [comment]
@qiuxiang  width and height must > 0

**Comment by qiuxiang** [comment]
我知道出错的原因了，但我还是不知道什么时候可能导致这个问题，你的代码我无法重现。

**Comment by johanntony** [comment]
我也是遇到这个问题了啦
