### ISSUE TITLE
cocopod问题

### ISSUE THREAD

**Issue by ys5678** [qiuxiang/react-native-amap3d#132]
你好，我按你写的cocopod去配置，但是报错了。不知道怎么回事。
报错：
- `React/CxxBridge (from `../node_modules/react-native/`)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `React/CxxBridge (from `../node_modules/react-native/`)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
请问你遇到过这种问题吗？该怎么解决呢？我是第一次用cocoapod

**Comment by qiuxiang** [comment]
你的 RN 版本

**Comment by ys5678** [comment]
0.44.3

**Comment by qiuxiang** [comment]
不支持低于 0.47，如果你一定要用，不能保证帮你解决问题，对于现在的问题，你可以把 CxxBridge 去掉。

**Comment by ys5678** [comment]
哦哦，好的，那我再试试，谢谢！
