### ISSUE TITLE
marker自定义icon点击事件问题

### ISSUE THREAD

**Issue by only4ly** [qiuxiang/react-native-amap3d#135]
rn 0.51.0
ios平台
使用自定义icon点击时第一次点击可以触发点击事件，之后点击并不是每次点击都触发事件（大多数情况不触发）
已经测试过不使用自定义View时没有该问题

代码

// marker
<Marker
            infoWindowEnabled={false}
            icon={() => {
              return (
                <Animatable.View animation="zoomInUp">
                  <DisMarker size={100} disName='市北区' total={100} online={10} rocks={10} />
                </Animatable.View>
              )
            }}
            coordinate={{
              latitude: 39.91095,
              longitude: 116.37296,
            }}
            clickable={true}
            onPress={ this._onMarkerPress({marker:'hahhahahah'}) }
          />

// onpress
 _onMarkerPress = (marker) => {
    return function() {
      console.log('onPress', marker)
    }
  }

**Comment by only4ly** [comment]
找到规律了，点击marker之后我要点击一下地图，然后再次点击marker才会触发事件，一直点击marker，只会第一次触发事件

**Comment by qiuxiang** [comment]
如果我没有理解错的话，这不是 bug，iOS SDK 就是这样的行为。对于 iOS 我用的是 `didSelectAnnotationView` 这个方法，也就是说，只有 select 的时候才会触发。更准确的说，是从 deselect 到 select 的切换才会触发，在已经 select 的情况下，点 marker 是不会重复触发的。

所以，更准确的说，这是一个 `onSelect` 事件而不是 `onPress`，但为了和 android 统一，所以都叫 `onPress`。

你说不使用自定义 View 不会有这个“问题”，能确定？在实现上，有没有使用自定义 View 是没有任何差异的，我自己测试也是如此。

**Comment by only4ly** [comment]
嗯 这个问题目前不影响我使用，我想问一下ios安卓都存在的marker
