### ISSUE TITLE
RN 0.50 / 0.51版本 安卓编译报错

### ISSUE THREAD

**Issue by huanxsd** [qiuxiang/react-native-amap3d#136]
1、使用react-native init 方法，创建一个空项目
2、react-native run-android
结果：可以正常运行demo工程

3、npm i react-native-amap3d --save
4、react-native link
5、react-native run-android
结果：编译报错
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

React Native在 0.44.x版本可以正常编译通过
用0.50和0.51上的空项目，加入react-native-amap3d后，编译报错

**Comment by qiuxiang** [comment]
我重新运行了一次编译测试，并没有失败：https://travis-ci.org/qiuxiang/react-native-amap3d/jobs/319764885

编译问题最好先自己解决，况且，你提供的这个错误信息根本不能说明是这个库的问题。

**Comment by huanxsd** [comment]
找到原因了，不是这个库的问题。
我的项目依赖第三方库太多了，正好加上这个库后，方法超出安卓限制。导致编译失败。
我去掉多余的第三方库后，编译通过。
谢谢
