### ISSUE TITLE
能否使用自定义image作为marker图标

### ISSUE THREAD

**Issue by only4ly** [qiuxiang/react-native-amap3d#137]
rn：0.51.0
amp3d： 0.8.1

代码：
<Marker
          infoWindowEnabled={false}
          key={markerData.name + markerData.code}
          title={markerData.name + markerData.code}
          coordinate={markerData.postion}
          image={require('../assets/pic/company_logo.png')}
        />

我这个写法好像是会报错的，
example的例子我也没看出怎么使用自己的图片作为marker的icon

**Comment by qiuxiang** [comment]
报什么错？

**Comment by only4ly** [comment]
![img_2530](https://user-images.githubusercontent.com/16274199/34317101-2ef4ddbe-e7e2-11e7-967b-1b85e53153de.PNG)

**Comment by qiuxiang** [comment]
哦。。你这样的写法是不行的，image 只能是原生的图片名称，你看 example 里我写的是 image='flag'，而 flag 的文件 android 要放在 https://github.com/qiuxiang/react-native-amap3d/tree/master/example/android/app/src/main/res/drawable ios 放在 https://github.com/qiuxiang/react-native-amap3d/tree/master/example/ios/RNAMap3D/Images.xcassets

这是我最推荐的做法。

**Comment by qiuxiang** [comment]
当然，也可以在自定义 View 里放图片，比如 `icon={() => <Image source={require('./flag.png')} />}`，但这个方法不够稳定。
