### ISSUE TITLE
自定义多个marker时，部分渲染不出来

### ISSUE THREAD

**Issue by jnzw1986** [qiuxiang/react-native-amap3d#138]
<Marker
                   key = {index}
                   icon={() =>
                       <View style={markerStyle}>
                           <Text style={styles.markerText}>{dataItem.name}</Text>
                           <Text style={styles.markerText}>{dataItem.desc}</Text>
                       </View>
                   }
                   coordinate={location}
                   onPress={() => this._onMarkerViewPress(dataItem.latitude, dataItem.longitude)}
                   clickable = {this.state.markerType == 3?false:true}
                   infoWindowEnabled = {false}
                   draggable = {true}
                   flat = {true}
               />

**Comment by qiuxiang** [comment]
要看你的 icon 里面是怎么写的

**Comment by jnzw1986** [comment]
v0.8.0还没有这个问题。更新到0.8.1出现概率性自定义marker不生效，应该显示自定义marker的地方依然显示红色锚点。

**Comment by jnzw1986** [comment]
<Marker
                   key = {index}
                   icon={() =>
                       <View style={markerStyle}>
                           <Text style={styles.markerText}>{dataItem.name}</Text>
                           <Text style={styles.markerText}>{dataItem.desc}</Text>
                       </View>
                   }
                   coordinate={location}
                   onPress={() => this._onMarkerViewPress(dataItem.latitude, dataItem.longitude)}
                   clickable = {this.state.markerType == 3?false:true}
                   infoWindowEnabled = {false}
                   draggable = {true}
                   flat = {true}
               />

**Comment by jnzw1986** [comment]
icon={() =>
                       <View style={markerStyle}>
                           <Text style={styles.markerText}>{dataItem.name}</Text>
                           <Text style={styles.markerText}>{dataItem.desc}</Text>
                       </View>
                   }

**Comment by jnzw1986** [comment]
`icon={() =>
                       <View style={markerStyle}>
                           <Text style={styles.markerText}>{dataItem.name}</Text>
                           <Text style={styles.markerText}>{dataItem.desc}</Text>
                       </View>
                   }`

**Comment by qiuxiang** [comment]
ios？android？红色锚点是什么，有截图？

**Comment by qiuxiang** [comment]
最好提供完整的，可以重现的，整个 screen 的代码

**Comment by jnzw1986** [comment]
`import React, { Component } from "react";
import {Alert, FlatList, StyleSheet, Text, View, TouchableOpacity} from 'react-native'
import {MapView, Marker} from 'react-native-amap3d'

export default class MapPageDemo extends Component {
    constructor(props) {
        super(props);
         this._loadData(1, 0 , 0);
    }
    state = {
        dataSource:[]
    }
    _loadData(level, latitude, longitude) {
        var me = this;
        var requestURL = 'https://www.easy-mock.com/mock/59c5d451e0dc663341b5c9f9/fg/api/v1/map/search/area';;

        fetch(requestURL)
          .then((response) => response.json())
          .then((responseJson) => {
                this.setState({
                    lastReqType:level,
                    dataSource: responseJson.data.list,
                    });
          })
          .catch((error) => {
            console.error(error);
          });
    }

    _renderMarker(){
        return this.state.dataSource.map(function(dataItem, index){
            var location = {
                latitude: dataItem.latitude,
                longitude: dataItem.longitude,
            };
            var markerStyle = styles.customMarker1;

           return(
               <Marker
                   key = {index}
                   icon={() =>
                       <View style={markerStyle}>
                           <Text style={styles.markerText}>{dataItem.name}</Text>
                           <Text style={styles.markerText}>{dataItem.desc}</Text>
                       </View>
                   }
                   coordinate={location}
                   onPress={() => this._onMarkerViewPress(dataItem.latitude, dataItem.longitude)}
                   clickable = {this.state.markerType == 3?false:true}
                   infoWindowEnabled = {false}
                   draggable = {true}
                   flat = {true}
               />
           );
       }, this);
    }

    render() {
        return (
            <View style={styles.body}>
                <MapView
                    ref={(c) => this._mapView = c}
                    locationEnabled
                    locationInterval={10000}
                    distanceFilter={100}
                    showsZoomControls = {true}
                    showsLocationButton = {true}
                    maxZoomLevel = {18}
                    minZoomLevel = {5}
                    onStatusChangeComplete={this._mapStatusChangeCompleteEvent}
                    style={styles.mapview}
                    >
                    {this._renderMarker()}
                </MapView>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    body: {
        flex: 1,
    },
    mapview: {
        flex: 1,
    },
    customMarker1: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: 'rgba(50, 205, 50, 0.8)',
    },
    markerText: {
      color: '#fff',
    },
})
`

**Comment by jnzw1986** [comment]
[App-map-demo.js.zip](https://github.com/qiuxiang/react-native-amap3d/files/1584121/App-map-demo.js.zip)

**Comment by qiuxiang** [comment]
ios？android？如果不用 icon，问题是不是还会出现？

**Comment by jnzw1986** [comment]
ios。不用icon怎么实现自定义marker？

**Comment by jnzw1986** [comment]
<img width="271" alt="123456" src="https://user-images.githubusercontent.com/3883252/34319804-b961ad4a-e825-11e7-9c9a-abf2bf60bafc.png">

**Comment by qiuxiang** [comment]
发布了一个新版本
