### ISSUE TITLE
Some properties are not working

### ISSUE THREAD

**Issue by ntbinh91** [qiuxiang/react-native-amap3d#143]
react-native-amap3d: v0.9.0

**anchor** is not work on Android.  The marker is hidden when it has this property.
**infoWindowEnabled** is not work on Android + iOS. InfoWindows are always opened when click on markers
**onPress** is not fired on Android + iOS

Checked with your examples and they don't work too!

**Comment by qiuxiang** [comment]
`anchor` problem I will check later.

`infoWindowEnabled` is replaced by `disabled`.

**Comment by ntbinh91** [comment]
But when the marker is `disabled`, It's not clickable.

**Comment by ntbinh91** [comment]
`onInfoWindowPress` is not working too

**Comment by qiuxiang** [comment]
`disabled` is just disabled click

**Comment by qiuxiang** [comment]
`onInfoWindowPress ` and `onPress` not working? But I tested it all worked fine in the example.

**Comment by qiuxiang** [comment]
`anchor` is also working.

Before:
![image](https://user-images.githubusercontent.com/1709072/34338429-9ebec0c0-e9a3-11e7-8d10-6d3ff211a35b.png)

After:

```javascript
<Marker
  image='flag'
  title='自定义图片'
  anchor={{x: 1, y: 0}}
  coordinate={this._coordinates[2]}
/>
```

![image](https://user-images.githubusercontent.com/1709072/34338436-add1f7da-e9a3-11e7-9faf-7cf0535e4bc8.png)

**Comment by ntbinh91** [comment]
> disabled is just disabled click

In my case, I want the marker to be clickable and don't open infowindow as well.

> onInfoWindowPress and onPress not working? But I tested it all worked fine in the example.

Have you check on iOS. Infowindow is opened but `onPress` is not triggered?

> anchor is also working.

 Sorry, I re-checked. That's my mistake.

**Comment by qiuxiang** [comment]
Thanks you feedback. There are indeed some bugs.

Replace `clickable` `infoWindowEnabled` with `disabled` is a bad decision.

**Comment by qiuxiang** [comment]
Now `disabled` has been removed and replaced by `clickDisabled` `infoWindowDisabled`. The reason why names are not `clickabled` `infoWindowEnabled` is that `clickabled` and `infoWindowEnabled` should be enabled by default.

For example, in order to disable infoWindow you just:
```javascript
<Marker infoWindowDisabled />
```

**Comment by ntbinh91** [comment]
It works like a charm. Thank you so much
