### ISSUE TITLE
example页面正常，点击菜单App异常崩溃

### ISSUE THREAD

**Issue by kevinchensd** [qiuxiang/react-native-amap3d#144]
1. 环境：  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-amap3d": "^0.9.0",
    "react-navigation": "^1.0.0-beta.22"
  },
2. 已经在android_studio下安装kotlin 插件，并gralde build成功
3. Genymotion Google Nexus 6.0
**4. 点击example上的页面任意一个菜单项目，相关联的页面会显示一下，然后程序就直接报错：unfotunately XXX has stopped**

下面是一些截图：
![1](https://user-images.githubusercontent.com/26289472/34346497-0356002c-ea33-11e7-8c44-5feff02096e0.jpg)
![2](https://user-images.githubusercontent.com/26289472/34346498-038575f0-ea33-11e7-8959-432bb9154ae0.jpg)
![3](https://user-images.githubusercontent.com/26289472/34346499-03b45604-ea33-11e7-8414-23bce1cc2ce4.jpg)
![4](https://user-images.githubusercontent.com/26289472/34346500-03e3e8f6-ea33-11e7-9bd7-983055c8c9b3.jpg)

**Comment by kevinchensd** [comment]
在打开的页面的render中，只要调用了<MapView>就出错，注销掉这块随便return一段文字，就能正常显示。

**Comment by qiuxiang** [comment]
基本可以确定是你的模拟器不支持3D加速，你看 Event Log 没用，要看 logcat，应该会有 GL 相关的错误

**Comment by kevinchensd** [comment]
不是很熟这块。试了2中方法，还是行，
1. 在Oracle VM VirtualBox，特意设置了3D还是不行（android 6和7都不行）
2. 打包成release版本，安装到真机上直接就闪退

![5](https://user-images.githubusercontent.com/26289472/34348812-332a068a-ea48-11e7-8a60-ce62628b125a.jpg)

**Comment by qiuxiang** [comment]
你用的模拟器我不熟，react-native run-android 在真机不能运行？release 闪退不一定是这个库的问题，昨天我一个 app 更新到最新 RN，release 就闪退了，然后发现是 RN 的问题。

**Comment by kevinchensd** [comment]
logcat日志截图，请帮忙看看，（RN升级太痛苦了。。）

![7](https://user-images.githubusercontent.com/26289472/34349332-684445ee-ea4b-11e7-971e-80e50c7bccb8.jpg)
![8](https://user-images.githubusercontent.com/26289472/34349333-6875e180-ea4b-11e7-8d32-eec03ff55c22.jpg)
![9](https://user-images.githubusercontent.com/26289472/34349334-68a6f8ce-ea4b-11e7-9835-76dbf6bff415.jpg)

**Comment by qiuxiang** [comment]
android studio 有 logcat，你这命令行 logcat 又没有 filter 太难看了

**Comment by kevinchensd** [comment]
应该是3D加速的问题，但是应该有比较多的手机没有3D加速，那就没法运行用了这个包的App了

**Comment by qiuxiang** [comment]
并不是，现在的手机怎么可能没有 GPU，只是模拟器可能不能提供底层的图形加速接口才导致地图渲染失败，我现在用的台式，因为系统和硬件问题就不能用 x86 带硬件加速的模拟器，但另一台 macbook 是可以的。

所以你为什么不用真机来测试呢？

**Comment by kevinchensd** [comment]
好的，谢谢给的思路。我试一下。

**Comment by kevinchensd** [comment]
兄嘚，真机调试可以的，谢谢。windows上有什么好的模拟器推荐一下。

**Comment by qiuxiang** [comment]
我都是用 android studio 提供的模拟器，详细信息看 https://developer.android.com/studio/run/emulator-acceleration.html
