### ISSUE TITLE
App is crashed when using zIndex property for marker

### ISSUE THREAD

**Issue by ntbinh91** [qiuxiang/react-native-amap3d#145]
`react-native-amap3d: v0.9.0`

It works fine on Android but app crashed on iOS without any reason. Please check it!

**Comment by ntbinh91** [comment]
I checked again. App never is crashed again but It seem that `zIndex` is till not working on iOS. I changed the `zIndex` value but the marker is still under other markers

**Comment by qiuxiang** [comment]
`zIndex` works fine:

### Before:

```javascript
state = {
  list: [1, 2, 3, 4, 5, 6],
}

render() {
  return <MapView style={StyleSheet.absoluteFill}>
    {this.state.list.map(item => <Marker
        key={item}
        image='flag'
        title={'Marker' + item}
        coordinate={{
          latitude: 39.906901 + (item * 0.01),
          longitude: 116.397972 + (item * 0.01),
        }}
      />
    )}
  </MapView>
}
```

<img width="114" alt="screen shot 2017-12-27 at 1 30 32 pm" src="https://user-images.githubusercontent.com/1709072/34371675-3162e67e-eb0a-11e7-912a-26679f5e4722.png">

### After:
`zIndex={10 - item}`

<img width="113" alt="screen shot 2017-12-27 at 1 32 10 pm" src="https://user-images.githubusercontent.com/1709072/34371707-68a3a16e-eb0a-11e7-9255-0a6e4c6af8f2.png">
