### ISSUE TITLE
地图导航无法显示缩放按钮

### ISSUE THREAD

**Issue by wabgy** [qiuxiang/react-native-amap3d#146]
<Navigation.Drive
              mapType={this.props.navigation.state.params.mapType}
              showsZoomControls={true}
              showsBuildings={true}
              showsScale={true}
              showsTraffic={true}
              ref={ref => this._navigation = ref}
              style={[StyleSheet.absoluteFill]}
              onCalculateRouteSuccess={this._start}
          />
在<Navigation.Drive>中增加showsZoomControls属性，没有作用。还是showsZoomControls这个属性只能在<MapView>中使用？

![qq 20171227165623](https://user-images.githubusercontent.com/18025875/34376480-e3631e86-eb26-11e7-9e5a-c719348924c5.png)

**Comment by qiuxiang** [comment]
导航组件不能这么用，况且在 android 尚且存在严重 bug #43，不建议使用
