### ISSUE TITLE
自定义Marker不设置Title时，点击marker显示空白弹窗

### ISSUE THREAD

**Issue by jnzw1986** [qiuxiang/react-native-amap3d#147]
<Marker
                key = {keyvalue}
              icon={() =>
                <View style={styles.customMarker}>
                  <Text style={styles.markerText}>{`${i}`+ "_title"}</Text>
                </View>
              }
              coordinate={dataItem}
            />

**Comment by jnzw1986** [comment]
<img width="129" alt="12" src="https://user-images.githubusercontent.com/3883252/34383415-fe344bee-eb4f-11e7-8ca7-e46a9b63ea95.png">

**Comment by jnzw1986** [comment]
`return <Marker
                key = {keyvalue}
              icon={() =>
                <View style={styles.customMarker}>
                  <Text style={styles.markerText}>{`${i}`+ "_title"}</Text>
                </View>
              }
              coordinate={dataItem}
            />`

**Comment by qiuxiang** [comment]
本来默认就是这样的，如果你不想弹出窗口，可以加 `infoWindowDisabled`

**Comment by jnzw1986** [comment]
问题解决，多谢。
