### ISSUE TITLE
react-native run link 无法安装安卓的项目依赖配置

### ISSUE THREAD

**Issue by jxintang** [qiuxiang/react-native-amap3d#148]
![image](https://user-images.githubusercontent.com/5434292/34399921-df8c2992-ebc6-11e7-80c1-d6055029bff9.png)

尝试按照example里进行手动安装，然后运行react-native run-android，发生报错，报错如下

![image](https://user-images.githubusercontent.com/5434292/34399960-5e41d94e-ebc7-11e7-99b9-bbe1dd252e92.png)

react-native  0.45.0
react-native-amap3d 0.8.0

**Comment by qiuxiang** [comment]
早就不支持 RN0.47 以下的版本了，这里是因为之前 RN 的 link 还不识别 kotlin。非要用也不是不可以，但要把 AMap3DPackage.kt 翻译成 AMap3DPackage.java，之前是用 AMap3DPackage.java 的，但后来索性删掉了，因为即便这个问题解决了，也有另一个地方要改，关键还不能写进项目。

**Comment by jxintang** [comment]
除了把AMap3DPackage.kt 翻译成 AMap3DPackage.java，还需要做其它工作么？

**Comment by qiuxiang** [comment]
不需要了

**Comment by qiuxiang** [comment]
这个项目是从 RN0.44 开始开发的，你可以在 Release Log 找到一些信息，AMap3DPackage.java 以前也是有的。这个 issue 关掉了。
