### ISSUE TITLE
集成高德定位模块

### ISSUE THREAD

**Issue by qiuxiang** [qiuxiang/react-native-amap3d#149]
本来没有打算单独封装定位模块，鉴于现在也没有比较靠谱的开源项目，索性把这个列入计划吧。

**Comment by kevinchensd** [comment]
接口开放了吗？

**Comment by qiuxiang** [comment]
没有，只是计划，短期内没时间实现

**Comment by wfxphoebus** [comment]
亲，同样需求，要赶紧啊，还有一个问题，我们的库能分开么，我看现在 android 编译后的 apk 很大，如果只需要定位功能，或者2D，不需要3D

**Comment by qiuxiang** [comment]
定位模块在另一个项目 [react-native-amap-geolocation](https://github.com/qiuxiang/react-native-amap-geolocation)
