### ISSUE TITLE
locationEnable 在真机上没有效果

### ISSUE THREAD

**Issue by xxtonglei4334** [qiuxiang/react-native-amap3d#15]
MapView 开启了locationEnable={true} 不能实现自动定位。

**Comment by xxtonglei4334** [comment]
是不是要使用其他项目来定位？

**Comment by qiuxiang** [comment]
确定高德 Key 设置正确了吗，还有试过 [example](https://github.com/qiuxiang/react-native-amap3d/tree/master/example) 了吗？

**Comment by xxtonglei4334** [comment]
@qiuxiang 确实是key有问题，重新改过后可以定位了。
定位点有些漂。
