### ISSUE TITLE
react-native link后package包不能用

### ISSUE THREAD

**Issue by Aaronnnnn** [qiuxiang/react-native-amap3d#150]
react-native 0.51.0
run-android的时候，会报MainApplication.java里对应的包错误

**Comment by qiuxiang** [comment]
什么错误？

**Comment by Aaronnnnn** [comment]
MainApplication.java:30: 错误: 找不到符号
            new AMap3DPackage(),
                ^
  符号: 类 AMap3DPackage
2 个错误

**Comment by qiuxiang** [comment]
不知道你是怎么操作的，很明显是 java 代码的问题，这种问题你还是要自己解决的。
