### ISSUE TITLE
Get user location coordinate

### ISSUE THREAD

**Issue by ntbinh91** [qiuxiang/react-native-amap3d#151]
I'm worndering that can I get user location infomation with your library? For example, we can have a function to return current user location info through this.map (Mapview ref attribute).

Another question, can I modify userLocation icon and color of the circle around user location point?

**Comment by qiuxiang** [comment]
React-Native component methods does not return data. But you can use `onLocation`:
```javascript
<MapView
  locationEnabled
  onLocation={({nativeEvent}) =>
    console.log(`${nativeEvent.latitude}, ${nativeEvent.longitude}`)}
/>
```

> Another question, can I modify userLocation icon and color of the circle around user location point?

No, This is not supported.

**Comment by ntbinh91** [comment]
Can I use onLocation without locationEnabled? Because I don't want to show default user location dot, I want to display a custom marker instead.

**Comment by qiuxiang** [comment]
Maybe I should add some props to custom locationStyle.

**Comment by z5614036** [comment]
I hope a cherish that I can get a function for user current location like getCurrentLocation! thanks

**Comment by qiuxiang** [comment]
@z5614036 
> **react native component methods can't return any data.**

**Comment by ntbinh91** [comment]
>Maybe I should add some props to custom locationStyle.

Yes, Hope to see your update as soon as posible because I really need this.

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-amap3d/blob/master/src/maps/MapView.js#L40

**Comment by ntbinh91** [comment]
@qiuxiang sorry but locationStyle is still not working now.
```
<MapView
            locationEnabled={true}
            locationStyle={{
              image: "flag",
              fillColor: "red",
              strokeColor: "red",
              strokeWidth: 2
            }}
/>
![simulator screen shot - iphone 6 - 2018-01-09 at 15 39 02](https://user-images.githubusercontent.com/19319495/34711830-4d2acb1c-f553-11e7-8e67-e45d713d535a.png)

Anw, as I said above, Can I display user location with custom image instead?

```

**Comment by qiuxiang** [comment]
I check later.

**Comment by qiuxiang** [comment]
In controls example:

```javascript
<MapView
    locationEnabled={this.state.showsLocationButton}
    showsCompass={this.state.showsCompass}
    showsScale={this.state.showsScale}
    showsLocationButton={this.state.showsLocationButton}
    showsZoomControls={this.state.showsZoomControls}
    locationStyle={{
      image: "flag",
      fillColor: "red",
      strokeColor: "red",
      strokeWidth: 2
    }}
    style={styles.map}
/>
```
<img width="487" alt="screen shot 2018-01-14 at 12 26 22 pm" src="https://user-images.githubusercontent.com/1709072/34912832-26ebb548-f926-11e7-85d1-a3d374566b99.png">

**Comment by kevinchensd** [comment]
lifestyle是起作用的，但是我想直接就用高德地图自己带的小蓝点，如图所示，不想自己再去实现（这个效果不好实现，而且搞得实现的这个效果已经很好了，不需要再去创造），不知道怎么能直接调出地图默认带的这个蓝色小圆点，我现在调出来的是蓝色飞机的图标，这个没有蓝色小圆点好；
![_20180117151658](https://user-images.githubusercontent.com/26289472/35030583-6fd64a68-fb9a-11e7-869c-a0ff00769eed.jpg)

**Comment by qiuxiang** [comment]
@kevinchensd 这个可不是 sdk 自带的，而是高德地图 app 里实现的。

**Comment by kevinchensd** [comment]
奥，谢谢；还有一个问题：当zoomlevel比较小的时候，显示的地图范围很大的时候，这个lifestyle的图标（image）依然是原来的大小，很清楚，但是圆圈就很小甚至看不到了；这个怎么让圆圈跟图片一样不会被影响？
![_20180117153133](https://user-images.githubusercontent.com/26289472/35030937-d1657a00-fb9b-11e7-8072-e031fbb0d61e.jpg)
![_20180117153139](https://user-images.githubusercontent.com/26289472/35030938-d19c5c6e-fb9b-11e7-8c8b-2a053dc19585.jpg)

**Comment by qiuxiang** [comment]
这个接口基本就这样了

**Comment by zjjjjjjjjjjd** [comment]
> ```js
> locationStyle={{
>       image: "flag",
>       fillColor: "red",
>       strokeColor: "red",
>       strokeWidth: 2
>     }}
> ```

这个在3.2.4不起作用，大神如何解决？

**Comment by liuyunzyj** [comment]
@qiuxiang 在3.2.4不起作用没有这个属性了 locationStyle={{
      image: "flag",
      fillColor: "red",
      strokeColor: "red",
      strokeWidth: 2
    }}
