### ISSUE TITLE
IOS使用 CocoaPods  安装依赖，ios编译错误

### ISSUE THREAD

**Issue by lany9527** [qiuxiang/react-native-amap3d#152]
## Podfile
platform :ios, '8.0'

target 'rn_ipad' do
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/'
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/ios/'
end

## 错误信息，

clang: error: no such file or directory: '/Users/rn_ipad/node_modules/react-native-amap3d/ios/AMapViewManager.m'
clang: error: no input files  

## 正在使用的版本，以及 RN 版本
"react-native-amap3d" : "0.10.1",
"react-native": "0.51.0",

### /node_modules/react-native-amap3d/ios/文件夹下的确不存在AMapViewManager.m  而AMapViewManager.m是在maps下面.

请问有什么解决办法？

**Comment by qiuxiang** [comment]
你确定不是自己的问题？我能确定的是，当前版本按照正常流程配置是不会有问题的。这是最新的编译测试：https://travis-ci.org/qiuxiang/react-native-amap3d/jobs/323744777

**Comment by lany9527** [comment]
@qiuxiang . 我是严格按照步骤配置的,安卓端通过了,ios就不行了

**Comment by Ariesliuh** [comment]
我是使用手动配置的，也有同样的问题，应该是iOS AMap3D项目配置是有问题的。你能出个手动link的说明吗,虽然官方是建议用pod去做，但pod有时候也会有问题。

**Comment by qiuxiang** [comment]
@Ariesliuh 直到最近也没有时间测试手动配置。
@lany9527 能运行一次我写在 CI 里的编译测试脚本？
```bash
npm i -g react-native-cli
react-native init App
cd App
npm i
npm i react-native-amap3d
cd ios
echo -e "platform :ios, '8.0'\n\ntarget 'App' do\n  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'\n  pod 'React', path: '../node_modules/react-native/'\n  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/ios/'\nend" > Podfile
pod install
xcodebuild -workspace App.xcworkspace -scheme App -sdk iphonesimulator -quiet
```
或者把你的操作过程脚本化，给我测试。

**Comment by lany9527** [comment]
@qiuxiang 问题在于自己手残，IOS使用 CocoaPods配置依赖， react-native link 安卓部分的时候，导致重复引入。

**Comment by lpb006** [comment]
怎么单独对安卓项目react-native link 而ios项目不执行这个命令

**Comment by qiuxiang** [comment]
@lpb006 只能自己单独做备份
