### ISSUE TITLE
marker无法显示自定义图片？

### ISSUE THREAD

**Issue by st4allen** [qiuxiang/react-native-amap3d#154]
看到marker显示图片的逻辑是_image = [UIImage imageNamed:name];
无法显示js端的图片？

**Comment by qiuxiang** [comment]
不提供直接设置 js 端图片的接口，因为在原生处理 js 端传过来的图片太麻烦了。

但是可以直接使用 ReactView 作为自定义图标：`icon={() => <Image source={...} />}`。不管怎么样，我会建议优先考虑 `image`，简单可靠。
