### ISSUE TITLE
拖动地图掉帧

### ISSUE THREAD

**Issue by lesvate** [qiuxiang/react-native-amap3d#157]
RN：0.51

<MapView style={{height:400}}
                             coordinate={this.state.point}
                             zoomLevel={13}
                    >
                 </MapView>

使用高通835的机器调试，虽然用起来没问题，但是拖动地图时掉帧，不知道是需要其他设置么，因为之前用webview调用百度地图是不会感觉到掉帧的。

**Comment by qiuxiang** [comment]
什么样的掉帧？

**Comment by lesvate** [comment]
怎么说呢，就是不是很跟手，没有那种十分顺滑的感觉，不知道是高通sdk的问题还是什么，或者有什么方法提高响应速度

**Comment by qiuxiang** [comment]
你不说我还不觉得，我仔细看了，还真是掉帧了，或者说，这根本就是帧率限制。我下载了一个[官方 demo](http://a.amap.com/lbs/static/apk/android-map-permission.apk)，和这里的表现是一样的。我又看了使用了高德地图 SDK 的 app，比如咕咚，发现情况好像好一些，但也是一样的掉帧。而高德自己发布的地图 app 就顺畅很多，当然，最流畅的还是 google maps。

所以，这个可以说是没什么办法的。

**Comment by lesvate** [comment]
😂捂脸 goodnight
