### ISSUE TITLE
iOS 10.3 上不显示 我的位置 按钮，安卓上没问题，已允许了获取地点的权限

### ISSUE THREAD

**Issue by ittianyu** [qiuxiang/react-native-amap3d#16]
属性设置代码如下，已经调试过，locationPermission 设置为 true 在 ios 上也不显示
```
                    locationEnabled={true}
                    showsCompass={false}
                    showsScale={false}
                    showsLocationButton={this.state.locationPermission}
                    showsZoomControls={false}
```
用的模拟器，已经开启了模拟定位功能，已申请并同意了权限

**Comment by qiuxiang** [comment]
抱歉，我没有在接口那里写清楚，有一些属性在 iOS 那里是没有用的，因为 SDK 本来就没提供，比如缩放按钮、定位按钮。

考虑到接口的统一，有计划在这个库实现这两个接口，但现在还没时间做。现在如果你需要 iOS 定位按钮，只能自己实现：在地图上放置一个按钮，然后用 animateTo 进行移动。

**Comment by ittianyu** [comment]
那是在 onLocation 回调的时候记录位置，然后在点击按钮的时候移动到那个位置吗

**Comment by qiuxiang** [comment]
对

**Comment by blueiris4** [comment]
请问最新版支持了吗

> 抱歉，我没有在接口那里写清楚，有一些属性在 iOS 那里是没有用的，因为 SDK 本来就没提供，比如缩放按钮、定位按钮。
> 
> 考虑到接口的统一，有计划在这个库实现这两个接口，但现在还没时间做。现在如果你需要 iOS 定位按钮，只能自己实现：在地图上放置一个按钮，然后用 animateTo 进行移动。
