### ISSUE TITLE
marker与calloutWindow点击事件是否有待实现？

### ISSUE THREAD

**Issue by zhouyonghui** [qiuxiang/react-native-amap3d#160]
设置了了onPress/onInfoWindowPress都无效
AmpMarker.m里面也没有相应代码

**Comment by qiuxiang** [comment]
你有看过 example？https://github.com/qiuxiang/react-native-amap3d/blob/master/example/src/examples/marker.js

**Comment by qiuxiang** [comment]
实现在这里 https://github.com/qiuxiang/react-native-amap3d/blob/master/ios/AMap3D/maps/AMapViewManager.m#L122

**Comment by zhouyonghui** [comment]
修改一下代码就可以正确回调oPress/onInfoWindowPress了：


- (void)mapView:(AMapView *)mapView didSelectAnnotationView:(MAAnnotationView *)view {
    if ([view.annotation isKindOfClass:[MAPointAnnotation class]]) {
        AMapMarker *marker = [mapView getMarker:view.annotation];
        if (marker != nil && marker.onPress) {
            marker.onPress(nil);
        }
    }
}

- (void)mapView:(AMapView *)mapView didAnnotationViewCalloutTapped:(MAAnnotationView *)view {
    if ([view.annotation isKindOfClass:[MAPointAnnotation class]]) {
        AMapMarker *marker = [mapView getMarker:view.annotation];
        if (marker != nil && marker.onInfoWindowPress) {
            marker.onInfoWindowPress(nil);
        }
    }
}

**Comment by qiuxiang** [comment]
在 example，`onPress` 和 `onInfoWindowPress` 都没问题呀。你的改动看起来并没有什么用，因为关键在于 `marker.onPress(nil)` 有没有运行。
