### ISSUE TITLE
iOS:初始打开mapview，marker的infowindow不显示，必须要点击一下才能出现

### ISSUE THREAD

**Issue by zhouyonghui** [qiuxiang/react-native-amap3d#161]
原因是，调用AmapMarker.m: setActive之前_annotationView还是nil。所以必须等到_annotationView就位以后才能显示marker的infowindow

**Comment by zhouyonghui** [comment]
我这样修改就可以正常显示了：
AMapView.m里面增加：

@implementation AMapView {
    NSMutableDictionary *_markers;
    AMapMarker* _initial_selected_marker;
}

- (void)layoutSubviews
{
    [_initial_selected_marker setActive:YES];
    _initial_selected_marker = nil;
}

- (void)initialSelectedMarker:(AMapMarker*) marker
{
    _initial_selected_marker = marker;
}

AMapMarker.m里面修改一处地方：

- (MAAnnotationView *)annotationView {
    if (_annotationView == nil) {
        if (_customView) {
            _customView.hidden = NO;
            _annotationView = [[MAAnnotationView alloc] initWithAnnotation:_annotation reuseIdentifier:nil];
            _annotationView.bounds = _customView.bounds;
            [_annotationView addSubview:_customView];
            [_annotationView addGestureRecognizer:[
                    [UITapGestureRecognizer alloc] initWithTarget:self action:@selector(_handleTap:)]];
        } else {
            _annotationView = [[MAPinAnnotationView alloc] initWithAnnotation:_annotation reuseIdentifier:nil];
            ((MAPinAnnotationView *) _annotationView).pinColor = _pinColor;
        }
        _annotationView.canShowCallout = _canShowCallout;
        _annotationView.draggable = _draggable;
        _annotationView.customCalloutView = _calloutView;
        _annotationView.centerOffset = _centerOffset;
        if (_image != nil) {
            _annotationView.image = _image;
        }
        //[self setActive:_active];
        if (_active) {
            [_mapView initialSelectedMarker:self];
        }
    }
    return _annotationView;
}

**Comment by qiuxiang** [comment]
之后再确认下

**Comment by qiuxiang** [comment]
之后再确认下

**Comment by qiuxiang** [comment]
之后再确认下

**Comment by qiuxiang** [comment]
之后再确认下

**Comment by qiuxiang** [comment]
之后再确认

**Comment by qiuxiang** [comment]
之后确认

**Comment by jiasaichao** [comment]
@qiuxiang  啥意思？我也碰到这个问题marker 这个组件设置 active属性为true不管用，必须点击才行。设置为false关闭也不起作用。

**Comment by zhouyonghui** [comment]
render()初次调用的时候构建整个mapview和markers，等等，这个阶段如果在- (MAAnnotationView *)annotationView函数里面[self setActive:_active]会因为相关的AnnotationView未准备好（正是要从- (MAAnnotationView *)annotationView里面返回的），所以marker的infowindow不能打开。所以应当先记下了，再AnnotationView准备好以后在打开。

**Comment by qiuxiang** [comment]
其实之前就知道这个问题，当时的 Marker 是有内部维护一个 _active 状态的，并在 viewForAnnotation 里更新 selected 状态。

https://github.com/qiuxiang/react-native-amap3d/blob/v0.8.0/ios/maps/AMapMarker.m
https://github.com/qiuxiang/react-native-amap3d/blob/v0.8.0/ios/maps/AMapViewManager.m

后来重构 Marker，我觉得内部的 _active 不再有必要，记得有测试过，并没有问题。既然这个问题再被提出，我需要再确认下。

**Comment by qiuxiang** [comment]
我想知道，你的 js 代码是怎么写的，我自己测试并没有问题

**Comment by zhouyonghui** [comment]
我的代码和你的example一样的
我现在的处理就是延迟到MapView::layoutSubViews里面显示初始的active-marker，这样就能正常显示出来了。

**Comment by qiuxiang** [comment]
可是 example 没问题呀

**Comment by zhouyonghui** [comment]
我是在ios版本上遇到的问题哦，android没问题

**Comment by qiuxiang** [comment]
我就是检查的 iOS
