### ISSUE TITLE
能否在animateTo 中增加一个显示指定的区域数据数组

### ISSUE THREAD

**Issue by ibmsoft** [qiuxiang/react-native-amap3d#163]
目前 animateTo 好像只支持一个指定的区域，能否增加一个区域数组
方法如下：
LatLngBounds.Builder builder = new LatLngBounds.Builder();
        for (Region region : clusterItems) {
            builder.include(region.getPosition());
        }
        LatLngBounds latLngBounds = builder.build();
        mAMap.animateCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds, 0)
        );

**Comment by qiuxiang** [comment]
还要看 iOS 支不支持

**Comment by ibmsoft** [comment]
IOS 支持
- (void)addAnnotationsToMapView:(MAMapView *)mapView
{
    /* 判断是否已建树. */
    if (self.coordinateQuadTree.root == nil)
    {
        return;
    }
    /* 根据当前zoomLevel和zoomScale 进行annotation聚合. */
    double zoomScale = self.mapView.bounds.size.width / self.mapView.visibleMapRect.size.width;
    /* 基于先前建立的四叉树索引，计算当前需要显示的annotations. */
    NSArray *annotations = [self.coordinateQuadTree clusteredAnnotationsWithinMapRect:mapView.visibleMapRect
                                withZoomScale:zoomScale
                                 andZoomLevel:mapView.zoomLevel];
   
    /* 更新annotations. */
    [self updateMapViewAnnotationsWithAnnotations:annotations];
}

**Comment by qiuxiang** [comment]
看起来不对呀，这是 addAnnotationsToMapView，而不是 animate

**Comment by ibmsoft** [comment]
没有仔细研究，只是参考的这个
https://github.com/amap-demo/iOS-cluster-marker

**Comment by qiuxiang** [comment]
。。这么看来你所关心的问题和这个 issue 根本就没有必要的联系

**Comment by ibmsoft** [comment]
还是有的，因为我要实现聚合，聚合点已经实现了，现在就是我点击聚合点的时候，我要让地图显示我这个聚合点的数据区域。我看代码中有animateTo，我就想能否增强加上这个显示指定区域，android上我已经通过修改代码实现

**Comment by qiuxiang** [comment]
你上面给出 iOS-cluster-marker 的时候我就大概知道你想要做什么了，我是想吐槽一下，你应该在一开始就说明你的意图，而不是提出一个你认为可能正确，但实际上给人误导的方向。

一个简单的方法是，新增一个 `animateToRegion` 接口，自己算出所有 markers 组成的边界。

另一个方法是在原生方法里实现，但其实也是要算 markers 组成的边界，只不过是库帮你做，[react-native-maps](https://github.com/react-community/react-native-maps/blob/master/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java#L631) 就是这么做的。

**Comment by ibmsoft** [comment]
可能是我描述的问题
因为我看android 代码中有 
        map.animateCamera(cameraUpdate, duration.toLong(), animateCallback)
算出所有 markers 组成的边界，最终调用的是
        map.animateCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds, 0))
我的意思，看你这边是否有必要加条件放到一个 animateTo 中，是这个意思

**Comment by qiuxiang** [comment]
也就是我说的 `animateToRegion`，不过我想了下，并不需要单独再做一个 `animateToRegion`，只需要对 `animateTo` 增加 `region`  支持，比如这样用：
```javascript
animateTo(
  {
    region: {
      latitude: number,
      longitude: number,
      latitudeDelta: number,
      longitudeDelta: number,
    },
  },
  duration
)
```

**Comment by lenglengiOS** [comment]
https://github.com/qiuxiang/react-native-amap3d/issues/163#issuecomment-356527935
@ibmsoft 请问聚合点怎么实现的？大佬
