### ISSUE TITLE
Execution failed for task ':app:transformClassesWithDexForDebug'.

### ISSUE THREAD

**Issue by qinfensky** [qiuxiang/react-native-amap3d#164]
"react-native": "^0.49.5",
"react-native-amap3d": "^0.11.0",
buildToolsVersion "25.0.0",
gradle-3.3-all

执行 react-native run-android 时候,报错.
已经严格按照安装步骤执行
npm i react-native-amap3d
react-native link react-native-amap3d

也尝试过 ./gradlew clean
删除 npm 缓存目录,删掉 node_modules/react-native-amap3d 里面的 build,结果依然如此,麻烦给我一些指导和帮助,谢谢.以下是报错信息:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output /Users/qinfensky/che-app/carknows/android/app/build/intermediates/transforms/dex/debug/folders/1000/1f/main /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_bb47eabc6a0c759a323fbc7be634577dae014b1a.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_b6c529b38237e29ee6d263c69b460a9885f5e642.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_b99f8279cb7777d11c0b3275b2d3fdd1d53ccfdb.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/glide-3.8.0_f199f815141ac4b9db2907ccc0ea44db0fd06248.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_89eb5c37ca9e17d2bf96be7d24f0c2b924f2d11a.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/jshare-sina-android-1.3.0_f96068547b9dcf6271bec4a75afaf34a274ff8cf.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/jshare-android-1.3.0_cbe6e701cc6934e3e3c2d1595919c624dd6460ec.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/navi-3dmap-5.3.0_3dmap5.3.0_55d74fe8236f1ee35ccf2277353e6c3edecb88a5.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_e651bac7868df2b3e12ef8539aa3da3f166149a6.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/support-annotations-25.2.0_cefc7f7254bf400b36ebb6860f6bafc23d84ca11.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_8ffb0cb8487034565a1300c76a76ceb3e100293c.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_32535a516d8c730b29f9c55e80803888fb99e80f.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_448f309cffd3daf74d5d1082da286ab4b40e5afc.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/staticlayout-proxy-1.0_0f49dd5cb2d58737a594a3544e68cdd447e7d9ee.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_260973e17686c274ce05a70005c30eb170aa5177.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/okhttp3-integration-1.5.0_00ac232e5d0e83dea4953f09b9b47036785b16cc.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/infer-annotations-4.0_6e6e9498ce7e6023902c355051b7e13c9156a3e7.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/jsr305-3.0.0_19f2dae531b9d820ef2d3cf7bba81437005c20b8.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_00e81a382eaf36291749e523aca98f58b0312311.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_05b3f821ede97f9b1ce91ce03abe3f3f9defdc95.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_19dce9468d5f13e160876b2813358dec77fba091.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_3fb787280ca6bb8794758e8db8c599c8e046078d.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_d64f5d40740cef62292501777a54af57201aa6f8.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_e62d9ae7c00cb9d70c215b839612814c46ccc2d4.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_e300b928ec67a19728f1e47869d8887be44b5a37.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_a88e21b9c2fdb6d1a5380590ba250b1601b3cc97.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_b5d880df97a23642da6a7a17118e4c038f9b33db.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_303a6a0c4ec5565464b5cd26bb4e861b18343dd1.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/reactive-streams-1.0.0_e8c0fd279cd6fa67b152b696eceb8de2c3e86392.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_a32700bd516ebf91664b6b4327fe758fe036f0cd.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/jcore-android-1.1.7_b768b8923d4919a43c71fe1c13304bea497618fe.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/kotlin-stdlib-jre7-1.2.0_04c917a5b9ee9b43d8aa6288389be614e9cad353.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_dba24392cac3b0c48c364f25baafb80408ca87b3.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_a94d1d03a7e82a074cce497759f96ee4244f6087.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/okhttp-3.6.0_21c09ddcafed4531fb4855ff9fe8d3278eff0154.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/javax.inject-1_6b2000b3074f1da91a9043e1a40cc07cc04863fb.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/jshare-wechat-android-1.3.0_83fb7b184026428e8be4b85fe11b24c17d81587c.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_86a273fdcbe2a0d77a23af0ae792d597deda83d0.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/jshare-qq-android-1.3.0_47fe35742530c49a4491fcb5c85b071fd7622e4a.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/bolts-tasks-1.4.0_15307090dae003746e7096619873eaff153aeb4d.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/okhttp-urlconnection-3.6.0_3f249c0d732748a9bae20a83b110d3b32c57b970.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/annotations-13.0_f7d10d6d93c0777802017eeef3f2db4ff864cccf.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_fb1dd1cc6ed194f8a3fc9e7108eddff83bec83cc.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_62937ecf78a2dbb489eed132b0a8ea1f1c587b84.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_adaad340b5f85054c448285be3fbb23fcf8aeb5c.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/okio-1.13.0_74f40018f1b7cf23e07a741d4b8beebec1e461ca.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_01244de3ae571eb5bfc1619c50a008cde53b3624.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/jpush-android-3.0.9_b0b015a98ab44899a33b1566aa96f3beafa182f3.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/debug_df70c928c56c93862a90f425f4d3601072f6b8a0.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/rxjava-2.1.0_4143a29f3a00cb2c4d9ff65cf11e7815b30c0008.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_ab574c88377038e3920363f17f45bb1895eb2628.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/jshare-facebook-android-1.3.0_c309c33a8e9b516da0207faa5064426912c5dfd9.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_b2bad05226671f4fe3c2604538d958034bd91197.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_0c4a5e2c7dd4cb3f1499840873b56f86b6ef25a2.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_b42dc492432c1eb638364d58bce3bce67ba29658.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/kotlin-stdlib-1.2.0_58f2a7982e746e7d1fb277ed5d25fbde48229da4.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_06a3a3417d4c693c30f22ec1822c188e8d96889c.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_6eb6f492490893aa480c21aac59f68aa2c551b4d.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_4b596cc23f0d5683fb46628f5c07a0106738daaf.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_987e1a09f200ab816f45872a5e66f3da1d6c864b.jar /Users/qinfensky/che-app/carknows/android/app/build/intermediates/pre-dexed/debug/classes_270dd17c784655d6c1ecd648e960790178ab67ea.jar}

**Comment by qiuxiang** [comment]
大概可以确认是你的 gradle 配置有问题，但就这些错误信息，没法确定具体的问题。

**Comment by qinfensky** [comment]
我集成其他第三方都没出现 Gradle 问题，这个是对 Gradle 有什么特殊版本要求吗？

**Comment by qiuxiang** [comment]
对 gradle 版本是没有什么特殊要求的，这显然是环境的问题，你应该自己 google app:transformClassesWithDexForDebug 错误可能的解决方案。

**Comment by qinfensky** [comment]
安卓目前编译过了,需要在 app/build.gradle 加上如下代码:
packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'lib*/*/*libGNaviData.so'
        exclude 'lib*/*/*libRoadLineRebuildAPI.so'
        exclude 'lib*/*/*libGNaviSearch.so'
        exclude 'lib*/*/*libGNaviMap.so'
        exclude 'lib*/*/*libGNaviMapex.so'
        exclude 'lib*/*/*libGNaviUtils.so'
        exclude 'lib/*/libGNaviGuide.so'
        exclude 'lib/*/libRoadLineRebuildAPI.so'
        exclude 'lib/*/libGNaviUtils.so'
        exclude 'lib/*/libGNaviPos.so'
        exclude 'lib/*/libwtbt800.so'
        exclude 'lib/*/libGNaviMapex.so'
        exclude 'lib/*/libGNaviData.so'
        exclude 'lib/*/libGNaviRoute.so'
        exclude 'lib/*/librtbt800.so'
    }

**Comment by zhouyonghui** [comment]
我用的是：
packagingOptions {
pickFirst 'lib/*.so'
}
