### ISSUE TITLE
地图定位图标是蓝色的纸飞机的图标，而不是想要的蓝色小圆点，怎么处理？

### ISSUE THREAD

**Issue by kevinchensd** [qiuxiang/react-native-amap3d#165]
下载的最新的react-native-amap3d 0.11.0版本，想要定位图标显示为蓝色的小圆点，不想要下图蓝色的纸飞机图标，这个怎么处理？

![_20180110222524](https://user-images.githubusercontent.com/26289472/34777414-3d65e51a-f655-11e7-83ee-e353fd03a37d.jpg)

**Comment by qiuxiang** [comment]
这是默认的样式 #151 有提到定位图标的定制，我已经实现了接口，测试过是可以的，但有人反馈设置不起作用，你可以先试试

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-amap3d/blob/master/src/maps/MapView.js#L15

**Comment by Aaronnnnn** [comment]
有几个属性设置不了，是因为好像是属性名称写错了，
![image](https://user-images.githubusercontent.com/24308182/35312207-59d4cc70-00f5-11e8-9543-436b8ba673ae.png)
在AMapView,kt里面

**Comment by Aaronnnnn** [comment]
有几个属性设置不了，好像是因为属性名称写错了，
![image](https://user-images.githubusercontent.com/24308182/35312248-835c39ac-00f5-11e8-9a67-136362616166.png)
在AMapView,kt里面。顺便问一下大神，image的参数有哪些呢~

**Comment by qiuxiang** [comment]
emm...确实拼错了

image 对应原生图片名称

**Comment by 1442916418** [comment]
请问怎么去除三角形旁边的淡蓝色圆圈？谢谢！

**Comment by liuyunzyj** [comment]
@qiuxiang 在3.2.4不起作用没有这个属性了 locationStyle={{
image: "flag",
fillColor: "red",
strokeColor: "red",
strokeWidth: 2
}}
