### ISSUE TITLE
Marker 组件active属性不起作用

### ISSUE THREAD

**Issue by jiasaichao** [qiuxiang/react-native-amap3d#167]
ios版本参照实例代码，加入了active属性，应该默认显示自定义信息窗口，结果是点击一下才显示
` <Marker
            active
                color='green'
                coordinate={this._coordinates[1]}>
                <TouchableOpacity activeOpacity={0.9} onPress={this._onCustomInfoWindowPress}>
                    <View style={styles.customInfoWindow}>
                        <Text>自定义信息窗口</Text>
                        <Text>{this.state.time.toLocaleTimeString()}</Text>
                    </View>
                </TouchableOpacity>
            </Marker>
`

**Comment by qiuxiang** [comment]
我可以确定，example 的例子是没问题的。我要知道你的整个代码是怎么写的。

**Comment by jiasaichao** [comment]
```
import React, {Component} from 'react'
import {Alert, StyleSheet, Text, TouchableOpacity, View} from 'react-native'
import {MapView, Marker} from 'react-native-amap3d'

export class PositionServiceScreen extends Component {
  static navigationOptions = {
    title: '添加标记',
  }

  state = {
    time: new Date(),
  }

  componentDidMount() {
    this.mounted = true
    setInterval(() => {
      if (this.mounted) {
        this.setState({time: new Date()})
      }
    }, 1000)
  }

  _coordinates = [
    {
      latitude: 39.806901,
      longitude: 116.397972,
    },
    {
      latitude: 39.806901,
      longitude: 116.297972,
    },
    {
      latitude: 39.906901,
      longitude: 116.397972,
    },
    {
      latitude: 39.706901,
      longitude: 116.397972,
    },
  ]

  componentWillUnmount() {
    this.mounted = false
  }

  _onInfoWindowPress = () => Alert.alert('信息窗口点击事件')
  _onCustomInfoWindowPress = () => Alert.alert('自定义信息窗口点击事件')
  _onDragEvent = ({nativeEvent}) => Alert.alert(`新坐标：${nativeEvent.latitude}, ${nativeEvent.longitude}`)

  render() {
    return <MapView style={StyleSheet.absoluteFill}>
      <Marker
        draggable
        title='一个可拖拽的标记'
        description={this.state.time.toLocaleTimeString()}
        onDragEnd={this._onDragEvent}
        onInfoWindowPress={this._onInfoWindowPress}
        coordinate={this._coordinates[0]}
      />
      <Marker
        active
        color='green'
        coordinate={this._coordinates[1]}>
        <TouchableOpacity activeOpacity={0.9} onPress={this._onCustomInfoWindowPress}>
          <View style={styles.customInfoWindow}>
            <Text>自定义信息窗口</Text>
            <Text>{this.state.time.toLocaleTimeString()}</Text>
          </View>
        </TouchableOpacity>
      </Marker>
      <Marker
        image='flag'
        title='自定义图片'
        coordinate={this._coordinates[2]}
      />
      <Marker
        title='自定义 View'
        icon={() =>
          <View style={styles.customMarker}>
            <Text style={styles.markerText}>{this.state.time.toLocaleTimeString()}</Text>
          </View>
        }
        coordinate={this._coordinates[3]}
      />
    </MapView>
  }
}

const styles = StyleSheet.create({
  customIcon: {
    width: 40,
    height: 40,
  },
  customInfoWindow: {
    backgroundColor: '#8bc34a',
    padding: 10,
    borderRadius: 10,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#689F38',
    marginBottom: 5,
  },
  customMarker: {
    backgroundColor: '#009688',
    alignItems: 'center',
    borderRadius: 5,
    padding: 5,
  },
  markerText: {
    color: '#fff',
  },
})


```
和example一样就是把active加到了“自定义信息窗口”的这个组件上面。
这样显示
![qq20180114-134034](https://user-images.githubusercontent.com/11605441/34913163-98d344aa-f930-11e7-8620-a0b181b58518.png)
应该是这样显示吧
![c989ec70-feab-4de7-bd36-234afb1b00bf](https://user-images.githubusercontent.com/11605441/34913165-a7f7d518-f930-11e7-9d0d-062a944f2fda.png)

**Comment by qiuxiang** [comment]
如果是这样那就没问题的，我有测试过，你能提供一个视频演示？

**Comment by jiasaichao** [comment]
![1 -14-2018 14-50-48](https://user-images.githubusercontent.com/11605441/34913648-dd8770aa-f93d-11e7-9a48-994786c884ac.gif)

**Comment by jiasaichao** [comment]
我的版本
```
		"react": "16.0.0",
		"react-native": "0.50.4",
		"react-native-amap3d": "^0.11.0",
```
运行examples试了下
还真是没问题

**Comment by qiuxiang** [comment]
如果可以，提供一个可以稳定重现问题的项目

**Comment by adventureSCL** [comment]
createMarkerView = (item, index) => {
        return (<Marker
            key={'marker' + index}
            coordinate={{
                latitude: item.latitude,
                longitude: item.longitude,
            }}
            icon={() => this.getMarkerImage(index)}
            clickable={true}
            active={isIos}
            //disabled = {!isIos}//禁用Marker的点击事件，处理浮动白框
            infoWindowEnabled={false}
            onPress={() => {
                // this.printerWindow.resetTimeCount();
                // this.setState({selectedIndex: index})
                alert('点击Marker');
                console.log('点击Marker')
            }}
        />)
    };

onPress 事件不执行，alert方法没有进入，是什么问题？

**Comment by qiuxiang** [comment]
@adventureSCL 你要确认在最简单的情况下，onPress 是不是失效，否则，就是你的用法有问题

**Comment by adventureSCL** [comment]
这个有什么注意事项吗？

**Comment by adventureSCL** [comment]
createMarkerView = (item, index) => {
        return (<Marker
            coordinate={{
                latitude: item.latitude,
                longitude: item.longitude,
            }}
            onPress={() => {
                alert('点击Marker');
                console.log('点击Marker')
            }}
        />)
    };

好像还是不可以，可以点击弹出气泡，但就是onPress方法不执行

**Comment by adventureSCL** [comment]
android 可以，在iPhone 上就不执行

**Comment by qiuxiang** [comment]
我刚测试了没问题，不过倒发现可以重现这个 issue 了

**Comment by adventureSCL** [comment]
怎么解决的？有什么问题吗？

**Comment by qiuxiang** [comment]
@adventureSCL onPress 我刚测试是没问题的
