### ISSUE TITLE
Marker onPress 如何修改当前Marker的active的值

### ISSUE THREAD

**Issue by Ariesliuh** [qiuxiang/react-native-amap3d#169]
比如这里面有3个marker，我想实现点击marker后，更换marker的图片，并且camera以这个marker为中心。我现在的实现方式是在state中设置一个数组，把marker的active绑定这个数组的一个元素，点击的时候更新这个数组中的这个元素。但貌似不起效果，我使用setState和forceUpdate2种方式，都不行。
以下是代码片段：
```javascript
constructor(props) {
    super(props);
    this.state = {
      markersActive: [],  // 记录所有markers 的状态
    }
    this.markers = [];

  }

  render() {
    let {locationEnabled, markerData, zoom, coordinate, ...others} = this.props;
    this.markers = [];
    markerData.map((val, index) => {
      const locStr = val.location;
      const lat = parseFloat(locStr.split(',')[1]);
      const lng = parseFloat(locStr.split(',')[0]);
      this.state = {markersActive: [...this.state.markersActive, false]}; // 初始化，将markers' active 设置为 false
      this.markers.push(
        <MapView.Marker
          key={index}
          clickable={true}
          active={this.state.markersActive[index]} // 绑定marker active 和 state中的属性
          icon={() =>
            <Image style={{width:20, height:28}} source={require('../../../asset/map/map-icon-gym-default-pin.png')} />
          }
          coordinate={{latitude: lat, longitude: lng}}
          onPress={({nativeEvent}) => {
            console.log(index)
            const actives = this.state.markersActive;
            actives[index] = true;
            this.setState({markersActive: actives}); // 更新state
            this.forceUpdate();
          }}
        >
          {/*hides the info window*/}
          <View style={{width:0, height:0}}></View>
        </MapView.Marker>
      );
    });

    return (
      <MapView
        locationEnabled={locationEnabled}
        showsScale={false}
        showsLocationButton={true}
        zoomLevel={zoom}
        coordinate={coordinate}
        onLocation={({nativeEvent}) => this.props.onLocation(nativeEvent)}
        onStatusChangeComplete={({nativeEvent}) => {
          console.log(nativeEvent)
        }}
        style={{flex:1}}>
        {this.markers}
      </MapView>
    );
  }
```

**Comment by qiuxiang** [comment]
你这是纯粹的 react 问题，这样的 setState 是无效的，引用根本就没变。关于 active 我就提一下，一个 mapview 只能有一个 active，我的建议是存一个 active marker 的引用而不是 active 状态列表。还有也你可以用 marker.active()。

**Comment by Ariesliuh** [comment]
@qiuxiang 
嗯，你的意思是active={true},只有一个对吧？我尝试了使用array保存所有marker的ref对象，之后点击调用，这里面有2个问题：
1. 我没有找到marker.active()方法
2.我用this.markers存储所有的ref，点击marker时候调用this.markers[index].active = true;依然无法使camera对焦到这个marker中。
我个人觉得整个过程还是没有刷新view

所以：

为了满足需求：
点击marker时，改变marker的图片，同时使view的渲染中心固定到所点击的marker上，你可否有什么好的建议。
因为我感觉这个需求是很普遍的。

**Comment by dongchuanlei** [comment]
{this.state.markerArray.map(marker => (
              <AMapView.Marker
                key={marker.type}
                title={marker.startAddress}
                description={marker.startDetail}
                coordinate={{latitude:marker.latitude,longitude:marker.longitude}}
                image={'app_image_location_start'}
                active={marker.type == this.state.pinCode ? true : false}
                onPress={()=> this.setState({pinCode:marker.type})}
                >
              </AMapView.Marker>
        ))}
我是这样实现的, 完全没问题

**Comment by qiuxiang** [comment]
@Ariesliuh 就像 @dongchuanlei 一样，用 key，然后存一个 activeMarkerKey，map markers 的时候就判断 key 是否为 activeMarkerKey 就可以根据条件渲染了。

**Comment by Ariesliuh** [comment]
@qiuxiang @dongchuanlei 感谢你们的回复，我设置active属性貌似还是不能够让camera自动以pressed marker为中心，所以不太清楚active的作用。但用animateTo方式也可以解决。图片的问题也解决了，使用的方式就是你们提到的方式通过保存key值并判断。
