### ISSUE TITLE
请问一下ios能否不用pod导入依赖包

### ISSUE THREAD

**Issue by BrutHellman** [qiuxiang/react-native-amap3d#17]
pod之前装过一次，似乎装出问题了

**Comment by qiuxiang** [comment]
当然可以，不用 cocoapods，自己配置也是可以的，只是这个过程我觉得非常麻烦且容易出错。

我自己没有手动配置的经验，你只能参考 http://lbs.amap.com/api/ios-sdk/guide/create-project/manual-configuration

**Comment by BrutHellman** [comment]
好的，3q
