### ISSUE TITLE
offline方法download后如何加载离线地图

### ISSUE THREAD

**Issue by zhangyuwu123** [qiuxiang/react-native-amap3d#170]
offline获取下载离线地图后如何加载离线地图了，
  getProvinces: () => AMapOffline.getProvinces(),
  getCities: () => AMapOffline.getCities(),
  download: name => AMapOffline.download(name),
  remove: name => AMapOffline.remove(name),
  addDownloadListener: callback => eventEmitter.addListener('download', callback)
只提供了这几个方法，download后如何加载离线地图；

**Comment by qiuxiang** [comment]
离线地图是自动加载的 http://lbs.amap.com/api/android-sdk/guide/create-map/offline-map

**Comment by zhangyuwu123** [comment]
哦，刚看了下下高德离线的使用说明，调用download后在Offline.addDownloadListener打印出信息data {progress: 0, state: "", name: "北京市"},但是图层是空白的。而且我是每次进地图页面都download一次，因为我不知道本地是否有离线地图包；我使用的方式是否正确了？

**Comment by qiuxiang** [comment]
你测试的是 android 还是 ios？

**Comment by zhangyuwu123** [comment]
android的版本

**Comment by zhangyuwu123** [comment]
andriod版本的

**Comment by qiuxiang** [comment]
我测试了，是没问题的，要确定是不是已经下载离线地图，一个方法是调用 `getCities` 或 `getProvinces`，列表数据项 `state: 'downloaded'` 就是已经下载了的；另一个方法是看本地目录 `/sdcard/amap/data/map` 下面会有已经下载了的地图包，比如 `wuhan.dat`

**Comment by zhangyuwu123** [comment]
请教个问题，在Offline.js里加几个方法，本地调试，麻烦推荐些资料，官网的原生模块封装太简单了，引入复杂的sdk还是不知道怎么搞。

**Comment by qiuxiang** [comment]
做 RN 的原生模块开发关键无非是要知道 native 和 js 怎么相互调用以及传参，这点上，官方文档已经都提到了。我就是看官方文档还有参考官方实现的原生模块，所以我是没有资料可推荐的。

**Comment by hbsblinking** [comment]
请问下 我的包也下载了 但是断网之后 还是加载不出来  这是为啥 ?
