### ISSUE TITLE
安装ios环境有问题，求大神解答

### ISSUE THREAD

**Issue by kongleeme** [qiuxiang/react-native-amap3d#172]
react-native 0.44.3 ios安装有问题：
[!] CocoaPods could not find compatible versions for pod "React/BatchedBridge":
  In Podfile:
    React/BatchedBridge (from `../node_modules/react-native/`)

None of your spec sources contain a spec satisfying the dependency: `React/BatchedBridge (from `../node_modules/react-native/`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

我按照提示更新pod也不行

**Comment by qiuxiang** [comment]
RN 版本太低，早就不支持了，你可以试试去掉 `BatchedBridge`。

**Comment by kongleeme** [comment]
我没有学过原生，这玩意是干什么的？BatchedBridge

**Comment by kongleeme** [comment]
去掉会不会有什么隐患？

**Comment by qiuxiang** [comment]
如果你知道怎么看 podspec 的话，`BatchedBridge` 是一个子依赖。

https://github.com/facebook/react-native/blob/master/React.podspec
https://github.com/facebook/react-native/blob/v0.44.3/React.podspec

**Comment by kongleeme** [comment]
好，多谢了

**Comment by qiuxiang** [comment]
0.47，但其实是几乎任何版本都能用，只是可能有些地方要稍做修改

**Comment by kongleeme** [comment]
我现在是android和ios一块开发，link以后再用pod重新设置ios环境，现在还是报文件路径错误，有什么好的解决方案吗？还是必须要手动改

**Comment by qiuxiang** [comment]
自己想办法，ios android 分开 link 的话只能自己改配置或做备份。
