### ISSUE TITLE
link 问题

### ISSUE THREAD

**Issue by johanntony** [qiuxiang/react-native-amap3d#173]
android 要link，ios不要link，都在主目录才能link，我怎么选择link哪个

**Comment by qiuxiang** [comment]
我是没有什么好的办法，或者手动改配置或者备份，react-native-maps 就简单粗暴的说 android 也不能 link，干脆就让你手动配置。

**Comment by johanntony** [comment]
作者 我现在需要groudoverlay 我现在写了一个ios的桥接了，但是我不会安卓，你要不要来写一个，福利大众一下

**Comment by qiuxiang** [comment]
暂时没时间

**Comment by johanntony** [comment]
作者，安卓上面mapview渲染当前的页面，滑动出不来，ios刚进去的时候出不来，滑动一下才会出来，是我用法不对吗,我去掉regionLimite 就不会了.
<MapView style={StyleSheet.absoluteFill}
                locationEnabled
                zoomLevel={8}
                showsBuildings={false}
                showsCompass={false}
                limitRegion={{
                    latitude: (24.474807 - 24.462063) / 2 + 24.462063,
                    longitude: (117.648575 - 117.624655) / 2 + 117.624655,
                    latitudeDelta: (24.474807 - 24.462063),
                    longitudeDelta: (117.648575 - 117.624655)
                }}>
                {
                    groundOverlay
                }
                <Marker
                    active
                    draggable
                    title='一个可拖拽的标记'
                    description={this.state.time.toLocaleTimeString()}
                    onDragEnd={this._onDragEvent}
                    onInfoWindowPress={this._onInfoWindowPress}
                    coordinate={this._coordinates[0]}
                />
                <Marker
                    color='green'
                    coordinate={this._coordinates[1]}>
                    <TouchableOpacity activeOpacity={0.9} onPress={this._onCustomInfoWindowPress}>
                        <View style={styles.customInfoWindow}>
                            <Text>自定义信息窗口</Text>
                            <Text>{this.state.time.toLocaleTimeString()}</Text>
                        </View>
                    </TouchableOpacity>
                </Marker>
                <Marker
                    image='flag'
                    title='自定义图片'
                    coordinate={this._coordinates[2]}
                />
                <Marker
                    title='自定义 View'
                    icon={() =>
                        <View style={styles.customMarker}>
                            <Text style={styles.markerText}>{this.state.time.toLocaleTimeString()}</Text>
                        </View>
                    }
                    coordinate={this._coordinates[3]}
                />
            </MapView>

**Comment by qiuxiang** [comment]
你贴的代码没法看呀

**Comment by johanntony** [comment]
![2018-01-22 4 00 56](https://user-images.githubusercontent.com/3167844/35210801-a2a90668-ff8e-11e7-88fb-87b0e298c55a.png)

**Comment by qiuxiang** [comment]
你还是自己看吧。。因为不知道你的 groundOverlay 是什么

**Comment by johanntony** [comment]
我的groundOverlay去掉也是一样的，真心的你不信自己试一下，渲染有问题

**Comment by qiuxiang** [comment]
你上面的描述我没看明白，具体什么问题？

**Comment by johanntony** [comment]
就是 我需要用limitRegion 这个属性定住我当前可以看的区域，不让他乱滑动，当然他也是可以放大缩小的，只是限定在这个区域坐标里面，我这个区域可能是有点大的（大概两个屏幕吧)，在安卓上面，刚初始化的时候，只显示当前屏幕的地图（没有任何盖图的)，我滑动到其他地方，其他地图的区域没有渲染出来（就是白白的)，ios那边，刚初始化的时候，整个屏幕是白的，滑动一下，才渲染出来。
当然我去掉这个limitRegion就是问题都没有了，但是需求就过不了了
