### ISSUE TITLE
程序包cn.qiuxiang.react.amap3d不存在

### ISSUE THREAD

**Issue by lj2312763** [qiuxiang/react-native-amap3d#176]
我用的react-native的0.49.5版本的，使用react-native-amap3d，就会报错
F:\product\AwesomeProjec\bdgps_native_2\android\app\src\main\java\com\bdgps_native\MainApplication.java:6: 错误: 程序包cn.qiuxiang.react.amap3d不存在
import cn.qiuxiang.react.amap3d.AMap3DPackage;
                               ^
F:\product\AwesomeProjec\bdgps_native_2\android\app\src\main\java\com\bdgps_native\MainApplication.java:28: 错误: 找不到符号
            new AMap3DPackage(),
                ^
  符号: 类 AMap3DPackage
2 个错误

FAILURE: Build failed with an exception.

但是下载你的demo就没问题？？？？

**Comment by qiuxiang** [comment]
gradle 依赖配置不正确，你 link 正确了？

**Comment by lj2312763** [comment]
_# **我link了，我看配置文件都有**_

# **_\android\settings.gradle_**
rootProject.name = 'bdgps_native'
include ':react-native-amap3d'
project(':react-native-amap3d').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-amap3d/android')
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')

include ':app'



# **_\android\app\src\main\java\com\bdgps_native\MainApplication.java_**
package com.bdgps_native;

import android.app.Application;

import com.facebook.react.ReactApplication;
import cn.qiuxiang.react.amap3d.AMap3DPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new AMap3DPackage(),
            new RNDeviceInfo()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

**Comment by qiuxiang** [comment]
这看起来不是一个常规问题，自己看看为什么 example 可以，另外，编译测试也可以作为参考

**Comment by lj2312763** [comment]
我看了与你的demo有出入的地方的
# **demo _settings.gradle_**
include ':react-native-amap3d'
project(':react-native-amap3d').projectDir = new File(rootProject.projectDir, '../../android')

# **_我的settings.gradle_**
include ':react-native-amap3d'
project(':react-native-amap3d').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-amap3d/android')

**Comment by lj2312763** [comment]
第一次编译的时候，会下载很多  .jar包，下载了很久都没有反应，demo下载了一段时间就好了。
第二次我在启动的时候就不会再去下载   .jar包了，然后就报错了

**Comment by qiuxiang** [comment]
这样的配置是没问题的，example 引用的路径不同而已。

下载慢，你可能要设置 gradle 代理。

**Comment by lj2312763** [comment]
但是，项目就不在下载那些  .jar包了，我新建的项目也不会下了，就直接进行编译

**Comment by qiuxiang** [comment]
你试过 android studio？

**Comment by lj2312763** [comment]
用了android studio还是不行，我想着怎么能把下载的   .jar包删除，说不定会好，但是不知道怎么删除

**Comment by Aaronnnnn** [comment]
我有同样的问题，删除了Android下的build文件夹，删除了app下的build文件夹，清理缓存后，重新run-Android就可以了

**Comment by lj2312763** [comment]
@Aaronnnnn 我按照你说的做了，但还是找不到包，你当时还有别的操作吗

**Comment by xie438305665** [comment]
这个问题解决了？ 我也遇到了一样的问题

**Comment by qiuxiang** [comment]
@xie438305665 这个根本就不是问题，而是个人配置喝本地环境导致的

**Comment by lichao2018** [comment]
我把百度地图，google地图相关的东西删除就好了

**Comment by NicoleQi** [comment]
我也遇到了这个问题，找了好久。最后发现，react-native link react-native-amap3d 执行这个命令的时候，配置了一些文件，但是app/build.gradle文件中的依赖并没有注入  compile project(':react-native-amap3d')，粘贴到dependencies中就可以了
