### ISSUE TITLE
有办法获取当前屏幕上下左右的坐标吗

### ISSUE THREAD

**Issue by ittianyu** [qiuxiang/react-native-amap3d#18]
现在 nativeEvent 中只有中心坐标和缩放级别

**Comment by qiuxiang** [comment]
你是想要 x y？

**Comment by ittianyu** [comment]
对，我想要当前屏幕 左下角 和 右上角的 经度纬度

**Comment by qiuxiang** [comment]
经纬度，目前只有 Press 事件提供

**Comment by ittianyu** [comment]
我现在是通过 onStatusChangeComplete 获取的屏幕中心经纬度
我记得安卓SDK有如下方法可以获取当前摄像头的范围，也就是左下和右上的经纬度，希望大神能加上
```
        LatLngBounds visibleBounds = aMap.getProjection().getVisibleRegion().latLngBounds;
```

**Comment by qiuxiang** [comment]
我估计你需要一个转换屏幕坐标到经纬度的功能：
http://a.amap.com/lbs/static/unzip/iOS_Map_Doc/AMap_iOS_API_Doc_3D/_m_a_geometry_8h.html#a849e7a4ab4b62647e497d6b93a1307cc
http://a.amap.com/lbs/static/unzip/Android_Map_Doc/3D/com/amap/api/maps/Projection.html#fromScreenLocation-android.graphics.Point-

**Comment by ittianyu** [comment]
我并不需要这么通用的方法，我只需要 当前可见范围
安卓中是 aMap.getProjection().getVisibleRegion().latLngBounds;
iOS中没找到，但有 MAMapView.visibleMapRect 获取到屏幕坐标

**Comment by qiuxiang** [comment]
库的接口肯定是考虑通用性的，当然这里还要考虑引入屏幕坐标的必要性，就目前来看还不太有必要。那么添加获取当前 region 的接口就可以了，除此之外，还要考虑数据类型的统一，已定义的 [Region](https://github.com/qiuxiang/react-native-amap3d/blob/master/components/PropTypes.js#L8) 就很合适。

**Comment by qiuxiang** [comment]
我居然找不到在 JS 端调用 Native UI Component Method 并获取返回值的方法，貌似只有在事件里才能得到 Native 的反馈。

现在 onStatusChangeComplete 事件里可以得到 latitudeDelta 和 longitudeDelta。

**Comment by ittianyu** [comment]
非常感谢大佬
