### ISSUE TITLE
 如何对整个工程进行调试修改

### ISSUE THREAD

**Issue by zhouzhiqiangzzq** [qiuxiang/react-native-amap3d#180]
我想基于作者的源码进行修改（添加些我需要的功能），如何做到边修改边调试呢
我的做法：
1、clone 整个工程到本地
2、执行npm link,
3、cd 到 example,删除 package.json中的 react-native-amap3d 依赖
4、执行 npm link react-native-amap3d，
5、在android 上run 
6、报错

求各位指点 正确的做法是啥（以这个项目举例）,谢谢

**Comment by qiuxiang** [comment]
我是用 example 进行开发测试的，example 的安装已经有说明了，不需要 react-native link，如果是 android 开发，可以用 android-studio 直接打开 example/android，ios 也差不多。

唯一需要注意的是，js 依赖不管怎么样都要放在 example/node_modules，依赖项 react-native-amap3d 是什么都不能是相对路径，也不能用 npm link。

对 js 的修改，要么是直接改 example/node_modules/react-native-amap3d 下面的，要么在外面写好然后复制进去。虽然有点麻烦，但我也没有发现更好的办法，还好 js 部分一般不怎么改。
