### ISSUE TITLE
打包成apk之后坐标定位不准

### ISSUE THREAD

**Issue by InitialSugar** [qiuxiang/react-native-amap3d#182]
- "react": "16.0.0",
  - "react-native": "0.50.3",
  - "react-native-amap3d": "^0.10.1",
  - 代码在测试的时候坐标显示是正确的，显示我当前位置坐标，进行准确的定位，但是将代码打包成apk之后安装在手机上显示的就是（0,0）的坐标，定位不准确，
  - 在提编译问题之前，请先检查最新的编译测试

**Comment by qiuxiang** [comment]
你能确定 key 的配置没问题？

**Comment by InitialSugar** [comment]
我确定呀    在还没打包之前在同一台手机上测试的时候都是正确的坐标定位   但是打包之后坐标定位就是0，0

**Comment by qiuxiang** [comment]
你这也只是看起来觉得没问题而已，可实际上，debug 和 release 的环境差太多了。我能确定的是自己的项目和 example 没问题。你有仔细看过 logcat？定位的问题提过不少，但都没有什么有用的信息，我只能认为是个人环境的问题了。

**Comment by yuezonglun** [comment]
@InitialSugar 我也遇到了打包后定位不准的问题，你是怎么解决的？
