### ISSUE TITLE
如何调用计算距离

### ISSUE THREAD

**Issue by fgxls** [qiuxiang/react-native-amap3d#183]
请问大神，我有看到您封装的计算距离方法，RN端怎么调用呢

**Comment by qiuxiang** [comment]
```javascript
```

**Comment by fgxls** [comment]
使用geolib不需要坐标转化吗？貌似不同定位软件定位得到的坐标是不同的坐标系里面的

**Comment by qiuxiang** [comment]
距离计算算法可以是通用的，我没有研究过不同坐标系偏移后的坐标对距离计算会产生多少影响。但就现有的讨论，普遍认为只要不混用坐标系，就不会什么问题。你要在意可能存在的误差，可以自己测试。
