### ISSUE TITLE
安卓配置了，但是地图不显示

### ISSUE THREAD

**Issue by DisturbJY** [qiuxiang/react-native-amap3d#185]
安卓手机，ios还没配置
 版本："react-native": "0.44.3",
望能指教

**Comment by DisturbJY** [comment]
望能指教

**Comment by qiuxiang** [comment]
你怎么调用的？

**Comment by DisturbJY** [comment]
import MapView from 'react-native-amap3d';
-----------------------------------------------
<MapView
  style={{width:375,height:300}}
  coordinate={{
    latitude: 39.37296,
    longitude: 116.37296,
  }}
/>


就这样

**Comment by qiuxiang** [comment]
然后？

**Comment by DisturbJY** [comment]
<img width="877" alt="qq20180129-140642 2x" src="https://user-images.githubusercontent.com/20720036/35495841-f31988d8-04fd-11e8-9638-6aa8f9cc2bd8.png">

**Comment by qiuxiang** [comment]
看看现在的截图

**Comment by DisturbJY** [comment]
你好，截图已上，现在我该怎么做呢，有没有好的思路，麻烦你了

**Comment by qiuxiang** [comment]
截图在哪？

**Comment by DisturbJY** [comment]
我已经上传了，不是这个吗？？
 https://user-images.githubusercontent.com/20720036/35495841-f31988d8-04fd-11e8-9638-6aa8f9cc2bd8.png

**Comment by qiuxiang** [comment]
我是说在手机上的截图

**Comment by DisturbJY** [comment]
![wechatimg6](https://user-images.githubusercontent.com/20720036/35496783-70cdccae-0502-11e8-99a0-609df1015cd0.png)

**Comment by DisturbJY** [comment]
1、$ npm i react-native-amap3d
2、$ react-native link react-native-amap3d
3、添加高德 Key
Android
获取高德 Key。

编辑 Android 项目的 AndroidManifest.xml（一般在 android\app\src\main\AndroidManifest.xml），添加如下代码：

<application>
    
    <meta-data
      android:name="com.amap.api.v2.apikey"
      android:value="你的高德 Key"/>
</application>
4、导入地图模块

我做安卓的配置就是以上的那些步骤，是不是还有其他漏了？？

**Comment by qiuxiang** [comment]
你这根本就没编译

**Comment by DisturbJY** [comment]
编译？？你好，我生成的是debug apk，还要弄什么吗

**Comment by qiuxiang** [comment]
就是 link 之后重新编译生成 apk

**Comment by DisturbJY** [comment]
谢谢作者的热心回复
我这边的run-android的错误是：

node_modules/react-native-amap3d/android/src/main/java/cn/qiuxiang/react/amap3d/AMap3DPackage.kt: (12, 1): Class 'AMap3DPackage' is not abstract and does not implement abstract member public abstract fun createJSModules(): (Mutable)List<Class<out JavaScriptModule!>!>! defined in com.facebook.react.ReactPackage
:react-native-amap3d:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-amap3d:compileReleaseKotlin'.
> Compilation error. See log for more details

**Comment by qiuxiang** [comment]
只支持 RN >= 0.47，其实也可以运行，只是要自己改，更多信息自己找已经关闭的 issue。
