### ISSUE TITLE
安卓打包体积过大，只编译arm仍然有9.7M  空工程4.4M

### ISSUE THREAD

**Issue by lpb006** [qiuxiang/react-native-amap3d#186]

**Comment by qiuxiang** [comment]
我只能给你一些意见，这个项目目前不会为了减少体积而做出改动。本来这应该是由你自己去分析并根据自己的情况做出调整。只要你想，即便是空项目的体积都能继续减。

这个项目的体积主要集中在高德 SDK，由项目代码及 kotlin 带来的体积可以忽略不计。你可以自己下载官方的 SDK。其中，如果只有地图的是 4.12 MB（打包的时候会小一些），在加入导航之后体积是 7.79 MB。所以如果你要减少体积，只有一个选择，舍去导航模块，只保留地图模块。

参考这里：http://lbs.amap.com/api/android-sdk/guide/create-project/android-studio-create-project

**Comment by lpb006** [comment]
@qiuxiang 非常感谢
