### ISSUE TITLE
您好，我android安装依赖遇到问题

### ISSUE THREAD

**Issue by Leijiawei** [qiuxiang/react-native-amap3d#188]
react-native-cli: 2.0.1
react-native: 0.50.3

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

android的配置我是进行的手动配置，没有link
希望得到您的帮助，谢谢！！！

**Comment by qiuxiang** [comment]
这个问题我没遇到过，自己看 https://github.com/qiuxiang/react-native-amap3d/issues?q=is%3Aissue+app%3AtransformClassesWithDexForDebug+is%3Aclosed
