### ISSUE TITLE
直接react-native run-ios 报错

### ISSUE THREAD

**Issue by ym1058117490** [qiuxiang/react-native-amap3d#19]
按照  https://github.com/qiuxiang/react-native-amap3d
上面的配置后，直接react-native run-ios  ，都没写页面，，就报错，启动就失败了

node_modules/react-native-amap3d/ios/AMapView.h:1:9: fatal error: 'MAMapKit/MAMapKit.h' file not found
#import <MAMapKit/MAMapKit.h>
        ^
1 error generated.

** BUILD FAILED **

**Comment by qiuxiang** [comment]
参考这里 https://github.com/qiuxiang/react-native-amap3d/issues/10#issuecomment-315544795 确定 Pods 已经安装成功了吗？

**Comment by ym1058117490** [comment]
方便邮件沟通吗，，这个上面图片上传太慢了

**Comment by qiuxiang** [comment]
你可以通过 i@7c00.cc 联系我
