### ISSUE TITLE
AppDelegate.m:14:9: fatal error: 'AMapFoundationKit/AMapFoundationKit.h' file not found 

### ISSUE THREAD

**Issue by wuge123** [qiuxiang/react-native-amap3d#193]
build都已经成功，可是一运行就报这个错，搞了很久不知道到底是什么原因
然后模拟器就报下面这个错native module cannot be null
![1f1228d9-5498-4bda-8d0a-d8f1ca4ec559](https://user-images.githubusercontent.com/11834723/35688285-cacf157c-07ab-11e8-90bd-e72612db6ded.png)

但是react模块是已经导入进去了的,另外我是手动配置的。
![qq20180201-233116](https://user-images.githubusercontent.com/11834723/35686799-1eb070d6-07a8-11e8-8f5e-b829dc6cc29d.png)

之后我重新用cocoapods方法出现ld: framework not found AMapFoundationKit

**Comment by qiuxiang** [comment]
这说明根本就没把这个项目的原生模块编译进去

**Comment by TanTouJunJun** [comment]
我也是手动配置的，碰到了，跟你同样的问题，请问你解决了吗？怎么解决的，求救啊！！

**Comment by GuoJiKaiHehe** [comment]
@TanTouJunJun   请问呢解决了没？ 求救
