### ISSUE TITLE
用cocoapods的方法出现ld: framework not found AMapFoundationKit

### ISSUE THREAD

**Issue by wuge123** [qiuxiang/react-native-amap3d#195]
我用cocoapods的方法出现ld: framework not found AMapFoundationKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![qq20180202-014016](https://user-images.githubusercontent.com/11834723/35693791-3b6032c2-07ba-11e8-9918-9f69d7cccba6.png)

这是我的Podfile内容
platform :ios, '8.0'

target 'dust' do
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'BatchedBridge',
    'DevSupport',
  ]
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios/'
end

**Comment by qiuxiang** [comment]
自己看 https://travis-ci.org/qiuxiang/react-native-amap3d/jobs/336143818
