### ISSUE TITLE
Marker 下的onPress 方法不执行（iOS 平台，RN版本0.5.1，设备iphone6s 11.2.5系统）请大神看看有什么问题，非常感谢🙏

### ISSUE THREAD

**Issue by adventureSCL** [qiuxiang/react-native-amap3d#196]
//根据后台得到的经纬度绘制poi点
createMarkerView = (item, index) => {
         return (<Marker
             key={'marker' + index}
             coordinate={{
                 latitude: item.latitude,
                 longitude: item.longitude,
             }}
             draggable={true}
             icon={() => this.getMarkerImage(index)}
             infoWindowEnabled={false}
//这个方法可以执行，方法内的代码被执行
             onDrag = {()=> {
                // alert('jj')
                 this.printerWindow.resetTimeCount();
                 this.setState({selectedIndex: index})
             }}
//这个方法不执行，方法内的代码不执行
             onPress={() => {
                 alert('kk')
                 this.printerWindow.resetTimeCount();
                 this.setState({selectedIndex: index})
             }}
        />)
    };
//这个问题困扰了我好久，希望能的到大神指点迷津！🙏🙏

**Comment by qiuxiang** [comment]
请先检查 [Example](https://github.com/qiuxiang/react-native-amap3d#%E6%9B%B4%E5%A4%9A%E7%A4%BA%E4%BE%8B)

https://github.com/qiuxiang/react-native-amap3d/blob/ab76c21497e57b8d415f2b81ed502921d7b82e4e/example/examples/marker.js#L98

**Comment by adventureSCL** [comment]
检查了，一模一样的写法，好像还是不能用。你那边能确认一下吗？

**Comment by qiuxiang** [comment]
我需要确认，你运行过了 Example 了吗，Example 的 onPress 方法能不能用？

**Comment by adventureSCL** [comment]
是的

**Comment by adventureSCL** [comment]
没有效果

**Comment by qiuxiang** [comment]
那我就没办法了，你的问题我怎么也没法重现，而同一个项目，在你那边却表现不一样

**Comment by adventureSCL** [comment]
我的水平有限，可能不太了解RN的机制，还有地图marker点击方法onPress的实现是怎样的，在这里我借助你的代码实现了我要的效果：下面是我改动的地方：AMapMarker.m
- (void)_handleTap:(UITapGestureRecognizer *)recognizer {
        self.onPress(NULL);
        [_mapView selectAnnotation:_annotation animated:YES];
}
实现点击其余marker点执行onPress方法，当前定位点会崩溃（可以用其余方法解决）
这样想的初衷是因为（在oc中我没找到onPress的调用）。
本人菜鸟一个，写得不对，还请谅解。

**Comment by qiuxiang** [comment]
onPress 的调用在：
https://github.com/qiuxiang/react-native-amap3d/blob/ab76c21497e57b8d415f2b81ed502921d7b82e4e/lib/ios/AMap3D/maps/AMapViewManager.m#L122

只要 Annotation Selected 就触发 didSelectAnnotationView，根本就没必要在其他地方调用 onPress。
