### ISSUE TITLE
求助！！！android link 以后在MainApplication导入不了。

### ISSUE THREAD

**Issue by allyju** [qiuxiang/react-native-amap3d#198]
正在使用的版本、RN 版本、设备信息
   "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    android  6.0.1
使用了npm i react-native-amap3d  
然后  react-native link react-native-amap3d

但会报如下错： 
Error:Unable to find module with Gradle path ':react-native-amap3d' (needed by module 'app'.)

检查了node_modules 里面的 react-native-amap3d    发现只有一个lib 。没有像导入一样出现android与ios 两个文件夹。如下：
![tim 20180205151740](https://user-images.githubusercontent.com/10126204/35792384-cdecb032-0a87-11e8-9da1-d16fa76196ef.png)

**Comment by qiuxiang** [comment]
只支持 RN >= 0.47
