### ISSUE TITLE
地图无法正常显示

### ISSUE THREAD

**Issue by CrayonShin-chan** [qiuxiang/react-native-amap3d#199]
地图显示不出来啊，只有一个红色边框
![screenshot_2018-02-05-16-55-19-153_com anyzdz](https://user-images.githubusercontent.com/32329565/35795838-7fee6d0e-0a95-11e8-843b-13b476ff8d94.png)

**Comment by qiuxiang** [comment]
没有 link 并编译

**Comment by CrayonShin-chan** [comment]
不是啊 ，我link了的

**Comment by CrayonShin-chan** [comment]
![tim 20180206091142](https://user-images.githubusercontent.com/32329565/35836907-c98f1f66-0b1d-11e8-8fec-91f1917ae9c3.png)

**Comment by qiuxiang** [comment]
重新编译了？

**Comment by CrayonShin-chan** [comment]
重新编译是什么指令啊？不是npm install吗？

**Comment by qiuxiang** [comment]
`react-native run-android`

**Comment by CrayonShin-chan** [comment]
我试了。。。没用，就是地图不能显示，很奇怪

**Comment by qiuxiang** [comment]
那就是你自己的问题了，因为我不知道你是怎么配置的，做了哪些改动，你需要自己检查原生模块的编译情况。

**Comment by CrayonShin-chan** [comment]
原生模块的编译是查看哪个文件呢

**Comment by qiuxiang** [comment]
最好自己了解下 RN 的原生模块是怎么编译进去的，要是我给你列一个长长的检查清单就太浪费我时间了。

先说一个最简单的检查，你吧 apk 文件解压，看看有没有高德 SDK 的库文件就知道有没有编译进去了。

**Comment by qiuxiang** [comment]
其次，你可能要检查 gracdle 配置

**Comment by CrayonShin-chan** [comment]
哦哦，好的，谢谢

**Comment by CrayonShin-chan** [comment]
找到问题了，是buildtools的版本太低了，所以不能编译成功
