### ISSUE TITLE
Apple Mach-O Linker Error Group

### ISSUE THREAD

**Issue by NodeList** [qiuxiang/react-native-amap3d#2]
Xcode8.3 编译报错 Apple Mach-O Linker Error Group ，clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by qiuxiang** [comment]
有用的信息太少了。
是编译 example 还是新项目出的错？

**Comment by NodeList** [comment]
example 和新建的项目 用Xcode 编译都会报错
 ![image](https://user-images.githubusercontent.com/9954739/27510400-21d5b9a2-5942-11e7-814d-3543c6b0759d.png)，
example run-ios 会提示 BUILD SUCCEEDED 但是运行会报错 
![image](https://user-images.githubusercontent.com/9954739/27510432-bd340b2e-5942-11e7-980f-7eb51f5488cb.png)

**Comment by qiuxiang** [comment]
如果你要用 xcode 运行的话，要打开 Example.xcworkspace，而不是 Example.xcodeproj。

实际上没必要打开 xcode，`npm run ios` 编译成功的话说明配置是没有问题的，之所以会打包错误是因为 `npm install` 的时候没有把 `file:..` 复制，而是进行链接，这会导致路径错误，所以我特地写了 `init` 脚本来处理这个问题。你应该是忘了运行 `npm run init`。

如果是新项目，通过 `npm i react-native-amap3d` 的方式进行安装是不会出现打包错误的。

**Comment by NodeList** [comment]
解决了，react-native 0.45 执行 pod install 后 会提示 jschelpers/JavaScriptCore.h file not found 
[Ship third-party-podspecs in the npm package #13922](https://github.com/facebook/react-native/issues/13922)

我把Podfile修改了下编译成功

```
platform :ios, '8.0'

target 'App' do
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge',
  'Core',
]
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'
end
```

**Comment by qiuxiang** [comment]
我还没试过 0.45

**Comment by qiuxiang** [comment]
我新建项目试了下，0.45 确实会出现 _jschelpers/JavaScriptCore.h file not found_ 的错误，那是因为 default_subspec "Core" 不再依赖 cxxreact，而这个库间接依赖 jschelpers。

你上面提到的 issue 虽然不是直接关联，但提供了线索：https://github.com/facebook/react-native/commit/5aca739cc25949eebc04a0309c2944f92b5b5391。

那么解决的方法其实不是添加 subspaces => ['BatchedBridge', 'Core']，而是 subspaces => ['jschelpers_legacy']，BatchedBridge 只是因为依赖 jschelpers_legacy 而恰巧解决了问题 。

还有另一种方法，就是使用新的 jschelpers，但这样 Podfile 写起来就很麻烦，因为要依赖 Folly、DoubleConversion、GLog、boost，而且还不能直接引用 third-party-podspecs（或者是我的方法不对？）。不管怎么样，你的 Podfile 大概会写成这样：
```ruby
platform :ios, '8.0'

target 'Your Target' do
  pod 'Folly', path: '...'
  pod 'DoubleConversion', path: '...'
  pod 'GLog', path: '...'
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'jschelpers',
  ]
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'
end
```
