### ISSUE TITLE
一个路由导致的问题。。。

### ISSUE THREAD

**Issue by FFlainsF** [qiuxiang/react-native-amap3d#20]
使用 router-flux 作为路由（3.X） rn 版本 0.44 
使用了 tab 其中两个tab页面都使用了地图
然后 页面二使用地图时 页面一已存在的地图会覆盖在页面二的地图上
如果页面二没有用地图的话  页面一的地图不会覆盖到页面二（这才是正常情况。。。）
。。。。。 具体请看图 请各位大大分析一下 thanks
![ty](https://user-images.githubusercontent.com/29249395/28661288-c0c56e62-72e8-11e7-903d-dd29921b91d3.png)

**Comment by qiuxiang** [comment]
或许和我之前遇到的问题是一样的，当时是用 react-navigation 的 tabs，出现了奇怪的问题。但因为还要赶着做项目，我也没有深究，后来就换了 react-native-navigation，就没有类似覆盖的问题。但也还是有手势混乱的问题，后来在官方文档 http://a.amap.com/lbs/static/unzip/Android_Map_Doc/index.html 得到了解答。

于是我的 Android 项目上实际用的是 TextureMapView。

**Comment by FFlainsF** [comment]
TextureMapView。 来代替 MapView 吗？

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-amap3d/blob/master/android/src/main/java/cn/qiuxiang/react/amap3d/AMapView.kt#L17 这里改为继承 TextureMapView 试试看。

**Comment by FFlainsF** [comment]
搞定 谢谢 大佬！！
你是我发现 做react native 中国大陆地区能用的地图 做的很不错的了
 赞一个
