### ISSUE TITLE
为什么开启定位模块还是显示北京

### ISSUE THREAD

**Issue by wuge123** [qiuxiang/react-native-amap3d#200]
<MapView 
              style={StyleSheet.absoluteFill}
              locationEnabled
              locationInterval={10000}
              distanceFilter={10}
              onLocation={({nativeEvent}) =>
                console.log(`${nativeEvent.latitude}, ${nativeEvent.longitude}`)}
            >
            
            </MapView>

**Comment by qiuxiang** [comment]
首先，定位后不会移动到定位点，其次，有没有定位成功看 onLocation

**Comment by wuge123** [comment]
能否加下你qq

**Comment by qiuxiang** [comment]
我不用 QQ，你可以给我发邮件，不过如果你的问题是关于这个库的，在这里讨论就好。

**Comment by wuge123** [comment]
我用的是xcode模拟器定位返回的怎么会是37.785834, -122.406417这样的

**Comment by qiuxiang** [comment]
有问题吗，坐标是模拟器设置的

**Comment by wuge123** [comment]
我用真机调试还是一样，地图返回北京，可是我现在在深圳

**Comment by qiuxiang** [comment]
我再看了下你上面给出的坐标，这不是模拟器默认的定位地址“苹果总部”吗，这说明已经定位正确了。

看来你没有理解我一开始所说的。

**地图不会在定位成功后移动到目标位置**，也就是说，如果你所谓的“地图返回北京”是期望定位后自动移动到定位点，从根本上就不对了。

**Comment by wuge123** [comment]
我现在人在深圳，那如何一打开app就自动定位到当前位置

**Comment by qiuxiang** [comment]
不是有接口可以设置地图中心坐标吗。

**Comment by wuge123** [comment]
我想要的是自动定位到当前位置，而不是去设置坐标

**Comment by qiuxiang** [comment]
你要明白，这是一个公共基础库，只提供基本接口，并且保证灵活性。你觉得自己处理定位点麻烦，可是有没有想过存在不需要自动移动到定位点的情况？

**Comment by zengyimin** [comment]
清问自动移动到定位点该怎么去做？

**Comment by qiuxiang** [comment]
没有自动移动到定位点的功能……整个 issue 我一直在重复这件事。

如果希望定位后移动到定位点，需要自己在 `onLocation` 重新设置地图中心，用  `MapView#coordinate` 或 `MapView#animateTo`。

**Comment by MrLaibin** [comment]
```
- (void)setLocationEnabled:(BOOL)enabled {
    if (enable) {
        self.showsUserLocation = enabled;
        self.userTrackingMode = MAUserTrackingModeFollow;
    }else{
        self.showsUserLocation = enabled;
        self.userTrackingMode = MAUserTrackingModeNone;
    }
}
```
我项目中的方法
