### ISSUE TITLE
设置自定义图片会报错

### ISSUE THREAD

**Issue by wuge123** [qiuxiang/react-native-amap3d#203]
<MapView.Marker
              image={require('./app/assets/images/online.png')}
              title="自定义图片"
              onPress={this._onMarkerPress}
              coordinate={{latitude: 39.706901,longitude: 116.397972}}
            />
            </MapView>

**Comment by qiuxiang** [comment]
不支持这种用法，image 对应的是原生图片名称，具体看 exmaple

**Comment by wuge123** [comment]
<MapView.Marker
              image="online"
              title="自定义图片"
              onPress={this._onMarkerPress}
              coordinate={{latitude: 39.706901,longitude: 116.397972}}
            />
怎么自定义marker无法显示
![0dd1aa3c-aac3-431c-a44b-2c680b49d575](https://user-images.githubusercontent.com/11834723/35844732-e6139a78-0b49-11e8-8a6a-87f7bc21608d.png)

**Comment by qiuxiang** [comment]
参考 https://github.com/qiuxiang/react-native-amap3d/tree/master/ios

**Comment by wuge123** [comment]
我把你的Images.xcassets放到我项目下一样显示不出来maker

**Comment by wuge123** [comment]
可以了，是我把一个标签写错了，谢谢
