### ISSUE TITLE
编译通过后，应用开启一瞬间闪退

### ISSUE THREAD

**Issue by ShowPenZ** [qiuxiang/react-native-amap3d#206]
"dependencies": {
    "react": "16.2.0",
    "react-native": "0.53.0",
    "react-native-amap3d": "^0.12.1"
  },

编译通过后，应用开启一瞬间闪退
图片不知道怎么上传不了 <..>

**Comment by qiuxiang** [comment]
android？ios？错误信息？

**Comment by ShowPenZ** [comment]
android 6.0  没有错误信息  打开应用后出现高德地图画面后就直接闪退了

**Comment by qiuxiang** [comment]
用的模拟器？

**Comment by ShowPenZ** [comment]
是的 genymotion android 6.0 直接闪退了过几天闲下来 再用真机倒腾下

**Comment by qiuxiang** [comment]
模拟器的问题，自己找已关闭 issue，不再讨论。
