### ISSUE TITLE
ios虚拟机放大缩小按钮不能显示

### ISSUE THREAD

**Issue by smallriver** [qiuxiang/react-native-amap3d#209]
老铁你好:
RN 版本是 0.52.2  ios跑的是虚拟机,按照这边的api写代码,折线都画了,但是放大缩小按钮不能显示showsZoomControls  这个好像对Android有用,对ios好像没用,默认显示了指南针,但是放大缩小按钮没有

**Comment by qiuxiang** [comment]
#159，#103

**Comment by smallriver** [comment]
好的 我晓得了  非常感谢你的回复  3q
