### ISSUE TITLE
请问有没有用户移动地图后选择中心点坐标的功能？

### ISSUE THREAD

**Issue by BrutHellman** [qiuxiang/react-native-amap3d#21]
如果没有，请问下3d地图的sdk支持吗？如果支持我想办法fork过来实现一下

**Comment by qiuxiang** [comment]
不太确定你想要什么，是指移动地图后，获取当前地图的中心点，还是不管用户移动到哪，都可以重新设置地图的中心点？不管哪个都是支持的。

**Comment by BrutHellman** [comment]
是的，很简单一个选地址的功能，用户可以通过移动地图来选择他指定的位置（MapView中间有个固定的Marker），当用户移动结束后，事件回调坐标，然后我通过坐标去调用webapi中逆地理位置编码接口换取地址信息

刚刚看了下高德的安卓文档3d地图的onCameraChangeFinish事件回调参数会带有坐标

**Comment by BrutHellman** [comment]
[在这](https://github.com/qiuxiang/react-native-amap3d/blob/master/android/src/main/java/cn/qiuxiang/react/amap3d/AMapViewManager.kt#L59) 应该是可以获得中心点的

**Comment by qiuxiang** [comment]
是的

**Comment by qiuxiang** [comment]
我想我应该找个时间把文档好

**Comment by BrutHellman** [comment]
参数有问题，全部都是get、set，拿不到真正的数据

**Comment by qiuxiang** [comment]
你怎么调用？

**Comment by BrutHellman** [comment]
`<MapView 
        style={StyleSheet.absoluteFill}
        coordinate={{
          longitude: 115.886054,
          latitude: 28.596628,
        }}
        onStatusChangeComplete={(arg1) => console.log({ arg1, target: arg1.target })}
      >
      </MapView>`

**Comment by qiuxiang** [comment]
```js
onStatusChangeComplete={event => console.log(event.nativeEvent)}
```
这样才对。

**Comment by BrutHellman** [comment]
`Object {latitude: 28.596628342338676, rotation: 0, tilt: 0, longitude: 115.8860541880131, zoomLevel: 10}`

得到了，现在还有个问题，有什么思路在地图中心放个Marker

**Comment by BrutHellman** [comment]
对了，还有上次的一个 #14 问题，在模拟器上设置OpenGL ES renderer为SwiftShader就可以在模拟器上跑了

**Comment by qiuxiang** [comment]
在地图中心放置 marker 很容易，只要 marker 的 coordinate 是地图中心就可以了

**Comment by BrutHellman** [comment]
thx

**Comment by BrutHellman** [comment]
顺带再说下，固定中心点用`onStatusChange`事件，完美解决问题，再次感谢分享
