### ISSUE TITLE
Invariant violation native component for "AMapView" does not exist

### ISSUE THREAD

**Issue by dasewan** [qiuxiang/react-native-amap3d#210]
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.53.0
蓝碟模拟器
**_Invariant violation native component for "AMapView" does not exist
This error is located at :
 in AMapView (at MapView.js:264)_**
in MapView(at App.js27)

**Comment by dasewan** [comment]
大神，学习rn第一个就用您的组件做demo，遇到了一个小问题，还望不惜赐教

**Comment by qiuxiang** [comment]
确定 link 并编译通过了？
