### ISSUE TITLE
onLocation事件定位失败问题

### ISSUE THREAD

**Issue by CrayonShin-chan** [qiuxiang/react-native-amap3d#211]

**Comment by CrayonShin-chan** [comment]
![tim 20180208101047](https://user-images.githubusercontent.com/32329565/35952153-9c5ce63e-0cb9-11e8-8c87-e7d624001777.png)

**Comment by CrayonShin-chan** [comment]
为什么我获取到的数据全是0啊，大神

**Comment by luojianguang** [comment]
我每次定位进去提示返回的都是0，请问是不是要获取当前的位置需要请求高德的网址接口来获取当前的经纬度，然后animiteTo进行定位

**Comment by qiuxiang** [comment]
定位的问题请找之前的 issue，我不再参与讨论，在我看来，这是纯粹的配置问题。
