### ISSUE TITLE
Android 自定义多个Marker时 部分渲染不出来

### ISSUE THREAD

**Issue by HelenChenVIP** [qiuxiang/react-native-amap3d#215]
"version": "0.10.1",
我在循环渲染Marker时候，发现概率性的部分站点渲染不出来，但是我捕获到的数据size是对的，渲染的点不完全，多次点击后全部的点可以渲染出来，概率性事件，概率有点大。
`
this.props.mallPointList ? this.props.mallPointList.map((item,key)=>{
            if(item.fillIcon!=null && item.fillIcon!=''){
                let mLat;
                let mLon;
                let mLonAndmLat;
                if(item.dbo__T_Bas_CommonPoint__Latitude!=null && item.dbo__T_Bas_CommonPoint__Latitude!="" && item.dbo__T_Bas_CommonPoint__Longitude!=null && item.dbo__T_Bas_CommonPoint__Longitude!=""){
                    mLat=item.dbo__T_Bas_CommonPoint__Latitude;
                    mLon=item.dbo__T_Bas_CommonPoint__Longitude;
                }else{
                    mLat=35.035278;
                    mLon=118.476389;
                }
                //将84坐标改为高德坐标
                mLonAndmLat=coordinate.wgs84togcj02(mLon,mLat);
                rtnVal.push(
                <Marker   
                key={key+1} 
                active={this.state.activecode==item.dbo__T_Bas_CommonPoint__DGIMN}  
                icon={() =>{
                    if(item.dbo__T_Bas_CommonPoint__PollutantType=='23' || item.dbo__T_Bas_CommonPoint__PollutantType=='24'
                     || item.dbo__T_Bas_CommonPoint__PollutantType=='25'){
                        return(<Image source={item.fillIcon} style={{width:30,height:30}}/>);
                    }else{
                        return(<Image source={item.fillIcon} style={{width:16,height:16}}/>);
                    }
                }}                  
                onPress={()=>{
                    this.setState({activecode:item.dbo__T_Bas_CommonPoint__DGIMN});
                }}               
                coordinate={{
                latitude: mLonAndmLat[1],
                longitude: mLonAndmLat[0],}}>     
               </Marker>)
            }
             })
 `
这是界面展示Marker数目：
![image](https://user-images.githubusercontent.com/19185883/36010529-e310edc2-0d8c-11e8-94b6-f7f89313495d.png)
这是我捕获到的数据size：
![image](https://user-images.githubusercontent.com/19185883/36010541-f139b3ca-0d8c-11e8-8078-37001ea5fc19.png)
小白一枚，希望楼主寄予解决思路，谢谢！

**Comment by HelenChenVIP** [comment]
@qiuxiang

**Comment by qiuxiang** [comment]
android Marker#icon 是 hack 的实现，所以在某些情况下会有问题，特别是使用 Image 的时候。因为不知道图片什么时候加载完毕，所以我有提供一个 update 方法用于手动更新。如果只是图片，建议用 Marker#image。

**Comment by HelenChenVIP** [comment]
@qiuxiang 你好，还想请问下，这个Marker中的image的style怎么定义呢？比如现在我的图片Marker很小，我想给他的style设置width height呢。
` <Marker   
                key={key+1} 
                active={this.state.activecode==item.dbo__T_Bas_CommonPoint__DGIMN}  
                image={
                    item.fillIcon
                }
                onPress={()=>{
                    this.setState({activecode:item.dbo__T_Bas_CommonPoint__DGIMN});
                }}               
                coordinate={{
                latitude: mLonAndmLat[1],
                longitude: mLonAndmLat[0],}}>
</Marker>   `
其中：item.fillIcon是android下drawable-xxhdpi下的图片'shik_l000'......

**Comment by qiuxiang** [comment]
image 不能设置大小，如果放 drawable-xxhdpi 显得很小，那么可以考虑换到 drawable-xhdpi 甚至 drawable-hdpi，但是可能会造成图片模糊。android 会根据设备 dpi 加载相应尺寸的 drawable，具体规则自己去了解。
