### ISSUE TITLE
Android 获取行政区划数据

### ISSUE THREAD

**Issue by HelenChenVIP** [qiuxiang/react-native-amap3d#216]
"version": "0.10.1",
楼主你好：我想实现一个获取行政区划数据并给此行政区划描绘边界的功能，类似于高德API中的这个功能，请问楼主在您的Demo中可以实现吗？
http://lbs.amap.com/api/android-sdk/guide/map-data/district
![image](https://user-images.githubusercontent.com/19185883/36015447-662c2340-0da9-11e8-9efd-fb60c8092511.png)
谢谢！
@qiuxiang

**Comment by qiuxiang** [comment]
http://lbs.amap.com/api/webservice/summary/
