### ISSUE TITLE
配置了放大缩小、当前定位按钮为true，但在ios上没显示

### ISSUE THREAD

**Issue by ym1058117490** [qiuxiang/react-native-amap3d#22]
<img width="375" alt="qq20170728-160129 2x" src="https://user-images.githubusercontent.com/6307413/28708219-09131ce4-73ae-11e7-9d75-7588c2e441f7.png">

**Comment by qiuxiang** [comment]
因为 iOS SDK 并没有提这两个接口，目前只能自己在地图上放置 View，然后用 animateTo 方法进行平移、缩放。

**Comment by ym1058117490** [comment]
当前地址 ios版的  配置 高德申请的id和locationEnabled为true后，不能定位到当前详细地址，，是有什么地方需要注意吗？

**Comment by qiuxiang** [comment]
只要 key 正确了，就没问题了，你可以看看 example 里的 events demo

**Comment by ym1058117490** [comment]
我跑你的例子，也没定位出当前的位置。

**Comment by qiuxiang** [comment]
<img width="487" alt="screen shot 2017-07-28 at 6 06 21 pm" src="https://user-images.githubusercontent.com/1709072/28712909-8bbab39e-73bf-11e7-90eb-3b2996a38339.png">

你用的是模拟器，确定设置好了模拟位置？

**Comment by ym1058117490** [comment]
模拟位置怎么设置捏，不是会根据gprs自动定位的吗

**Comment by qiuxiang** [comment]
你是在手机上测试还是模拟器？

**Comment by ym1058117490** [comment]
模拟器，真机上都试了，，locationEnabled设置为true 了

**Comment by qiuxiang** [comment]
看下 example 里的“地图事件”有 onLocation 的记录吗？

**Comment by ym1058117490** [comment]
<img width="368" alt="qq20170728-205208 2x" src="https://user-images.githubusercontent.com/6307413/28717996-a22e025e-73d6-11e7-99c3-4ae058e68d7a.png">


下面会动的这个是吧。

**Comment by qiuxiang** [comment]
那就是已经有定位了

**Comment by qiuxiang** [comment]
这模拟器吧，因为没有设置 Location，所以默认定位到了美国

**Comment by ym1058117490** [comment]
不是直接locationEnabled设置为true 就行了吗，还要怎么设置

**Comment by qiuxiang** [comment]
已经定位成功了，但定位到了美国，当前视角是北京，当然看不到定位点，你设置地图中心到定位的位置就能看到了。

**Comment by ym1058117490** [comment]
能不能初始化的时候就知道当前的地址

**Comment by qiuxiang** [comment]
怎么可能呢，定位又不是马上就能得到的。

**Comment by ym1058117490** [comment]
onLocation 得到当前位置， animateTo在渲染位置，这样就回定位到当前位置了，，同时也能有定位到当前位置的按钮事件。

**Comment by qiuxiang** [comment]
不太明白你想要表达什么
