### ISSUE TITLE
关于iOS定位权限问题

### ISSUE THREAD

**Issue by fumeng354** [qiuxiang/react-native-amap3d#220]

**Comment by fumeng354** [comment]
真机和模拟器上面都会出现在刚进入APP时就申请访问定位权限。
而地图页面不在首页，造成APP在审核时被拒    
刚开始以为是js代码的问题    但是重新创建了一个新的RN工程文件    只导入了amap3d一个插件时    同样的情况出现了   所以定位错误在插件里面

**Comment by fumeng354** [comment]
有时间回复个邮件么    我这边刚解决完重复引用的问题   而且知道源头在哪   可以交流一下   fumeng354@163.com   iOS开发

**Comment by qiuxiang** [comment]
这个问题我暂时没时间确认。

你说的是什么重复引用的问题？

**Comment by fumeng354** [comment]
定位在权限出现在APP启动的问题昨天已经解决了   把导航下面的AMapDriveManager，AMapWalkManager，AMapRideManager下面的init方法注释掉就行了，但是导航没法使用了。

**Comment by fumeng354** [comment]
重复引用的问题是用cocoapod导入地图时出现的，由于项目其他插件中使用到了地图中所用到的几个依赖库，导致在react工程文件下会有一份依赖库的代码    pod下面也同时拥有一份。处理办法：点Pods-->TARGETS-->React-->Build Phases-->Compile Sources中把重复引用的.m文件减掉。这个问题可能出现的不多  我这边是接手另外一个同事的工作，他之前的代码是手动拖入的，我这边是cocoapod导入的

**Comment by qiuxiang** [comment]
我看了下，权限的问题挺好改的。

而你说的重复引用问题，就是你们的问题了。
