### ISSUE TITLE
Marker单击问题

### ISSUE THREAD

**Issue by dev-v** [qiuxiang/react-native-amap3d#222]
1、我单击marker的时候不希望该marker居中可否实现？
2、因为问题1没法实现，通过禁用默认单击事件，然后通过icon自定义marker后，在自定义的icon注册的onPress（TouchOpacity）没有效果，自定义的View可以展示。

**Comment by qiuxiang** [comment]
对于 iOS，这是默认行为，所以也没什么办法

**Comment by dev-v** [comment]
那自定义的icon上面注册的onPress没有效果能解决么？

**Comment by qiuxiang** [comment]
应该是可以解决，只是我不想因为这个原因而做出改动，因为你的做法在 android 是有问题的，android 的自定义 marker 根本就不能用 Touchable 组件。

况且，我刚测试了，点击 marker 的时候并没有强制居中呀，只是，如果 marker 显示不完全，会强制位移一小段以显示完全，而这样的行为，我觉得是完全合理的。

**Comment by dev-v** [comment]
嗯 如果情况是你这样说的 肯定说合理的
我是在android模拟器上面测试的 有强制居中的问题，不知道真机上面有没有这个问题。
另外没有再往icon上面加更多功能了，用原始提供的API基本解决我的需求了，🙏

**Comment by qiuxiang** [comment]
如果是 android 就没办法了，这是 SDK 默认的行为。

**Comment by dongchuanlei** [comment]
改Android底层代码可实现此需求, AMapView文件第60行改为true就不会出现点击强制居中现象, 不过又会出现点击marker不弹出callOut的问题, 不过可以在js层使用Marker的active属性解决实现。
