### ISSUE TITLE
ios接入成功后使用地图时，地图显示不出来，日志报错为Failed to make complete framebuffer object 8cd6

### ISSUE THREAD

**Issue by black1997** [qiuxiang/react-native-amap3d#223]
按照文档接入成功后，使用地图时，地图渲染不出来，用xcode打开，日志报错：
Failed to make complete framebuffer object 8cd6
Failed to bind EAGLDrawable: <CAEAGLLayer: 0x6040008283c0> to GL_RENDERBUFFER 1

![331519270762_ pic](https://user-images.githubusercontent.com/15035749/36519228-4461bc7c-17c5-11e8-879a-1dc20d930b03.jpg)
![wx20180222-114038](https://user-images.githubusercontent.com/15035749/36519230-44b67078-17c5-11e8-9794-821ead995237.png)

**Comment by qiuxiang** [comment]
版本是？

**Comment by black1997** [comment]
"react": "16.2.0",
 "react-native": "0.52.2",
react-native-amap3d,使用的是最新的版本

**Comment by qiuxiang** [comment]
你的 render 怎么写？

**Comment by black1997** [comment]
render() {
        return (
            <View style={styles.container}>
                <MapView
                    coordinate={{
                        latitude: 39.91095,
                        longitude: 116.37296,
                    }}
                />
            </View>
        );
    }


按照官网的实例写的，还是不行

**Comment by qiuxiang** [comment]
mapview 没有指定 width 和 height

**Comment by black1997** [comment]
真的是耶，还是建议在文档上说明一下。十分感谢哈

**Comment by perfecten** [comment]
我有地图显示出来，也能定位，但是就是后台log有错误。
（写flex：1，或者指定width/height都是一样的结果）
---------------
Failed to bind EAGLDrawable: <CAEAGLLayer: 0x6000010898a0> to GL_RENDERBUFFER 1
Failed to make complete framebuffer object 8cd6
---------------

请大神百忙之中抽空指导，不胜感激

**Comment by AlanWen2016** [comment]
原来要指定宽高
`import React from 'react'
import { MapView } from 'react-native-amap3d'
const AmapContainer = () => {
  return (
    <MapView style={{ width: 300, height: 200 }}>
      <MapView.Marker
        draggable
        title='这是一个可拖拽的标记'
        onDragEnd={({ nativeEvent }) =>
          console.log(`${nativeEvent.latitude}, ${nativeEvent.longitude}`)}
        coordinate={{
          latitude: 39.91095,
          longitude: 116.37296
        }}
      />
    </MapView>
  )
}

export default AmapContainer
`

**Comment by AlanWen2016** [comment]
原来要指定宽高
import React from 'react' 
import { MapView } from 'react-native-amap3d' 
const AmapContainer = () => { 
  return ( 
<MapView style={{ width: 300, height: 200 }}> 
<MapView.Marker draggable title='这是一个可拖拽的标记' onDragEnd={({ nativeEvent }) => console.log(${nativeEvent.latitude}, ${nativeEvent.longitude}`)}
coordinate={{
latitude: 39.91095,
longitude: 116.37296
}}
/>

)
}

export default AmapContainer
`
