### ISSUE TITLE
native module cannot be null

### ISSUE THREAD

**Issue by hecomzhangzhiguo** [qiuxiang/react-native-amap3d#224]
rn 0.50版本，部署项目手动部署，未用pod,编译通过，但当在用地图的时候提示native module cannot be null

**Comment by qiuxiang** [comment]
那就是没被编译进去

**Comment by hecomzhangzhiguo** [comment]
# #

**Comment by peppermints** [comment]
怎么解决？

**Comment by quietautumn** [comment]
解决了吗？我也遇到了，用CocoaPods能自动部署，但是用了CocoaPods后用Archive打包ipa会报错，很无奈啊。

**Comment by qiuxiang** [comment]
#84

**Comment by quietautumn** [comment]
感谢楼主，问题解决了。

**Comment by DuanYanShan** [comment]
怎么解决的？

**Comment by DuanYanShan** [comment]
你是手动配置？还是CocoaPods自动配置？ @quietautumn

**Comment by quietautumn** [comment]
@DuanYanShan ，CocoaPods自动部署的，手动部署的没成功，打算等项目上架不忙之后再来研究一下手动部署。

**Comment by DuanYanShan** [comment]
好的，谢谢，我CocoaPods自动部署的也成功了。

**Comment by zhaochu0821** [comment]
@qiuxiang  Why use pod ipa to appear white ah after the start page
