### ISSUE TITLE
xcode打包报错

### ISSUE THREAD

**Issue by alansuhe** [qiuxiang/react-native-amap3d#225]
环境：
  - RN: 0.50.3及0.53.3。

模拟运行均正常，在xcode打包时报错：
![image](https://user-images.githubusercontent.com/4684804/36574555-32d5d9b8-1881-11e8-833b-e43931e53bdc.png)
![image](https://user-images.githubusercontent.com/4684804/36574571-431a614a-1881-11e8-8b4e-74a16b3887b1.png)
查了资料，修改Pod，:subspecies => 中加入‘ BatchedBridge’，此错误消失，但出现duplicate symbols for architecture armv7。

**Comment by qiuxiang** [comment]
#189

**Comment by alansuhe** [comment]
首先，pod加入‘ BatchedBridge’是必须的吗？

**Comment by qiuxiang** [comment]
我没法亲自测试打包，就反馈来看，是必须的，不过需要注意的是，最新的 RN 用 `CxxBridge ` 取代了 `BatchedBridge`。
