### ISSUE TITLE
定位时如何显示周边的那个圆形区域

### ISSUE THREAD

**Issue by hecomzhangzhiguo** [qiuxiang/react-native-amap3d#226]
高德地图原生能够直接显示定位周边圆形区域，这个有接口吗

**Comment by qiuxiang** [comment]
你说的圆形区域是指精度圈？

**Comment by guuguo** [comment]
@qiuxiang 精度圈要去掉的话是怎么去掉呢

**Comment by qiuxiang** [comment]
@guuguo 你的意思是现在不行？

**Comment by rzl8023** [comment]
> @qiuxiang 精度圈要去掉的话是怎么去掉呢？
> 自己找到解决方案了：打扰了！！
> locationStyle={{fillColor:'rgba(0,0,0,0)',strokeWidth:0}}

我也加上你这行代码了，但是精度圈还在呢

**Comment by 1442916418** [comment]
locationStyle={{fillColor:'rgba(0,0,0,0)',strokeWidth:0}}

加上这个精度圈怎么还在，请大神解答！！！

**Comment by guuguo** [comment]
改kotlin代码,设置颜色后重新设置locationStyle就可以了

**Comment by 1442916418** [comment]
有案例吗？


------------------ 原始邮件 ------------------
发件人: "guuguo"<notifications@github.com>;
发送时间: 2019年10月14日(星期一) 晚上11:01
收件人: "qiuxiang/react-native-amap3d"<react-native-amap3d@noreply.github.com>;
抄送: "余水生"<1442916418@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qiuxiang/react-native-amap3d] 定位时如何显示周边的那个圆形区域 (#226)




改kotlin代码,设置颜色后重新设置locationStyle就可以了

**Comment by zjjjjjjjjjjd** [comment]
> ~@guuguo 你的意思是现在不行？~

大神，如何解决呀
