### ISSUE TITLE
ios下安装后运行报错

### ISSUE THREAD

**Issue by flicat** [qiuxiang/react-native-amap3d#229]
![qq 20180226121213](https://user-images.githubusercontent.com/4149263/36653219-9fdc86d2-1aee-11e8-8115-578b0ff37883.png)

文件名：YGNodePrint.cpp 208行

`const uint32_t childCount = node->children.size();`

错误信息：
`Implicit conversion loses integer precision: 'size_type' (aka 'unsigned long') to 'const uint32_t' (aka 'const unsigned int')`

求教大神！

**Comment by flicat** [comment]
@qiuxiang

**Comment by qiuxiang** [comment]
RN 版本？

**Comment by flicat** [comment]
react-native: 0.52.1

**Comment by qiuxiang** [comment]
如果是最新的版本呢？

**Comment by flicat** [comment]
试过 react-native upgrade也不行。。。

**Comment by qiuxiang** [comment]
不要用 upgrade，重新 init 一个
