### ISSUE TITLE
有没有react-native link react-native-amap3d只作用于安卓，不作用于ios

### ISSUE THREAD

**Issue by laclys** [qiuxiang/react-native-amap3d#23]

**Comment by qiuxiang** [comment]
还没仔细研究过 rnpm 不确定是不是能设置忽略 iOS

_Sent from my Meizu M5s using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by qiuxiang** [comment]
我自己的话是先 link，然后 git checkout iOS 部分的变更。

**Comment by laclys** [comment]
@qiuxiang  谢谢咯。这是个好办法。感谢
