### ISSUE TITLE
android报错Native component for "AMapMarker" does not exist

### ISSUE THREAD

**Issue by wuge123** [qiuxiang/react-native-amap3d#230]
Invariant Violation: Native component for "AMapMarker" does not exist

This error is located at:
    in AMapMarker (at Marker.js:180)
    in Marker (at Map.js:73)
    in AMapView (at MapView.js:264)
    in MapView (at Map.js:71)
    in RCTView (at View.js:71)
    
文档里面说andriod下面执行react-native link react-native-amap3d，而ios不要这么做是不是自相矛盾

**Comment by qiuxiang** [comment]
确实矛盾，因为没办法分开 link，只能自己处理，备份什么的

**Comment by wuge123** [comment]
ios下面是正常的，如果我再react-native link react-native-amap3d会不会出现问题

**Comment by qiuxiang** [comment]
用 cocoapods 再 link 肯定会出问题，你可以看看类似的 [react-native-maps](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md) 是怎么说明的。

**Comment by wuge123** [comment]
# **怎么还是提示这个错误**
![3f8e5adf-7980-4726-a681-b7de1401cca1](https://user-images.githubusercontent.com/11834723/36801136-2fef5b4c-1cec-11e8-8044-4583ff486717.png)

**Comment by qiuxiang** [comment]
看你的 `MainApplication.java`

**Comment by wuge123** [comment]
![f78c013f-0561-4d7a-93cd-fc46eea9baac](https://user-images.githubusercontent.com/11834723/36823264-3edfdd3e-1d37-11e8-848c-f8c8da9a72bd.png)

这个有问题吗

**Comment by wuge123** [comment]
没有把Package引进来

**Comment by wuge123** [comment]
能否发我一下

**Comment by qiuxiang** [comment]
看 example，或自己重新建一个项目重新 link
