### ISSUE TITLE
Error:Execution failed for task ':react-native-amap3d:compileReleaseKotlin'. > Compilation error. See log for more details

### ISSUE THREAD

**Issue by InitialSugar** [qiuxiang/react-native-amap3d#231]
[-->](url
![qq 20180228095516](https://user-images.githubusercontent.com/33045757/36765767-d0ab1f28-1c6d-11e8-88e8-a155de93c2ef.png)
![qq 20180228095713](https://user-images.githubusercontent.com/33045757/36765768-d0fd3bc8-1c6d-11e8-9b79-4b31db14455f.png)

)

**Comment by qiuxiang** [comment]
https://stackoverflow.com/questions/47005859/duplicate-entry-meta-inf-mylibrary-kotlin-module

**Comment by qiuxiang** [comment]
这基本上是你自己本地的问题，应该自己想办法

**Comment by InitialSugar** [comment]
楼主   我新建了一个项目来跑地图   我用android studio跑项目没有任何报错  成功安装
![qq 20180228142459](https://user-images.githubusercontent.com/33045757/36773263-c55a2ddc-1c93-11e8-9144-b72ca78a5dbd.png)
  但是用命令react-native run-android  就报这个错误了
![qq 20180228142909](https://user-images.githubusercontent.com/33045757/36773260-c0f70f6c-1c93-11e8-83cd-7c7a1a3a1952.png)

**Comment by qiuxiang** [comment]
那就是本地环境的问题了，你 clean 过了？
