### ISSUE TITLE
android下定位很慢，获取到的都是0

### ISSUE THREAD

**Issue by zhang504988670** [qiuxiang/react-native-amap3d#232]
react-native-amap3d: 最新版本，
RN：0.47.1
设备：android，
开启实时定位，获取到的数据
accuracy:0
altitude:0
latitude:0
longitude:0
speed:0
timestamp:0
iOS没有此问题。

**Comment by qiuxiang** [comment]
试过 example 了

**Comment by zhang504988670** [comment]
是的。只在android真机上会这样，虚拟机没有问题。

**Comment by qiuxiang** [comment]
在自己设备上测试了过并没有问题。

**Comment by xiaoliuxiansheng** [comment]
我也遇到了 请问最后是怎么解决的了？

**Comment by xiaoliuxiansheng** [comment]
我也遇到了 请问最后是怎么解决的了？
