### ISSUE TITLE
组件使用问题

### ISSUE THREAD

**Issue by 18203555752** [qiuxiang/react-native-amap3d#233]
react-native-amap3d: 最新版本，
RN-cli：2.0.1
RN：0.53.3
设备：android

我新创建的一个RN项目，按照你的教程是三步：
1.安装  yarn add react-native-amap3d
2.项目配置  react-native link react-native-amap3d
3.application标签加带有高德key的meta-data

但是我发现不执行第二步app报错找不到AMapView,执行了link以后就安装不了app。
求解！

**Comment by qiuxiang** [comment]
肯定要 link 呀，但问题是 link 之后的编译显然是出错了，这需要你自己去找原因

**Comment by 18203555752** [comment]
我发现安装过其他的组件后会影响 已经link的这个组件，就打包安装不成功；我要重新link，link后要在MainApplication.java文件里面删掉重复link产生的     重复语句new AMap3DPackage()。
就可以了
