### ISSUE TITLE
求助无法定位到当前位置

### ISSUE THREAD

**Issue by Melondad** [qiuxiang/react-native-amap3d#234]
react-native-amap3d: 最新版本，
RN-cli：2.0.1
RN：0.53.0
设备：android
我开发了一个工程，引用此组件，之前是可以正常定位到当前我的位置，真机和模拟器都可以（locationEnabled）
但是这两天突然不行了，然后我尝试使用你工程下面的examples/events.js，并打包发布包，在真机上也无法定位到当前位置！
没有思路怎么排查这个问题啊~能否给个思路~在我同事的电脑上的模拟器也无法定位当前位置

**Comment by qiuxiang** [comment]
要检查的无非是权限、Key，除此之外我也没什么可建议的了

**Comment by Melondad** [comment]
无法定位的问题解决了，debug和发布包有两个KEY，多谢指导！另外我使用locationInterval={3000000}属性，不起作用，仍然是默认的两秒重新定位一次，请教下是啥原因啊？

**Comment by qiuxiang** [comment]
`locationInterval` 的问题我有空再看
