### ISSUE TITLE
定位服务打不开 返回的都是0，

### ISSUE THREAD

**Issue by kukudedaxia** [qiuxiang/react-native-amap3d#235]
react-native-amap3d: 最新版本，
RN：0.53.0
设备：android，
定位无论真机还是模拟器都定位不了，打印nativeEvent里面的每一项都为0，而其locationInterval定位间隔时间设置不起作用，求大大帮忙解决， 
![image](https://user-images.githubusercontent.com/30620856/36942572-b4ca5940-1fb0-11e8-9adc-013cb252ea55.png)
![image](https://user-images.githubusercontent.com/30620856/36942575-c14909a0-1fb0-11e8-94fe-b8feabdcd8bd.png)

**Comment by qiuxiang** [comment]
定位问题不再讨论，[自己看其他 issue ](https://github.com/qiuxiang/react-native-amap3d/issues?utf8=%E2%9C%93&q=is%3Aissue+%E5%AE%9A%E4%BD%8D)
