### ISSUE TITLE
用cocoapods集成地图之后，打包报了如下错误

### ISSUE THREAD

**Issue by jianjiandandan** [qiuxiang/react-native-amap3d#236]
用cocoapods集成地图之后，打包报了如下错误：
177 duplicate symbols for architecture arm64
谁遇到过 怎么解决，直接运行没有问题，就是打包的时候才会出现

**Comment by qiuxiang** [comment]
#189

**Comment by jianjiandandan** [comment]
@qiuxiang 你好 我删掉了 打包成功 但是闪退 而且把那两个文件删掉之后，在手机或者模拟器上运行，会报这两个文件没有找到，而且我按照您集成的cocoapods文档来，当加入CxxBridge之后，pod Install 会报错
<img width="571" alt="a338d313bb265b0750275cca3b0f810b" src="https://user-images.githubusercontent.com/21035792/37015461-43043e46-2142-11e8-8c63-27e950491fff.png">

**Comment by qiuxiang** [comment]
我发现引入 CxxBridge 还要做一些其他工作，过段时间再好好看看

**Comment by qiuxiang** [comment]
请参考新的 Podfile
