### ISSUE TITLE
编译过程出现 ':app:transformNativeLibsWithMergeJniLibsForDebug'

### ISSUE THREAD

**Issue by inows** [qiuxiang/react-native-amap3d#238]
错误信息如下
* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/arm64-v8a/libGNaviGuide.so
       File1: C:\Users\Evan\.gradle\caches\modules-2\files-2.1\com.amap.api\navi-3dmap\5.3.0_3dmap5.3.0\5efddf73e99ccd39311bd841ef72c10c21bfd58c\navi-3dmap-5.3.0_3dmap5.3.0.jar
      File2: E:\Reacts\reactnativeofo\node_modules\react-native-amap3d\lib\android\build\intermediates\bundles\default\jni

**Comment by qiuxiang** [comment]
这属于非常规的编译错误，你应该自己找解决方案，我只是大概看了下，https://www.jianshu.com/p/b60675aa5611

**Comment by inows** [comment]
package.json显示"react-native-amap3d": "^0.12.1",

执行react-native link react-native-amap3d的时候并没进行android连接，我是参考其它插件进行的手动连接，而且按这个提示也应该是高德的某些模块有问题吧，还请帮忙看看 谢谢

**Comment by qiuxiang** [comment]
虽然提到了的这个库，但也是因为个人配置引起的

**Comment by POJOa** [comment]
这个问题我也遇到了，但解决方法肯定是不好的...
本来我的ndk路径是错误的，编译是没问题的
我把它改对了，就报这个错
又把它改错，就编译正常了
