### ISSUE TITLE
标注点

### ISSUE THREAD

**Issue by huffmanX** [qiuxiang/react-native-amap3d#239]
标注点不能加载网络图片么

**Comment by huffmanX** [comment]
例如react-native-baidumap-sdk中的
<MapView>
  <MapView.Marker
    icon={() => (
      <View>
        <Image source={image} />
        <Text>This is a custom marker</Text>
      </View>
    )}
  />
</MapView>

**Comment by qiuxiang** [comment]
可以，不过要手动 update，实现是和 react-native-baidumap-sdk 一样的

**Comment by huffmanX** [comment]
![image](https://user-images.githubusercontent.com/22385741/37139875-883e98ae-22ea-11e8-82fc-2b60f29a7b32.png)
谢谢回答哈，这样写了之后，图片没有加载出来，是什么原因呢？

**Comment by huffmanX** [comment]
额 给外层view加了具体的宽高后图片加载出来了

**Comment by qiuxiang** [comment]
需要注意的是，你这是因为有缓存才能加载出来的

**Comment by qiuxiang** [comment]
差不多可以，如果你只是为了自定义图片，那么建议使用原生图片 `image` 属性
