### ISSUE TITLE
如何更改导航的polyline color?

### ISSUE THREAD

**Issue by davidyu37** [qiuxiang/react-native-amap3d#243]
Version: 0.11.1
我在官网上找到实践方法，只是我不太了解Objective-C。
不晓得是否能给我些指引
https://lbs.amap.com/api/ios-navi-sdk/guide/navigation-map/ui-settings
要如何实践navigation的polyline换色？
只需要iOS就好，不一定要有js的接口

谢谢

**Comment by qiuxiang** [comment]
官方给的例子已经很详细了 https://lbs.amap.com/api/ios-navi-sdk/guide/navigation-map/ui-settings#custom-polyline 。

你可以通过 [AMapDriveManager.m](https://github.com/qiuxiang/react-native-amap3d/blob/master/lib/ios/AMap3D/navigation/AMapDriveManager.m) 里的 `_navigationView` 去设置。
