### ISSUE TITLE
在模拟器上运行时闪退？？

### ISSUE THREAD

**Issue by LuyaoLI** [qiuxiang/react-native-amap3d#246]
你好，

项目的运行环境是：
"react-native-amap3d": "^0.12.1",
"react-native": "0.52.0",
Google Nexus 5X - 7.1.0 - API25 - 1080x1920

编译通过。现在想跑你在examples中给出的小例子，可是在模拟器中运行程序的时候一直闪退，但是真机上运行可以成功~

我的模拟器是Genymotion 2.12.0 .

请问有人遇到过类似的问题吗？都是怎么解决的呢？求回复。

谢谢项目编写者提供的repo~

**Comment by qiuxiang** [comment]
基本是因为硬件加速的问题，之前的 issue 有讨论
