### ISSUE TITLE
地图频率

### ISSUE THREAD

**Issue by huffmanX** [qiuxiang/react-native-amap3d#248]
![image](https://user-images.githubusercontent.com/22385741/37460870-8d8796a6-2887-11e8-8a5a-e3ef3c7aa171.png)
这个频率是由map的locationInterval控制的么，我已经把这个时间改成了半小时，现在还是2秒一次？

**Comment by qiuxiang** [comment]
晚些时候确认

**Comment by huffmanX** [comment]
多谢，麻烦啦

**Comment by iDay** [comment]
给个 locationType 的设置吧，不然安卓下总是在不停地定位

**Comment by qiuxiang** [comment]
@iDay locationType 对应哪个接口？

**Comment by iDay** [comment]
安卓下
locationStyle.myLocationType(MyLocationStyle.LOCATION_TYPE_LOCATE)
https://lbs.amap.com/api/android-sdk/guide/create-map/mylocation
ios 下
_mapView.userTrackingMode
https://lbs.amap.com/api/ios-sdk/guide/create-map/location-map

**Comment by qiuxiang** [comment]
这是 traceMode 与定位频率无关

**Comment by iDay** [comment]
对使用者来讲是一样的。

**Comment by qiuxiang** [comment]
怎么可能一样呢 = =，你的目的是设定定位频率，traceMode 与此没有任何关系

**Comment by huffmanX** [comment]
![image](https://user-images.githubusercontent.com/22385741/37512898-56fee8b6-293e-11e8-88e0-e753678e474a.png)
这个频率又悄悄变了T T

**Comment by qiuxiang** [comment]
@huffmanX 这是 android 还是 ios？

**Comment by huffmanX** [comment]
android  红米

**Comment by iDay** [comment]
我要的是定位一次或者跟踪定位要可以选，而不是一进来就是一直跟踪定位

**Comment by iDay** [comment]
现在这个android 跟 ios 的表现完全不一样。没法用。

**Comment by qiuxiang** [comment]
要知道，高德地图 SDK 只提供被动连续定位，而 ios 只能通过 distanceFilter，android 只能通过 locationInterval 限制定位回调。

更多自定义定位只能在单独的定位模块实现。

**Comment by huffmanX** [comment]
我的那个locationInterval失效问题有发现么

**Comment by iDay** [comment]
我还是自己实现吧。。。

**Comment by qiuxiang** [comment]
然而我并没有发现 `locationInterval` 失效

<img src="https://user-images.githubusercontent.com/1709072/37608361-4bd24a34-2bd5-11e8-90b9-245c0a31b518.png" width=300>

**Comment by huffmanX** [comment]
我这里不行哦...能加微信（hfm670826352）或者QQ（670826352）帮下忙么

**Comment by qiuxiang** [comment]
@huffmanX 抱歉。。最近实在没时间

**Comment by POJOa** [comment]
我也遇到了locationInterval失效的问题... 我注意到一点，失效的时候每次nativeEvent里的timestamp都是负值，而且刚开始几个会变化，后面就不变了。把新加的locationType功能改成locate定位一次，倒是不会持续定位了。可以用这个方法自己interval来苟一下...
![111](https://user-images.githubusercontent.com/13232736/40578201-ae2333d6-6142-11e8-9f89-2beb2386e55d.PNG)

**Comment by POJOa** [comment]
在kotlin的代码里把locationInterval硬编码为50000，问题依旧... 这会不会是上游的问题...

**Comment by qiuxiang** [comment]
我觉得还是放弃高德地图内置的定位改用独立的定位模块吧，这点百度地图就做得很好，地图本身不提供定位功能，但提供接口来更新定位图层 https://github.com/qiuxiang/react-native-baidumap-sdk#定位并关联定位图层
