### ISSUE TITLE
build error about yoga   我用的RN   0.52

### ISSUE THREAD

**Issue by 729504321** [qiuxiang/react-native-amap3d#249]
![2018-03-16 11 04 18](https://user-images.githubusercontent.com/10694458/37501553-d0011e3a-2909-11e8-973d-09f4b5ed220e.png)
![2018-03-16 11 05 04](https://user-images.githubusercontent.com/10694458/37501568-e942acd8-2909-11e8-94e0-75e8e33ee47d.png)

**Comment by 729504321** [comment]
换个版本就好了

**Comment by huffmanX** [comment]
请问换什么版本能修复这个问题？

**Comment by qiuxiang** [comment]
这是环境问题，自己看编译测试 https://travis-ci.org/qiuxiang/react-native-amap3d/jobs/366715343
