### ISSUE TITLE
IOS 中心点数据和地图显示偶尔会出现一定偏移

### ISSUE THREAD

**Issue by lzctbyong** [qiuxiang/react-native-amap3d#251]
RN 版本:0.54

中心点回调数据正常 , 但地图显示的中心点有偏移, 偶尔正常,偶尔异常,大佬帮忙看看?

![osxrklaa uiwd_46m ugjzq](https://user-images.githubusercontent.com/17008940/37699870-6678897a-2d24-11e8-8ee2-3081ec763bf8.png)

**Comment by lzctbyong** [comment]
只在IOS上出现问题
android不会出现

**Comment by lzctbyong** [comment]
我用你提供的demo测试
固定中心坐标的情况下,
 mapView.centerCoordinate = CLLocationCoordinate2DMake(21.89034586588542, 111.9731564670139);
打开地图依然会出现这样的bug
大佬你看是RN版本的问题,还是你的代码有些小问题?
谢谢

**Comment by lzctbyong** [comment]
我确认了下,很大概率是RN版本问题
0.54以上貌似都这样

**Comment by lzctbyong** [comment]
用Inspect 查看AMapView的宽高
发现异常情况的宽高是正常情况的2倍,
这是啥原因

**Comment by qiuxiang** [comment]
RN v0.53 是有问题，0.54 还没看过

**Comment by lzctbyong** [comment]
@qiuxiang 
据了解,是RN 0.53以上自定义View会有bug,我打算降版本了

**Comment by xiuzhongjin** [comment]
我ios也遇到这个问题，请问现在可以解决了吗

**Comment by lzctbyong** [comment]
@xiuzhongjin 降版本或者试试最新版本, rn 的bug

**Comment by xiuzhongjin** [comment]
@lzctbyong 我的RN是0.50.3的也这样，请问你是降到哪个版本才可以的

**Comment by lzctbyong** [comment]
用作者的版本0.52.2,保证没问题的

**Comment by lzctbyong** [comment]
@xiuzhongjin 要申明一下,这问题,我只在ios上出现这种bug,安卓无论什么版本都是正常的,如果你是在安卓上出现的,建议检查代码问题

**Comment by yuantrybest** [comment]
@lzctbyong 0.53以上解决这个问题了吗？

**Comment by lzctbyong** [comment]
@yuantrybest  我测试的0.54都没有解决, 最新的0.55.0,我没试,你也去试试

**Comment by yuantrybest** [comment]
@lzctbyong 又一个 Region ，但是没看到详细的说明

**Comment by yuantrybest** [comment]
@qiuxiang 目前 0.55.3 有什么办法能解决中心点便宜的问题吗？比较急

**Comment by qiuxiang** [comment]
@yuantrybest 暂时没有

**Comment by brucehelen** [comment]
0.52.3 偶尔也遇到这个问题
```
双指缩放和放大的时候 有时候中心点就不是以地图中心缩放,而是以右下角,或者右边中心点.
```

**Comment by heeween** [comment]
@brucehelen 现在降到0.52.2 还没发现问题

**Comment by slyvanas** [comment]
@qiuxiang 我看了下，出问题的map是因为生成的地图的宽高的不等于包裹地图的View的宽高，上面有人说是大了近两倍，看看是不是源码哪里加载顺序的原因或者写个promise，获取外围View定义的宽高或者等View加载后的有实际宽高后再渲染地图？

**Comment by lzctbyong** [comment]
@slyvanas 这是官方的bug,让官方修复,目前是0.55,你试试修复没有,哈哈

**Comment by slyvanas** [comment]
@qiuxiang 出问题的map有个很明显的特征就是左边的高德的比例尺不见了，正常情况下存在的，不正常情况会跑出屏幕范围（即渲染的地图范围比外围的View要大），所以看起来地图中心点不在地图中间

**Comment by slyvanas** [comment]
@qiuxiang 目前是0.55.3的版本，仍然没有解决，我注意到有个Region显示区域的设置，这个能设置地图的显示的宽高嘛？如果能的话，也算能够解决这个问题吧

**Comment by slyvanas** [comment]
@qiuxiang 目前是0.55.3的版本，仍然没有解决，我注意到有个Region显示区域的设置，这个能设置地图的显示的宽高嘛？如果能的话，也算能够解决这个问题吧

**Comment by qiuxiang** [comment]
@slyvanas 我当然知道出现问题时内部 MapView 与外部 ReactView 宽高不一致，但这需要研究为什么，以找到最佳的解决方法。同时受影响的还有自定义 View 获取不到宽高。你对 region 的理解不对，这不是设置地图宽高的，而是设置显示区域的。

**Comment by heeween** [comment]
就在RN项目里的pagejson文件中指定RN版本用0.52.2的 先保证项目正常运行 其他原因不必过多纠缠.
`"dependencies": {
    "prop-types": "^15.6.1",
    "react": "16.2.0",
    "react-native": "0.52.2",
    "react-native-amap3d": "^1.0.0",
    "react-native-camera": "^1.1.4",
    "react-native-maps": "^0.21.0",
    "react-native-root-toast": "^3.0.1",
    "react-navigation": "^2.0.4",
    "redux": "^4.0.0"
  },`

**Comment by lzctbyong** [comment]
这问题不要再纠结了，是rn版本问题

**Comment by BooYeu** [comment]
0.56存在这个问题吗？

**Comment by wd** [comment]
这个问题看来是 ios + RN >= 0.53 版本的问题。主要表现是下面几个
1. 中心点不对。
2. 手指缩放会不正常，明显的能看到不是以手指捏合那块缩放的。
3. 有一定概率会白屏没有地图内容，但是点击等动作有响应。

btw: 我感觉这个问题没解决之前应该先不要关闭这个 issue，提供一个跟踪解决类似问题的第一个地方。

**Comment by qiuxiang** [comment]
另一个类似的问题是开着的 #218

**Comment by wd** [comment]
sorry, 我没看到。那在那个跟踪也可以。

**Comment by liyanfei1004774105** [comment]
这么恶心的 bug  还没 0.57 了还没修复,心累啊,哪个 Rn 版本修复了,在这里通知一下奥

**Comment by hydraZty** [comment]
react-native: "0.57.3"
react-native-amap3d: "1.0.2"

同样遇到了这个问题，总结下发现的规律 供大家参考

> 地图实际尺寸大约是容器尺寸的两倍，origin为左上角，导致地图初始定位偏移，缩放偏移，拖动偏移，地图组件显示不全。并且伴随卡顿

以上遇到的问题 时好时坏好的情况这些问题都没有，也不卡顿，所以可能并不全是ReactView宽高引起的。

**Comment by wei63w** [comment]
@hydraZty  我用的跟你情况一样...  唉. 我试试自己能 改下不能

**Comment by gaoxiaosong** [comment]
@lzctbyong @xiuzhongjin @yuantrybest @heeween @wd @BooYeu @slyvanas @wei63w #465

**Comment by js1121302139** [comment]
> RN 版本:0.54
> 
> 中心点回调数据正常 , 但地图显示的中心点有偏移, 偶尔正常,偶尔异常,大佬帮忙看看?
> 
> ![osxrklaa uiwd_46m ugjzq](https://user-images.githubusercontent.com/17008940/37699870-6678897a-2d24-11e8-8ee2-3081ec763bf8.png)

请问一下你的中心点坐标是固定在屏幕上的么？那么他的坐标该怎么获取呢？

**Comment by wangdanting** [comment]
兼容android与iOS的解决方法：
第一步：在外层套个View，样式设置宽高和overflow: hidden
第二步：将高度或者宽度写成变量，页面渲染完后，过1s后让地图重新渲染。
```javascript
state = {
  mapHeight: 200
};

componentDidMount(){
  setTimeout(() => {
    this.setState(prev => ({
      mapHeight: prev.mapHeight + 1
    }));
  }, 1000);
}

<View style={{height: 200, overflow: 'hidden'}}>
  <MapView style={{ width: "100%", height: this.state.mapHeight }}>
  </MapView>
</View>
```
