### ISSUE TITLE
如何设置MultiPoint组件的image的大小（）自定义

### ISSUE THREAD

**Issue by unionTime** [qiuxiang/react-native-amap3d#252]
RN 4.9  iOS 11.2
我用了自定义图片作为图标，放置在Images.xcassets下；
图片能正常显示，可是我觉得大小不太协调，我想设备一下，图片的大小；
如图
![img_0127](https://user-images.githubusercontent.com/19386499/37715586-5fcf53dc-2d57-11e8-8832-385ef85d1e1e.PNG)
如何设备里面的黄色的灯灯大小（marker的图标）?

谢谢，工作顺利～

**Comment by qiuxiang** [comment]
不能设置大小，你应该重新调整图片大小，你这图片都模糊掉了，肯定是图片尺寸不对，自己了解下原生图片尺寸适配。

**Comment by qiuxiang** [comment]
简单的来说，原生图片应该提供 1x、2x、3x 不同的尺寸，如果你这图片是 1x 的话，放到 2x 就会变小，并且不会模糊。

**Comment by unionTime** [comment]
@qiuxiang 谢谢
