### ISSUE TITLE
集成高德版本6.0,Marker会有bug

### ISSUE THREAD

**Issue by lzctbyong** [qiuxiang/react-native-amap3d#253]
RN:0.52.2

Marker信息窗显示异常,弹不出来

**Comment by qiuxiang** [comment]
> 集成高德版本6.0
没看懂

**Comment by lzctbyong** [comment]
@qiuxiang 就是秒闪 , 弹出信息窗不到1秒, 又会消失掉,
最新版本的高德6.0,0会出现这问题

**Comment by qiuxiang** [comment]
iOS 还是 Android

**Comment by qiuxiang** [comment]
没注意到高德 SDK 都 6.0 了，看来要重新检查一下

**Comment by lzctbyong** [comment]
反正经我测试,
RN 0.52.2
SDK 5.3.0
是最正常的,高于这些版本都很大可能出现未知的bug

**Comment by qiuxiang** [comment]
发现了，但得过段时间才有空再看看怎么解决

**Comment by LiuTangLei** [comment]
android没问题，ios在marker设置coordinate那一步就崩溃了，我也发现了

**Comment by qiuxiang** [comment]
Fixed https://github.com/qiuxiang/react-native-amap3d/commit/af65ab509142b8d2bff0ed80444adf0cb25db12c
