### ISSUE TITLE
ios新建项目运行不起来T_T

### ISSUE THREAD

**Issue by huffmanX** [qiuxiang/react-native-amap3d#256]
RN版本0.52.0，新建项目按照文档pod配置，一直跑不起来。下图是最新一次结果

![image](https://user-images.githubusercontent.com/22385741/37886392-9a8adfca-30ed-11e8-996c-55cf61552932.png)

**Comment by qiuxiang** [comment]
这个错误我没法重现

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-baidumap-sdk/issues/25 和这个应该是一样

**Comment by huffmanX** [comment]
在xcode里面报错信息是一样的，怎么修改这个编译版本呢？

**Comment by jimmy2012** [comment]
我也遇到同样的问题，修改了react和react-native的版本后没问题了
"react": "16.0.0",
"react-native": "^0.51.0",
"react-native-amap3d": "^0.12.1"

**Comment by qiuxiang** [comment]
请参考最新的 Podfile
