### ISSUE TITLE
RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks

### ISSUE THREAD

**Issue by lzctbyong** [qiuxiang/react-native-amap3d#257]
提供你正在使用的版本 : latest
RN 版本 :0.52.2

![image](https://user-images.githubusercontent.com/17008940/37951483-1e38d700-31cf-11e8-8db0-ff5900cbd007.png)

**Comment by lzctbyong** [comment]
AMapRideManager requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

是不是代码还缺点什么?

**Comment by lzctbyong** [comment]
经了解,好像是要加入这东西
+ (BOOL)requiresMainQueueSetup {
    return YES/NO;
}

**Comment by qiuxiang** [comment]
看来又是一个 breaking change

**Comment by qiuxiang** [comment]
但是我并没有发现这个问题
