### ISSUE TITLE
提示MAMapView.h不存在，但是却能在模拟器上运行

### ISSUE THREAD

**Issue by wuge123** [qiuxiang/react-native-amap3d#258]
/Users/wuge/dust/node_modules/react-native-amap3d/lib/ios/AMap3D/RCTConvert+AMap3D.m:1:9: fatal error: 'MAMapKit/MAMapView.h' file not found
#import <MAMapKit/MAMapView.h>

xcode上提示#import <MAMapKit/MAMapKit.h>这个文件不存在

**Comment by qiuxiang** [comment]
你的 xcode 整个截图

**Comment by wuge123** [comment]
![image](https://user-images.githubusercontent.com/11834723/38004740-3fd22050-3270-11e8-98e9-e2be1ae05bdc.png)

**Comment by qiuxiang** [comment]
不明，自己看 search path 吧

**Comment by wuge123** [comment]
![image](https://user-images.githubusercontent.com/11834723/38006772-fab1f424-3278-11e8-92e6-37e8e8feb77f.png)

之前一直是好的啊

**Comment by wuge123** [comment]
我执行unlink就可以了，可能之前不小心执行link了
