### ISSUE TITLE
cocoapods集成RN0.54.4编译报错'React/RCTNetworking.h' file not found

### ISSUE THREAD

**Issue by hzlgit** [qiuxiang/react-native-amap3d#263]

**Comment by qiuxiang** [comment]
0.52 以上还没时间测试，建议还是用 0.52，RN 的 podspec 经常变，大概要改成：
```
pod 'React', path: '../node_modules/react-native/', :subspecs => [
  'DevSupport',
  'RCTNetwork',
]
```

也可以参考 https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#ios---cocoapods

**Comment by hzlgit** [comment]
ok了

**Comment by shantj** [comment]
同样的问题，解决了，建议修改一下中文网上面的教程 https://reactnative.cn/docs/integration-with-existing-apps/ @qiuxiang
