### ISSUE TITLE
MultiPoint 无法实时更新

### ISSUE THREAD

**Issue by unionTime** [qiuxiang/react-native-amap3d#267]
react-native-amap3D ^0.7.0
react-native 0.48.3
iOS 11.2

问题：传入MultiPoint的data 数组更新时，marker并不能更新。不随数据的变化而变化。

`
 markerArr = (arr) => {
         let _arr = [];
        for(let key in arr){
            _arr.push(
                <MultiPoint key={key} points={arr[key]} onItemPress={this.onItemPress} image={objMap[key]} >
                </MultiPoint>
            )
        }
        return _arr;
    }

{this.markerArr(this.state.equipments)}
`

请问可以解决吗

**Comment by qiuxiang** [comment]
没有细看，应该是和热度图一样的，只能设置一个新 key 强制重新渲染
