### ISSUE TITLE
地图导航语音功能

### ISSUE THREAD

**Issue by KumikoYYC** [qiuxiang/react-native-amap3d#268]
"react": "16.3.0-alpha.1",
"react-native": "0.54.1",
"react-native-amap3d": "^0.12.1",

导航没有语音提示的功能吗？

**Comment by qiuxiang** [comment]
没有

**Comment by LiuTangLei** [comment]
最新版本的高德地图已经支持语音功能，把这个库搞成静态的自己改依赖地图版本就行了，再去导航源码里面去开启语音

**Comment by KumikoYYC** [comment]
不太懂你说的 ？ @LiuTangLei

**Comment by LiuTangLei** [comment]
@KumikoYYC iOS开启语音的api是[_navigationManager setIsUseInternalTTS:YES]; 安卓开启语音的api是mAMapNavi.setUseInnerVoice(true) ，你自己去源码里面添加
