### ISSUE TITLE
BUILD FAILED 

### ISSUE THREAD

**Issue by zhouxxiaolong** [qiuxiang/react-native-amap3d#27]
Installing build/Build/Products/Debug-iphonesimulator/Conference.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Conference.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by qiuxiang** [comment]
这个错误怎么看都与这个项目无关，你能确定是因为引入这个项目才出现这个问题？

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zhouxxiaolong** [comment]
CompileC build/Build/Intermediates/Conference.build/Debug-iphonesimulator/Conference.build/Objects-normal/x86_64/AppDelegate.o Conference/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
