### ISSUE TITLE
安卓compileSdkVersion 27 定位不成功，原本compileSdkVersion 23是成功的

### ISSUE THREAD

**Issue by LukeChenyk** [qiuxiang/react-native-amap3d#270]
"react-native": "0.51.0",
"react-native-amap3d": "^0.12.1",

安卓编译配置：
compileSdkVersion 27
 buildToolsVersion "27.0.0"

 minSdkVersion 16
targetSdkVersion 26

**Comment by qiuxiang** [comment]
注意定位权限的动态申请，targetSDK > 23 不会自动获得

**Comment by LukeChenyk** [comment]
是权限问题

**Comment by LukeChenyk** [comment]
大神，请教一下，这组件有定位权限的动态申请吗？不太懂原生，谢谢。

**Comment by LukeChenyk** [comment]
@qiuxiang 大神，请教一下，这组件有定位权限的动态申请吗？不太懂原生，谢谢
