### ISSUE TITLE
Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by internet5** [qiuxiang/react-native-amap3d#272]
地图页面开启定位onLocation，onLocation里会setState坐标以更新地图坐标位置
问题是：进入地图页，马上返回，页面已不存在了，但是onLocation还会执行，并且调用setState，这时候就会报错Unable to find node on an unmounted component
尝试Unmount时设置一个flag去控制，但是发现不管是Unmount，还是navigator的disAppear事件都会再onLocation之后才执行，所以根本控制不了

**Comment by internet5** [comment]
onLocation里用mobx或者redux居然页不行，同样报错，求解决

**Comment by internet5** [comment]
android环境

**Comment by internet5** [comment]
我用setTimeout模拟onLocation，发现并不会报错，只会给出个warning
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component.

**Comment by qiuxiang** [comment]
首先，MapView 只要被移除，onLocation 肯定会停止，否则这个 https://github.com/qiuxiang/react-native-amap3d/blob/master/example/examples/events.js 就会出错。

这很可能就是你代码处理的问题。

**Comment by internet5** [comment]
这就么一段代码，我发现移除Marker之后，定位很快了，不会报错
我把Marker里面的TouchableOpacity全部删除，定位也会快一些，但是进入页面很快的点返回，还是会报错，你看我这代码有什么问题吗
<MapView style={{ flex: 1 }}
                    coordinate={this.state.coordinate}
                    locationEnabled={this.state.locationEnabled}
                    onLocation={this.handleLocation}
                    zoomLevel={this.state.zoomLevel}
                >
                    {this.state.mapData && this.state.mapData.map(item => {
                        return (
                            <MapView.Marker key={item.id}
                                icon={() => {
                                    return <Entypo
                                        name='location-pin'
                                        color={item.businessType == '零售商' ? '#1260d9' : '#7c2723'}
                                        size={30}
                                    />
                                }}
                                coordinate={{
                                    latitude: item.latitude,
                                    longitude: item.longitude
                                }}
                                active={this.state.chooseId == item.id}
                            >
                                <TouchableOpacity activeOpacity={0.9}>
                                    <View style={{alignItems:'center'}}>
                                        <View style={styles.customInfoWindow}>
                                            <Text>经营类型：{item.businessType}</Text>
                                            <Text>名称：{item.businessUnit}</Text>
                                            <Text>地址：{item.address}</Text>
                                            <Text>联系人：{item.linkMan}</Text>
                                            <Text>联系电话：{item.contactNumber}</Text>
                                        </View>
                                        <View style={styles.triangle}></View>
                                    </View>
                                </TouchableOpacity>
                            </MapView.Marker>
                        )
                    })}
                </MapView>

**Comment by qiuxiang** [comment]
这应该是自定义 Marker 的 bug，可以肯定的是，如果不用自定义 Marker 就不会出现这个错误。

之前有人提到过，自己也意识到存在出错的可能，但一直不能重现，没有找到根源。

大概是因为 Marker 在不合适的时候调用了 `sendCommand`
https://github.com/qiuxiang/react-native-amap3d/blob/10b3f19c1320efc88aeb73f7920d72bb26597aab/lib/js/maps/Marker.js#L147
https://github.com/qiuxiang/react-native-amap3d/blob/10b3f19c1320efc88aeb73f7920d72bb26597aab/lib/js/Component.js#L22

**Comment by qiuxiang** [comment]
最好能提供一段能让我直接运行并重现的代码

**Comment by qiuxiang** [comment]
再仔细看了下，你的处理是有问题的，因为根据你的描述

> 进入地图页，马上返回，页面已不存在了，但是onLocation还会执行

这个是正常的，因为在 Native 端无法确认 Component 是否 unMounted（或许是可以的，只是我没有去验证）。你需要在 JS 端判断 Component isMounted，在 onLocation 的时候避免在 unMounted 的情况下 setState。

请参考 https://github.com/qiuxiang/react-native-amap3d/blob/master/example/examples/marker.js

这么想来，之前提过的 issue 也大概是因为这个导致的。

**Comment by qiuxiang** [comment]
又想了下，这个问题是应该处理好的，只是在改进之前，你只能先自己处理了。

**Comment by internet5** [comment]
我用rn的定位来获取位置，可以避免报错的问题
但是自定义marker加载实在是有点慢，我才60个左右的点，要5秒左右

**Comment by qiuxiang** [comment]
@internet5 从来就不建议使用自定义 Marker，灵活与方便是要付出代价的，在实现上就决定了不稳定以及性能的问题。建议使用 `image` 来获得性能最优。

**Comment by ismjt** [comment]
我的项目中也碰到了“Unable to find node on an unmounted component“””这个问题，不过没能写出简单的代码来复现出这个问题。
我这里出现的情况是，某个Marker是否显示出来受一个bool状态机的控制，实际代码是：
```jsx
          {!this.state.locationEnabled && <Marker
              infoWindowDisabled
              coordinate={{
                  latitude: this.state.latitude,
                  longitude: this.state.longitude,
                }}
              icon={() => (<Image
                style={{ width: 30, height: 30 }}
                source={require('../../../res/images/off_location.png')}
              />)}
            />}
```
调试的时候，我在
https://github.com/qiuxiang/react-native-amap3d/blob/10b3f19c1320efc88aeb73f7920d72bb26597aab/lib/js/Component.js#L21
这里插入了两个输出语句：
```javascript
console.info(this);
console.info(findNodeHandle(this));
```
那么，在正常情况下看到的信息是：
![normal](http://codepush.ismjt.cn/github/normal.png)

出现该issues时看到的信息是：
![Unable to find node on an unmounted component.](http://codepush.ismjt.cn/github/unnormal2.png)

换句话说就是，当我这个目标Marker从显示变为不显示时，sendCommand里面的这个findNodeHandle(this)方法就报错了。

现在我采取的修复方案是在sendCommand方法中加个组件的isMounted状体的判断：
```
     if(this.updater.isMounted(this)){
        UIManager.dispatchViewManagerCommand(
          findNodeHandle(this),
          UIManager[this.name].Commands[command],
          params,
        )
      }
```
其实，怕应用闪退，我连try{}catch(){}也加上了.=_=.

希望这个回答能给碰到同样问题的小伙伴一个参考。

**Comment by zhongjie-chen** [comment]
https://github.com/zhongjie-chen/react-native-amap3d
