### ISSUE TITLE
ios打包提示'MAMapKit/MAMapKit.h' file not found

### ISSUE THREAD

**Issue by zyf540860996** [qiuxiang/react-native-amap3d#279]
RN版本0.52

安装执行 react-native link react-native-amap3d 后，
ios打包 提示 'MAMapKit/MAMapKit.h' file not found

**Comment by suwu150** [comment]
#258

**Comment by qiuxiang** [comment]
明天我更新一个版本，link 将对 ios 不起作用

**Comment by zyf540860996** [comment]
好的，真机打包会提示 'MAMapKit/MAMapKit.h' file not found，模拟机可以完美运行

**Comment by qiuxiang** [comment]
@zyf540860996 你指的打包是 release 还是 archive？估计你只能自己去看了，或者新建项目重新测试，这个 issue 关闭了，除非你能提供更有价值的的信息。

**Comment by zyf540860996** [comment]
<img width="983" alt="wx20180423-085726 2x" src="https://user-images.githubusercontent.com/10524382/39102217-5d54b5c0-46d4-11e8-97ac-e6a2bfddd0e0.png">

react-native link 对 ios 起作用后打包就报错
感觉还是更新一个版本，link 对 ios 不起作用，就可以完全解决
