### ISSUE TITLE
应该怎么去适配RN0.47

### ISSUE THREAD

**Issue by dongchuanlei** [qiuxiang/react-native-amap3d#28]

**Comment by dongchuanlei** [comment]
![screenshot_2017-08-11-11-53-56-203_com vehicleman](https://user-images.githubusercontent.com/19383409/29200962-631ec2ea-7e8c-11e7-80ea-d426f92c0d42.png)

安卓地图先出现北京地区闪一下就变成这样了

**Comment by qiuxiang** [comment]
我稍候看看

**Comment by qiuxiang** [comment]
我测试了，发现一个编译错误，但并没有发现使用上的问题

**Comment by dongchuanlei** [comment]
使用react-navigation, 第一页加上地图, 然后this.props.navigation.navigate("SecondView",{title:"第二页"}); SecondView上也有地图, 但是第一页的地图还会存在, 盖在了SecondView上. Toggle Inspector后就变成白页面了, 然后退出Appza再次进入地图也是白页面。
![screenshot_2017-08-11-16-25-41-333_com amapdemo](https://user-images.githubusercontent.com/19383409/29206245-a43335be-7eb3-11e7-8671-5005fedf912c.png)
![screenshot_2017-08-11-16-29-34-290_com amapdemo](https://user-images.githubusercontent.com/19383409/29206246-a45e9dd0-7eb3-11e7-88c1-388c5f824964.png)

![screenshot_2017-08-11-16-25-22-922_com amapdemo](https://user-images.githubusercontent.com/19383409/29206200-65a61a96-7eb3-11e7-88ff-80af0af50912.png)

**Comment by qiuxiang** [comment]
估计和这个是一样的问题 https://github.com/qiuxiang/react-native-amap3d/issues/20

**Comment by dongchuanlei** [comment]
感谢作者的提示与更新, 我使用的还是react-navigation, 覆盖问题没有了。首页作为View可以正常显示, 但是首页换成地图就是白屏, 但是进入到react-native-amap3d的MapView.js里, 什么都不改保存一下(热更新开启), 地图马上就出来了.
![default](https://user-images.githubusercontent.com/19383409/29343891-aedefed8-8266-11e7-880b-93b249516079.png)

**Comment by qiuxiang** [comment]
没有遇到过，不确定什么问题

**Comment by dongchuanlei** [comment]
不好意思地图白屏是我这边的问题。 另外我发现没有onRegionChange这个方法, 要是实现拖动地图获取到地图中心点的经纬度应该怎么实现?

**Comment by qiuxiang** [comment]
不是有 [onStatusChange](https://github.com/qiuxiang/react-native-amap3d/blob/master/components/MapView.js#L156) 方法吗
