### ISSUE TITLE
怎么退出导航？

### ISSUE THREAD

**Issue by zhuchaoming** [qiuxiang/react-native-amap3d#281]
用的0.12.1版本的导航组件Navigation，点击左下角的X，提示确定退出导航？点确定后，没有退出。要怎么才能退出？

**Comment by qiuxiang** [comment]
因为根本就没做这个接口

**Comment by zhuchaoming** [comment]
不知道这个弹框代码在哪里？能不能调用自己的代码来退出导航？

**Comment by qiuxiang** [comment]
目前没有精力开发和维护导航组件，v1+ 已经移除了
