### ISSUE TITLE
不想使用 CocoaPods，能否出一份手动配置的说明文档

### ISSUE THREAD

**Issue by 12343954** [qiuxiang/react-native-amap3d#283]
你好, 我的项目写了太多代码, 不想用pod ,请问,能否出一份手动配置的说明文档? 谢谢

目前想在 RN 0.50 下使用

**Comment by qiuxiang** [comment]
因为手动配置太麻烦且容易出错，我自己都没试过，后来干脆把 xcode 项目删掉了，如果你熟悉 ios 开发，完全可以自己配置，官方是有文档的，否则配置失败的概率太高了。

**Comment by 12343954** [comment]
我鼓捣了半天, 竟然可以了

步骤就是

1. 按高德官网手动配置sdk, 安装一堆lib
2. 把你的代码放到项目里
3. run

居然跑起来了, 哈哈, 非常感谢你的lib
不喜欢pod, 我只是个 js coder

136MB的sdk, 体积瞬间变大, 我觉得不是个好的解决方案, 我去看看 js api ,用webview代替, 看看效果怎么样

**Comment by qiuxiang** [comment]
体积的问题你可以试试降级到 5.6.0。
https://github.com/qiuxiang/react-native-amap3d/blob/657c0d4d371775ee4ee6bec46d122cd663773d6a/lib/ios/react-native-amap3d.podspec#L19

**Comment by 12343954** [comment]
嗯, 有机会我试试, 谢谢

**Comment by qiuxiang** [comment]
你要这么想的话，根本就没必要考虑 RN，因为 RN 默认打包出来的体积已经差不多是这么大了。

**Comment by 12343954** [comment]
嗯, 我有我的考虑
