### ISSUE TITLE
安卓如何手动引入Amap3d?

### ISSUE THREAD

**Issue by DuanYuna** [qiuxiang/react-native-amap3d#286]
- RN版本0.46.4
  - 由于公司项目问题无法使用React Native link 只能通过手动集成所以想问一下大神如何手动集成安卓的包
我fork了您的项目之后修改文件上传之后ios使用cocoapod无法安装依赖,是有什么地方没有修改到吗,我看错误提示的意思是,cocoapod找不到依赖
fork的原因是 我是原生和RN混写的,集成在别人的应用中已经存在高德地图,所以如果在依赖中指定了高的版本,就无法安装成功,所以删除了您的高德地图的版本指定
还有添加多个标注需要全部在视野内,我添加修改了这两个内容,然后cocoapod无法安装成功了

**Comment by qiuxiang** [comment]
android 手动配置需要修改的地方（注意路径）：
https://github.com/qiuxiang/react-native-amap3d/blob/657c0d4d371775ee4ee6bec46d122cd663773d6a/android/settings.gradle#L3
https://github.com/qiuxiang/react-native-amap3d/blob/657c0d4d371775ee4ee6bec46d122cd663773d6a/android/app/build.gradle#L157
https://github.com/qiuxiang/react-native-amap3d/blob/657c0d4d371775ee4ee6bec46d122cd663773d6a/android/app/src/main/java/com/rnamap3d/MainApplication.java#L28
