### ISSUE TITLE
xcodeBuild失败 Library not found for -lDoubleConversion

### ISSUE THREAD

**Issue by jaikensai888** [qiuxiang/react-native-amap3d#288]
按照markDown的设置，配置了cocopad ，可以成功使用react Native run ios 来运行项目，
但是当在xcode里面进行build操作，报错误

![image](https://user-images.githubusercontent.com/5178454/39618455-58956594-4fb6-11e8-9f97-5b9d580f88e9.png)

尝试将library Search Path里面的缺少库的路径重新定位到iso/pods/Target Support file中
还是报错误
![image](https://user-images.githubusercontent.com/5178454/39618412-2ffcd2fc-4fb6-11e8-9404-a8999ba9d7c6.png)

请求大神帮忙解答一下

**Comment by qiuxiang** [comment]
确定打开的是 xcworkspace 而不是 xcodeproj ？

**Comment by qiuxiang** [comment]
参考 release 分支的编译测试

**Comment by stoneWeb** [comment]
@qiuxiang 重装几次都解决不了这个问题

**Comment by stoneWeb** [comment]
Xcode: 9.3.1
react-native-cli: 2.0.1
react-native: 0.54.2
react-native-amap3d: 1.0.0-beta.1

报错：
```
ld: library not found for -lDoubleConversion
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by qiuxiang** [comment]
看起来很可能是 Podfile 不对，不同 RN 版本 Podfile 有区别，具体看 RN 官方文档的 [Integration with Existing Apps](https://facebook.github.io/react-native/docs/0.52/integration-with-existing-apps.html)

Readme 给出的 Podfile 可能只适用 RN v0.52

**Comment by qiuxiang** [comment]
@stoneWeb 还是建议你看下 example 和 编译测试

https://travis-ci.org/qiuxiang/react-native-amap3d/jobs/377766294
https://travis-ci.org/qiuxiang/react-native-amap3d/jobs/368980486

**Comment by woshicezai** [comment]
应该吧pod install 后生成的pod文件夹里的.xcodeproj的文件拖入到该工程下就能找到了 我也遇到过这个问题 就是这样解决的
