### ISSUE TITLE
地图不显示

### ISSUE THREAD

**Issue by liyanfei1004774105** [qiuxiang/react-native-amap3d#289]
"react": "16.0.0-beta.5",
      "react-native": "0.49.5",
      ios 模拟器及真机
       "react-native-amap3d": "^1.0.0-beta.1",
      
pod 'GLog', :podspec => './RN/node_modules/react-native/third-party-podspecs/GLog.podspec'
pod 'Folly', :podspec => './RN/node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-amap-geolocation', path: './RN/node_modules/react-native-amap-geolocation/lib/ios'
pod 'react-native-amap3d', path: './RN/node_modules/react-native-amap3d/lib/ios'
cocoPod 导入正常   

Xcode 输出
 [MAMapKit] 无效的资源bundle，请检查AMap.bundle是否正确导入。

Error create directory /mapcache with: Error Domain=NSCocoaErrorDomain Code=513 "您没有将文件“mapcache”存储到文件夹“Macintosh HD”中的权限。" UserInfo={NSFilePath=/mapcache, NSUnderlyingError=0x600000a48190 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}

**Comment by qiuxiang** [comment]
到底是编译通过了没？截图？

**Comment by liyanfei1004774105** [comment]
已解决,是我的 cocoPods 导入文件时, bounle 包会识别不到, 但都把 bunlde 包放到项目里就好了
