### ISSUE TITLE
自定义标记的显示问题

### ISSUE THREAD

**Issue by liyanfei1004774105** [qiuxiang/react-native-amap3d#290]
ios 项目,
我项目里需要用到海量图,然后点击海量图,显示自定义标记,  
1,我目前实现的效果是,点击海量图,红色标记变为绿色,再次点击才弹出自定义标记
2,想问一下有没有方法能点击一次就出现自定义标记

**Comment by qiuxiang** [comment]
没看明白

**Comment by liyanfei1004774105** [comment]
ios 项目 ,
定位信息中没有逆地理编码,但是当我调用过 react-Native-amap3D 地图之后,再去定位,就都有城市信息就都有了
