### ISSUE TITLE
纯RN项目0.53，0.55都有这个问题

### ISSUE THREAD

**Issue by fgxls** [qiuxiang/react-native-amap3d#297]
可以debug 可以release 但是archive就不行了
下面是xcode编译时的报错 只截取了一小部分 所有的RN模块都是duplicate，不知道该怎么办，因为pod install的时候也安装了RN模块 与react native init 的时候载入的RN模块重复了
duplicate symbol _OBJC_IVAR_$_RCTWebSocketModule._sockets in:
    /Users/lashare/Library/Developer/Xcode/DerivedData/bunnyfit-dulprzlzkhzaefhcjswwhhmnzojc/Build/Intermediates.noindex/ArchiveIntermediates/bunnyfit/BuildProductsPath/Release-iphoneos/libReact.a(RCTWebSocketModule.o)
    /Users/lashare/Library/Developer/Xcode/DerivedData/bunnyfit-dulprzlzkhzaefhcjswwhhmnzojc/Build/Intermediates.noindex/ArchiveIntermediates/bunnyfit/BuildProductsPath/Release-iphoneos/libRCTWebSocket.a(RCTWebSocketModule.o)

**Comment by qiuxiang** [comment]
#189
