### ISSUE TITLE
安卓集成后 打开地图报错 信息如图

### ISSUE THREAD

**Issue by DuanYuna** [qiuxiang/react-native-amap3d#299]

**Comment by DuanYuna** [comment]
![281525836689_ pic](https://user-images.githubusercontent.com/13826312/39794419-caa4e668-537c-11e8-90c2-ef1d36080607.jpg)

**Comment by qiuxiang** [comment]
这问题有点奇怪，我还特地重新配置了一个新项目，但并没有重现

<img src="https://user-images.githubusercontent.com/1709072/39794966-b37e61aa-537f-11e8-8400-68601bd56029.png" width=300>

有试过 example？

**Comment by DuanYuna** [comment]
嗯 试过了




Yuna
React Native (iOS)开发工程师
在2018年05月09日 11:58，7c00 写道：

这问题有点奇怪，我还特地重新配置了一个新项目，但并没有重现

有试过 example？

**Comment by qiuxiang** [comment]
结果呢？

**Comment by DuanYuna** [comment]
正常 只是集成到工程就报错 断点直接就进高德的jar包了 所以才找您看下有没有思路




Yuna
React Native (iOS)开发工程师
在2018年05月09日 11:59，7c00 写道：

结果呢？

**Comment by qiuxiang** [comment]
那就是项目配置的问题了，我想不到什么情况下会出现这个问题。

**Comment by DuanYuna** [comment]
那行 我在研究下 成功的话再告诉您原因 祝我好运




Yuna
React Native (iOS)开发工程师
在2018年05月09日 12:03，7c00 写道：

那就是项目配置的问题了，我想不到什么情况下会出现这个问题。
