### ISSUE TITLE
android平台，编译都正常，地图界面不显示

### ISSUE THREAD

**Issue by fanyongbing** [qiuxiang/react-native-amap3d#3]
android平台，编译都正常，地图界面不显示，只显示一个边框

**Comment by qiuxiang** [comment]
只出现框，主要是因为没有对应的原生组件，确定 link 了吗？你可以用 android studio 打开 android 项目确认一下。
![image](https://user-images.githubusercontent.com/1709072/27858401-a53993b4-61a7-11e7-8721-8162fa39c154.png)

**Comment by fanyongbing** [comment]
新的项目，我刚刚又重新init了一个新的项目，link也不行，全程没有报错的地方，界面不显示

**Comment by fanyongbing** [comment]
c:\amapdemo>react-native link react-native-amap3d
Scanning 555 folders for symlinks in c:\amapdemo\node_modules (21ms)
rnpm-install info Linking react-native-amap3d ios dependency
rnpm-install info iOS module react-native-amap3d has been successfully linked

link之后没有看到关于android的提示

**Comment by qiuxiang** [comment]
把你新建的项目打包发到这里来看看，注意删掉 node_modules/ 和 android 里面的 build/

**Comment by qiuxiang** [comment]
我新建项目发现了。。确实没有 link android，我找下原因

**Comment by fanyongbing** [comment]
@qiuxiang   好的   麻烦了

**Comment by ytqiu** [comment]
可能权限问题，我开始调试时候也遇到了。我的PR中修改了这点。

**Comment by qiuxiang** [comment]
@ytqiu 不是的，我已经找到问题了，是因为现在发布的 react-native link 还不支持 kotlin 项目，6 天前才开始支持的 https://github.com/facebook/react-native/commit/d666f30665e4cd336e1a1017954447f486a3e8ce#diff-03184c2240e3fc10bb2c9148569cb51f。

我居然一直没有注意到这个问题……

但我们不可能等 react-native 发布新版本，所以我多加了一个 `AMap3DPackage.java`，这样 `react-native link` 的时候就能找到包名了。

@fanyongbing 用 npm 重新安装 react-native-amap3d 应该就能解决问题了。

**Comment by fanyongbing** [comment]
感谢大神，问题已经解决！ @qiuxiang
