### ISSUE TITLE
example npm install 后 react-native run-android 失败

### ISSUE THREAD

**Issue by my4piano** [qiuxiang/react-native-amap3d#30]
example npm install 后 react-native run-android 失败

**Comment by qiuxiang** [comment]
错误信息？

**Comment by my4piano** [comment]
P:\example>npm install
npm ERR! code ENOLOCAL
npm ERR! Could not install from ".." as it does not contain a package.json file.


npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\love\AppData\Roaming\npm-cache\_logs\2017-08-14T03_21_
34_468Z-debug.log


log文件内容：
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install runPreinstallTopLevelLifecycles
5 silly preinstall example
6 info lifecycle @~preinstall: @
7 silly lifecycle @~preinstall: no script for preinstall, continuing
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly fetchPackageMetaData error for react-native-amap3d@file:.. Could not install from ".." as it does not contain a package.json file.
14 verbose stack Error: ENOENT: no such file or directory, open 'P:\package.json'
15 verbose cwd P:\example
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
18 verbose node v8.0.0
19 verbose npm  v5.0.0
20 error code ENOLOCAL
21 error Could not install from ".." as it does not contain a package.json file.
22 verbose exit [ 1, true ]

**Comment by my4piano** [comment]
提问错误，是 npm install  阶段失败

**Comment by qiuxiang** [comment]
example 的 npm install，我也想改了，直接引用 `..` 确实会出问题

**Comment by qiuxiang** [comment]
现在应该没问题了

**Comment by my4piano** [comment]
P:\example>react-native run-android
Scanning 479 folders for symlinks in P:\example\node_modules (25ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat install
Debug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Project :app declares a dependency from configuration 'compile' to configur
ation 'default' which is not declared in the descriptor for project :react-nativ
e-amap3d.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 1.995 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by qiuxiang** [comment]
`P:\example>react-native` 你难道把 example 单独拿了出来？

**Comment by my4piano** [comment]
是的

**Comment by qiuxiang** [comment]
这是不行的，example 里引用了上级目录里的 native 代码

**Comment by my4piano** [comment]
可以了 大神
