### ISSUE TITLE
ios 使用CocoaPods安装报错

### ISSUE THREAD

**Issue by yoyo0427** [qiuxiang/react-native-amap3d#302]
"react-native": "0.52.0",
![qq20180510-163401](https://user-images.githubusercontent.com/12933263/39860474-0374f958-5470-11e8-9f24-faa1c4568ced.png)

**问题一：**
"react-native-amap3d": "^0.12.1",
报错截图：
![qq20180510-163509](https://user-images.githubusercontent.com/12933263/39860504-1e8fa5bc-5470-11e8-8541-29f8daa5f725.png)

**问题二**
"react-native-amap3d": "^1.0.0-beta.1",
报错截图：
![qq20180510-163714](https://user-images.githubusercontent.com/12933263/39860712-e62ee7e0-5470-11e8-8323-e2a6dc45488d.png)

**Comment by qiuxiang** [comment]
一个是网络问题一个是源过时了，你自己看错误提示啊，该怎么做，提示已经说得很明白了
