### ISSUE TITLE
能不能提供一个纯java的版本

### ISSUE THREAD

**Issue by lzctbyong** [qiuxiang/react-native-amap3d#304]
目前 Kt和java混合,对于没学过kt的人来说 , 使用上会有点不方便 o(╥﹏╥)o

**Comment by qiuxiang** [comment]
为什么需要关心是用什么语言写的？

**Comment by lzctbyong** [comment]
如果私人想实现自定的功能代码 , kt代码那一块压根看不懂啊

**Comment by qiuxiang** [comment]
这个项目一开始就是用 java 写的，后来换成 kotlin。并没有什么特别的理由，就是个人喜好而已，对我来说，kotlin 比 java 写出来的代码更简洁易读，更容易维护。况且这个项目并没有绝对的理由一定要用 java。

当然，我也知道 kotlin 对一些人不太友好，但已经不是我考虑的范围了。

**Comment by qiuxiang** [comment]
况且，kotlin 与 java 的互转实在太简单了，属于 android studio 内置的功能
