### ISSUE TITLE
0.44.0版本可否使用本组件

### ISSUE THREAD

**Issue by VesperHan** [qiuxiang/react-native-amap3d#305]

**Comment by qiuxiang** [comment]
简单来说，不可以，我也不会再提供过多的支持。

iOS 应该没什么问题，但 android 需要改代码才能编译，自己看 #82 #166

**Comment by qiuxiang** [comment]
你对 RN 的 platform-specific 理解有问题，现在这个项目的 link 对 iOS 没用作用的，但你只要用了这个项目的原生组件，但又没用编译的话肯定会出错。

参考 https://facebook.github.io/react-native/docs/platform-specific-code.html
