### ISSUE TITLE
Tag 0.7 之前的版本支持 0.44.0的RN吗

### ISSUE THREAD

**Issue by VesperHan** [qiuxiang/react-native-amap3d#306]

**Comment by qiuxiang** [comment]
你这个想法很危险啊 = =

以前的版本，功能不完善，也存在一些 bug，非要在低版本的 RN 使用，也只是稍微改下代码而已。

**Comment by VesperHan** [comment]
哈哈 是这个样子
昨天用了最新的代码集成了一整天,iOS是各种报错, 因为ios 跑不起来,安卓也跑不起来
所以萌生了 只集成到安卓的诡异想法

因为我集成的之后还没达到改动代码的哪一步,因为继承中就一堆乱起八糟的问题

能方便告知,具体改动那些代码,可以跑在0.44的版本上?

**Comment by qiuxiang** [comment]
不是让你看之前的 issue 了吗
