### ISSUE TITLE
Pod Third Party Error

### ISSUE THREAD

**Issue by VesperHan** [qiuxiang/react-native-amap3d#308]
RN:0.44.0

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

这三个pod感觉路径不对 ,没有third-party-podspecs的文件目录啊?

path需要更改么

**Comment by qiuxiang** [comment]
都不晓得 RN 0.44 能不能用 pod

**Comment by Maplesog** [comment]
@qiuxiang 能帮忙看下我的问题吗 #307
