### ISSUE TITLE
xcode无法运行

### ISSUE THREAD

**Issue by wcmboy** [qiuxiang/react-native-amap3d#31]
<img width="1397" alt="2017-08-15 9 35 59" src="https://user-images.githubusercontent.com/1540087/29298834-3afa9f5a-819d-11e7-9b1d-1c24cb4d1c95.png">
按照说明：使用Pod install安装，没有运行react-native link。是全新创建的项目，RN0.46.
react-native run-ios却可以正常运行，而使用xcode则报上面的错误。

**Comment by qiuxiang** [comment]
你确定打开的是 xcworkspace？

**Comment by wcmboy** [comment]
原来是打开另一个文件的，不好意思，对IOS不是很懂，太尴尬了。现在可以了，之前一直打开的是xcodeproj文件。
