### ISSUE TITLE
react-native link react-native-amap3d 貌似ios和安卓都链接了

### ISSUE THREAD

**Issue by VesperHan** [qiuxiang/react-native-amap3d#310]

**Comment by qiuxiang** [comment]
貌似？

**Comment by VesperHan** [comment]
react-native link react-native-amap3d  不能指定平台

**Comment by qiuxiang** [comment]
我不明白你像表达什么，这个库根本就没用 ios 模块可以 link。

https://travis-ci.org/qiuxiang/react-native-amap3d/jobs/368980485#L1940
![](https://user-images.githubusercontent.com/1709072/40105014-5ef44564-5924-11e8-81a6-dc6b632cbb9c.png)

**Comment by VesperHan** [comment]
![image](https://user-images.githubusercontent.com/16316152/40109078-2f736f62-592f-11e8-9728-ceb389550174.png)

react-native link react-native-amap3d 我运行就显示link ios

**Comment by qiuxiang** [comment]
你 link 的是其他模块啊

**Comment by VesperHan** [comment]
![image](https://user-images.githubusercontent.com/16316152/40110022-89b7e848-5931-11e8-83da-43eea53047d5.png)
那我安卓的就应该没link上是吧 因为没有出现你发出来的那个log

**Comment by qiuxiang** [comment]
你应该运行 `react-native link react-native-amap3d`

**Comment by VesperHan** [comment]
相信我, react-native link react-native-amap3d 我复制粘贴运行的

**Comment by qiuxiang** [comment]
相信你什么？我并不怀疑你运行了错误的命令。

**Comment by qiuxiang** [comment]
直到现在我还是不知道你的问题是什么
