### ISSUE TITLE
看一个原生的高德地图引入问题

### ISSUE THREAD

**Issue by Maplesog** [qiuxiang/react-native-amap3d#311]
这样写，为啥属性设置的初始值都不起作用？大佬帮忙看一下：
```
#import "Amap.h"
#import <MAMapKit/MAMapKit.h>
#import <AMapFoundationKit/AMapFoundationKit.h>

@implementation Amap

  RCT_EXPORT_MODULE()
  - (UIView *)view {
    MAMapView *mapView = [MAMapView new];
    mapView.centerCoordinate = CLLocationCoordinate2DMake(39.9242, 116.3979);
    mapView.zoomLevel = 10;
    return mapView;
  }

  RCT_EXPORT_VIEW_PROPERTY(zoomLevel, CGFloat)
  RCT_EXPORT_VIEW_PROPERTY(coordinate, CLLocationCoordinate2D)
@end
```

**Comment by Maplesog** [comment]
RCT_EXPORT_VIEW_PROPERTY(locationEnabled, BOOL)
RCT_EXPORT_VIEW_PROPERTY(showsCompass, BOOL)
RCT_EXPORT_VIEW_PROPERTY(showsScale, BOOL)
RCT_EXPORT_VIEW_PROPERTY(showsIndoorMap, BOOL)
RCT_EXPORT_VIEW_PROPERTY(showsLabels, BOOL)
RCT_EXPORT_VIEW_PROPERTY(showsTraffic, BOOL)
RCT_EXPORT_VIEW_PROPERTY(showsBuildings, BOOL)
RCT_EXPORT_VIEW_PROPERTY(zoomLevel, CGFloat)
RCT_EXPORT_VIEW_PROPERTY(maxZoomLevel, CGFloat)
RCT_EXPORT_VIEW_PROPERTY(minZoomLevel, CGFloat)
RCT_EXPORT_VIEW_PROPERTY(zoomEnabled, BOOL)
RCT_EXPORT_VIEW_PROPERTY(scrollEnabled, BOOL)
RCT_EXPORT_VIEW_PROPERTY(rotateEnabled, BOOL)
RCT_EXPORT_VIEW_PROPERTY(tiltEnabled, BOOL)
RCT_EXPORT_VIEW_PROPERTY(mapType, MAMapType)
RCT_EXPORT_VIEW_PROPERTY(coordinate, CLLocationCoordinate2D)
RCT_EXPORT_VIEW_PROPERTY(limitRegion, MACoordinateRegion)
RCT_EXPORT_VIEW_PROPERTY(region, MACoordinateRegion)
RCT_EXPORT_VIEW_PROPERTY(tilt, CGFloat)
RCT_EXPORT_VIEW_PROPERTY(rotation, CGFloat)
RCT_EXPORT_VIEW_PROPERTY(distanceFilter, CLLocationDistance)
RCT_EXPORT_VIEW_PROPERTY(locationStyle, LocationStyle)

**Comment by Maplesog** [comment]
@qiuxiang 你的这些属性我怎么在高德地图ios sdk文档里面找不见呢？

**Comment by qiuxiang** [comment]
你在哪找？

**Comment by Maplesog** [comment]
文档里面看不到。不是ios出身看不太懂。但是在xcode里面点击MAMapView这个对象，看到啦一些。

不过我想问的还是第一个问题。我给这些属性赋值了，为啥在界面上没作用呢？

**Comment by Maplesog** [comment]
```

#import "Amap.h"
#import <MAMapKit/MAMapKit.h>
#import <AMapFoundationKit/AMapFoundationKit.h>

@implementation Amap

  RCT_EXPORT_MODULE()
  
  RCT_EXPORT_VIEW_PROPERTY(showsCompass, BOOL)
  
  - (UIView *)view {
    MAMapView *mapView = [[MAMapView alloc] init];
    mapView.delegate = self;
    mapView.showsUserLocation = YES;    // 显示用户位置蓝点
    mapView.userTrackingMode = MAUserTrackingModeFollow;
    mapView.showsCompass = true;
//  mapView.centerCoordinate = CLLocationCoordinate2DMake(39.9242, 116.3979);
    return mapView;
  }
  
  
@end
```


我就添加一个指南针，不起作用

**Comment by Maplesog** [comment]
![image](https://user-images.githubusercontent.com/18155748/40154326-681dcd6c-59c0-11e8-9d9b-9fc5683535c3.png)
地图界面一直是这样的

**Comment by qiuxiang** [comment]
这个问题我没法回答你，是 RN 导致的

**Comment by qiuxiang** [comment]
你这个 issue 不是讨论这个项目，关掉了。

**Comment by Maplesog** [comment]
能给个方向吗？

**Comment by qiuxiang** [comment]
没有方向，这个问题我都没用解决

**Comment by shukaka** [comment]
这个BUG无解吗？我也遇到了

**Comment by qiuxiang** [comment]
@shukaka 你指的是什么 bug？

**Comment by shukaka** [comment]
@qiuxiang 位置不稳定，经常跑到国外去了

**Comment by qiuxiang** [comment]
这个 issue 根本就不是讨论定位的，你应该找以前的关于定位的 issue，因为不能确定是 bug，我也不再讨论。
