### ISSUE TITLE
'MAMapKit/MAMapKit.h' file not found

### ISSUE THREAD

**Issue by VesperHan** [qiuxiang/react-native-amap3d#312]
.h:1:9: fatal error: 'MAMapKit/MAMapKit.h' file not found
#import <MAMapKit/MAMapKit.h>   
这是0.7.3的提示

使用npm安装的时候因为我的环境是0.44
导致的问题就是 link无效,就是没有显示 android success 的字样

我想先帮忙解决第一个问题就是 头文件 not found

我也想用最新的,但是除了那两个issue就是这个link问题

**Comment by VesperHan** [comment]
issue看了下 我加上了 JSModules那三行代码,还是跑不起来

**Comment by qiuxiang** [comment]
自己看编译测试 https://travis-ci.org/qiuxiang/react-native-amap3d/builds/368980483 我已经不知道怎么回复你了
