### ISSUE TITLE
组件不存在

### ISSUE THREAD

**Issue by VesperHan** [qiuxiang/react-native-amap3d#313]
RN 0.44.0
Map:1.0.0Beta
![image](https://user-images.githubusercontent.com/16316152/40160941-d29199fa-59e1-11e8-93e4-a1954a03c4d1.png)

代码已经改了
![image](https://user-images.githubusercontent.com/16316152/40161027-0e7f85c6-59e2-11e8-895a-478335e38a63.png)

**Comment by qiuxiang** [comment]
组件代码没有编译或没有引用

**Comment by VesperHan** [comment]
我当前的项目 react-native link 不好用,因为不显示连接android 
所以我配置的,是Android Studio配置有问题是吧?

**Comment by qiuxiang** [comment]
是配置的问题
