### ISSUE TITLE
请问移除了导航组件，我能用MapView实现导航功能吗

### ISSUE THREAD

**Issue by since66** [qiuxiang/react-native-amap3d#316]
我看到更新日志里面写移除了导航组件，导航组件的确有些不需要显示的，我想请问下能用MapView实现导航的路线功能吗？

**Comment by qiuxiang** [comment]
用 polyline + marker 是能做路径规划的，只是 polyline 现在还不支持自定义纹理

**Comment by qiuxiang** [comment]
不是很简单吗，定位是被动的，设置地图状态的接口也有

**Comment by qiuxiang** [comment]
@benshayu2015 如果你这么理解的话，那么现在就是做不了路径规划

**Comment by benshayu2015** [comment]
原生的有导航的，是不是封装下就可以了？

**Comment by qiuxiang** [comment]
导航并不是线路规划

**Comment by benshayu2015** [comment]
线路规划好整吗？

**Comment by qiuxiang** [comment]
如果你要自己实现的话就是用 polyline + marker 呀，官方 demo 也是这么实现的，只是现在 polyline 不支持纹理而已

**Comment by HeiSiBaby** [comment]
我也想实现导航功能，请问你是怎么实现的呢？
