### ISSUE TITLE
关于ios多个实例情况下,获取mapview实例的疑问

### ISSUE THREAD

**Issue by lzctbyong** [qiuxiang/react-native-amap3d#317]
- (UIView *)view {
    AMapView *mapView = [AMapView new];
    mapView.centerCoordinate = CLLocationCoordinate2DMake(39.9242, 116.3979);
    mapView.zoomLevel = 10;
    mapView.delegate = self;
    return mapView;
}
在ios初始化完成后,比如我js里面创建了3个mapview组件, 那就会被初始化三次 , 那如何在其他method里面获取到当前的mapView ?还望指点一下,谢谢

**Comment by qiuxiang** [comment]
什么 method？具个例子？

**Comment by lzctbyong** [comment]
比如说,我想实现一个路径规划的功能,自己写了功能代码

//在地图上添加起始和终点的标注点
- (void)addDefaultAnnotations {
  //添加起点
  .....
  //添加终点
  ...
  
  //然后添加标注到当前的mapview, (怎么获取到当前的mapview变量?)
}

**Comment by qiuxiang** [comment]
这是 objc 的问题，你自己看源代码不就知道了

**Comment by lzctbyong** [comment]
ok
