### ISSUE TITLE
[ IOS ] 海量点不能动态刷新

### ISSUE THREAD

**Issue by lzctbyong** [qiuxiang/react-native-amap3d#319]
只显示初始化的一次数据,之后更新数组的话,不会刷新

**Comment by lzctbyong** [comment]
....这么恐怖的吗 , 太恐怖了,安卓的倒是可以

**Comment by qiuxiang** [comment]
恐怖？MultiPoint 和 HeatMap 本来就不应该频繁更新，如果非要更新，那么完全可以设置一个新 key 触发重绘。

**Comment by lzctbyong** [comment]
那对于滴滴打车那种地图小车 , 是用大量的maker来实现的吗??

**Comment by qiuxiang** [comment]
显然不是，你没观察到移动位置会获取新数据吗，每次只渲染当前可见区域的 marker，数量并不会太多
