### ISSUE TITLE
给地图中心添加一个标记，无论地图怎么拖动，标记均固定在地图中心，如何做到？

### ISSUE THREAD

**Issue by my4piano** [qiuxiang/react-native-amap3d#32]
给地图中心添加一个标记，无论地图怎么拖动，标记均固定在地图中心，如何做到？

**Comment by qiuxiang** [comment]
你说的是独立于地图的 view？

**Comment by my4piano** [comment]
不是，就在地图里面

**Comment by qiuxiang** [comment]
`地图怎么拖动，标记均固定在地图中心` 我不确定你说的地图中心到底指的是什么

**Comment by my4piano** [comment]
微信小程序有怎么一个功能，chooseLocation，会弹出一个地图窗口，无论地图怎么拖动，那个标记都会在窗体中心，拖动停下后 callback 返回当前的坐标点。

https://mp.weixin.qq.com/debug/wxadoc/dev/api/location.html#wxchooselocationobject

**Comment by qiuxiang** [comment]
chooseLocation 其实就是实现了拖放定点的功能

**Comment by my4piano** [comment]
所以请问，这个功能在 react-native-amap3d 怎么实现？

**Comment by qiuxiang** [comment]
你的目的？从地图上取点？为什么不用 onPress 或 onLongPress 或 Marker 的拖放事件？

**Comment by my4piano** [comment]
我的目的是在地图上精确取点。拖动地图 比 拖放 marker 更容易精确取点。

**Comment by qiuxiang** [comment]
我并不认同。

可以明确的是，高德地图并没有提供微信地图里 chooseLocation 类似的接口。

如果你非要拖动取点，也是可以的，`onStatusChangeComplete`就可以在地图移动之后得到中心坐标，但交互怎么做就自己想办法了。
