### ISSUE TITLE
请问怎么获取地图可视区域的边界

### ISSUE THREAD

**Issue by madong190** [qiuxiang/react-native-amap3d#321]
请问怎么获取地图可视区域的边界，在注释上没有找到。的高得手册上找到了getMapScreenShot(AMap.OnMapScreenShotListener listener)
截取当前屏幕设备上的可见地图区域。
因为刚学rn不清楚应该怎么调用

**Comment by qiuxiang** [comment]
截图就说截图嘛，为什么要说成“可视区域的边界”？如果你想要截图，这个接口没有打算做，请参考 https://github.com/gre/react-native-view-shot

**Comment by madong190** [comment]
是这样的，我想在地图上标点，数据来自后台，后台只返回手机当前可视区域的数据，所以要知道地图的边界，可以提供一个好的思路吗

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-amap3d/blob/master/lib/js/maps/MapView.js#L250
