### ISSUE TITLE
安卓定位

### ISSUE THREAD

**Issue by madong190** [qiuxiang/react-native-amap3d#326]
直接运行你的demoe，在不打开gps的情况下手机也可以定位，但是自己新建的demo必须打开gps才能定位到，否则定位坐标就是0，0。请问这里有什么需要注意的吗

**Comment by qiuxiang** [comment]
这个问题自己看吧，大致上使用上的问题

**Comment by madong190** [comment]
我自己回答一下吧。几年前在高得申请过web的key,拿过来直接用发现能用，就这么用了。应该先生成一个签名，在根据项目的报名新申请key，key要与项目对应上才可以，build.gradle中也要有
android {
    signingConfigs {
        example {
            ...
        }
    }
  }
信息
