### ISSUE TITLE
地图上自定义的方法返回undefined

### ISSUE THREAD

**Issue by wuge123** [qiuxiang/react-native-amap3d#328]
我仿照onCalculateRouteSuccess回调函数写了一个onCalculateRouteDistance方法，通过调试可以看到可以正常的执行，但是在console.log(dis)打印的却是undefined，请问是我遗漏了什么吗
<Navigation.Drive
            ref={ref => this._navigation = ref}
            style={StyleSheet.absoluteFill}
            onCalculateRouteSuccess={this._start}
            onCalculateRouteDistance={({dis}) =>console.log(dis)}
          />

![image](https://user-images.githubusercontent.com/11834723/40607582-7d095c1c-629b-11e8-813a-ef0ba4072d8b.png)

![image](https://user-images.githubusercontent.com/11834723/40607651-af70c2f8-629b-11e8-9baa-b3b12dfa5d9d.png)

**Comment by qiuxiang** [comment]
`onCalculateRouteDistance={e => console.log(e)}` 你就知道什么回事了

另外，我要吐槽你这个做法是真糟糕，一方面，为什么非要用 native 实现距离计算？考虑到 native 与 js 通信产生的性能损耗，性能未必比纯 js 实现好；另一方面，就算你一定在 native 算距离，完全可以用 SDK 提供的距离计算函数，没必要重新实现。
