### ISSUE TITLE
很抱歉，“******”已停止运行。

### ISSUE THREAD

**Issue by siroer** [qiuxiang/react-native-amap3d#33]
在电脑A正常运行，在电脑B弹出该错误Alert，没有红屏，后台也没有输出错误，比较诡异。

注释掉 MapView 代码就不会出现该问题。

**Comment by qiuxiang** [comment]
ios 还是 android？截图？

**Comment by my4piano** [comment]
安卓，

不在电脑B面前了，P一下
![qq 20170816082210](https://user-images.githubusercontent.com/17940455/29342200-009bee12-825c-11e7-8687-54dcfdaad223.png)

**Comment by qiuxiang** [comment]
这问题描述看得我莫名其妙，直接说在模拟器运行出错不就行了。还有，android app 崩溃是肯定会有 error log 的，`react-native log-android` 不一定能看到，需要用 android-studio。

模拟器运行出错，十有八九是这个问题 https://github.com/qiuxiang/react-native-amap3d/issues/14 。

**Comment by qiuxiang** [comment]
这个 Issue 我先关掉了，除非你能给出更多的错误信息

**Comment by siroer** [comment]
你说得对，是模拟器的问题，我用Android Studio 打开的模拟器来测试是没有问题的

**Comment by JoinBelieve** [comment]
我在一台电脑上使用menymotion正常，另一台出现这种问题
