### ISSUE TITLE
路线规划成功和失败回调返回undefined

### ISSUE THREAD

**Issue by wuge123** [qiuxiang/react-native-amap3d#330]
路线规划成功和失败回调返回undefined
 onCalculateRouteSuccess={({dis}) =>console.log(dis)}
  onCalculateRouteFailure={({dis}) =>console.log(dis)}
![image](https://user-images.githubusercontent.com/11834723/40712133-893ac10c-642f-11e8-8dab-b1469a4a27f0.png)

**Comment by wuge123** [comment]
为什么将这个问题关闭掉

**Comment by qiuxiang** [comment]
这个问题不属于维护的范围，且已回复过
