### ISSUE TITLE
想要在地图上画多个圆形，怎么弄判断圆不重复

### ISSUE THREAD

**Issue by madong190** [qiuxiang/react-native-amap3d#331]
点击地图可以画圆，但是各个圆不能有重叠部分。该怎么判断，现在的版本里没有提供某点是否在一个圆里的方法吧，用react-native-baidumap-sdk（百度地图 SDK）地图也可以，现在有解决方法吗，或者提供一个思路

**Comment by qiuxiang** [comment]
https://github.com/manuelbieh/Geolib#geolibispointincircleobject-latlng-object-center-integer-radius
