### ISSUE TITLE
安卓地图只显示高德地图四个字

### ISSUE THREAD

**Issue by DMCHZP** [qiuxiang/react-native-amap3d#332]
安卓地图只显示高德地图四个字 ，ios 没问题
![image](https://user-images.githubusercontent.com/19619027/40780656-ae460088-650b-11e8-9190-0558832c4112.png)

**Comment by DMCHZP** [comment]
key 没设置错，权限也没问题，之前还行的，不知道为何现在就这样了
我看到 高德官方的一个类似的问题，不知道跟这个有没有关
http://lbs.amap.com/faq/android/android-map/349

**Comment by qiuxiang** [comment]
是否试过 example？

**Comment by DMCHZP** [comment]
观察logcat 的日志 发现
Could not find generated setter for class cn.qiuxiang.react.amap3d.maps.AMapViewManager
06-01 11:39:56.212 11917-12046/com.localsapp W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class cn.qiuxiang.react.amap3d.maps.AMapMarkerManager
06-01 11:39:56.217 11917-12046/com.localsapp W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class cn.qiuxiang.react.amap3d.maps.AMapInfoWindowManager
06-01 11:39:56.218 11917-12046/com.localsapp W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class cn.qiuxiang.react.amap3d.maps.AMapPolylineManager
06-01 11:39:56.222 11917-12046/com.localsapp W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class cn.qiuxiang.react.amap3d.maps.AMapPolygonManager
06-01 11:39:56.225 11917-12046/com.localsapp W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class cn.qiuxiang.react.amap3d.maps.AMapCircleManager
06-01 11:39:56.228 11917-12046/com.localsapp W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class cn.qiuxiang.react.amap3d.maps.AMapHeatMapManager
06-01 11:39:56.231 11917-12046/com.localsapp W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class cn.qiuxiang.react.amap3d.maps.AMapMultiPointManager

**Comment by DMCHZP** [comment]
我看到有一条相关的问题
https://github.com/qiuxiang/react-native-amap3d/issues/206
但是找不到解决方法

**Comment by DMCHZP** [comment]
example 试过了，还是这样只显示高德地图四个字

**Comment by DMCHZP** [comment]
还有这句
not allowing consideration of lib/armeabi-v7a/libAMapSDK_MAP_v6_1_0.so: deferring to libdir

**Comment by DMCHZP** [comment]
看了官方的相关问题
http://lbs.amap.com/faq/top/hot-questions/335
跟这个有关吗？

**Comment by qiuxiang** [comment]
你上面提到的都不是一个问题，如果说连 example 都这样，那就只能怀疑你的本地环境有问题了。我编译了一个 example.apk 上传到 release，你可以下载安装看看 https://github.com/qiuxiang/react-native-amap3d/releases/download/v1.0.0-beta.1/example.apk

**Comment by DMCHZP** [comment]
之前还行的，后来我升级了 android studio 3.1.2 就不行了，会跟android studio版本有关吗

**Comment by qiuxiang** [comment]
我都是用最新版，更新过程也没有发现什么问题

**Comment by DMCHZP** [comment]
解决了 太奇怪了，我在 AndroidManifest.xml 加了
 android:hardwareAccelerated="false"
 android:largeHeap="true" 这两句导致的。。。，为何呢。。
![image](https://user-images.githubusercontent.com/19619027/40827567-8675b0a8-65b0-11e8-8bee-dbeb16274ef6.png)

**Comment by DMCHZP** [comment]
准确来说应该是 android:hardwareAccelerated="false" 这句导致的 （关闭了硬件加速。。。）

**Comment by qiuxiang** [comment]
那大概就是你的手机硬件加速的问题

**Comment by DhlOne** [comment]
我把这句设置为true或者不设置，地图可以出现了，但是我不知道会不会影响手机性能或者程序运行
