### ISSUE TITLE
如何获取中心点的坐标跟缩放比

### ISSUE THREAD

**Issue by since66** [qiuxiang/react-native-amap3d#335]
例如我地图上面有3个点，我先已加载就显示到这3个点的中心（都显示出这3个点，无论这3个点距离多远），请问怎么实现？谢谢

**Comment by qiuxiang** [comment]
MapView#region

**Comment by since66** [comment]
老大能不能说清楚一点，照顾下我们这些菜鸟呀

**Comment by qiuxiang** [comment]
要知道，issue 是用来反馈问题的，而不是提供支持的，非 bug 反馈，而且不能把问题说明白的我都不太想回复了。特别是现在又不是很有空。

**Comment by lenglengiOS** [comment]
@qiuxiang 大佬，region里面那几个参数代表什么意义？请问该怎么传值？翻了很久issues没找到
