### ISSUE TITLE
无法获取当前位置的经纬度

### ISSUE THREAD

**Issue by Actioing** [qiuxiang/react-native-amap3d#336]
"react": "16.2.0",
    "react-native": "0.52.3",
    "react-native-amap3d": "^1.0.0",

**Comment by Actioing** [comment]
nativeEvent.latitude === 0

**Comment by Actioing** [comment]
<MapView
          style={StyleSheet.absoluteFill}
          zoomLevel={12}
          tilt={0}
          mapType="standard"
          locationInterval={10000} // 定位间隔(ms)，默认 2000
          distanceFilter={10} // 定位的最小更新距离
          locationEnabled // 开启定位
          showslocationbutton
          showsCompass // 罗盘
          showsscale
          showsTraffic // 交通
          region={{
              latitude: this.state.mLatitude,
              longitude: this.state.mLongitude,
              latitudeDelta: 0.1,
              longitudeDelta: 0.1,
          }}
          // onlocation 启动定位显示  regison  中的显示区域
          onLocation={({ nativeEvent }) => { this.toPosition(nativeEvent); }}
        >

**Comment by qiuxiang** [comment]
自己看以前的 issue https://github.com/qiuxiang/react-native-amap3d/issues?q=is%3Aissue+%E5%AE%9A%E4%BD%8D+is%3Aclosed

**Comment by GalaxySystem** [comment]
搞什么啊？解决方案循环嵌套给人看？

**Comment by hufans** [comment]
> 搞什么啊？解决方案循环嵌套给人看？

翻了一遍没有解决方案。
