### ISSUE TITLE
RN0.52-android环境下new AMap3DPackage() 报错

### ISSUE THREAD

**Issue by sylviaHit** [qiuxiang/react-native-amap3d#337]
想请教下，执行 react-native run-android 后，报 MainApplication.java 文件内  new AMap3DPackage() 的错，是怎么回事啊？

**Comment by yangcf** [comment]
没有引入包

**Comment by sylviaHit** [comment]
之前引入了也报这个错，重新弄了一下，现在没有问题了，谢谢
