### ISSUE TITLE
开发工具是vscode,npm i react-native-amap3d 后，js页面引用报错，typescript错误

### ISSUE THREAD

**Issue by katyzp** [qiuxiang/react-native-amap3d#339]
<img width="921" alt="aaaa" src="https://user-images.githubusercontent.com/39953083/41019351-cece7a90-6990-11e8-9bf1-d8c0f64b792c.png">

请问，怎么支持js引入？

**Comment by qiuxiang** [comment]
https://github.com/flowtype/flow-for-vscode
