### ISSUE TITLE
rn升级到0.47.1后报错

### ISSUE THREAD

**Issue by siroer** [qiuxiang/react-native-amap3d#34]
e: G:\MyProject\node_modules\react-native-amap3d\android\src\main\java\cn\qiuxiang\react\amap3d\AMap3DPackage.kt: (10, 5): 'createJSModules' overrides nothing 
:react-native-amap3d:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-amap3d:compileReleaseKotlin'.
> Compilation error. See log for more details

**Comment by qiuxiang** [comment]
这个问题我是知道的，也已经改好了 https://github.com/qiuxiang/react-native-amap3d/commit/7972eb4112843554f42c092aa8ab9eefc6852775#diff-956fab68d13a3f80e0d0a5061fc0a725 ，只是目前还没有发布新版本，明天或后天再发布。

**Comment by siroer** [comment]
还没更新啊 哥们

**Comment by qiuxiang** [comment]
已经更新了 v0.2.4
