### ISSUE TITLE
android link不了 有手动配置的文档吗？

### ISSUE THREAD

**Issue by showtan001** [qiuxiang/react-native-amap3d#340]
配置时候不能link，求一份手动配置文档。

**Comment by qiuxiang** [comment]
没有手动配置文档

**Comment by showtan001** [comment]
react: 16.0.0-alpha.6
react-native: 0.44.0
react-native-amap3d: 1.0.0

android:
`:react-native-amap3d:compileReleaseKotlin
e: D:\project\lidianchi\node_modules\react-native-amap3d\lib\android\src\main\ja
va\cn\qiuxiang\react\amap3d\AMap3DPackage.kt: (9, 1): Class 'AMap3DPackage' is n
ot abstract and does not implement abstract member public abstract fun createJSM
odules(): (Mutable)List<Class<out JavaScriptModule!>!>! defined in com.facebook.
react.ReactPackage
:react-native-amap3d:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-amap3d:compileReleaseKotlin'.
> Compilation error. See log for more details`
大兄弟看看是什么问题

**Comment by qiuxiang** [comment]
不支持 0.47 以下版本

**Comment by showtan001** [comment]
哦

**Comment by CrazyMan2** [comment]
> 不支持0.47以下版本

0.59.8也是要手等连接的啊，请问怎样连接，还是说新版只支持0.6x以上？
