### ISSUE TITLE
mac系统pod install报错/bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by ligson** [qiuxiang/react-native-amap3d#341]
操作系统mac ios
package.json

```json
{
  "name": "aidemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "moment": "^2.22.2",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-amap3d": "^1.0.0",
    "react-navigation": "^2.0.4"
  },
  "devDependencies": {
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
ios目录pod install报错

```bash
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `react-native-amap3d` from `../node_modules/react-native-amap3d/lib/ios`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing AMap3DMap (6.1.0)
Installing AMapFoundation (1.5.2)
Installing DoubleConversion (1.1.5)
Installing Folly (2016.09.26.00)
Installing React (0.55.4)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.4)
[!] /bin/bash -c 
set -e
#!/bin/bash
set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH:-armv7}"

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h

/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif

/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif

/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

/bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory


[!] 'AMap3DMap' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.

[!] 'AMapFoundation' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.

```

**Comment by ligson** [comment]
哪个脚本你提交的是dos格式不是unix格式

**Comment by qiuxiang** [comment]
这个项目并没有用脚本，configure 是编译系统生成的，与这个项目没有关系

**Comment by ligson** [comment]
那这个问题是RN的问题了？

**Comment by qiuxiang** [comment]
更大的可能是你本地的编译系统有问题，你可以试试运行 example，如果连 example 都相同的错误，就可以确定了。

**Comment by ZSH-HSZ** [comment]
你好，你解决了吗？我的也是这样

**Comment by ligson** [comment]
没有。我悬赏一百元。也没人帮我。




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            ligson
                            
                            
                                
                                    邮箱：ligson@aliyun.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master
在2018年07月13日 16:13，ZSH-HSZ 写道： 你好，你解决了吗？我的也是这样

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/qiuxiang/react-native-amap3d","title":"qiuxiang/react-native-amap3d","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/qiuxiang/react-native-amap3d"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ZSH-HSZ in #341: 你好，你解决了吗？我的也是这样"}],"action":{"name":"View Issue","url":"https://github.com/qiuxiang/react-native-amap3d/issues/341#issuecomment-404760917"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/qiuxiang/react-native-amap3d/issues/341#issuecomment-404760917",
"url": "https://github.com/qiuxiang/react-native-amap3d/issues/341#issuecomment-404760917",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [qiuxiang/react-native-amap3d] mac系统pod install报错/bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory (#341)",
"sections": [
{
"text": "",
"activityTitle": "**ZSH-HSZ**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ZSH-HSZ",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"qiuxiang/react-native-amap3d\",\n\"issueId\": 341,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/qiuxiang/react-native-amap3d/issues/341#issuecomment-404760917"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 342914094\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by qiuxiang** [comment]
如果问题不能重现，就根本无从帮助

**Comment by ligson** [comment]
可以，但是的确像你说的。是我编译环境问题。换同事的电脑，就没事。所以我也想弄清楚，到底依赖哪些c的库。问题应该出在glog上。


原始邮件
发件人:7c00notifications@github.com
收件人:qiuxiang/react-native-amap3dreact-native-amap3d@noreply.github.com
抄送:沙舟狼客ligson@aliyun.com; Authorauthor@noreply.github.com
发送时间:2018年7月13日(周五) 17:11
主题:Re: [qiuxiang/react-native-amap3d] mac系统pod install报错/bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory (#341)


如果问题不能重现，就根本无从帮助

**Comment by ligson** [comment]
@ZSH-HSZ 加了，问题还是没有解决，困惑很长时间了

**Comment by chenyang-biu** [comment]
sdk 使用http请求的原因?

**Comment by ligson** [comment]
@chenyang-biu  不确定，的确是编译环境问题。。但是我没有找到区别
