### ISSUE TITLE
安卓编译报错 

### ISSUE THREAD

**Issue by VesperHan** [qiuxiang/react-native-amap3d#343]
(com.amap.api.mapcore.util.hx) that doesn't come with an
associated EnclosingMethod attribute.

This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Dex: The number of method references in a .dex file cannot exceed 64K.

1.0.0-beta.1

rn 0.44.0 之前改完代码已经成功跑起来,隔了几天跑不起来了 报这个错误

**Comment by qiuxiang** [comment]
这是 android 的 64K 限制，https://developer.android.com/studio/build/multidex?hl=zh-cn
