### ISSUE TITLE
当前插件是否支持向地图窗口添加Overlay，即添加层。

### ISSUE THREAD

**Issue by markm4** [qiuxiang/react-native-amap3d#346]
当前插件是否支持向地图窗口添加Overlay，即添加层。如果可以，是否能给出示例。

**Comment by markm4** [comment]
我看到支持绘制多边形，多边形可以填充颜色。我们需要展示多边形图片，同时要求图片和行政区拟合。在原生中可以把图片作为图层和对应行政区拟合。

**Comment by qiuxiang** [comment]
这个不支持
