### ISSUE TITLE
功能请教

### ISSUE THREAD

**Issue by fgxls** [qiuxiang/react-native-amap3d#348]
大佬，请问应用切到后台能继续获取当前位置信息吗

**Comment by fgxls** [comment]
也许我问的地方不对，应该在react-native-amap-geolocation那边问。我看高德文档是需要开启后台定位和持续定位的 所以如果您没有接入的话 RN这边是不行的![2018-06-21 8 33 56](https://user-images.githubusercontent.com/26613491/41719405-827933a2-7592-11e8-9f10-a902ef51c609.png)

**Comment by fgxls** [comment]
http://lbs.amap.com/api/ios-location-sdk/guide/get-location/backgroundlocation

**Comment by qiuxiang** [comment]
那就不应该在这个项目提这个 issue，这需要测试
