### ISSUE TITLE
以经纬度为中心画圆，填充颜色，这个圆不能让他半透明吗？

### ISSUE THREAD

**Issue by cuijiashi** [qiuxiang/react-native-amap3d#349]
以经纬度为中心画圆，填充颜色，这个圆不能让他半透明吗？我设置了opacity也没有用，我看了Circle没有这个透明属性

**Comment by qiuxiang** [comment]
没有 opacity 这个属性，但你可以用 rgba

**Comment by cuijiashi** [comment]
好的，谢谢，忘记rgba也可以做透明了
