### ISSUE TITLE
关于定位

### ISSUE THREAD

**Issue by siroer** [qiuxiang/react-native-amap3d#35]
单独测试example的地图控件例子
https://github.com/qiuxiang/react-native-amap3d/blob/master/example/src/examples/controls.js
在Android Studio的模拟器的 Extended controls 中模拟GPS坐标是成功的，
但是我将这段代码拷贝到我的项目 （RN Version 0.44.3）测试定位按钮的时候没有生效（定位到零度经纬）

**Comment by qiuxiang** [comment]
是高德 Key 的问题吧，Key 是否匹配 android studio logcat 是有提示的

**Comment by siroer** [comment]
通过对比，README配置权限比 Example 的 少了下面这一段


    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
