### ISSUE TITLE
海量点不刷新展示的问题

### ISSUE THREAD

**Issue by RQZeng** [qiuxiang/react-native-amap3d#351]
## 使用AMapMultiPoint问题，第二次不刷新展示
* 第一次设置了海量点的比如为`[{39,116},{39.01,116.01},{39.02,116.02}]`，其展示了这些点在北京
* 第二次设置了海量点的比如为`[{22,114},{22.01,114.01},{22.02,114.02}]`，其展示了这些点依然在北京，实际上，那些点应该为深圳
* 对kt不是很熟悉，请问是啥造成的？

**Comment by qiuxiang** [comment]
Duplicate of #267 #319

**Comment by RQZeng** [comment]
”恐怖？MultiPoint 和 HeatMap 本来就不应该频繁更新，如果非要更新，那么完全可以设置一个新 key 触发重绘。“

这个怎么弄？

**Comment by qiuxiang** [comment]
你还是自己找资料看看 react key 的用法吧
