### ISSUE TITLE
安卓依赖配置完成打包报错

### ISSUE THREAD

**Issue by http-lbw** [qiuxiang/react-native-amap3d#352]
> Could not resolve org.jetbrains.kotlin:kotlin-android-extensions:1.2.41.
           Required by:
               dabao:react-native-amap3d:unspecified > org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41
            > Could not resolve org.jetbrains.kotlin:kotlin-android-extensions:1.2.41.
               > Could not parse Ivy file /home/hefoni/.gradle/caches/modules-2/metadata-2.16/descriptors/org.jetbrains.kotlin/kotlin-android-extensions/1.2.41/22da77b0d76ea8df17298218f
3ec1f87/ivy.xml
                  > Premature end of file.
         > Could not resolve org.jetbrains.kotlin:kotlin-compiler-runner:1.2.41.
           Required by:
               dabao:react-native-amap3d:unspecified > org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41
            > Could not resolve org.jetbrains.kotlin:kotlin-compiler-runner:1.2.41.
               > Could not parse Ivy file /home/hefoni/.gradle/caches/modules-2/metadata-2.16/descriptors/org.jetbrains.kotlin/kotlin-compiler-runner/1.2.41/22da77b0d76ea8df17298218f3ec
1f87/ivy.xml
                  > Premature end of file.
         > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.2.41.
           Required by:
               dabao:react-native-amap3d:unspecified > org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41
            > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.2.41.
               > Could not parse Ivy file /home/hefoni/.gradle/caches/modules-2/metadata-2.16/descriptors/org.jetbrains.kotlin/kotlin-reflect/1.2.41/22da77b0d76ea8df17298218f3ec1f87/ivy
.xml
                  > Premature end of file.

**Comment by qiuxiang** [comment]
你本地环境的问题

**Comment by http-lbw** [comment]
我这里没添加依赖环境时候打包是好的，然后link之后在打包就报这个错了，大佬可以+qq联系下吗，我QQ：602175977

**Comment by qiuxiang** [comment]
抱歉，这需是 android 的问题，我不用 QQ，也不太有时间解决你的问题。

**Comment by qiuxiang** [comment]
大概提一下，你这个问题需要清除个人目录的 gradle cache
