### ISSUE TITLE
使用地图打包报错

### ISSUE THREAD

**Issue by http-lbw** [qiuxiang/react-native-amap3d#358]
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-amap3d'.
      > Failed to notify project evaluation listener.
         > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by qiuxiang** [comment]
看起来这是你本地的问题

**Comment by http-lbw** [comment]
我试过一运行react-native link react-native-amap3d 之后就这个样子了，

**Comment by qiuxiang** [comment]
这是需要你自己解决的问题，仅供参考：https://stackoverflow.com/questions/44094037/android-studio-failed-to-notify-project-evaluation-listener-error

**Comment by http-lbw** [comment]
这个插件对gradle版本有什么兼容吗？有没有需要gradle的版本是多少？

**Comment by qiuxiang** [comment]
没有什么要求，你可以试试 example
