### ISSUE TITLE
0.47.1版本的项目，地图不显示

### ISSUE THREAD

**Issue by yuluosheng** [qiuxiang/react-native-amap3d#36]
配置了高德地图的权限和KEY，在启动也里面添加了地图控件，但是没有显示地图出来，也没有报错。
![image](https://user-images.githubusercontent.com/9364478/29511544-0903971e-8692-11e7-9672-f2e8a272d275.png)

      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <MapView>
          <Marker
              draggable
              title='这是一个可拖拽的标记'
              onDragEnd={({nativeEvent}) =>
              console.log(`${nativeEvent.latitude}, ${nativeEvent.longitude}`)}
                      coordinate={{
              latitude: 39.91095,
              longitude: 116.37296,
            }}/>
        </MapView>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
      </View>

**Comment by qiuxiang** [comment]
这应该是 react-native 的常识吧。。MapView 本质上还是一个 View，你要设置宽度和高度

**Comment by yuluosheng** [comment]
可以了，谢谢！
