### ISSUE TITLE
[问题]引用地图时执行./gradlew assembleRelease时报错

### ISSUE THREAD

**Issue by kai0214** [qiuxiang/react-native-amap3d#360]
Import statement may only appear at top level in file /C:/Documents/mapView/index.js at 2:2

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by qiuxiang** [comment]
这错误信息没有任何价值

**Comment by kai0214** [comment]
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-amap3d'.
      > Could not resolve all dependencies for configuration ':react-native-amap3d:classpath'.
         > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.41.
           Required by:
               ride_app:react-native-amap3d:unspecified > org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41
               ride_app:react-native-amap3d:unspecified > org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41 > org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.2.41
            > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.41.
               > Could not parse Ivy file /home/hefoni/.gradle/caches/modules-2/metadata-2.16/descriptors/org.jetbrains.kotlin/kotlin-stdlib/1.2.41/22da77b0d76ea8df17298218f3ec1f87/ivy.
xml
                  > Premature end of file.
         > Could not resolve org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.41.
           Required by:
               ride_app:react-native-amap3d:unspecified > org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41
            > Could not resolve org.jetbrains.kotlin:kotlin-compiler-embeddable:1.2.41.
               > Could not parse Ivy file /home/hefoni/.gradle/caches/modules-2/metadata-2.16/descriptors/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.41/22da77b0d76ea8df17298218
f3ec1f87/ivy.xml
                  > Premature end of file.
         > Could not resolve org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.2.41.
           Required by:
               ride_app:react-native-amap3d:unspecified > org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41
            > Could not resolve org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.2.41.
               > Could not parse Ivy file /home/hefoni/.gradle/caches/modules-2/metadata-2.16/descriptors/org.jetbrains.kotlin/kotlin-annotation-processing-gradle/1.2.41/22da77b0d76ea8d
f17298218f3ec1f87/ivy.xml
这个错是什么

**Comment by qiuxiang** [comment]
网络问题，你可能要翻墙
