### ISSUE TITLE
如何实现marker动画效果

### ISSUE THREAD

**Issue by markm4** [qiuxiang/react-native-amap3d#362]
请问这个插件是否支持，地图上的marker添加动画，比如marker使用的图片是两张或更多图片资源循环播放，或者marker的样式不断修改实现光晕效果，类似 css样式，如下：
@-webkit-keyframes  shineRed {  
    from { -webkit-box-shadow: 0 0 5px #bbb; }  
    50% { -webkit-box-shadow: 0 0 50px red; }  
    to { -webkit-box-shadow: 0 0 10px #bbb; }  
    }  
    .shine_red{  
    -webkit-animation-name: shineRed;   
    -webkit-animation-duration: 2s;  
    -webkit-animation-iteration-count: infinite;   
    }  

前提是不反复渲染所有点，如果支持请指明用法，如果目前不支持是否有成熟的思路实现？
在此先感谢您的帮助。

**Comment by markm4** [comment]
目前已经有了临时的解决方案。
在创建marker时，使用自定义方式创建，向icon中传入一个被Animated标签包裹的组件，使用react native自带的Animated控件控制动画效果，示例代码如下：
闪烁组件的主要代码片段：
   componentDidMount() {
        animatieContinue = true;
        this._startAnimation();
    }
    componentWillUnmount() {
        animatieContinue = false;
    }

    _startAnimation = () => {
        this.state.borderWidth.setValue(0);
        Animated.timing(                            // 随时间变化而执行的动画类型
            this.state.borderWidth,                      // 动画中的变量值
            {
                velocity: 10,
                toValue: 4,                             // 透明度最终变为1，即完全不透明
            },
          ).start(() => {if (animatieContinue){this._startAnimation();}}); 
    }
         <Animated.View                            // 可动画化的视图组件
            style={{
              ...this.props.style,
              borderWidth: this.state.borderWidth,          // 将透明度指定为动画变量值
              borderColor:'red',
              borderRadius:10,
              backgroundColor:'red',
              justifyContent:'center',
              alignItems: 'center',
            }}
          > 
            <Image 
                style={[{height:16,width:16,borderRadius:8,}]}
            source={require('../../images/gisover.png')} />
          </Animated.View>

创建marker 的代码片段：
        <MapView.Marker
          style={{height:20,width:20}}
          infoWindowDisabled={true}
          key={key}
          icon={() => ImageView}
          coordinate={{
            latitude: parseFloat(item.Latitude, 10),
            longitude: parseFloat(item.Longitude, 10),
          }}
          onPress={()=>{
            // this.props.dispatch(NavigationActions.navigate({ routeName: 'Detail' }));
            this.props.dispatch(NavigationActions.navigate({ routeName: 'SingleStationDetail' }));
          }}
        />
我是通过控制Animated的border 实现红色光圈向外扩展的动画，类似于之前提到的css样式，有光晕向外扩散。
之后遇到了新的问题，如果地图上同时渲染多个点（30个以内），有3个闪烁样式的点，这时候会产生大量的内存泄漏，大约10分钟内存扩张至700m，内存泄漏的主要角色是android的native层，graphics的内存占用大约在60-70m之间。希望与作者交流这方面的相关信息。

**Comment by qiuxiang** [comment]
如果你知道 android 自定义 view 的实现，就不要这样用，这是没法优化的的，如果你一定做 marker 动画，最好用 SDK 提供的动画播放功能 http://a.amap.com/lbs/static/unzip/Android_Map_Doc/3D/com/amap/api/maps/model/Marker.html#setIcons-java.util.ArrayList- 。但这个功能我暂时不考虑实现。

**Comment by markm4** [comment]
感谢您的支持，正在阅读kotlin相关资料，目前只能使用java对原生编码，同时我会认真查看您提供的资料。

**Comment by qiuxiang** [comment]
我记得官方实例是有 demo 的 http://amappc.cn-hangzhou.oss-pub.aliyun-inc.com/lbs/static/zip/AMap_Android_Demo.zip

**Comment by markm4** [comment]
好的，我会认真查看demo，谢谢您的帮助

**Comment by markm4** [comment]
<MapView.Marker
            style={{ height: 20, width: 20 }}
            infoWindowDisabled={true}
            key={key}
            /* image={imageName} */
            icon={() => ImageView}
            coordinate={{
              latitude: parseFloat(item.Latitude, 10),
              longitude: parseFloat(item.Longitude, 10),
            }}
            onPress={() => {
              // this.props.dispatch(NavigationActions.navigate({ routeName: 'Detail' }));
              this.props.dispatch(
                NavigationActions.navigate({ routeName: 'SingleStationDetail' })
              );
            }}
          />
请问您的这个插件，中的icon实现自定义marker，对应原生部分那种实现方式，是通过infowindow显示的吗？

**Comment by qiuxiang** [comment]
marker 是 marker，infoWindow 是 infoWindow。android marker 的 icon 是通过将 view 渲染成图片再用 sdk marker 的自定义图片接口来显示，这是我目前唯一知道的能实现自定义 view 的方法了，react-native-maps 也是用这种方法。

这种方法的问题在于每次 view 变更就必须重新渲染一次图片，如果频繁更新或有大量的 marker 同时渲染，就会导致性能问题。

**Comment by markm4** [comment]
@qiuxiang 非常感谢您的解答

**Comment by markm4** [comment]
在AMapMarkerManager.kt中增加如下代码：
@ReactProp(name = "gif")
    fun setGif(marker: AMapMarker,names: ReadableArray) {//(marker: AMapMarker, image: String) {
        marker.setGif(names.toArrayList())
    }

在AMapMarker.kt中增加如下代码：
fun setGif (names: ArrayList<Any>){//setGif(name: String) {
      var mList:ArrayList<BitmapDescriptor?> = arrayListOf()
      bitmapDescriptor = BitmapDescriptorFactory.fromResource(context.resources.getIdentifier("gisover", "drawable", context.packageName))
      mList.add(bitmapDescriptor)
      bitmapDescriptor = BitmapDescriptorFactory.fromResource(context.resources.getIdentifier("gisfault", "drawable", context.packageName))
      mList.add(bitmapDescriptor)
      bitmapDescriptor = BitmapDescriptorFactory.fromResource(context.resources.getIdentifier("gisnormal", "drawable", context.packageName))
      mList.add(bitmapDescriptor)
      Log.e("hxf",mList.toString())
      marker?.setAnchor(0.5f,0.5f)
      marker?.setIcons(mList)
      marker?.setPeriod(20)
    }

根据java部分代码猜测的写法，但是只能显示最后放入list的图片，这是为什么呢

**Comment by markm4** [comment]
已经解决。需要在override fun add中实现模拟gif的代码
override fun add(map: AMap) {
        marker = map.addMarker(MarkerOptions()
          .setFlat(flat)
//          .icon(bitmapDescriptor)
          .alpha(opacity)
          .draggable(draggable)
          .position(position)
          .anchor(anchorU, anchorV)
          .infoWindowEnable(!infoWindowDisabled)
          .title(title)
          .snippet(snippet)
          .icons(mList)
          .period(20)
          .zIndex(zIndex))
     
        this.clickDisabled = clickDisabled
        this.active = active
    }

还是不太熟悉，有些着急，已经解决了
