### ISSUE TITLE
地图sdk冲突，本地项目使用的是2d地图，并且做成了组件在多个项目中使用，但是RN里面是3d地图，有2d版本的吗

### ISSUE THREAD

**Issue by shuifengYu** [qiuxiang/react-native-amap3d#364]
如题，我们项目已经使用到了2d地图的sdk，并且使用内部2次封装的组件，该组件在多个项目被使用，不能轻易升级，因此和RN中的3d地图sdk就冲突了，所以我在想有没有解决方案或者有提供2d地图sdk的RN版本吗

**Comment by qiuxiang** [comment]
这个项目没有 2D 版本
