### ISSUE TITLE
如何获取我当前的旋转角度

### ISSUE THREAD

**Issue by since66** [qiuxiang/react-native-amap3d#366]
我想在3D地图实现导航功能，要一直获取箭嘴后面的角度，就是转弯的时候也要跟着转变角度，请问怎么实现

**Comment by qiuxiang** [comment]
这个 SDK 的定位图层是支持的吧

**Comment by since66** [comment]
你DEMO没有哦，能不能做一个3D的DEMO出来？

**Comment by qiuxiang** [comment]
你说的应该是 follow mode，这个没有实现
