### ISSUE TITLE
实时定位改变了setstate值

### ISSUE THREAD

**Issue by HelenChenVIP** [qiuxiang/react-native-amap3d#367]
你好，我现在用了一个定位的功能，但是我发现这是个实时定位，每隔几秒自动刷新定位位置，这样的话就会总是改变我的setState的值。那么其他界面会被重新绘制。我想请教一下，怎么把实时定位关掉，我只需要进入这个界面定位一次即可，有需要定位手动触发，谢谢！
<MapView 
                zoomLevel={13} 
                locationEnabled={true}
                showsLocationButton={true}
                rotateEnabled={this.state.rotateEnabled}    
                onLocation={({ nativeEvent }) =>
                {
                  this.setState({
                    longitude: nativeEvent.longitude,
                    latitude: nativeEvent.latitude
                  });
                }}   
                coordinate={{
                  latitude: this.state.latitude ? this.state.latitude : 35.103663,
                  longitude: this.state.longitude ? this.state.longitude : 118.356618,
                }}
                style={{width:SCREEN_WIDTH,height:150,borderColor:'#dedede',borderWidth:1}}>
              </MapView>

**Comment by qiuxiang** [comment]
不是有 `locationEnabled` 吗

**Comment by HelenChenVIP** [comment]
ocationEnabled={true} 我这设置的。我发现这样设置上以后默认就是实时刷新呢。

**Comment by qiuxiang** [comment]
你不是问怎么把定位关掉吗，不会设置成 false 吗

**Comment by HelenChenVIP** [comment]
我意思是，我在第一次进入这个界面的时候自动定位一次就可以了。不需要实时定位。我把ocationEnabled={false}则无法定位了。

**Comment by qiuxiang** [comment]
没有你要的这个接口，你完全可以自己处理呀，定位成功就设置为 false

**Comment by dccmmtop** [comment]
你可以这样,只是提供一个思路。
```jsx
constructor(props){
  super(props);
  this.state={
    longitude:0,
    latitude:0,
  }
}
<MapView
  zoomLevel={13}
  locationEnabled={true}
  showsLocationButton={true}
  rotateEnabled={this.state.rotateEnabled}
  onLocation={({ nativeEvent }) => {
  if(this.state.latitude == 0){
    this.setState({
      longitude: nativeEvent.longitude,
      latitude: nativeEvent.latitude
    })}
  }}
  style={{ width: SCREEN_WIDTH, height: 150, borderColor: '#dedede', borderWidth: 1 }}>
```
