### ISSUE TITLE
debug的时候没问题，release后一切换到用了react-native-amap3d的页面就闪退

### ISSUE THREAD

**Issue by fiowind** [qiuxiang/react-native-amap3d#369]
"react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-amap3d": "^1.0.0",

**Comment by IngoDeng** [comment]
我也遇到同样的问题，请问你解决了吗？

**Comment by qiuxiang** [comment]
该 issue 关闭，除非能提供有用信息
