### ISSUE TITLE
CocoaPods use_framework! 导入成功

### ISSUE THREAD

**Issue by PMExtra** [qiuxiang/react-native-amap3d#370]
> The 'Pods-ProjectName' target has transitive dependencies that include static binaries ...

看到很多人遇到这个问题，这个问题也困扰了我很多天，现在终于解决，分享一下：

导致问题的根本原因是，`react-native-amap3d`引用了高德官方的SDK `pod 'AMap3DMap'`，而高德官方SDK并不开源，只有一个Framework。

在不使用`use_frameworks!`标记时，嵌套的官方SDK直接通过`-l`连接到项目中。`react-native-amap3d`只编译自己的部分，所以所有的互相传递的依赖的静态库都能最终被导入。
但是在使用`use_frameworks!`时，打包的`react-native-amap3d`就会包含高德`AMap3DMap`库中的内容。所以对于我们的主项目，这里就有一个符号冲突的问题了。
而CocoaPods对于这种问题，统一通过报错来拒绝这种情况。

解决方法：
第一步：强行设置`react-native-amap3d`在运行时动态查找符号。
在`react-native-amap3d`的`Podsec` (node_modules/react-native-amap3d/lib/ios/react-native-amap3d.podspec) 中添加以下内容：
```
s.pod_target_xcconfig = {
    'OTHER_LDFLAGS' => '$(inherited) -undefined dynamic_lookup'
}
```

第二步：设置CocoaPods不要检查静态库嵌套依赖（static_framework_transitive_dependencies）。
在自己项目的`Podfile`中添加`pre_install`脚本：
```
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```

然后重新执行`pod install`，编译即可。

参考资料：
http://luoxianming.cn/2016/03/27/CocoaPods/
https://github.com/CocoaPods/CocoaPods/issues/3289
https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md

**Comment by yidahis** [comment]
可以把以下语句直接放到目标  `installer`  的 `podspec`，例如
```
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

Pod::Spec.new do |s|
...

```
