### ISSUE TITLE
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-amap3d'. 

### ISSUE THREAD

**Issue by wm2zfei** [qiuxiang/react-native-amap3d#372]
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-amap3d'. Minimum required is 25.0.0

RN升级到0.56.0 官方稳定版后，编译android出现以上提示，
查看了一下build.gradle buildToolsVersion 是26.0.03 高于23 也高于25
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"

不知如何修复

**Comment by qiuxiang** [comment]
目前你只能把这个项目的 buildToolsVersion 改成与 app 一致
