### ISSUE TITLE
下载你的项目 npm install ，react-native run-android 后报错

### ISSUE THREAD

**Issue by my4piano** [qiuxiang/react-native-amap3d#375]
下载你的项目

npm install 

添加key：
<application>
  <meta-data
    android:name="com.amap.api.v2.apikey"
    android:value="xxx" />
</application>

react-native run-android 报错

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-amap3d'.
      > Could not resolve all dependencies for configuration ':react-native-amap3d:classpath'.
         > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41.
           Required by:
               RNAMap3D:react-native-amap3d:unspecified
            > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41.
               > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.41/kotlin-gradle-plugin-1.2.41.pom'.
                  > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.41/kotlin-gradle-plugin-1.2.41.pom'.
                     > Host name 'jcenter.bintray.com' does not match the certificate subject provided by the peer (CN=*.campaign.adobe.com, OU=Adobe Campaign, O=Adobe Systems Incorporated, L=San Jose, ST=California, C=US)

**Comment by qiuxiang** [comment]
网络问题

**Comment by my4piano** [comment]
你说得对，换了一个地方再试，成功了
