### ISSUE TITLE
pod install报错

### ISSUE THREAD

**Issue by nazihead** [qiuxiang/react-native-amap3d#378]
git拉下来yarn之后
在ios目录下执行pod install报错
`
$ pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `GLog` from `../node_modules/react-native/third-party-podspecs/GLog.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-amap3d` from `../lib/ios/`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] CocoaPods could not find compatible versions for pod "AMap3DMap":
  In Podfile:
    react-native-amap3d (from `../lib/ios/`) was resolved to 1.0.1, which depends on
      AMap3DMap (~> 6.3.0)

None of your spec sources contain a spec satisfying the dependency: `AMap3DMap (~> 6.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
`

**Comment by qiuxiang** [comment]
你都不看提示的吗
