### ISSUE TITLE
移动地图  标记点一直显示在地图中心点  能拿到当前地图标记点的经纬度

### ISSUE THREAD

**Issue by NightCold** [qiuxiang/react-native-amap3d#379]
大哥  我们公司有个需求  就是当用户移动地图 然后 定位的那个点一直在移动地图的中心点 然后点击确定的时候  把中心点的位置给整出来发送后台

**Comment by qiuxiang** [comment]
你需要的是
https://github.com/qiuxiang/react-native-amap3d/blob/1d50d6fa0d2e1b7b2bc565089b02fdaf8ceffe02/lib/js/maps/MapView.js#L250

**Comment by NightCold** [comment]
现在还有两个问题 希望请教一下你  
 1  当我在cocoaPods 里面加入下面的三个命令的时候  Glog 一直下载不成功
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
2 当我不加入上面的三句话时 我搞一个iOS 的测试项目 模拟器没有问题  但是打包就会遇到 一个问题 我直接截图


ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libRCTWebSocket.a(RCTSRWebSocket.o)
duplicate symbol _OBJC_METACLASS_$_RCTSRWebSocket in:
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libReact.a(RCTSRWebSocket.o)
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libRCTWebSocket.a(RCTSRWebSocket.o)
duplicate symbol _OBJC_METACLASS_$__RCTSRRunLoopThread in:
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libReact.a(RCTSRWebSocket.o)
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libRCTWebSocket.a(RCTSRWebSocket.o)
duplicate symbol _OBJC_CLASS_$_RCTWebSocketModule in:
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libReact.a(RCTWebSocketModule.o)
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libRCTWebSocket.a(RCTWebSocketModule.o)
duplicate symbol _OBJC_IVAR_$_RCTWebSocketModule._sockets in:
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libReact.a(RCTWebSocketModule.o)
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libRCTWebSocket.a(RCTWebSocketModule.o)
duplicate symbol _OBJC_METACLASS_$_RCTWebSocketModule in:
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libReact.a(RCTWebSocketModule.o)
    /Users/guojiaozeng/Library/Developer/Xcode/DerivedData/test-fkhvfvbnrjuidbcspuaambffykyy/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/libRCTWebSocket.a(RCTWebSocketModule.o)
ld: 230 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by qiuxiang** [comment]
不同 RN 版本，podfile 写法不同，参考 https://facebook.github.io/react-native/docs/0.52/integration-with-existing-apps.html 。

Archive 的问题，自己找已关闭的 issue 看看。
