### ISSUE TITLE
README.md 配置必要的权限一段 缺少 ACCESS_FINE_LOCATION

### ISSUE THREAD

**Issue by my4piano** [qiuxiang/react-native-amap3d#38]
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

**Comment by qiuxiang** [comment]
我知道的，其实这条权限并不是必须的，只是某些情况下影响定位精度，之后我再改

**Comment by qiuxiang** [comment]
其实这个项目的 manifest 已经声明过权限了（旧版确实漏了一些权限），没有必要再写一边权限声明。
