### ISSUE TITLE
地图路径规划

### ISSUE THREAD

**Issue by http-lbw** [qiuxiang/react-native-amap3d#382]
如何在地图上使用poyline绘制线路图，已知起点与终点的经纬度，可是拿poyline绘制出的线路是一条直线，如何绘制出路径规划一样的线路图？

**Comment by qiuxiang** [comment]
多个点的 polyline 不就是线路图了？

**Comment by http-lbw** [comment]
呢我该如何获取多个点的经纬度呢？我怎么获取起点与终点的推荐路线呢？

**Comment by qiuxiang** [comment]
自己看高德地图的 Web API

**Comment by http-lbw** [comment]
没有封装好的方法是吧

**Comment by qiuxiang** [comment]
没有
