### ISSUE TITLE
程序包cn.qiuxiang.react.geolocation不存在

### ISSUE THREAD

**Issue by learn4** [qiuxiang/react-native-amap3d#384]
安装react-native-amap3d包后，后面需要gps定位模块，就继续安装react-native-amap-geolocation，然后就报错了。
![image](https://user-images.githubusercontent.com/40156494/43558968-78b26e48-963e-11e8-8f5c-21253fca0486.png)

**Comment by qiuxiang** [comment]
看来是配置有问题，看看 gradle 配置是否正确
