### ISSUE TITLE
安卓渲染地图报红屏的问题

### ISSUE THREAD

**Issue by feijw** [qiuxiang/react-native-amap3d#387]
RN版本为0.46.4；
并不是必现的，红屏之后看到下面的图片信息
![b8dc4f6750d2d0a86d799e19e635c325](https://user-images.githubusercontent.com/42127280/43693604-7f56f216-9961-11e8-9b15-264786aa7a7d.png)

**Comment by feijw** [comment]
你好，在地图上使用用有自定义图片的marker渲染出几百个，反复更改了数据源重新生成渲染的marker，反复多次之后就会报如图所示的红屏，根据红屏中的提示感觉是timer的问题，但又不能确定。

**Comment by qiuxiang** [comment]
不再建议用自定义 view
