### ISSUE TITLE
Duplicate files copied in APK lib/armeabi/libAMapSDK_MAP_v6_3_0.so

### ISSUE THREAD

**Issue by jinghun1999** [qiuxiang/react-native-amap3d#388]
``Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi/libAMapSDK_MAP_v6_3_0.so
        File1: C:\Users\User\.gradle\caches\modules-2\files-2.1\com.amap.api\3dmap\6.3.0\938d6c45e7487787e6eecfcef5e8ab1fa425337f\3dmap-6.3.0.jar
        File2: D:\Work\GitHub\Yzb\node_modules\react-native-amap3d\lib\android\build\intermediates\bundles\default\jni

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.``

**Comment by qiuxiang** [comment]
看起来是本地环境的问题

**Comment by since66** [comment]
安卓文件的android\build.gradle版本号错了
classpath 'com.android.tools.build:gradle:2.2.+'

做个记录
