### ISSUE TITLE
安卓代码疑问

### ISSUE THREAD

**Issue by DuanYuna** [qiuxiang/react-native-amap3d#389]
在marker中为什么要给安卓的自定义图片添加延时呢
componentDidUpdate() {
    if (this.icon && Platform.OS === 'android') {
      setTimeout(() => this.sendCommand('update'), 0)
    }
  }

目前出现的问题 在地图上是用有自定义图片的marker渲染出几百个 然后在将marker数组变为空数组 就会崩溃报timer的问题
猜测是因为本来创建marker的时候创建了几百个timer然后marker数组为空之后就timer没有释放就变成空指针
但主要问题是想知道您加这个timer的意义是什么

**Comment by DuanYuna** [comment]
![b8dc4f6750d2d0a86d799e19e635c325](https://user-images.githubusercontent.com/13826312/43748301-6f7a9c06-9a21-11e8-84fe-514a4feb2644.png)

**Comment by qiuxiang** [comment]
如果不 setTimeout，native 拿到的 view 可能还没来得及 render，导致第一次 render，自定义 view 出不来，这个是之前测试过，最终采用的解决方案。

但我在另一个类似的项目 [react-native-baidumap-sdk](https://github.com/qiuxiang/react-native-baidumap-sdk/blob/master/lib/js/map-view/marker.js) 没有用 setTimeout 也没有问题。

你可以去掉 setTimeout 直接 update 试试，但你说的情况也挺奇怪的，什么情况才可能渲染出来又马上被释放掉了呢？

**Comment by DuanYuna** [comment]
第一次渲染几百个没有问题，然后经过筛选第二次渲染后数据为空的时候就会报错，怀疑是没有释放掉timer 
因为没有看到timer释放的地方 所以觉得可能是一次创建几百个 有一下变为空数据时候timer没有被释放掉的原因 我尝试过去掉这个timer发现运行也正常 没有什么异常出现 所以想问一下您这段代码的含义

另外在安卓的AMapView中我添加了一些代码  实现了将添加的所有marker都显示在视线范围内  
![image](https://user-images.githubusercontent.com/13826312/43759901-403b749c-9a53-11e8-8ca4-601d366fcace.png)
