### ISSUE TITLE
关于 配置的问题

### ISSUE THREAD

**Issue by NightCold** [qiuxiang/react-native-amap3d#39]
各位大佬 我想问一下 如果我安卓react-native link  iOS不用CocoaPods  是不是也行 iOS 也不用 手动配置了 而且 看官网手动配置 整个人都不好了  这几天 为地图发愁 能不能 给一份 这个插件的 配置文档  拜托了 辛苦了各位

**Comment by qiuxiang** [comment]
用 cocoapods 就是为了简化配置过程，这种情况不能 link；另一种选择是 link，然后自己把高德地图 SDK 加到 ios 项目，当然，你甚至可以不用 link，全程手动配置，只要你熟悉 ios 项目配置和编译。

**Comment by qiuxiang** [comment]
简单的配置文档 README 不是已经写了吗，至于手动配置的文档……我自己压根就不打算手动配置，所以就没写。

**Comment by NightCold** [comment]
你的意思是不是    我一个 项目  link之后 android 跟着你下面的步骤配置 然后 iOS 我自己在手动配置吧SDK包所需的东西 整进去  我先试试 谢谢了

**Comment by qiuxiang** [comment]
ios 手动配置真的很麻烦且容易出错，熟悉编译还好，不然手动配置过程中各种花式出错。我就不喜欢看到编译相关的 issue，因为绝大多数的原因都是出自自己对编译过程的不了解，而且因为环境差异，我可能根本碰不到相同的错误。

**Comment by bssunjiayang** [comment]
麻烦大家有么有遇到react-native-amap3d下面的Overlay.js找不到AMapOverlay，这个是什么原因呢

UIManager.AMapOverlay.Commands.update

**Comment by qiuxiang** [comment]
@bssunjiayang 没有编译吧

**Comment by bssunjiayang** [comment]
@qiuxiang 怎么可能。。。。
![image](https://user-images.githubusercontent.com/6613302/29995694-b63fe904-902a-11e7-9372-1648a02fde34.png)

**Comment by bssunjiayang** [comment]
![image](https://user-images.githubusercontent.com/6613302/29995706-d1ee9a6a-902a-11e7-8f1f-dc8716815baf.png)

**Comment by qiuxiang** [comment]
@bssunjiayang 只要 ios 里的 [AMapOverlayManager.m](https://github.com/qiuxiang/react-native-amap3d/blob/v0.5.0/ios/AMapOverlayManager.m) 有被编译，不可能没有 AMapOverlay。

你说不可能，那我先确认另一件事，不用 Marker，MapView 能正常显示吗？

**Comment by bssunjiayang** [comment]
@qiuxiang webstorm上这个文件，提示我安装一个plugin，安装之后这个问题就解决了，这应该是你说的没编译的问题，多谢帮忙，初学者，不好意思，多有得罪了。

**Comment by bssunjiayang** [comment]
@qiuxiang 不用marker是指的是？UIManager.AMapOverlay.Commands.update,这句话我注释掉？
初学者，有些东西有点迷惑

**Comment by qiuxiang** [comment]
@bssunjiayang 我的意思是，只 render MapView，能显示就说明经过了编译。

**Comment by danielwang2015** [comment]
IOS下地图不能显示，添加Mapview不起作用，请问该怎么解决

**Comment by qiuxiang** [comment]
@danielwang2015 首先你要安装这个库，并编译。

**Comment by bssunjiayang** [comment]
@qiuxiang 不好意思，我还是没什么头绪，我能通过什么方式联系你一下么，谢谢

**Comment by qiuxiang** [comment]
@bssunjiayang 你没有看 README 吗？

看起来，你对 react native 没有足够的认识，也不了解 ios 开发，这种情况下，我并不能提供什么帮助。

**Comment by bssunjiayang** [comment]
@qiuxiang 多谢提醒，我再去查查相关资料看看。

**Comment by danielwang2015** [comment]
@qiuxiang , 需要引用的库都在xcode里面引用了，同时也安装了这个包，但是就是不显示地图

> @danielwang2015 首先你要安装这个库，并编译。

**Comment by qiuxiang** [comment]
@danielwang2015 你确定已经经过配置（使用 pod 或按照 SDK 文档进行手动配置），而不只是 `npm install`？

还有，怎么个不显示，你也要描述得具体点，有没有出错？出现红框？有没有尝试用 logcat 工具寻找信息？

**Comment by danielwang2015** [comment]
@qiuxiang , 今天试了一下Android下面地图也无法显示，没有报错， 只有一个红点

**Comment by qiuxiang** [comment]
@danielwang2015 说明两个问题：

1. 没有引用个库
2. MapView 没有设置大小

Android 的配置是最简单的了，只要 link。

**Comment by danielwang2015** [comment]
@qiuxiang , 安装了包，也引用了库，我用Mapview标签的时候应该会报错，设置mapview大小以后只出现一个红色的框，但是地图内容没显示，我查了地图的key也没有问题，正常设置的

**Comment by qiuxiang** [comment]
@danielwang2015 

- 你说引用了，怎么证明？
- 什么叫“应该会报错”？报了什么错？
- 出现红框就是原生组件没有被编译，和 key 没有任何关系

你有用 Android Studio 和 Xcode 吗？有些东西不是你觉得是就是的，你要去证明，我需要更有价值的信息，而不是你单方面地诉说自己的问题。

**Comment by danielwang2015** [comment]
@qiuxiang , 重新pod install 提示 ：  Could not automatically select an Xcode project. Specify one in your Podfile like so:

    project 'path/to/Project.xcodeproj'  ， 尝试把项目文件的路径加进去还是报这个错误，请问该如何设置，谢谢

**Comment by qiuxiang** [comment]
……你的 Podfile 放在哪？

**Comment by Muriel0603** [comment]
我们使用的RN版本较低，所以选择了手动配置并降低版本，但是最后地图不显示就显示出来一个红色的框。。
![1](https://user-images.githubusercontent.com/14799431/30144630-e8a0f63a-93be-11e7-9b95-5dfaec15870e.jpeg)

**Comment by qiuxiang** [comment]
@Muriel0603 其实跟版本关系不大，在这里，看起来是虽然引入了高德地图，但没有引入这个库。

**Comment by Muriel0603** [comment]
link 之后一直报错 'MAMapKit/MAMapKit.h' file not found ，  search path 都配置过了的

![2](https://user-images.githubusercontent.com/14799431/30148134-a5964884-93d4-11e7-8c1d-fffbe6d0763a.jpeg)

**Comment by qiuxiang** [comment]
@Muriel0603 你还是自己想办法吧，可以肯定是 search path 的问题。但在哪设置，我没有手动配置过并不知道。

**Comment by danielwang2015** [comment]
@qiuxiang , Podfile文件放在IOS目录下面

**Comment by qiuxiang** [comment]
@danielwang2015 你的 Podfile 怎么写？

**Comment by Muriel0603** [comment]
用了最新版本的demo，降级后，用cocoapods是可以的，谢谢！

**Comment by danielwang2015** [comment]
@qiuxiang , Podfile 如下：
platform :ios, '10.25'

target 'HlkcApp' do
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/'
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'
end

**Comment by danielwang2015** [comment]
@qiuxiang , 请教一下，安装完成之后Xcode里面编译都时候报 link command failed with exit code 1， 网上查了很多方法都试过了还是不行，这个该怎么解决，谢谢

**Comment by qiuxiang** [comment]
`link command failed with exit code 1` 这个错误太宽泛了，对于编译错误，还是自己解决吧

**Comment by jiyarong** [comment]
@Muriel0603 怎么解决的，我现在也碰到这个问题了，编译不过去

**Comment by qiuxiang** [comment]
好吧，我想我知道你们所说的 'MAMapKit/MAMapKit.h' file not found 是怎么造成的了，想起来之前的一个 issue #10，我自己又试了下对 ios 项目 link，重新编译就出现这个问题了。

所以为什么你们没有仔细看 README 的安装说明呢。

**Comment by UncleLI-V** [comment]
我下载并运行了你的example，安卓真机测试，打开应用是一片空白。另我在已有项目的地图中添加标记Marker没有效果，请问需要怎么配置
![Uploading image.png…]()

**Comment by qiuxiang** [comment]
一片空白我也遇到过，很大一定程度是 RN 的问题，再次感谢 run 就可以了

**Comment by alisa-hui** [comment]
请问在安卓下显示一个红色边框，怎么回事啊？需要引入一个库？是什么库啊？

**Comment by qiuxiang** [comment]
@alisa-hui 显示红框是因为对应的 native component 没有编译，android 配置很简单呀，只要 link 就可以了

**Comment by alisa-hui** [comment]
我link了，添加了ak之后就link，但是还是显示的红框

**Comment by qiuxiang** [comment]
看 android-studio 的 logcat，应该有说哪个 native component 不存在

**Comment by alisa-hui** [comment]
我用的真机测试的，而且我没用过 android-studio，我是不是需要重装一下啊？

**Comment by qiuxiang** [comment]
和真机无关，这肯定是配置问题了，因为不知道你是怎么操作的，这需要做自己检查 `build.gradle`、`MainApplication.java`、`settings.gradle` 这些文件，要确认配置正确，这个项目的 example 可以作为参考。另外不管你用什么语言，错误日志永远是最有助于找到问题的。

**Comment by alisa-hui** [comment]
我重装的时候报com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
的错，是包重复引用了吗？

**Comment by qiuxiang** [comment]
我不是 android 专家，光这个信息根本不知道到底发生了什么

**Comment by alisa-hui** [comment]
好吧，谢谢你

**Comment by qiuxiang** [comment]
android 配置真的已经很简单了，你应该看下 example，既然要用 native component，一些原生知识肯定是要懂的

**Comment by WoAiLiMoChou** [comment]
用pod就报错
![image](https://user-images.githubusercontent.com/13573280/37019761-81d9dab0-2154-11e8-89b3-32986ccb8086.png)
然后手动配置的话
![image](https://user-images.githubusercontent.com/13573280/37019790-9a8874ea-2154-11e8-8700-b2159c34a0eb.png)
搞了几天了 有毒呀

**Comment by PMExtra** [comment]
@WoAiLiMoChou 你不看错误提示么，你那个Pods的错误都不关这个项目的事，最基础的React-Native都没配置好。https://facebook.github.io/react-native/docs/integration-with-existing-apps
