### ISSUE TITLE
IOS pod install 安装失败

### ISSUE THREAD

**Issue by since66** [qiuxiang/react-native-amap3d#390]
[!] CocoaPods could not find compatible versions for pod "AMap3DMap":
  In Podfile:
    react-native-amap3d (from `../lib/ios/`) was resolved to 1.0.1, which depends on
      AMap3DMap (~> 6.3.0)

None of your spec sources contain a spec satisfying the dependency: `AMap3DMap (~> 6.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by since66** [comment]
rm -rf ~/.cocoapods/repos/master
pod setup
pod install --verbose --no-repo-update

自己解决了

**Comment by Gamma-Ko** [comment]
Although I do not know what these are doing, I follow this steps;
rm -rf ~/.cocoapods/repos/master
pod setup
pod install --verbose --no-repo-update
pod install --repo-update 
Now I can install Amap but I got the error Native module cannot be null.
