### ISSUE TITLE
在渲染时触发一次定位？

### ISSUE THREAD

**Issue by chenyinlong** [qiuxiang/react-native-amap3d#391]
你好，根绝业务需求，怎么设置，才能只在程序打开时触发一次定位，并且不持续定位？

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-amap-geolocation

**Comment by qiuxiang** [comment]
或者自己控制 locationEnabled

**Comment by chenyinlong** [comment]
是用的持续定位，然后点击时通过方法聚焦到定位点上。现在正在发愁关于第一次进入时的定位和提供业务地区的匹配和逻辑关系问题，用web的服务过去反地理位置的获取，有什么好的建议吗？
