### ISSUE TITLE
Android导入高德导航sdk后运行出现包重复问题Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'

### ISSUE THREAD

**Issue by ALiaoo** [qiuxiang/react-native-amap3d#395]
项目本身需要导航功能，所以引入了高德导航sdk，但是高德导航sdk是和3dmap绑定的，高德导航sdk里已经包含了3dmap，在引入react-native-amap3d后，会和react-native-amap3d里的3dmap造成重复包的问题，运行项目报该错误：
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
目前的解决办法是把react-native-amap3d当做module添加到项目中，手动修改build.gradle中的compile 'com.amap.api:3dmap:6.3.0'为compile 'com.amap.api:navi-3dmap:latest.integration'
但是对以后的升级修改都要手动维护
是否可在react-native-amap3d加入导航的sdk呢

**Comment by qiuxiang** [comment]
不能。

之前我就有做过导航组件，也引入了导航 SDK，但后来导航组件暂停开发，也就又换回了原来的 SDK。理由在于引入导航 SDK 会导致打包体积无端增大，这显然不是绝大数人希望的。

**Comment by js1121302139** [comment]
可否开一个带导航组件的版本？
