### ISSUE TITLE
0.56.0 ios pod后整个app尺寸变大

### ISSUE THREAD

**Issue by BooYeu** [qiuxiang/react-native-amap3d#397]
没有pod时正常，pod后图片文字的大小占比都变大？

**Comment by qiuxiang** [comment]
有截图？

**Comment by BooYeu** [comment]
不好意思不好意思，调了好久解决了，是我把默认的启动图删了，自己没添加新的启动图，里面dimension获取的尺寸就全小，，，没想到居然是通过启动图判断的尺寸、、、
