### ISSUE TITLE
Marker 点击不灵敏 点击区域变大

### ISSUE THREAD

**Issue by HelenChenVIP** [qiuxiang/react-native-amap3d#398]
"react-native-amap3d": "^1.0.0",
  "react-native": "^0.51.0",

我想请问下：我再渲染多个Marker时候，点击某个Marker没有那么灵敏，想着扩大下Marker的点击范围，应该怎么实现呢？
现在的地图中是否有这个实现了呢？如果没有实现可否提供些解决方法，谢谢！
 <Marker   
                key={key+1} 
                active={this.state.activecode==item.DGIMN}  
                image={
                    item.fillIcon
                }
                onPress={()=>{
                    this.setState({
                        avglat:this.state.avglat === item.latitude ? item.latitude+ 1 / 10000 :item.latitude,
                        avglong:this.state.avglong === item.longitude ? item.longitude + 1 / 10000:item.longitude,
                        activecode:item.DGIMN
                    },);
                }}               
                coordinate={{
                latitude: mLonAndmLat[1],
                longitude: mLonAndmLat[0],}}/>

**Comment by qiuxiang** [comment]
自定义图片，留白多点不就行了

**Comment by HelenChenVIP** [comment]
您意思是，在做图片的时候吧图片周边留白多点是吗？代码中没法处理扩大点击区域吗？ @qiuxiang

**Comment by HelenChenVIP** [comment]
没有找到，试了多种方法也不行....

**Comment by qiuxiang** [comment]
那不就是了
