### ISSUE TITLE
安装react-native-amap3d无法找到模块的声明文件？

### ISSUE THREAD

**Issue by zhangxinjie** [qiuxiang/react-native-amap3d#399]
rn版本0.56    安卓设备和安卓模拟器上
Could not find a declaration file for module 'react-native-amap3d'. 
node_modules/react-native-amap3d/lib/js/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-amap3d` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-amap3d';

npm install @types/react-native-amap3d也下载不成功
![image](https://user-images.githubusercontent.com/20285578/44770620-30b13300-ab9b-11e8-9f7a-df0d62cdcce0.png)

**Comment by qiuxiang** [comment]
这并不会影响使用
