### ISSUE TITLE
用户主动点击“定位”按钮取得的 和 每隔x秒被动接收取得的 坐标数据，这两者如何区分？

### ISSUE THREAD

**Issue by my4piano** [qiuxiang/react-native-amap3d#41]
这两者触发的都是 onLocation 事件

**Comment by qiuxiang** [comment]
首先，我觉得点击定位按钮和 onLocation 事件没有任何关系，就算会触发事件，为什么要区分开来？

**Comment by my4piano** [comment]
当页面打开时，取得坐标数据，在onLocation中对该数据进行处理。
我只需要处理启动时第一次被动收到的，和每一次用户点击“定位”按钮的数据。

不需要处理每隔x秒就触发onlocation的坐标数据，太频繁。

**Comment by my4piano** [comment]
能否增加一个属性，是否循环取得坐标，要是0就取一次，n就隔n秒取一次，另外允许手动点击“定位”按钮取得。

**Comment by qiuxiang** [comment]
所以这问题问得。。让人完全不知道你想要做什么。

其实就是限制定位频率或者使用另一种成本更低的定位模式，对于 android 有设置定位间隔和定位模式的接口，对于 ios 有距离过滤的接口，我有计划在做。

**Comment by qiuxiang** [comment]
另外，与其指望点击定位按钮触发定位，不如实现一个主动请求定位的接口

**Comment by HADB** [comment]
@my4piano 定位按钮和onLocation事件不是一个维度的东西。你可以在点了定位按钮之后设置一个参数，在onLocation去根据这个参数决定是否需要处理onLocation的结果
