### ISSUE TITLE
关于Marker的自定义图片问题

### ISSUE THREAD

**Issue by liguanhan** [qiuxiang/react-native-amap3d#429]
问题描述:
先对开源库的开源作者表示感谢,谢谢作者的无私奉献!
但是在使用这个库时遇到了一些小问题:
一开始使用icon={() => <Image source={...} />}这种方式来自定义地图图片标记,但是不稳定,在debug模式下刷新有时会显示有时不显示,然后打包之后会有较大概率不显示,所以最后改用了原生image的图片引用方式.但是我照着文档和作者的例子,但是地图标记依然显示的是原来的蓝色图标,依然没有变化.所以特地来向作者求助.

截图:

![image](https://user-images.githubusercontent.com/24800090/47126990-c0cb4900-d2bd-11e8-8cd0-ef94442fd079.png)
![image](https://user-images.githubusercontent.com/24800090/47127034-f53f0500-d2bd-11e8-8393-88ecfa84e80d.png)
![image](https://user-images.githubusercontent.com/24800090/47127059-13a50080-d2be-11e8-9bf0-5105632d841a.png)

代码:
                 <MapView
                      style={{
                          width:'100%',
                          height:335*RNDP,
                      }}
                      coordinate={{
                        latitude: this.state.latitude,
                        longitude: this.state.longitude,
                      }}
                      showsZoomControls={false}
                      zoomLevel={10}
                      tiltEnabled={false}
                    >
                        <MapView.Marker
                          image="flag"
                          title="自定义图片"
                          onPress={()=>alert('自定义图片')}
                          coordinate={{
                            latitude:22.611039,
                            longitude:114.121942
                          }}
                        />
                </MapView>

安卓版本:7.1.1;
RN版本:0.55.3;
设备信息:360 N6

**Comment by liguanhan** [comment]
[注意：RN v0.53+ 存在一些 bug（主要影响 iOS 自定义 View），建议使用 RN v0.52。]

我是安卓版本,也会有这个问题吗?
谢谢作者。

**Comment by qiuxiang** [comment]
这没什么好说的，你自己看看和 example 有什么不一样

**Comment by qiuxiang** [comment]
如果你觉得是版本问题，那么你可以把 example 的版本升级到 0.55 来测试

**Comment by liguanhan** [comment]
好的,谢谢作者,我把 example 的版本升级到 0.55来测试了,是没有问题的,但是第一次进去的时候显示的是蓝色的原始图标,第二次进入的时候就会变成正常的自定义图标,

是和这个有关吗:
![image](https://user-images.githubusercontent.com/24800090/47142476-85e50780-d2f5-11e8-9903-930fef7861e7.png)
里面的update方法是要我自己写的是吗,有example给我看看吗,我原生不是很熟.
谢谢作者抽空回答.

**Comment by liguanhan** [comment]
谢谢作者!!!!已经解决问题了.打扰了作者.

**Comment by Marcello168** [comment]
> 谢谢作者!!!!已经解决问题了.打扰了作者.

我也是第二次进去才改，这个是怎么解决的呢

**Comment by Marcello168** [comment]
> 我也是第二次进去才改，是什么情况，该怎么做😂

请问下找到方法了吗？我也遇到了这个问题

**Comment by zhuhengtan** [comment]
> > 我也是第二次进去才改，是什么情况，该怎么做😂
> 
> 请问下找到方法了吗？我也遇到了这个问题

我忘记了。。。好像是在其他issue里面找到的解决办法

**Comment by esdotzed** [comment]
@qiuxiang @liguanhan 我用了原生image=“flag”之后，依然要第二次打开才是原生图片，第一次打开是默认的标记，我的代码和example里面一样的，请问这个问题当时是解决了吗？如果解决了如何解决的？

**Comment by liumengniu** [comment]
0.59.10依然有此问题

**Comment by dzoneo** [comment]
I resolved this issue by using setTimeout to set markers later~
