### ISSUE TITLE
Android 导航某些控件无法正确显示

### ISSUE THREAD

**Issue by qiuxiang** [qiuxiang/react-native-amap3d#43]
用 layout inspector 查看，控件是存在的，只是不知道为什么不显示；在新的 activity 中显示正常。初步判断与 ReactView 有关。

**Comment by yu629** [comment]
导航功能好用了吗?

**Comment by qiuxiang** [comment]
@yu629没时间

**Comment by qiuxiang** [comment]
由于精力有限，导航组件暂时停止开发并在 v1 移除。
