### ISSUE TITLE
大佬们救命啊

### ISSUE THREAD

**Issue by Nocturne-FFG** [qiuxiang/react-native-amap3d#448]
好不容易熬到半夜4点才编译成功，但是安装的时候报：
BUILD SUCCESSFUL in 22s
85 actionable tasks: 2 executed, 83 up-to-date
Running /Users/moonlitnight/Documents/tools/android-sdk-macosx/platform-tools/adb -s G2W0215402006701 reverse tcp:8081 tcp:8081
Starting the app on G2W0215402006701 (/Users/moonlitnight/Documents/tools/android-sdk-macosx/platform-tools/adb -s G2W0215402006701 shell am start -n com.jyserver/com.jyserver.MainActivity)...
Starting: Intent { cmp=com.jyserver/.MainActivity }
Error type 3
Error: Activity class {com.jyserver/com.jyserver.MainActivity} does not exist.

在装这个插件之前我还是可以debg android的，装了之后就 Activity class {com.jyserver/com.jyserver.MainActivity} does not exist.了

网上基本能搜到的办法我都试过了，包括

清除 缓存
什么 因为装了两个相同的app
检查一系列文件的包名
.........

全部没用 ........

求大佬帮助，万分感谢
、、、、、、
react-native: 0.57.5

**Comment by qiuxiang** [comment]
你这个错误和这个库没有任何关系，这是因为 adb 启动的 package name 和你设置的不一致，你肯定是改了什么配置但你自己没有意识到而已，表现为 adb 启动不了但你可以自己点图标启动。

**Comment by Nocturne-FFG** [comment]
@qiuxiang 抱歉上面没有把问题描述清楚，首先大佬我对天发誓绝对没有改动过任何name，另外他确实安装成功了，但是桌面上却没有显示图标，导致我也没法启动，而在设置里面 - 应用管理里面可以看到，并且应用的图标也不再是rn默认的图标，而是绿色安卓机器人的图标。 另外我今天又试了下，无论通过adb install  还是 吧apk发到手机上安装都是这样！

昨天晚上过程是这样的，我这个项目才刚刚开始写，昨天晚上安装 amap3d 这个组件的时候运行安卓一直报一个错，后来我搞到3点多 还是搞不定，于是我就重新init了一个不同名称的项目，打算重新弄， 这次我非常小心，每装完一个插件（其实除了react 和 react native 就四个插件而已 ，项目刚开始嘛 0.0）我都会跑一下 ios 和 安卓确保没有问题我再装下一个，然后在装完react-native-amap-geolocation后并且没有问题后我就接着装 amap3d，除了你文档里面说的要改的地方我其他地方丝毫未动，然后就出现这个问题了.......,！ ios 可以正常跑起来...

**Comment by Nocturne-FFG** [comment]
@qiuxiang 我刚刚有重新init了项目测试，只装了 amap3d，也测试了不同手机（目前测试了华为和小米）还是同样的问题！大佬可以试下

**Comment by qiuxiang** [comment]
既然你上面的信息已经 build success，那应该有 apk 生成吧？

**Comment by Nocturne-FFG** [comment]
@qiuxiang 有的
