### ISSUE TITLE
定位问题

### ISSUE THREAD

**Issue by YueYeWeiAi** [qiuxiang/react-native-amap3d#460]
"react": "16.6.3",
"react-native": "0.57.8",
"react-native-amap3d": "^1.0.2",
打开地图正常显示，但是配置定位图标和指南针图标都无法出现是什么问题。

**Comment by YueYeWeiAi** [comment]
问题解决，安卓6.0版本以上定位权限属于危险权限，写在默认的安卓配置文件中并不起效果，需要弹窗确认。也和android sdk有关，react-native版本使用的android sdk不一样

**Comment by cuitwangshicheng** [comment]
> 问题解决，安卓6.0版本以上定位权限属于危险权限，写在默认的安卓配置文件中并不起效果，需要弹窗确认。也和android sdk有关，react-native版本使用的android sdk不一样

具体怎么弹窗提示呢？
