### ISSUE TITLE
ios 无法运行报错

### ISSUE THREAD

**Issue by VictorYuan666** [qiuxiang/react-native-amap3d#47]
"react-native": "0.47.2",
"react-native-amap3d": "^0.3.2"
运行报错
No visible @interface for 'MAMultiPolyline' declares the selector 'setDrawStyleIndexes:'

**Comment by qiuxiang** [comment]
我测试过了没问题，你自己配置的问题吧

**Comment by Hermaner** [comment]
请问你怎么解决的呢，我也是同样的问题

**Comment by ismjt** [comment]
我也遇到了类似的问题：
No visible @interface for 'RCTView' declares the selector 'didUpdateReactSubviews'

这里报的错误：
https://github.com/qiuxiang/react-native-amap3d/blob/768c806d1cb3fed22a6a058fa0a738da6b5868e6/ios/maps/AMapInfoWindow.m#L8

开发环境：
"react-native": "^0.49.5",
"react-native-amap3d": "^0.7.3",
xcode: 9.1 (9B55)

**Comment by qiuxiang** [comment]
怎么看都是配置的问题，我准备在持续集成里写个编译测试，如果测试环境里能编译通过那么就要自己去找原因了，因为编译相关的，除非我遇到过，或者信息足够，不然也没办法。
