### ISSUE TITLE
IOS 点击Marker的onPress方法，会触发MapView的onPress方法

### ISSUE THREAD

**Issue by jianxinzhoutiti** [qiuxiang/react-native-amap3d#476]

**Comment by iqysf** [comment]
+1

**Comment by Wodezhishi321** [comment]
我也是这样有什么办法解决么

**Comment by jianxinzhoutiti** [comment]
仅仅就是命名问题，改个名字就行了，重写原生里的方法名，把原生的marker，mapView里的触发方法名字修改，在RN里的调用方法改成你修改的名字，就可以了。

**Comment by Wodezhishi321** [comment]
我不是很懂原生，能具体一点么比如截图什么的？

**Comment by whit15** [comment]
> 仅仅就是命名问题，改个名字就行了，重写原生里的方法名，把原生的marker，mapView里的触发方法名字修改，在RN里的调用方法改成你修改的名字，就可以了。
@jianxinzhoutiti 大佬，能不能详细说一下怎么改啊，因为这个问题已经停留在0.52很久了，非常感谢

**Comment by jianxinzhoutiti** [comment]
@whit15 
![image](https://user-images.githubusercontent.com/22340846/67848471-b766f480-fb3f-11e9-80f7-df4a10527d57.png)
我是把组件拖到项目里的,
![image](https://user-images.githubusercontent.com/22340846/67848550-debdc180-fb3f-11e9-8512-625c4a21d823.png)
![image](https://user-images.githubusercontent.com/22340846/67848730-2f351f00-fb40-11e9-8bca-76b93c24365d.png)

主要问题是文件的的onPress方法一样,调用冲突,你把其中一个的方法名改一下
例:
![image](https://user-images.githubusercontent.com/22340846/67848796-51c73800-fb40-11e9-8f0a-da637c2cea99.png)
还有把相关的调用文件里的方法名也改了,RN项目里的JS文件也要修改
我是iOS的,但是android的修改流程是一样的

**Comment by whit15** [comment]
> @whit15
> ![image](https://user-images.githubusercontent.com/22340846/67848471-b766f480-fb3f-11e9-80f7-df4a10527d57.png)
> 我是把组件拖到项目里的,
> ![image](https://user-images.githubusercontent.com/22340846/67848550-debdc180-fb3f-11e9-8512-625c4a21d823.png)
> ![image](https://user-images.githubusercontent.com/22340846/67848730-2f351f00-fb40-11e9-8bca-76b93c24365d.png)
> 
> 主要问题是文件的的onPress方法一样,调用冲突,你把其中一个的方法名改一下
> 例:
> ![image](https://user-images.githubusercontent.com/22340846/67848796-51c73800-fb40-11e9-8f0a-da637c2cea99.png)
> 还有把相关的调用文件里的方法名也改了,RN项目里的JS文件也要修改
> 我是iOS的,但是android的修改流程是一样的

老哥，我改完后试过才发现你这个问题跟我遇到的问题不是同一个，目前你这个问题在1.1.1版本下不用修改就已经没问题了，MapView和Marker都为onPress可以正常触发。
我遇到的是自定义infowindow里的TouchableOpacity标签的onPress不触发，老哥有办法解决不啊？

**Comment by jianxinzhoutiti** [comment]
我不知道代码,你看看是否是页面view层级,还有手势冲突拦截,如果你在地图上放View遮挡自定义infowindow可能会有问题,你可以断点查看是哪块代码有问题,思路就这些.

**Comment by whit15** [comment]
@jianxinzhoutiti 不是业务代码的问题，只存在在iOS上，rn用0.52以后的版本就会出现这个问题，作者以前的readme里面有说这个问题建议大家都停留在0.52，后来readme里这一段被删掉了但是问题没有解决，issue里面很多人提了这个问题，一直没有大神来解决。现在0.60以后的版本变动太大了，后续的其他库更新后可能不会兼容0.52了，最近我在研究点击海量点后用rn自带的View组件模拟infowindow覆盖到地图上来规避这个问题，但是点击位置的坐标锁定不到海量点的中心，看着有点怪怪的
