### ISSUE TITLE
导航功能问题

### ISSUE THREAD

**Issue by X-Liang** [qiuxiang/react-native-amap3d#48]
导航功能在 iOS ，Android 两端还有那些东西需要完善？？

**Comment by qiuxiang** [comment]
现在只是做了最基本的两点导航，很多定制性的接口都没有。

最近不打算在导航上花时间，因为还不需要。

**Comment by dongchuanlei** [comment]
希望作者能加上“点平滑移动”功能, 这又是一个功能亮点🙂。

**Comment by qiuxiang** [comment]
@dongchuanlei 以后再考虑
