### ISSUE TITLE
SUPPORT RN 0.59 

### ISSUE THREAD

**Issue by MrPluto** [qiuxiang/react-native-amap3d#491]
![image](https://user-images.githubusercontent.com/13927313/54339657-6ff32d00-4670-11e9-8c56-c3cc23987a80.png)

0.59 Adds nullable annotations, i think it's why i can't compile successfully.

[see the fourth changelog ](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#android-specific-1)

**Comment by Wqleonard** [comment]
0.59   I have the save question , how to solve?
