### ISSUE TITLE
定位点会自己乱动，这是什么情况？wifi，4G都会

### ISSUE THREAD

**Issue by fanyongbing** [qiuxiang/react-native-amap3d#5]
定位点会自己乱动，这是什么情况？wifi，4G都会，手机放着不动，定位点会变来变去，定位事件经纬度得不到，能否提供单独的定位方法？

px：图片上传不了

**Comment by qiuxiang** [comment]
这是 SDK 的问题，之前用高德地图的时候就发现了，因为基于 wifi 和 基站的定位是不准的，误差大概在 50 米左右，nativeEvent 里有返回定位精度。

我之前做过轨迹记录，即便用单独的定位 SDK 也是一样的。

如果需要更精准的定位，只能是 GPS，也就是在开阔的室外才行，精度大概在3米左右，基本就不会出现定位漂移的问题。

得不到定位数据，你是怎么调用的呢？

PS. 图片上传不了可能是网络太慢，我都是用代理来访问的。

**Comment by qiuxiang** [comment]
没有定位数据的问题……我也不知道当时怎么想的，参数都构造好了，但忘了传过去。

稍后我会修复。

**Comment by fanyongbing** [comment]
@qiuxiang  好的  还有能否给定位加一个精度参数？这样就可以舍弃一定的精度换区定位的稳定。 还有能否提供单独定位的api？

**Comment by qiuxiang** [comment]
不太确定你说的单独定位 API 指的是什么，如果指的是单独的 NativeModule，这个项目目前不会考虑，因为已经有别的库在做这件事了 https://github.com/xiaobuu/react-native-amap-location

**Comment by fanyongbing** [comment]
这个已经弃坑了……

**Comment by fanyongbing** [comment]
而且用一个组件实现岂不是更好？

**Comment by qiuxiang** [comment]
你希望的调用方式是什么样的？发一段 demo 看看

**Comment by fanyongbing** [comment]
import { MapView, Polygon,AMapLocation } from 'react-native-amap3d'
// 开始获取位置
startLocation(options)
// 停止获取位置
stopLocation()
类似与这样，也就是期望能够在不显示地图的情况下，调用一个单独的方法就可以获取当前的定位信息，麻烦大神看能否把此功能加进去，如果再使用另外的组件，第一增加维护量，第二sdk的内容肯定会有重复，增大了app的size

**Comment by qiuxiang** [comment]
那其实就是要做和 react-native-amap-location 一样的事，地图模块和定位模块是分开的，并不会重复，这个项目不引入定位 SDK 的话，是做不了独立的定位接口的。

这个项目的重点毕竟是 MapView，而不是 Location，如果因为 react-native-amap-location 太坑，我会倾向于做改进，或者重新做一个类似的项目，而不是把 Location 模块加入到现有的项目。

**Comment by qiuxiang** [comment]
又想了下，确实可以考虑引入定位模块，让 MapView 使用 Location SDK 的定位会更好一些，然后再考虑做独立的定位接口。

不过，当前的重点还是 MapView  的开发。

**Comment by fanyongbing** [comment]
感谢 @qiuxiang

**Comment by qiuxiang** [comment]
多颜色渐变 Polyline 的实现是有问题的，我也知道用 `MAMultiColoredPolylineRenderer` 但可能是 styleIndexes 没处理好，导致虽然画出了颜色渐变，但颜色是不对的。

**Comment by hhahh2011** [comment]
做了 很多年GPS 相关的开发，这个属于定点漂移问题。及时使用GPS也会因为信号问题 产生漂移。除非信号很好。手机自带的GPS 更加会漂移了，因为通常手机 都是放在室内，信号不好。这里的信号不是GSM信号，而是GPS接收卫星的信号

**Comment by qiuxiang** [comment]
“即使用 GPS 定位也会漂移”我是认同的，但就我的经验来看，GPS 定位是要比网络定位稳定得多，不管是漂移的概率还是漂移的程度。

手机在室内与其说 GPS 信号不好，不如说 GPS 根本不可用，高德定位 SDK 是明确说明不支持在室内使用 GPS 定位的，室内定位依靠的是网络定位。

**Comment by fanyongbing** [comment]
我更新了新版本，点击定位的时候，定位到的位置到了欧洲，定位事件打印出来的经纬度是0,0
locationEnabled={true}
onLocation={({ nativeEvent }) =>
console.warn(`${nativeEvent.latitude}, ${nativeEvent.longitude}`)}


还有怎么在打开地图的时候就定位到当前位置？

**Comment by fanyongbing** [comment]
现在定位的问题好了，是因为高德的key被同事删除了……
  但是打开地图不能自动定位到当前点的位置，必须点击定位按钮，这个怎么回事？

**Comment by qiuxiang** [comment]
“自动定位到当前位置”是指定位成功后地图移动到当前定位的位置？

**Comment by fanyongbing** [comment]
@qiuxiang 进入到地图界面的时候就直接定位当前位置

**Comment by qiuxiang** [comment]
利用现有 API 是可以做到的，你可以通过监听 onLocation 事件，然后将定位到的坐标设置到 coordinate 属性上，或用 animateTo 方法移动到当前定位点。

**Comment by qiuxiang** [comment]
单独的定位模块暂时是不做了
