### ISSUE TITLE
请教是否有办法通过region来设置显示区域？

### ISSUE THREAD

**Issue by idlesong** [qiuxiang/react-native-amap3d#50]
react-native-amap3d中似乎是通过 中心坐标点 和 zoomLevel来设置显示区域的。请问能否通过region来设置显示区域，就像设置limitRegion一样？
不能的话，请问如何将region转换到 中心坐标点 + zoomLevel？

**Comment by qiuxiang** [comment]
region 的接口我稍后再加吧

**Comment by idlesong** [comment]
多谢
