### ISSUE TITLE
react-native  0.59.4 link 后报错

### ISSUE THREAD

**Issue by lijiaxi** [qiuxiang/react-native-amap3d#502]
react-native  0.59.4
  
![image](https://user-images.githubusercontent.com/20659256/56187861-7fdaa400-6056-11e9-9ee5-45c30355408b.png)

请问有懂kotlin报错的吗

**Comment by qiuxiang** [comment]
还没发布到 npm，你可以用 master 版本

**Comment by lijiaxi** [comment]
master版本可以用，谢谢！~！

**Comment by CrazyMan2** [comment]
> master版本可以用，谢谢！〜！

请问怎样引用master版
