### ISSUE TITLE
RN 0.59 react-native-amap3d 1.0.0 如何让marker旋转？

### ISSUE THREAD

**Issue by EastWooden** [qiuxiang/react-native-amap3d#504]
在marker 的icon上 transform 无效啊

**Comment by mrcwl** [comment]
@EastWooden  请问解决了吗？

**Comment by EastWooden** [comment]
解决了

**Comment by mrcwl** [comment]
@EastWooden 请问怎么解决的

**Comment by EastWooden** [comment]
> @EastWooden 请问解决了吗？

解决了

**Comment by mrcwl** [comment]
> > @EastWooden 请问解决了吗？
> 
> 解决了

请问怎么解决的

**Comment by EastWooden** [comment]
> @EastWooden 请问怎么解决的
可以在外面在包裹一层View，用这个View去做transform

**Comment by mrcwl** [comment]
> > @EastWooden 请问怎么解决的
> > 可以在外面在包裹一层View，用这个View去做transform

这个View 可以用Animate.View吗？

**Comment by EastWooden** [comment]
> > > @EastWooden 请问怎么解决的
> > > 可以在外面在包裹一层View，用这个View去做transform
> 
> 这个View 可以用Animate.View吗？

可以的

**Comment by mrcwl** [comment]
> > > > @EastWooden 请问怎么解决的
> > > > 可以在外面在包裹一层View，用这个View去做transform
> > 
> > 
> > 这个View 可以用Animate.View吗？
> 
> 可以的

包一个View在外面Marker就不显示了

`
<MapView
        ref={ref => (mapViewRef.current = ref)}
        style={{
          width: '100%',
          height: Dimensions.get('window').height - 400,
        }}
        coordinate={{
          latitude: location.location?.latitude ?? 0,
          longitude: location.location?.longitude ?? 0,
        }}
        zoomLevel={14}
        showsCompass={false}
        onStatusChange={mapStatus => {
          setMapRotation(mapStatus.nativeEvent.rotation);
        }}
      >
        <View
          style={{
            transform: [
              {
                rotate: '90deg',
              },
            ],
          }}
        >
          <MapView.Marker
            icon={() => renderCar}
            coordinate={location.location ?? { latitude: 0, longitude: 0 }}
          />
        </View>
      </MapView>
`

**Comment by EastWooden** [comment]
> > > > > @EastWooden 请问怎么解决的
> > > > > 可以在外面在包裹一层View，用这个View去做transform
> > > 
> > > 
> > > 这个View 可以用Animate.View吗？
> > 
> > 
> > 可以的
> 
> 包一个View在外面Marker就不显示了
> 
> `<MapView ref={ref => (mapViewRef.current = ref)} style={{ width: '100%', height: Dimensions.get('window').height - 400, }} coordinate={{ latitude: location.location?.latitude ?? 0, longitude: location.location?.longitude ?? 0, }} zoomLevel={14} showsCompass={false} onStatusChange={mapStatus => { setMapRotation(mapStatus.nativeEvent.rotation); }} > <View style={{ transform: [ { rotate: '90deg', }, ], }} > <MapView.Marker icon={() => renderCar} coordinate={location.location ?? { latitude: 0, longitude: 0 }} /> </View> </MapView>`

可以这样
<MapView.Marker
              icon={this.renderCarmakerIcon}
              zIndex={5}
              opacity={this.state.showCarInMap ? 1 : 0}
              anchor={{ x: 0.5, y: 0.5 }}
              infoWindowDisabled={true}
              coordinate={{
                latitude: this.state.showCarInMap ? carPosition.lat : 39.909178,
                longitude: this.state.showCarInMap ? carPosition.lng : 116.397454,
              }}
            ></MapView.Marker>

this.renderCarmakerIcon  这个方法向下面这样写 return (
      <Animated.View style={[styles.carMarkContainer, Platform.OS === 'android' ? {
        transform: [{
          rotate: maprotation.interpolate({
            inputRange: [0, 360],
            outputRange: ['0deg', '360deg']
          })
        }]
      } : {
          opacity: showCarInMap ? 1 : 0
        }]}><Animated.Image resizeMode="contain" source={{ uri: 'car' }} style={[styles.carImage, {
          transform: [{
            rotate: maprotation.interpolate({
              inputRange: [0, 360],
              outputRange: ['0deg', '360deg']
            })
          }]
        }]} /></Animated.View>
    )

**Comment by mrcwl** [comment]
> > > > > > @EastWooden 请问怎么解决的
> > > > > > 可以在外面在包裹一层View，用这个View去做transform
> > > > 
> > > > 
> > > > 这个View 可以用Animate.View吗？
> > > 
> > > 
> > > 可以的
> > 
> > 
> > 包一个View在外面Marker就不显示了
> > `<MapView ref={ref => (mapViewRef.current = ref)} style={{ width: '100%', height: Dimensions.get('window').height - 400, }} coordinate={{ latitude: location.location?.latitude ?? 0, longitude: location.location?.longitude ?? 0, }} zoomLevel={14} showsCompass={false} onStatusChange={mapStatus => { setMapRotation(mapStatus.nativeEvent.rotation); }} > <View style={{ transform: [ { rotate: '90deg', }, ], }} > <MapView.Marker icon={() => renderCar} coordinate={location.location ?? { latitude: 0, longitude: 0 }} /> </View> </MapView>`
> 
> 可以这样
> <MapView.Marker
> icon={this.renderCarmakerIcon}
> zIndex={5}
> opacity={this.state.showCarInMap ? 1 : 0}
> anchor={{ x: 0.5, y: 0.5 }}
> infoWindowDisabled={true}
> coordinate={{
> latitude: this.state.showCarInMap ? carPosition.lat : 39.909178,
> longitude: this.state.showCarInMap ? carPosition.lng : 116.397454,
> }}
> ></MapView.Marker>
> 
> this.renderCarmakerIcon 这个方法向下面这样写 return (
> <Animated.View style={[styles.carMarkContainer, Platform.OS === 'android' ? {
> transform: [{
> rotate: maprotation.interpolate({
> inputRange: [0, 360],
> outputRange: ['0deg', '360deg']
> })
> }]
> } : {
> opacity: showCarInMap ? 1 : 0
> }]}><Animated.Image resizeMode="contain" source={{ uri: 'car' }} style={[styles.carImage, {
> transform: [{
> rotate: maprotation.interpolate({
> inputRange: [0, 360],
> outputRange: ['0deg', '360deg']
> })
> }]
> }]} /></Animated.View>
> )

好的 感谢
