### ISSUE TITLE
是否可以在地图上继续覆盖图层

### ISSUE THREAD

**Issue by aoarashi1988** [qiuxiang/react-native-amap3d#511]
使用海量点功能，希望能达成和高德搜索类似，有一个结果列表是浮在地图上方的，每个海量点对应列表其中一个结果。
现在遇到的问题是我写了一个覆盖的View,但是完全看不见不显示，应该是被MapView遮挡了，调整zIndex也没用
`
<View style={UI.container}>

        <MapView 
          locationEnabled
          showsBuildings
          showsScale
          showsLocationButton
          zoomEnabled
          scrollEnabled
          coordinate={this.state.coordinate}
          onLocation={this.onLocation}
          style={StyleSheet.absoluteFill}
          minZoomLevel={8}
          zoomLevel={12}
          onStatusChangeComplete={this.onMapStatusChangeComplete}
          onStatusChange={this.onMapStatusChange}
        >
          <MapView.MultiPoint 
            points={this.state.points} 
            image="point" 
          />
        </MapView>
        <SearchMapResultList points={this.state.points} onPress={this.onListItemPress} />
      </View>
`
SearchMapResultList就是这个希望显示在地图上面的图层

**Comment by qiuxiang** [comment]
这是 reacnative view 布局的问题，不是 mapview 的问题，如果这样有问题，那你把 mapview 换成 view 也一样有问题

**Comment by qiuxiang** [comment]
这里注意 mapview 是 StyleSheet.absoluteFill

**Comment by aoarashi1988** [comment]
了解
