### ISSUE TITLE
Android 下Debug正常，Release版，进入地图页会闪退，logcat

### ISSUE THREAD

**Issue by chaoa888** [qiuxiang/react-native-amap3d#517]
"react": "16.6.3",
 "react-native": "^0.57.8",

Android 下Debug地图正常，Release版，进入地图页会闪退，logcat：日志显示如下：请大神看下什么情况呢？

![avatar](http://img.b2b321.366ec.net/UserFiles/Supplier839/Images/Product/20190528/f6452115bc614d5896868f6f30f7cbf6.png)

**Comment by zim-lee** [comment]
@chaoa888 解决了？遇到一样的问题

**Comment by vmto** [comment]
"react": "16.9.0",
"react-native": "^0.61.5",
"react-native-amap3d": "^1.1.1"

Debug ok，Release 闪退~
