### ISSUE TITLE
出现高德标志和放大缩小但是地图黑屏

### ISSUE THREAD

**Issue by fallomo** [qiuxiang/react-native-amap3d#532]
RN版本 0.59.9
高德版本 1.1.1
as模拟机 android 9.0 pixel 2 api28

按照readme配置好了，只用了一个最简单的例子
![图片](https://user-images.githubusercontent.com/37293554/61171639-fed76e00-a5ac-11e9-8ece-544cf6e89faa.png)
高德的标志出来了，放大缩小也有，但是地图是黑屏的
![图片](https://user-images.githubusercontent.com/37293554/61171654-1c0c3c80-a5ad-11e9-9d61-975d1c08c4dc.png)
请问是哪里出了问题？官网上android sdk的jar包和so库需要安装吗？

**Comment by DhlOne** [comment]
试试，把AndroidManifest.xml文件里面的android:hardwareAccelerated="false"删掉或者设置为true

**Comment by lanjinli** [comment]
@fallomo 你解决了吗，我也出现这种情况

**Comment by fallomo** [comment]
@lanjinli 似乎是模拟器不支持硬件加速/opengl3的原因。换了一圈模拟器，bluestacks可以正常显示（然而它的页面我受不太了），现在还是真机调试了

**Comment by lanjinli** [comment]
可是我发布正式包在真机上也是黑的，我也改了AndroidManifest
`<application
      android:hardwareAccelerated="true"
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/zhyf_icon"
      android:allowBackup="false"
      tools:node="replace"
      android:theme="@style/AppTheme">`

**Comment by lanjinli** [comment]
@fallomo 可是我发布正式包在真机上也是黑的，我也改了AndroidManifest
<application android:hardwareAccelerated="true" android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/zhyf_icon" android:allowBackup="false" tools:node="replace" android:theme="@style/AppTheme">

**Comment by no3forfuk** [comment]
我也遇到黑屏了  然后我使用夜神模拟器也是可以 竖屏模式样式什么的也还不错

**Comment by dongchacha** [comment]
这个作者是完全放弃这个库了吗？真是坑死了
