### ISSUE TITLE
请问下如何根据marker的位置实现 地图居中

### ISSUE THREAD

**Issue by 15669028801** [qiuxiang/react-native-amap3d#533]
https://lbs.amap.com/api/javascript-api/example/marker/adaptive-show-multiple-markers

例如百度地图APK 中的setFitView 方法

**Comment by lenglengiOS** [comment]
@15669028801 你好，请问你是怎么解决的？

**Comment by edwards19900128** [comment]
> https://lbs.amap.com/api/javascript-api/example/marker/adaptive-show-multiple-markers
> 
> 例如百度地图APK 中的setFitView 方法

同问,请问下怎么解决这个问题的...
