### ISSUE TITLE
增加支持通过mapLanguage属性改变中英文

### ISSUE THREAD

**Issue by Marcello168** [qiuxiang/react-native-amap3d#543]
增加支持通过mapLanguage属性改变中英文  没有更新对应的npm 版本呢

**Comment by 546669204** [comment]
"react-native-amap3d": "git+https://github.com/qiuxiang/react-native-amap3d.git",

可以使用 git库的形式引入

**Comment by Marcello168** [comment]
@546669204 谢谢
