### ISSUE TITLE
关于自定义marker自定义图标第一次加载不显示问题

### ISSUE THREAD

**Issue by zhangyoof** [qiuxiang/react-native-amap3d#556]
在第一次加载的时候没有将自定义图标显示出来，返回一次，在进入页面则图标正常显示，且在不杀死程序前提下，以后再进去页面均可正常显示自定义图标，还望作者解答一下，不胜感激

RN版本0.6，设备是华为荣耀20，加载自定义图标代码如下，循环一个坐标数组，生成多个图标
{
    cameraData.map((item,index)=>{
            return <Marker
                             key={index}
                             onPress={()=>{cameraClick(item)}}
                             infoWindowDisabled={true}
                              icon={()=> {
                                     return <Image 
                                                  source={require("../../assets/video.png")} 
                                                  style={{width:25,height:25,zIndex:100}} 
                                               >
                                              </Image>
                                }}
                                coordinate={item.data}
                        />
      })
  }

**Comment by zhanglong11** [comment]
定义一个变量，让组件加载两次
    useEffect(() => {
        setTimeout(()=>{setIsShow(true)},300);
    }, [refresh,isShow]);

**Comment by RoarRain** [comment]
楼主 怎么解决的
