### ISSUE TITLE
Component 'AIRMapMarker' re-registered bubbling event 'topDragStart' as a direct event

### ISSUE THREAD

**Issue by gaollard** [qiuxiang/react-native-amap3d#571]
## 提供你正在使用的版本、RN 版本、设备信息
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-amap3d": "^1.1.1",
  设备信息：IOS 11

## 错误信息
Component 'AIRMapMarker' re-registered bubbling event 'topDragStart' as a direct event

![image](https://user-images.githubusercontent.com/34447750/70585389-11f37600-1bff-11ea-8663-305b352c66ac.png)

**Comment by wei63w** [comment]
为什么关了呢 , 我也遇到了这个问题

**Comment by wei63w** [comment]
弄好了 是事件冲突了 其他地图的初始化时间跟amap的冲突 保留一个就好了

**Comment by GuhuoRen** [comment]
> 弄好了 是事件冲突了 其他地图的初始化时间跟amap的冲突 保留一个就好了

请问具体是什么原因呢，我也碰到了一样的报错。同时用了amap3d和rn maps

**Comment by GuhuoRen** [comment]
> > 弄好了 是事件冲突了 其他地图的初始化时间跟amap的冲突 保留一个就好了
> 
> 请问具体是什么原因呢，我也碰到了一样的报错。同时用了amap3d和rn maps

是事件和RN maps里冲突了，我改的是amap，修改RN Maps应该也可以，保持两边一致应该就OK了。不过我看RN Maps是故意改成RCTDirectEventBlock，可能有什么原因，我没研究，所以最好改amap：
RCT_EXPORT_VIEW_PROPERTY(onDragStart, RCTDirectEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onDrag, RCTDirectEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onDragEnd, RCTDirectEventBlock)

**Comment by tigerzhang** [comment]
> > > 弄好了 是事件冲突了 其他地图的初始化时间跟amap的冲突 保留一个就好了
> > 
> > 
> > 请问具体是什么原因呢，我也碰到了一样的报错。同时用了amap3d和rn maps
> 
> 是事件和RN maps里冲突了，我改的是amap，修改RN Maps应该也可以，保持两边一致应该就OK了。不过我看RN Maps是故意改成RCTDirectEventBlock，可能有什么原因，我没研究，所以最好改amap： RCT_EXPORT_VIEW_PROPERTY(onDragStart, RCTDirectEventBlock) RCT_EXPORT_VIEW_PROPERTY(onDrag, RCTDirectEventBlock) RCT_EXPORT_VIEW_PROPERTY(onDragEnd, RCTDirectEventBlock)

具体怎么改？
