### ISSUE TITLE
标记的时候图片显示不出来，这个问题很严重啊

### ISSUE THREAD

**Issue by martineden2017** [qiuxiang/react-native-amap3d#58]

**Comment by martineden2017** [comment]
Marker的icon,   如<Marker
                icon={()=>this.renderKnightMarker(item)}
                onPress={()=>this.handleKnightPress(item)}
                clickable
                infoWindowEnabled={false}
                coordinate={{
                      latitude: item.lat,
                      longitude: item.lng,
                }}
                />

**Comment by qiuxiang** [comment]
`renderKnightMarker` 这里面又是什么

**Comment by qiuxiang** [comment]
你的设备是 android 吧？
 
之前版本的 example 应该和你的写法差不多 https://github.com/qiuxiang/react-native-amap3d/blob/v0.5.0/example/src/examples/marker.js#L70 。

因为 android 自定义 View 的实现本身就是个 hack，包含的异步渲染组件（比如 Image）无法同步更新。于是后来加了 [`image`](https://github.com/qiuxiang/react-native-amap3d/blob/v0.6.1/components/maps/Marker.js#L58) 接口，直接使用图片资源，如果你只自定义图片，就应该用这个接口。参考后来更新的 example：https://github.com/qiuxiang/react-native-amap3d/blob/v0.6.1/example/src/examples/marker.js#L69 。

**Comment by martineden2017** [comment]
但我的每一个marker里面包含两张图片和文字，image接口只能包一张图片吧

**Comment by qiuxiang** [comment]
对，所以你要自己想办法，在图片渲染之后，触发一次更新。我是没什么办法了，要是能解决我就解决了。

根本问题在于，高德地图 SDK 的 Marker 只能用图片作为自定义 Marker，你可以看[官方文档](http://lbs.amap.com/api/android-sdk/guide/draw-on-map/draw-marker)。为了实现自定义 View，我用了一些 hack。比如，[把 View 转成 Bitmap](https://github.com/qiuxiang/react-native-amap3d/blob/v0.6.1/android/src/main/java/cn/qiuxiang/react/amap3d/maps/AMapMarker.kt#L134)，为了实现一般的同步更新，我[在 js 端用 componentDidUpdate 向原生组件发送更新命令](https://github.com/qiuxiang/react-native-amap3d/blob/v0.6.1/android/src/main/java/cn/qiuxiang/react/amap3d/maps/AMapMarker.kt)，但是如果自定义 View 里包含异步更新，就没办法了，因为不知道子组件里的内容什么时候会更新。

**Comment by martineden2017** [comment]
按道理来说把自定义view转化成bitmap应该是文字和图片一起显示或一起不显示，但我这里有的时候只显示了文字，图片不显示（标记包括两张图片和文字）

**Comment by qiuxiang** [comment]
你的理解不对，Image 和 Text 是不一样的，Text 可以直接 render，但 Image 要等图片加载。在不改变 state 的情况下，icon 只会 update 一次，在第一次 update 的时候，文字已经 render 了，但图片还在等待加载，所以不会 render。

**Comment by martineden2017** [comment]
隔了好多秒后去发送update命令，还是刷不出图片来

**Comment by qiuxiang** [comment]
你怎么发送 update 命令？

**Comment by martineden2017** [comment]
在Marker.js的componentDidMount方法里，  componentDidMount(){
    if (this._icon && Platform.OS === 'android') {
      setTimeout(() => this._sendCommand('update'), 5000)
    }
  }

**Comment by qiuxiang** [comment]
不建议你改 Marker.js 里的代码，不过如果你非要这么做。。必须触发两次更新：
```jsx
  componentDidMount() {
    setTimeout(() => this.componentDidUpdate(), 2000)
    setTimeout(() => this.componentDidUpdate(), 3000)
  }
```

**Comment by qiuxiang** [comment]
不过依赖定时器终究是个糟糕的实践，最靠谱的做法是，在 `Image` `onLoadEnd` 的时候去触发更新：
```jsx
_onLoad = () => {
  this.marker.componentDidUpdate()
  setTimeout(() => this.marker.componentDidUpdate(), 200)
}

<Marker
  title='自定义标记'
  ref={ref => this.marker = ref}
  icon={() =>
    <View style={styles.customIcon}>
      <Image
        style={styles.customIcon}
        source={{uri: 'https://avatars0.githubusercontent.com/u/1709072?v=4&s=88'}}
        onLoadEnd={this._onLoad}
      />
    </View>
  }
  coordinate={this._coordinates[3]}
/>
```
为什么要触发两次更新？你把第二个定时器 `200` 改为 `100` 就知道了。

**Comment by qiuxiang** [comment]
优化了 marker 的结构，但仍然要在 Image onLoadEnd 之后延迟 200ms 发送刷新命令，这是图片渐显动画需要的时间。

**Comment by ray-zyh** [comment]
如果是多个 MapView.Marker 要如何触发呢

**Comment by ray-zyh** [comment]
显示多张图片  
_coordinates = [
  {
    latitude: 39.987280001,
    longitude: 116.3976890001,
    url: 'https://avatars0.githubusercontent.com/u/1709072?v=4&s=88',
  },
  {
    latitude: 39.997280001,
    longitude: 116.3976890001,
    url: 'https://csdnimg.cn/pubfooter/images/csdn_cs_qr.png',
  },
];
 <View>
        {
     this._coordinates.map((item, index) =><MapView.Marker
         ref ={ (ref) => this.marker[index]=ref}
         key={index}
         title={String(item.latitude)}     
         icon={() => <View>
           <Image
                style={styles.customIcon}
                source={  require('../../images/example/banner.jpg')}
              />
            </View>
              }
          coordinate={item}
        />)}
        </View>

  ref ={ (ref) => this.marker[index]=ref} 这样取ref 不对吗?
执行  this.marker[index].map.componentDidUpdate();会报下面的错误
Cannot read property 'componentDidUpdate' of undefined

**Comment by angleneo** [comment]
> 

你试试直接在componentdidmount里执行定时器执行this.forceUpdate
