### ISSUE TITLE
ios右上角的定位图标，点击无效

### ISSUE THREAD

**Issue by BooYeu** [qiuxiang/react-native-amap3d#581]
点击图标后只是恢复了zoomlevel，位置没有到定位点？

**Comment by qiuxiang** [comment]
iOS 地图哪有定位图标

**Comment by BooYeu** [comment]
新sdk里好像自动添加了
![C3B5311A-F9D6-4380-BC28-4DBDC9593E21](https://user-images.githubusercontent.com/16587763/75846866-857cdc00-5e18-11ea-9e5f-71ddf90ad4cd.jpeg)

**Comment by BooYeu** [comment]
![Simulator Screen Shot - iPhone 7 - 2020-03-05 at 19 23 36](https://user-images.githubusercontent.com/16587763/75977231-e7237000-5f16-11ea-996b-baa60df3c06b.png)
偶尔会报这个错

**Comment by BooYeu** [comment]
。。。太早前写的了，是我自己家的，，，，不好意思 太马虎了
