### ISSUE TITLE
RN ^0.62.2  真机测试  requirenativecomponent:"AMapMarker" was not found in the UIManager

### ISSUE THREAD

**Issue by Konmers** [qiuxiang/react-native-amap3d#595]
安装 react-native-amap3d  -v ^1.1.1
运行 react-native run-android

报错
Invarlant Volation:
 requireNathveComponent: "AMapMarker" was not found In the UIManager.

This error Is located at
In AMapMarker (at Marker.Js:176)
in Marker (at MapDemo.js:202)
In AMapVlew (at MapVlew.Js:273)
in MapVlew (at MapDemo.Js:176)
in RCTVlew (at MapDemo.Js:175)
in MapDemo (at navigationStore.js:441)
in Wrapped (at SceneVlew.js:9)
in SceneVlew (at StackVlewLayout.tsx:88i9)
 in RCTView (at StackViewL.ayout,tsx:888)
 in RCTView (at StackViewLayout.tsx:887)
In RCTVlew latcreateAnimatedComponent. Is:144)in AnimgtedComponent (otCreateAnimatedComponent.Js:194in ForwardRef(AnimatedComponentWrapper) (at StackVlewCard.tsx:106)in RCTVew (at createAnimatedComponent.js:144In AnimotedComponent (atcreateAnimatedComponent.Is:194)in ForwordRef(AnimatedComponentwrapper) (at screens.native.Js:71In Screen (at StackVewCard.tsx:93)in Card (at createPointerEventsContainer.tsx95)

**Comment by zjafei** [comment]
我也又这样的问题

**Comment by Konmers** [comment]
是不是依赖没加起，在哪加这个依赖？？？

**Comment by wf1999** [comment]
请问这个问题有解决吗？

**Comment by wf1999** [comment]
npm i react-native-amap3d
react-native link react-native-amap3d
执行了这两步，还是没法使用，请问这个问题有解决吗？

**Comment by Konmers** [comment]
em。。。 我尝试手动添加 react-native-amap3d&nbsp; 链接，但是还是执行不了，我猜测是react-native v0.62.2 版本不兼容问题 ，现在在尝试降版本测试，之前使用react-native v 0.61.3是完全可执行的，解决了会在github留言的
&nbsp;


Konmer
konmer@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "王飞"<notifications@github.com&gt;; 
发送时间: 2020年4月21日(星期二) 中午1:52
收件人: "qiuxiang/react-native-amap3d"<react-native-amap3d@noreply.github.com&gt;; 
抄送: "1916794877"<1916794877@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [qiuxiang/react-native-amap3d] RN ^0.62.2  真机测试  requirenativecomponent:&quot;AMapMarker&quot; was not found in the UIManager (#595)





 
npm i react-native-amap3d
 react-native link react-native-amap3d
 执行了这两步，还是没法使用，请问这个问题有解决吗？

**Comment by AaronTon** [comment]
我的项目执行以下操作，可以正常运行
react-native: 0.62.2
hermes-engine: 0.4.2-rc1
设备: 华为CUN-TL00
android版本: 5.1

1. 安装依赖
```
yarn add react-native-amap3d@next // 安装最新版本 2.0.1-0
yarn add react-native-amap-navi // 项目中需要用到的高德导航

```
2. 按照```react-native-amap-navi```说明添加排除项

- 在```android/app/build.gradle``` -> ```dependencies```

```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    // 添加这几行
    implementation (project(':react-native-amap3d')) { 
        exclude group:'com.amap.api', module:'3dmap'
    }
    // 添加结束

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}
```

- 在```android/app/build.gradle``` -> ```defaultConfig```

```
    defaultConfig {
        applicationId "com.xxxx.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        multiDexEnabled true  // <- 添加这行
    }
```

3. ```cd android && gradlew clean```

4. ```yarn android```

详细依赖信息
```
{
    "name": "xxx",
    "version": "2.0.1",
    "private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
        "clean": "cd android && gradlew clean"
    },
    "dependencies": {
        "@eva-design/eva": "^2.0.0-alpha.1",
        "@react-native-community/async-storage": "^1.9.0",
        "@react-native-community/masked-view": "^0.1.8",
        "@react-native-community/netinfo": "^5.7.0",
        "@react-native-community/viewpager": "^3.3.0",
        "@react-navigation/bottom-tabs": "^5.2.6",
        "@react-navigation/drawer": "^5.4.1",
        "@react-navigation/native": "^5.1.5",
        "@react-navigation/stack": "^5.2.10",
        "@ui-kitten/components": "^5.0.0-alpha.1",
        "@ui-kitten/eva-icons": "^5.0.0-alpha.1",
        "axios": "^0.19.2",
        "hermes-engine": "0.4.2-rc1",
        "mobx": "^5.15.4",
        "mobx-react": "^6.2.2",
        "moment": "^2.24.0",
        "react": "16.11.0",
        "react-native": "0.62.2",
        "react-native-amap-navi": "^0.2.0",
        "react-native-amap3d": "^2.0.1-0",
        "react-native-datepicker": "^1.7.2",
        "react-native-gesture-handler": "^1.6.1",
        "react-native-reanimated": "^1.8.0",
        "react-native-render-html": "^4.2.0",
        "react-native-safe-area-context": "^0.7.3",
        "react-native-screens": "^2.4.0",
        "react-native-scrollable-tab-view": "^1.0.0",
        "react-native-svg": "9.13.3",
        "react-native-webview": "^9.2.1"
    },
    "devDependencies": {
        "@babel/core": "^7.6.2",
        "@babel/plugin-proposal-decorators": "^7.8.3",
        "@babel/runtime": "^7.6.2",
        "@react-native-community/eslint-config": "^1.0.0",
        "@types/color": "^3.0.1",
        "@types/jest": "^24.0.24",
        "@types/lodash": "^4.14.149",
        "@types/node": "^13.11.1",
        "@types/react-native": "^0.62.0",
        "@types/react-native-datepicker": "^1.7.0",
        "@types/react-native-scrollable-tab-view": "^0.10.1",
        "@types/react-test-renderer": "16.9.2",
        "@typescript-eslint/eslint-plugin": "^2.27.0",
        "@typescript-eslint/parser": "^2.27.0",
        "babel-jest": "^24.9.0",
        "babel-plugin-module-resolver": "^4.0.0",
        "eslint": "^6.5.1",
        "jest": "^24.9.0",
        "metro-react-native-babel-preset": "^0.58.0",
        "prettier": "^2.0.4",
        "react-test-renderer": "16.11.0",
        "typescript": "^3.8.3"
    },
    "jest": {
        "preset": "react-native",
        "moduleFileExtensions": [
            "ts",
            "tsx",
            "js",
            "jsx",
            "json",
            "node"
        ]
    }
}


```

**Comment by Konmers** [comment]
使用react-native&nbsp;v0.61.3&nbsp;可以正常使用amap3d，不会报以上出现的错误，个人认为可能是react-native&nbsp;v0.62.2版本与amap3d&nbsp;v1.1.1不兼容产生的问题




Konmer
konmer@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王飞"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 中午1:52
收件人:&nbsp;"qiuxiang/react-native-amap3d"<react-native-amap3d@noreply.github.com&gt;;
抄送:&nbsp;"1916794877"<1916794877@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [qiuxiang/react-native-amap3d] RN ^0.62.2  真机测试  requirenativecomponent:"AMapMarker" was not found in the UIManager (#595)





 
npm i react-native-amap3d
 react-native link react-native-amap3d
 执行了这两步，还是没法使用，请问这个问题有解决吗？

**Comment by Konmers** [comment]
可运行，无报错

{
  "name": "xxx",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.3",
    "react-native-amap-geolocation": "^1.0.4",
    "react-native-amap3d": "^1.1.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-modalbox": "^2.0.0",
    "react-native-reanimated": "^1.8.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-screens": "^2.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.4.0",
    "eslint": "^6.8.0",
    "jest": "^25.4.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by zjafei** [comment]
@Konmers 谢谢你

**Comment by inkCrazy** [comment]
@Konmers RN0.62不是不用link，然后我发现这个问题，pods里面找不到 react-native-amap3d这个库 
https://github.com/qiuxiang/react-native-amap3d/issues/601

**Comment by Konmers** [comment]
> @Konmers RN0.62不是不用链接，然后我发现这个问题，pods里面找到react-native-amap3d这个库
> [＃601](https://github.com/qiuxiang/react-native-amap3d/issues/601)

**Comment by Konmers** [comment]
> @Konmers RN0.62不是不用链接，然后我发现这个问题，pods里面找到react-native-amap3d这个库
> [＃601](https://github.com/qiuxiang/react-native-amap3d/issues/6

**Comment by Konmers** [comment]
> @Konmers RN0.62不是不用link，然后我发现这个问题，pods里面找不到 react-native-amap3d这个库
> #601

https://github.com/Konmers/react-native-mapdemo   
你看看这个

**Comment by inkCrazy** [comment]
> > @Konmers RN0.62不是不用link，然后我发现这个问题，pods里面找不到 react-native-amap3d这个库
> > #601
> 
> https://github.com/Konmers/react-native-mapdemo
> 你看看这个，能不能帮到你

嗯，谢谢，原来需要podfile里面手动添加路径就可以了：pod 'react-native-amap-geolocation', :path => '../node_modules/react-native-amap-geolocation'
