### ISSUE TITLE
想哭了！！！MapView.Marker的onPress点击事件失效

### ISSUE THREAD

**Issue by KenSuperboy** [qiuxiang/react-native-amap3d#597]
ReactNative版本：react-native": "0.62.0
安装：npm install react-native-amap3d@next
package.json："react-native-amap3d": "^2.0.1-0",

Android 9.1.0真机
MapView.Marker的onPress点击事件失效，尝试了好久一直没反应，想哭！！！求大佬指教
又遇到同样问题的吗兄弟吗？

**Comment by momtboy** [comment]
我也遇到了  修改如下
AMapView文件里面：
`map.setOnMarkerClickListener { marker ->
            markers[marker.id]?.let {
                it.active = true
                emit(it.id, "onPress")  // emit(it.id, "onClick")  把onClick 修改成 onPress
            }
            true
        }`

**Comment by KenSuperboy** [comment]
感谢大佬，已解决。

**Comment by wxingheng** [comment]
@KenSuperboy  我遇到了同样的问题，但是没有找到

我也遇到了 修改如下
AMapView文件里面：
map.setOnMarkerClickListener { marker -> markers[marker.id]?.let { it.active = true emit(it.id, "onPress") // emit(it.id, "onClick") 把onClick 修改成 onPress } true }


上面说到的这段代码，可以提供一些帮助吗

wxingheng@outlook.com

**Comment by qiuxiang** [comment]
已修正 https://github.com/qiuxiang/react-native-amap3d/commit/a5a95d3feb374413bc484d98326d4f8e071b021f

**Comment by ShaoGongBra** [comment]
没有发不到npm吗，还是2.0.1 @qiuxiang
