### ISSUE TITLE
定位问题

### ISSUE THREAD

**Issue by starsion** [qiuxiang/react-native-amap3d#60]
在根据示例走了之后，在用真机调试的时候，为什么就是定位不到呢，打印出来的位置老是(0,0),手机已经允许使用GPS了，后台也可以看到在搜索GPS，部分代码如下
`        <MapView style={StyleSheet.absoluteFill}
          coordinate={this.state.coordinate}
          mapType='standard'
          locationEnabled={this.state.locationEnabled}
          locationInterval={5000}
          distanceFilter={10}
          onLocation={({nativeEvent}) =>alert('当前位置: '+`${nativeEvent.latitude}, ${nativeEvent.longitude}`)}
        >`

**Comment by qiuxiang** [comment]
检查高德 Key

**Comment by starsion** [comment]
问题已经解决，果然是key的原因，是自己忘了之前使用其他项目创建了key，然后直接用在新的工程了。
