### ISSUE TITLE
pod install 不会安装依赖

### ISSUE THREAD

**Issue by ZeroJian** [qiuxiang/react-native-amap3d#603]
- react-native-amap3d: 1.1.1
- ReactNatvie: 0.62.2
- Xcode: 11.4.1
- pod: 1.9.0

1.使用 **npm i react-native-amap3d** 后 node_modules 会显示包, 项目 package.json dependencies 显示 **react-native-amap3d 1.1.1**
2.打开 ios 目录,  pod install 不会更新任何依赖, 尝试使用 react-natvie link 然后 pod install 问题依旧
3.安装过一些其他第三方库没有出现过这种问题

**Comment by Lenlyl** [comment]
只能手动依赖，在podfile加依赖代码
pod 'react-native-amap3d', :path => '../node_modules/react-native-amap3d/lib/ios'

并且在../node_modules/react-native-amap3d/ios/react-native-amap3d.podspec文件中增加一行代码
s.static_framework = true

/**位置 */
s.dependency 'React'
s.dependency 'AMap3DMap', "~> 7.2.0"
s.static_framework = true

**Comment by qiuxiang** [comment]
最新版应该是没问题的，2.0 之前还没支持 RN 的 auto linking

**Comment by Lenlyl** [comment]
不行的，今天down的最新的，这问题上周就困扰了我，项目做的七七八八了今天才来重点搞这问题的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 7c00 <notifications@github.com&gt;
发送时间: 2020年7月31日 16:44
收件人: qiuxiang/react-native-amap3d <react-native-amap3d@noreply.github.com&gt;
抄送: Lenlyl <363819948@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[qiuxiang/react-native-amap3d] pod install 不会安装依赖 (#603)





 
最新版应该是没问题的，2.0 之前还没支持 RN 的 auto linking

**Comment by ZeroJian** [comment]
新项目使用,这个问题修复了,先关闭

**Comment by inkcrazy666** [comment]
podspec里面明明写了有依赖的，上周还好好的，今天安装的时候怎么它自己把这个库删掉了
![image](https://github.com/qiuxiang/react-native-amap3d/assets/130324703/3829a604-d49f-4931-9414-d8d77f7e1159)
![image](https://github.com/qiuxiang/react-native-amap3d/assets/130324703/6382a1cb-4eac-4f56-83a1-2ce3fc9d9832)
