### ISSUE TITLE
Use of undeclared identifier 'AMapServices'

### ISSUE THREAD

**Issue by perfecten** [qiuxiang/react-native-amap3d#626]
1.版本
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-amap-geolocation": "^1.1.2",
"react-native-amap3d": "^2.0.1",

2.问题 
iOS虚拟机测试debug版好的，真机测试debug版也好的。
但是在Xcode里Archive就报错，
错误信息：Use of undeclared identifier 'AMapServices'

AppDelegate.m中有 

```
#import <AMapFoundationKit/AMapFoundationKit.h>
 [AMapServices sharedServices].apiKey = @"我的key";
```

就是这句报的错，有劳大神百忙中，给予指导。谢谢谢谢。

![image](https://user-images.githubusercontent.com/28498833/87866739-cf292600-c9b7-11ea-8e47-d6f14dc4d4e8.png)

**Comment by perfecten** [comment]
实在不好意思。
刚提交就发现问题所在了，
我的定义居然放在了debug的下面，晕死
再次感谢大神开发这么好的库给大家用

**Comment by chenshaxuanjing** [comment]
> 实在不好意思。
> 刚提交就发现问题所在了，
> 我的定义居然放在了debug的下面，晕死
> 再次感谢大神开发这么好的库给大家用

请问应该放在哪里，我打包的时候也遇到了这个问题

**Comment by Moxmoon** [comment]
> 实在不好意思。 刚提交就发现问题所在了， 我的定义居然放在了debug的下面，晕死 再次感谢大神开发这么好的库给大家用

我也犯了同样的错误😭
