### ISSUE TITLE
当customInfoWindow高度改变会弹到屏幕左上角

### ISSUE THREAD

**Issue by FarmersReact** [qiuxiang/react-native-amap3d#639]
```
import React, { Component } from "react";
import { Alert, StyleSheet, Text, TouchableOpacity, View, Image } from "react-native";
import { MapView } from "react-native-amap3d";

const styles = StyleSheet.create({
  customInfoWindow: {
    flexDirection: 'column',
    width: 300,
    backgroundColor: "#FFFFFF",
    padding: 5,
    borderRadius: 10,
    elevation: 4,
    borderWidth: 2,
    borderColor: "#BEBEBE",
    opacity: 0.8,
    marginBottom: 5
  }
});

export default class MarkerExample extends Component {

  state = {
    time: new Date()
  };

  componentDidMount() {
    setInterval(() => {
        this.setState({ time: new Date() });
    }, 1000);
  }

  index = 0

  _onInfoWindowPress = () => {
    if(this.index === 3){
      this.index = 0
    }
    else{
      this.index += 1
    }
  }

  render() {
    let res = [];
    for (let i = 0; i <= this.index; i++) {
      res.push(
        <>
          <Text>自定义信息窗口</Text>
          <Text>{this.state.time.toLocaleTimeString()}</Text>
        </>
      )
    }
    return (
      <MapView style={StyleSheet.absoluteFill}>
        <MapView.Marker
          coordinate={{latitude: 39.806901,longitude: 116.397972}}
          image="flag"
        >
          <TouchableOpacity activeOpacity={0.9} onPress={this._onInfoWindowPress}>
            <View style={styles.customInfoWindow}>
              {res}
            </View>
          </TouchableOpacity>
        </MapView.Marker>
      </MapView >
    );
  }
}
```
![Screenshot_2020-08-25-15-19-37-206_com totarget_ios_project](https://user-images.githubusercontent.com/50646999/91144427-9848dd00-e6e6-11ea-98be-dc0add2e401f.png)
当customInfoWindow高度改变会弹到屏幕左上角

**Comment by qiuxiang** [comment]
我用你的代码试了，并没有问题：
<img src="https://user-images.githubusercontent.com/1709072/91375049-386c4680-e84c-11ea-827f-f82648b265b7.jpg" width=400>

你的版本是？

**Comment by FarmersReact** [comment]
我的版本是 "react-native-amap3d": "^2.0.2",
你需要点击customInfoWindow让它变高，应该就会出现我的情况。

**Comment by Bull778** [comment]
时时获取后端数据更新时，我也出现这个问题了，请问解决了吗

**Comment by qiuxiang** [comment]
看起来动态更新 infowinfow 确实会导致这个问题，我看看怎么解决吧

**Comment by supermaverickws** [comment]
可以试试这个 [673](https://github.com/qiuxiang/react-native-amap3d/pull/673)

**Comment by FarmersReact** [comment]
@supermaverickws 试了好像没起作用

**Comment by StevenGardnerGMJ** [comment]
模拟器这么写没有infowindow 怎么办

` <Marker
      // key={1}
      active
      title="这是一个标注点"
      description="Hello world!"
      onPress={() => {
        console.log('====Marker');
        return (
          <Tooltip popover={<Text>no caret!</Text>} withPointer={false}>
            <Text>without caret</Text>
          </Tooltip>
        );
      }}
      icon={
        1 === 1
          ? require('./res/marker_red.png')
          : require('./res/marker_green.png')
      }
      position={{
        latitude: 34.751148,
        longitude: 113.774146,
      }}></Marker>`
