### ISSUE TITLE
新建的项目使用podfile，结果编译不成功

### ISSUE THREAD

**Issue by jiyarong** [qiuxiang/react-native-amap3d#66]
这是我的Podfile

platform :ios, '8.0'

target 'AmapDemo' do
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'DevSupport',
  ]
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'
end

$ pod install
然后跑ios的时候就报错了

In file included from /Users/jiyarong/webs2/AmapDemo/node_modules/react-native-amap3d/ios/AMapViewManager.m:2:
/Users/jiyarong/webs2/AmapDemo/node_modules/react-native-amap3d/ios/AMapView.h:1:9: fatal error: 'MAMapKit/MAMapKit.h' file not found
#import <MAMapKit/MAMapKit.h>
        ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
        CompileC /Users/jiyarong/webs2/AmapDemo/ios/build/Build/Intermediates/AMap3D.build/Debug-iphonesimulator/AMap3D.build/Objects-normal/x86_64/AMapViewManager.o AMapViewManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AmapDemo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AmapDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
我项目叫AmapDemo, 是我podfile写错了吗

**Comment by jiyarong** [comment]
你的example我拉下来，安卓可以跑, ios的好像也是一样的错误

**Comment by jiyarong** [comment]
#import <MAMapKit/MAMapKit.h>  //编译的时候这一行报错

@interface AMapView : MAMapView

@property(nonatomic, copy) RCTBubblingEventBlock onLocation;
@property(nonatomic, copy) RCTBubblingEventBlock onPress;
@property(nonatomic, copy) RCTBubblingEventBlock onLongPress;
@property(nonatomic, copy) RCTBubblingEventBlock onStatusChange;
@property(nonatomic, copy) RCTBubblingEventBlock onStatusChangeComplete;

@property(nonatomic) BOOL loaded;
@property(nonatomic) MACoordinateRegion initialRegion;

@end

**Comment by qiuxiang** [comment]
看起来是根本没有引入高德地图 SDK，我只能保证一般情况下一个新项目安装标准的安装流程不会出错，但因为每个人的开发环境不一样，只能你自己去找问题。

我是不太想管这种编译相关的 issue，给一个方向吧，你要用 xcode 打开 xcworkspace，确认 AMap3DMap 有引入
<img width="1111" alt="screen shot 2017-09-11 at 6 27 49 pm" src="https://user-images.githubusercontent.com/1709072/30270371-f1d95bc6-971e-11e7-8f2c-470f2903d5a8.png">

另外，确认一个问题，你的 ios 项目是不是 link 了这个库？

**Comment by qiuxiang** [comment]
很有可能是这个类似的问题 #10

**Comment by jiyarong** [comment]
看样子是因为我跑了link，那跑ios的时候需要unlink? 或者手动配置SDK？
我再试试，多谢老哥，要是能优化一下pod指令就更好了

**Comment by qiuxiang** [comment]
ios 项目要 unlink

**Comment by jiyarong** [comment]
以后要是打包也是这样吗，安卓link之后再打包？

**Comment by qiuxiang** [comment]
#23

**Comment by jiyarong** [comment]
unlink之后编译成功了，但是在ios模拟器上的地图为什么没有放大和缩小的按钮，demo里地图控件版块里，点击定位开关，地图上也并没有出现相应的选项

**Comment by qiuxiang** [comment]
这两个接口是 android only 的
