### ISSUE TITLE
关于定位精度

### ISSUE THREAD

**Issue by starsion** [qiuxiang/react-native-amap3d#67]
请问一下码主，您封装的这个api 里面的定位方法，是采用的高德定位sdk的哪种定位模式呢？（高德sdk有三种模式：高精度模式、低功耗模式、设备模式），这边是否可以切换模式呢？

**Comment by qiuxiang** [comment]
官方文档也没有说 MapView 内置的定位使用了哪种精度，也没有提供切换的接口

**Comment by starsion** [comment]
哦哦，好的，是那个android定位sdk有选项
