### ISSUE TITLE
地图控件不显示

### ISSUE THREAD

**Issue by vvizden** [qiuxiang/react-native-amap3d#670]
# 地图控件不显示

## 问题

地图控件不显示，测试了您的示例APP，一样的问题

## 截图

![image](https://user-images.githubusercontent.com/32644183/103343010-f424d780-4ac5-11eb-8386-d431321d26b6.png)

## 环境

- react-native@0.63.4
- react-native-amap3d@^2.0.3
- 真机信息：
  - 魅族 m1 metal ( Flyme 6.3.0.2A )
  - android 5.1

请问，是什么原因呢？

**Comment by qiuxiang** [comment]
这个问题很早就存在，我只能猜测是 react view 的问题，一直也没有找到好的解决办法

**Comment by vvizden** [comment]
> 这个问题很早就存在，我只能猜测是 react view 的问题，一直也没有找到好的解决办法

后来经过我的测试，当前页面不使用状态栏组件，地图控件是可以正常出来的。

另外发现一个与这个问题不相关的另一个问题，在路由切换到地图页面时，地图会短暂的黑屏闪一下。

**Comment by chenshaxuanjing** [comment]
> > 这个问题很早就存在，我只能猜测是 react view 的问题，一直也没有找到好的解决办法
> 
> 后来经过我的测试，当前页面不使用状态栏组件，地图控件是可以正常出来的。
> 
> 另外发现一个与这个问题不相关的另一个问题，在路由切换到地图页面时，地图会短暂的黑屏闪一下。

请问不使用状态栏组件，是指不用StatusBar么

**Comment by vvizden** [comment]
> > > 这个问题很早就存在，我只能猜测是 react view 的问题，一直也没有找到好的解决办法
> > 
> > 
> > 后来经过我的测试，当前页面不使用状态栏组件，地图控件是可以正常出来的。
> > 另外发现一个与这个问题不相关的另一个问题，在路由切换到地图页面时，地图会短暂的黑屏闪一下。
> 
> 请问不使用状态栏组件，是指不用StatusBar么

是的。但是当前页面不使用状态栏组件的话，会引发新的问题，就是 `react-navigation` 在切换页面的时候会因为前后页面状态栏状态不一致导致布局抖动。后来想着自己写安卓，封装一个最小程度业务可用的高德地图 `react component` ，尝试之后还是放弃了，最后，我选用了兜底的方案，webview + 高德JS-SDK。
