### ISSUE TITLE
Property 'lineDash' not found on object of type 'MAMultiColoredPolylineRenderer *'

### ISSUE THREAD

**Issue by Miluaaa** [qiuxiang/react-native-amap3d#685]
"react-native": "0.64.0"
"react-native-amap3d": "^2.0.4"

yarn add react-native-amap3d
cd ios 
pod install

<img width="906" alt="1" src="https://user-images.githubusercontent.com/49137179/124085169-544f0300-da82-11eb-8f08-d7f8d72d907a.png">
<img width="905" alt="2" src="https://user-images.githubusercontent.com/49137179/124085181-5749f380-da82-11eb-8f3b-df9ab1830f66.png">

**Comment by firmliao789** [comment]
将地图sdk降级到7.8.0

**Comment by qilovehua** [comment]
> 将地图sdk降级到7.8.0

我降到7.8.0 ios有2%的用户crash了。

@Miluaaa  把报错的注释调就能跑起来
