### ISSUE TITLE
Android不会自动link

### ISSUE THREAD

**Issue by saludyan** [qiuxiang/react-native-amap3d#69]
看了其它issus,你说已经修复
但我用npm下载,没有你更新的java
android/src/main/java/cn/qiuxiang/react/amap3d/AMap3DPackage.java

![image](https://user-images.githubusercontent.com/10394008/30317542-f490ae8c-97dc-11e7-9bbd-f5f933ff94d5.png)

**Comment by qiuxiang** [comment]
你的 RN 版本是多少？

**Comment by qiuxiang** [comment]
如果你的 RN 版本低于 0.47，那么很遗憾，现在已经不支持了，因为 0.47 有一个修改导致无法向后兼容，之前的 java 文件也就失去意义被删了。如果要支持旧版的 RN，需要自己做修改。

**Comment by saludyan** [comment]
ok,明白了,我是0.44.3,我升级一下吧
