### ISSUE TITLE
重构方向是什么呢

### ISSUE THREAD

**Issue by caopeng000** [qiuxiang/react-native-amap3d#695]
现在用到RN中使用高德地图。刚卡了下大佬你说要重构，现在有release版本不，以及重构方向，谢谢分享

**Comment by qiuxiang** [comment]
1. 全部使用 typescript 严格模式编写并发布。
2. 接口名改动（主要是属性名和一些使用方式），之前没有一个很好的参考，接口命名挺乱的，现在有了 google_maps_flutter 作为参考之后决定使用这套接口，包括之后要做的百度地图、腾讯地图 RN 组件。
3. 顺便修复之前存在的一些问题。
4. 所有代码都重新梳理，移除不好的代码，跟进最新最佳实践，总的来说就是代码更少、逻辑更清晰、更容易维护。
5. 使用 swift 重构 iOS 端代码。
5. Marker 支持 [ImageSrouce](https://reactnative.dev/docs/image#imagesource)。
6. 新增点聚合功能。
7. 移除 InfoWindow，InfoWindow 不管在 iOS 和 android 还是各地图 SDK 都差异过大，兼容性太差，维护成本过高。
8. 原生组件方法可以返回数据，目前可以实现调用地图的坐标转换（屏幕坐标转地图坐标，地图选点的时候可以用到），之后也可以根据需要新增更多类似的接口，这是 RN 并不支持的，我是自己实现了一套回调机制，其实之前就有这个想法，只是没有做。

**Comment by qiuxiang** [comment]
目前 android 部分已经基本完成，现在在写 iOS，release 大概在两周之后

**Comment by caopeng000** [comment]
3q
