### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'latLngBounds.southwest')

### ISSUE THREAD

**Issue by caopeng000** [qiuxiang/react-native-amap3d#698]
![报错](https://user-images.githubusercontent.com/7322422/141432083-fb169bd0-9915-48ed-aeff-bb588ed08b55.jpg)
 
使用点聚合的时候报错了，尝试了各种方法，依旧识别说是这个不是一个对象，大佬怎么回事呢

**Comment by qiuxiang** [comment]
你用了 `cameraMove` 事件吧？

**Comment by qiuxiang** [comment]
要用 `cameraIdle`

**Comment by caopeng000** [comment]
![image](https://user-images.githubusercontent.com/7322422/141447464-05e4c856-cc80-45d0-a7e4-977aeb60ecb5.png)
这样用法是需要调整吗？

**Comment by caopeng000** [comment]
![image](https://user-images.githubusercontent.com/7322422/141450214-b1e7e960-3307-463c-b2ca-6a2d697468bc.png)

我是直接复制readme上面的点聚合。
是我前期需要准备工作吗？点聚合相关的

**Comment by qiuxiang** [comment]
很显然，update 传的参数就不对

**Comment by caopeng000** [comment]
![image](https://user-images.githubusercontent.com/7322422/141671387-b6feaffb-6bec-449e-a999-f129f05f7f7c.png)
可以了。typescrip语法太恶心了，怎么写都对，错了都不知道哪里的问题

**Comment by qiuxiang** [comment]
你都 ts ignore 了还能怪 ts 的吗
