### ISSUE TITLE
启动报错Execution failed for task ':react-native-amap3d:compileDebugKotlin'

### ISSUE THREAD

**Issue by niuzhaoxia** [qiuxiang/react-native-amap3d#702]
"react-native": "^0.62.3",
"react-native-amap3d": "^3.0.3",

报错：
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings
747 actionable tasks: 13 executed, 734 up-to-date
e: D:\a_work\youyouProject\app\youyouProject\node_modules\react-native-amap3d\lib\android\src\main\java\qiuxiang\amap3d\Utils.kt: (36, 43): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: D:\a_work\youyouProject\app\youyouProject\node_modules\react-native-amap3d\lib\android\src\main\java\qiuxiang\amap3d\map_view\MapView.kt: (157, 57): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?
e: D:\a_work\youyouProject\app\youyouProject\node_modules\react-native-amap3d\lib\android\src\main\java\qiuxiang\amap3d\map_view\MultiPoint.kt: (41, 43): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableMap?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-amap3d:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by LiJingCute** [comment]
如何改的啊？
