### ISSUE TITLE
setState点聚合不会更新

### ISSUE THREAD

**Issue by NapChen** [qiuxiang/react-native-amap3d#704]
RN:0.61.5
amap3d:3.0.4
如下代码所示，初始化的marker可以在点聚合中显示，但是通过网络请求数据以后，再次setState数据，界面不会更新，是我缺少什么步骤吗？
![image](https://user-images.githubusercontent.com/19644794/145789921-0f4de589-dbc1-426e-92c4-dc07876ffcba.png)
我在constructor方法中设置的markers可以显示，但数据从后台请求完setState以后界面不会更新，是需要手动更新吗？
最后非常感谢作者又回来了，之前一直用baidu-sdk，但是在安卓是遇到Android12时闪退了，所以看到这个库又开始更新而且是重构，非常期待！

另外：api文档页面好像打不开了

**Comment by qiuxiang** [comment]
api 文档不打算提供了，直接看 tsserver 的提示吧，现在 ts 的类型和注释都是完备的，没有必要单独提供接口文档了，代码也足够简单，直接源码也不会有任何负担

**Comment by NapChen** [comment]
> api 文档不打算提供了，直接看 tsserver 的提示吧，现在 ts 的类型和注释都是完备的，没有必要单独提供接口文档了，代码也足够简单，直接源码也不会有任何负担

感谢，没有文档就只有点开源文件查看了，好在里面注释都很清晰

**Comment by qiuxiang** [comment]
setState 之后数据已经更新了，但 update 没有调用就不会更新渲染，你可以在 setState 之后手动调用一次 update：

```js
setTimeout(() => this.cluster?.update(this.status!), 0);
```

**Comment by NapChen** [comment]
> setState 之后数据已经更新了，但 update 没有调用就不会更新渲染，你可以在 setState 之后手动调用一次 update：
> 
> ```js
> setTimeout(() => this.cluster?.update(this.status!), 0);
> ```

setState是异步的，我调setState后再掉update并不能保证此时state已经更新

**Comment by qiuxiang** [comment]
setState 不一定是异步的，你要是不确定，完全可以在 setState callback 里调用：
```js
this.setState({ markers }, () => {
  this.cluster?.update(this.status!);
});
```

**Comment by NapChen** [comment]
> setState 不一定是异步的，你要是不确定，完全可以在 setState callback 里调用：
> 
> ```js
> this.setState({ markers }, () => {
>   this.cluster?.update(this.status!);
> });
> ```

![image](https://user-images.githubusercontent.com/19644794/145928966-2cbdb6f1-e1a8-4d40-a798-981719ef9624.png)
数据确实更新了，从打印的log可以看出，但是即使我调用了`this.cluster?.update(this.status!)`，界面也不会刷新，不管
`this.setState({ markers }, () => {
  this.cluster?.update(this.status!);
});`
是在setState的回调中还是不在

**Comment by qiuxiang** [comment]
发布了个新版本，应该不需要做任何处理了

**Comment by NapChen** [comment]
双端测试都可以了，给大佬递茶.jpg
