### ISSUE TITLE
【点聚合】怎么实现单次就能点击打开呢

### ISSUE THREAD

**Issue by caopeng000** [qiuxiang/react-native-amap3d#714]
大佬，现在点聚合只能双击两次才能打开下一个层级的marker。看了看源码也没有找到合适的修改方案。目前是有个onPress方法。但是不知道怎么调到下个级别的缩放

**Comment by qiuxiang** [comment]
最简单的做法是像 example 一样 onPress 的时候 moveCamera zoom +1
