### ISSUE TITLE
点击Marker切换图片

### ISSUE THREAD

**Issue by caopeng000** [qiuxiang/react-native-amap3d#715]
大佬，地图点击Marker的时候要切换图片。我看了下网上大部分都是说，集合重新渲染，然后把选中的换个图片。这个大佬怎么看，有没有更好的方案呢

**Comment by qiuxiang** [comment]
是的，这里的重新渲染只是 react 重新运行一次 render 函数而已，实际 marker 并不会重新渲染，只是调用了一下属性更新接口对原生 view 进行一次细粒度的更新。
