### ISSUE TITLE
iOS MapView 的onCameraIdle 回调。只有target，Android 会有更多信息，大佬帮忙看看这个问题吧

### ISSUE THREAD

**Issue by caopeng000** [qiuxiang/react-native-amap3d#717]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/7322422/153533235-521b363e-20d4-4f6e-855d-31363c3c2d4d.png">

获取地图---{"target":15}

设备： iOS
目的： 获取地图中心点坐标，通过此方法的
` // @ts-ignore
                        const { longitude, latitude } =
                            nativeEvent.cameraPosition.target;
                        centerLatRef.current = latitude;
                        centerLonRef.current = longitude;`

安卓是没有问题的。我是安卓开发，iOS不会，希望大佬看到后帮忙看下这个问题吧，谢谢感恩

**Comment by qiuxiang** [comment]
![image](https://user-images.githubusercontent.com/1709072/153738398-31445b25-85a3-4b97-bbce-0d2dcfb3e7da.png)
我看起来没问题

**Comment by caopeng000** [comment]
嗯嗯，我运行大佬的项目也是能返回值的。但是我集成到我的项目里总是只有{"target":15}  ，什么情况下会出现这个呢，iOS设备

**Comment by caopeng000** [comment]
这是安卓的
`获取地图---{"latLngBounds":{"northeast":{"longitude":116.66642078847178,"latitude":40.30721139986867},"southwest":{"longitude":116.49318629889503,"latitude":40.029586568514105}},eraPosition":{"bearing":0,"tilt":0,"zoom":12,"target":{"longitude":116.57980421423564,"latitude":40.16860190177908}}}
`

**Comment by caopeng000** [comment]
现在安卓基本上都没啥问题了，开始调iOS.然后就发现刚开始onCamaraIdle方法在iOS端就返回了一个target对象，其他的都没了。卡在这里了。

**Comment by caopeng000** [comment]
没问题了。多谢
