### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by unionTime** [qiuxiang/react-native-amap3d#72]
维护者，您好！我是一个新手。为在使用的过程中，出现了报错，不知道怎么解决。麻烦您指导一下。
我按照你的教程安装并引入SDK。在填入key，编译的时候出现报错！（其实，连[AMapServices sharedServices].apiKey = @"key"放在哪，我也不知道;）
这是我的引入配置：
`#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <AMapFoundationKit/AMapFoundationKit.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
  [AMapServices sharedServices].apiKey = @"key";
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"smartphone"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end
`
出现如下报错：
<img width="237" alt="cfdd66df-ffd8-4b45-a1d7-2145d186368b" src="https://user-images.githubusercontent.com/19386499/30520253-9610d31a-9bdc-11e7-8cdb-1493b4803df4.png">
打扰你了！

**Comment by qiuxiang** [comment]
仅有 `Apple Mach-O Linker Error` 这个错误信息根本没法确定问题

**Comment by qiuxiang** [comment]
你可以看看 example

**Comment by unionTime** [comment]
我已经解决了！使用CocoaPods构建项目，启动项目的入口是.xcworkspace文件，而不是.xcodeproj文件。主要问题是我对ios开发和CocoaPods没有一定的认识。谢谢你 @qiuxiang

**Comment by unionTime** [comment]
找到问题的本质，也是重点。只能不断补课了。感谢做出这么好的东西 @qiuxiang

**Comment by qiuxiang** [comment]
不客气

**Comment by ChenZhaobin** [comment]
@qiuxiang @unionTime 请问[AMapServices sharedServices].apiKey = @"key"放在哪？可以指导一下吗？

**Comment by qiuxiang** [comment]
@ChenZhaobin 
https://github.com/qiuxiang/react-native-amap3d/blob/7fb14551cfc6337bd5562ba3b16e0ffa6858e589/ios/RNAMap3D/AppDelegate.m#L20

**Comment by ChenZhaobin** [comment]
@qiuxiang  got it , thanks very much!
