### ISSUE TITLE
android上启动报错，‘Marker’ has no propType for native prop

### ISSUE THREAD

**Issue by orangeh8** [qiuxiang/react-native-amap3d#73]
![image](https://user-images.githubusercontent.com/6930818/30573567-39a30a16-9d27-11e7-91c9-d9fc47bedd08.png)

请问这个错误该怎么解决？

**Comment by qiuxiang** [comment]
我忘了给 example 升级了，`npm i react-native-amap3d@0.7.0` 应该是可以解决的

**Comment by orangeh8** [comment]
非常感谢，问题已解决 @qiuxiang
