### ISSUE TITLE
函数式组件怎么自定义 定位图标 放大缩小图标 的样式和显示的位置

### ISSUE THREAD

**Issue by XuanChuYun** [qiuxiang/react-native-amap3d#731]
"react-native-amap3d": "^3.0.7",
"react-native": "0.67.1",
现在想自定义 交互控件的 样式和显示的位置。
然后目前是自己写了几个图标，然后添加点击事件来更新地图。没有找到更新地图的方法，函数式组件 useRef 对组件的话，用forwardRef，你代码用的class。然后我就卡壳了。

**Comment by qiuxiang** [comment]
你用函数式来写组件和你用的组件是不是函数式有什么关系？
参考：https://github.com/qiuxiang/react-native-amap3d/blob/main/example/screens/animated.tsx

**Comment by XuanChuYun** [comment]
> 你用函数式来写组件和你用的组件不是函数式实现的有什么关系？ 参考：[https://github.com/qiuxiang/react-native-amap3d/blob/main/example/screens/animated。 tsx](https://github.com/qiuxiang/react-native-amap3d/blob/main/example/screens/animated.tsx)

好的，谢谢大佬，新手上路。
