### ISSUE TITLE
点聚合两个点很近的问题

### ISSUE THREAD

**Issue by caopeng000** [qiuxiang/react-native-amap3d#738]
使用版本： v3.1.1
RN 版本：0.64.2
设备： 华为P30

问题：使用点聚合发现两个点很近的时候，一直处于聚合状态。
经纬度A: lat 39.885634 lon 116.31671
经纬度B:lat 39.885534 lon 116.31671

![middle_img_v2_421dd811-b276-4dff-b30d-8974fc1d18dg](https://user-images.githubusercontent.com/7322422/169935432-23bcd846-4516-40ab-b08f-e6c0f84e7a0c.jpg)
 也看了下点聚合的方案：
https://github.com/mapbox/supercluster
不过不知道是哪个函数导致的问题。大佬帮忙看下吧，谢谢谢，头疼已久

**Comment by qiuxiang** [comment]
你是自己又实现了一遍点聚合？

**Comment by caopeng000** [comment]
> 你是自己又实现了一遍点聚合？

没有，我是用文档里面的点聚合。只不过看了下大佬源码里面用的是和supercluster相关的，顺着看了下文档。不过依旧没有发现怎么改这个问题

**Comment by caopeng000** [comment]
主要想说明下我是看了源码，不是遇到问题直接问的。哈哈。不过尴尬的是还是不知道怎么解决

**Comment by qiuxiang** [comment]
不是有这个参数？

https://github.com/qiuxiang/react-native-amap3d/blob/0b9f91ad026c1bff639e93175b6e8d455642cbb8/lib/src/cluster/index.tsx#L38-L41

**Comment by caopeng000** [comment]
> 

嗯，尝试过了，改成10，也是聚合状态

**Comment by qiuxiang** [comment]
再大一点呢

**Comment by qiuxiang** [comment]
这个单位不是 flutter 的，而是 supercluster 的，可能要 100+ 才有效果

**Comment by caopeng000** [comment]
> 这个单位不是 flutter 的，而是 supercluster 的，可能要 100+ 才有效果

尝试半径设置为5，那两个点是能出来了，但是其他的有的还是聚合状态。和产品那沟通了下，打算做成一定比例尺下不用点聚合，直接遍历所有点渲染上去。
