### ISSUE TITLE
点聚合先渲染小红点再显示自定义锚点情况

### ISSUE THREAD

**Issue by caopeng000** [qiuxiang/react-native-amap3d#739]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/7322422/169973140-aa410335-d669-4da6-89e1-121b54d777b5.png">
在缩放的时候会有一个大红头针这是什么情况呢，我目前只使用了Marker。我看这个图片是在海量MultiPoint才会出现

**Comment by qiuxiang** [comment]
发个视频

**Comment by caopeng000** [comment]
https://user-images.githubusercontent.com/7322422/169999434-929aba30-56db-4b0b-a79a-5e888681d00d.mp4

**Comment by caopeng000** [comment]
> 发个视频

发了

**Comment by qiuxiang** [comment]
不像 android 可以去掉不造成任何影响，ios 去掉大头针，会影响后续的显示

**Comment by caopeng000** [comment]
> 不像 android 可以去掉不造成任何影响，ios 去掉大头针，会影响后续的显示

那能把大头针替换成别的图片吗，比如一个透明的图片。
