### ISSUE TITLE
iOS Marker自定义children 先显示红色锚点再显示正确视图问题

### ISSUE THREAD

**Issue by caopeng000** [qiuxiang/react-native-amap3d#740]
![image](https://user-images.githubusercontent.com/7322422/170937082-b31d0350-355b-45e3-89b2-50f7baeaebeb.png)
在iOS中先显示红色锚点再显示正确视图
问题：请问下大佬，红色锚点在哪设置替换图片
小方案：我想替换成一个透明的png图片，把这个过渡效果降低

**Comment by caopeng000** [comment]
@qiuxiang 看了下iOS高德开发者，改了一个地方这个就没有大头针了。目前没发现问题。
![8d2rctvYKu](https://user-images.githubusercontent.com/7322422/171536835-1ccfb334-12c6-475d-b398-2148f346cc74.jpg)
![image](https://user-images.githubusercontent.com/7322422/171537016-97223594-d3a8-433d-ab89-71d35620b6af.png)

**Comment by scc02** [comment]
这个问题之前怎么解决的？目前似乎仍存在
