### ISSUE TITLE
pod install 失败 

### ISSUE THREAD

**Issue by cuiken** [qiuxiang/react-native-amap3d#75]
你好，我pod配置中使用了 use_frameworks!
安装地图时提示：
target has transitive dependencies that include static binaries: (.../Pods/AMapNavi/AMapNaviKit.framework)

**Comment by qiuxiang** [comment]
为什么要用 `use_frameworks!`？那你应该知道这意味着什么

**Comment by cuiken** [comment]
@qiuxiang 其他库需要这个。暂时没有找到区分开的办法
手动配置，按照步骤下来总卡在 “.../AMapView.h:1:9: 'MAMapKit/MAMapKit.h' file not found  。

**Comment by qiuxiang** [comment]
https://github.com/qiuxiang/react-native-amap3d/issues/39#issuecomment-328499271

**Comment by cuiken** [comment]
@qiuxiang 谢谢你的回答，#39 这个我看了，我和 @Muriel0603 一样的问题。但是他最终也放弃了手动配置。
如果你方便的话，试试手动配置，看能否发现问题所在。
我是一个ios新手，各种尝试后无果🙏

**Comment by qiuxiang** [comment]
既然选择手动配置，就应该要知道 search path 怎么配置。

没有必要我不会做手动配置，我平时根本就不做 ios 开发，ios 开发相关的东西都是现学现用的。只是因 c/c++ 基础还不错，编译相关的问题能自己解决而已。别人的问题我只能看情况，如果信息足够能让我做出判断，或许还能解答一下。但类似第三方库引用问题，我就没办法了，这本来就应该是要自己解决的。

**Comment by cuiken** [comment]
@qiuxiang 谢谢你的耐心。经过多次尝试，我还是编译通过了。没有采用react-native link 后者react-native 官网上说的手动link。

项目结构整体结构是这样的：
1.把代码直接拖到工程中了。
<img width="280" alt="screen shot 2017-09-22 at 17 23 00" src="https://user-images.githubusercontent.com/1669444/30737886-cde04b72-9fba-11e7-978c-adc400743e71.png">

2.同时在原有项目中新建libs目录添加了依赖
<img width="250" alt="screen shot 2017-09-22 at 17 25 39" src="https://user-images.githubusercontent.com/1669444/30738004-46dff2a2-9fbb-11e7-880a-4a9f6b57c982.png">

以上可以通过运行。
直接link的方式找不到头文件，我的初步判断是库缺少依赖所致，不知道正不正确。因为在项目中那些frameworks已经添加了。
