### ISSUE TITLE
设置Marker的zIndex属性无效果

### ISSUE THREAD

**Issue by fupingwu** [qiuxiang/react-native-amap3d#750]
RN: 0.66.1
设备：IphoneXR、小米cc 9e
map3d：3.0.6
大佬你好：

现在有个问题，地图中的Marker是根据数据自定义的，然后想通过操作数据改变zIndex，将数据对应Marker置于最顶层，但是发现设置了zIndex为最大的Marker，不会置于最顶层。手动点击Marker的时候不需要设置zIndex却又可以置于最顶层，能麻烦看下吗
![1](https://user-images.githubusercontent.com/56752045/175491882-7e0c8997-11fa-440b-bbc8-461276134942.png)

**Comment by fupingwu** [comment]
问题解决了。因为是接口数据遍历渲染的<Marker>有一个唯一的key值，所以通过修改当前<Marker>的key值重新渲染实现了。

**Comment by mrcao2011** [comment]
ios也正常了？
