### ISSUE TITLE
android模拟器正常，iOS报错

### ISSUE THREAD

**Issue by wubaibin** [qiuxiang/react-native-amap3d#753]
TypeError: null is not an object (evaluating 'AMapSdk.initSDK') 
这个问题如何解决

**Comment by FarmersReact** [comment]
我也有这个问题，你是怎么弄的？

**Comment by wubaibin** [comment]
RN 用0.68.2 就可以了

**Comment by FarmersReact** [comment]
你是升级解决的？我看一下能不能不升级

**Comment by wubaibin** [comment]
现在不是0.69了吗，我是回退的

**Comment by yiyou1992** [comment]
> RN 用0.68.2 就可以了

我的就是0.68.2，但也是报这个错

**Comment by wubaibin** [comment]
"react-native-amap3d": "^3.1.1"

**Comment by inkcrazy666** [comment]
"react-native-amap3d": "^3.2.3",
"react-native": "0.63.5",

+1
