### ISSUE TITLE
大哥，3.1.1版本被移除了，0.69版本以前的版本使用3.1.2 iOS pod install会移除react-native-amap3d

### ISSUE THREAD

**Issue by showtan001** [qiuxiang/react-native-amap3d#754]
大哥，3.1.1版本被移除了，0.69版本以前的版本使用3.1.2 iOS pod install会移除react-native-amap3d.
![image](https://user-images.githubusercontent.com/32892347/180756207-7f441523-ebdc-4498-8dd5-d64bb45386fc.png)

**Comment by leajiang** [comment]
手动引入一下  pod 'react-native-amap3d', :path => "../node_modules/react-native-amap3d"
