### ISSUE TITLE
期望新增地理编码、地理逆编码接口

### ISSUE THREAD

**Issue by unionTime** [qiuxiang/react-native-amap3d#77]
期待增加地理编码功能！我没有做过原生的开发，（正在尝试增加），希望能够增加经纬度转地址，地址转经纬度的接口。谢谢！

**Comment by qiuxiang** [comment]
这些接口不打算做，一方面，做原生接口太麻烦，另一方面，完全可以用 [Web服务API](http://lbs.amap.com/api/webservice/summary/)。

**Comment by unionTime** [comment]
@qiuxiang 好的！。我看到别人的定位sdk，https://github.com/react-native-component/react-native-smart-amap-location。如果引用会跟react-native-amap3d发生冲突吗

**Comment by qiuxiang** [comment]
不确定

**Comment by hsl5315156** [comment]
API的地理解析 只能解国内的吧

**Comment by qiuxiang** [comment]
应该是，毕竟高德地图只做国内
