### ISSUE TITLE
更新了新版本pod install 就报错了。。。。

### ISSUE THREAD

**Issue by happystudy666** [qiuxiang/react-native-amap3d#771]
[!] CocoaPods could not find compatible versions for pod "AMapLocation":
  In Podfile:
    react-native-amap-geolocation (from `../node_modules/react-native-amap-geolocation`) was resolved to 1.2.0, which depends on
      AMapLocation (~> 2.9.0)

None of your spec sources contain a spec satisfying the dependency: `AMapLocation (~> 2.9.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Symous** [comment]
@happystudy666 你好，请问你是怎么解决的？
