### ISSUE TITLE
如何在其他View中使用

### ISSUE THREAD

**Issue by pyb0924** [qiuxiang/react-native-amap3d#773]
react-native: 0.70.2,
react-native-amap3d: ^3.1.3

在页面根组件直接使用MapView可以正常显示，嵌套在View中显示白屏
`<View>
      <AMapView />
 </View>`

**Comment by Dwyaneluo** [comment]
这个怎么在其他View中使用呢

**Comment by pyb0924** [comment]
显式指定一下宽度和高度直接使用就可以了
