### ISSUE TITLE
ios版本兼容问题，Marker点不显示

### ISSUE THREAD

**Issue by hwcncd** [qiuxiang/react-native-amap3d#774]
RN->0.63.4,

**Comment by hwcncd** [comment]
react-native-amap3d ->3.13.3,
ios->15.5,
ios部分版本会不显示marker
代码：
<If condition={track_horseman_lat && track_horseman_lng}>
          <Marker
            zIndex={99}
            position={{latitude: track_horseman_lat, longitude: track_horseman_lng}}
          >
            <View style={{alignItems: 'center'}}>

              <View style={{alignItems: 'center'}}>
                <View style={{
                  zIndex: 999,
                  backgroundColor: colors.white,
                  marginBottom: 15,
                  padding: 8,
                  borderRadius: 6,
                }}>
                  <If condition={distance_store > 0}>
                    <Text style={{
                      color: colors.color333,
                      fontSize: 12,
                    }}>骑手距离商家{this.filterDistance(distance_store)} </Text>
                  </If>
                  <If condition={distance_destination > 0}>
                    <Text style={{
                      color: colors.color333,
                      fontSize: 12,
                    }}>骑手距离顾客{this.filterDistance(distance_destination)} </Text>
                  </If>
                </View>
                <Entypo name={'triangle-down'}
                        style={{color: colors.white, fontSize: 30, position: 'absolute', top: 20}}/>
              </View>

              <Image source={{uri: 'https://cnsc-pics.cainiaoshicai.cn/icon-waimai@2x.png'}} style={{
                width: 30,
                height: 34,
              }}/>
            </View>
          </Marker>
        </If>

**Comment by hwcncd** [comment]
异步渲染的问题

**Comment by scc02** [comment]
怎么解决的？
