### ISSUE TITLE
Marker的自定义窗体infoWindow怎么显示呢？

### ISSUE THREAD

**Issue by cvabm** [qiuxiang/react-native-amap3d#777]
旧版2.0.2直接包裹在marker内就行，新版3.1.3却变成修改marker的view，该如何显示自定义窗口？实在不行的话该如何在MapView上显示一个dialog

**Comment by krmao** [comment]
所以现在的 InfoWindow 实现是使用一个 marker 专门替换作为infoWindow显示？
