### ISSUE TITLE
混用CocoaPods(iOS) 和react-native link(android)时是否有影响

### ISSUE THREAD

**Issue by unionTime** [qiuxiang/react-native-amap3d#78]
我先用CocoaPods配置ios的已经成功，正常运行。到android的时候，我用react-native link，执行提示iOS 和android都配置成功（可是我已经配置了iOS）我在运行react-native run-ios时，有报错：
<img width="564" alt="c787a8b4-6bca-41da-bcd9-08fcab5a8f0b" src="https://user-images.githubusercontent.com/19386499/30796272-ed120954-a203-11e7-9e16-cc357b1a49bb.png">
但是iOS应用照样能够运行。这个对iOS会不会有影响

**Comment by qiuxiang** [comment]
配置是要自己把控的，react-native link 只是方便配置而已，已经用 pods 配置成功不能再用 react-native link，如果你同时支持 Android 和 iOS，那么 react-native link 对 iOS 部分的修改要撤销。

**Comment by unionTime** [comment]
@qiuxiang  ！我已经知道如何解决这个问题了。特别感谢。但是我的android部分出现了问题。
我感觉这个不是配置的问题，它已经说配置成功了
<img width="567" alt="176581a0-73ee-4806-af95-fab09440a9da" src="https://user-images.githubusercontent.com/19386499/30797454-b1b52684-a208-11e7-9906-c644fda20d93.png">
