### ISSUE TITLE
手动集成amap3d后，真机调试可以，Archive打包的时候出现Undefined symbol: _OBJC_CLASS_$_XXX问题

### ISSUE THREAD

**Issue by SpringAndMay** [qiuxiang/react-native-amap3d#783]
报错提示如下：
![截屏2023-03-09 15 47 10](https://user-images.githubusercontent.com/57424550/223955646-cb2b2615-413a-40b4-9584-4b39fbe89b9f.png)
不知是否是SDK不支持armv7导致

**Comment by pencilCool** [comment]
你是不是没把库中的swift 的代码包含进去

**Comment by SpringAndMay** [comment]
> 你是不是没把库中的swift 的代码包含进去

这个没问题，之前用的xcode13，后台更新xcode14后就没问题了

**Comment by SpringAndMay** [comment]
更新xcode14后问题就解决了
