### ISSUE TITLE
小米应用市场提示com.loc隐私不合规

### ISSUE THREAD

**Issue by qilovehua** [qiuxiang/react-native-amap3d#785]
APP向用户明示SDK的收集使用规则，未经用户同意，SDK存在com.loc.et,com.loc.ej获取位置、com.loc.et,com.loc.ej,com.loc获取位置、com.loc,com.loc.ap,com.loc.bj,com.loc.bg,com.loc.ck获取MAC、com.loc获取位置、com.loc.ek,com.loc.ej获取位置、com.loc.eq,com.loc.ej获取传感器、com.loc,com.loc.ap,com.loc.bj,com.loc.bg,com.loc.ck获取Android ID的行为。

都是授权前的行为(首次打开app，同意隐私政策前）。
AMapSdk.init以及react-native-amap-geolocation的init都是在同意隐私政策后才调用的。
    "react-native-amap-geolocation": "^1.1.2",
    "react-native-amap3d": "^3.1.3",

有大佬知道咋处理吗？
升级react-native-amap3d和react-native-amap-geolocation到最新版？

**Comment by qilovehua** [comment]
android.location.LocationManager.requestLocationUpdates(LocationManager.java:891)<---android.location.LocationManager.requestLocationUpdates(LocationManager.java:505)<---com.loc.h.i(Unknown Source:145)<---com.loc.h.a(Unknown Source:25)<---com.loc.d$a.handleMessage(Unknown Source:220)<---android.os.Handler.dispatchMessage(Handler.java:106)<---android.os.Looper.loop(Looper.java:164)<---android.os.HandlerThread.run(HandlerThread.java:65)<---com.loc.d$b.run(Unknown Source:0)

**Comment by qilovehua** [comment]
android.telephony.TelephonyManager.getAllCellInfo(TelephonyManager.java:3983)<---com.loc.et.u(Unknown Source:15)<---com.loc.et.a(Unknown Source:24)<---com.loc.ej.c(Unknown Source:36)<---com.loc.e.a(Unknown Source:50)<---com.loc.e.a(Unknown Source:0)<---com.loc.e$a.handleMessage(Unknown Source:272)<---android.os.Handler.dispatchMessage(Handler.java:106)<---android.os.Looper.loop(Looper.java:164)<---android.os.HandlerThread.run(HandlerThread.java:65)<---com.loc.e$b.run(Unknown Source:0)

**Comment by yt303085600** [comment]
react-native-amap-geolocation升级到最新就行了，https://github.com/qiuxiang/react-native-amap-geolocation

**Comment by qilovehua** [comment]
> react-native-amap-geolocation升级到最新就行了，https://github.com/qiuxiang/react-native-amap-geolocation

谢谢！
升级后复测了下确认正常了，非常感谢！
