### ISSUE TITLE
unaligned pointer(s) for architecture arm64

### ISSUE THREAD

**Issue by xjy0925** [qiuxiang/react-native-amap3d#791]
ld: warning: pointer not aligned at address 0x10109A0BA ('_dbl_lnds_data_TileDataRespMsg_fields' + 50 from /Users/xxxxx/Documents/xxxxx/ios/Pods/AMap3DMap/MAMapKit.framework/MAMapKit(MAMapKit-arm64-master.o))
ld: warning: pointer not aligned at address 0x10109A15E ('_dbl_lnds_mapping_TileSdHdLinkMappingRespMsg_fields' + 79 from /Users/xxxxx/Documents/xxxxx/ios/Pods/AMap3DMap/MAMapKit.framework/MAMapKit(MAMapKit-arm64-master.o))

ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

查询了一下，从Xcode13.3开始 ‘unaligned’ 就会失败
with Xcode13.3 it started failing with error ld: unaligned pointer(s) for architecture arm64 on some projects (while compiled ok but probably with changes to it might fail).

<img width="1063" alt="截屏2023-04-18 14 52 33" src="https://user-images.githubusercontent.com/3435271/232695751-67b29140-4092-4ed1-8ec2-a5c0c59f64c6.png">

**Comment by Cyx1994** [comment]
how to fix it?

**Comment by Cyx1994** [comment]
最后是在Pods -> Building Settings -> Exceluded Architectures -> 修改属性为arm64 ;  然后 Product -> Clearn Build Folder -> 重新Build ;  就好了，看来是amap本身的内核配置不会随RN项目变化而变化；本地用了不同平台的设备之后就会有这个问题；

**Comment by Cyx1994** [comment]
替换高德官方的 2.4.0 MAMapKit 到Pod/AMap3DMap里，原因是原sdk不支持arm64

**Comment by qilovehua** [comment]
> 替换高德官方的 2.4.0 MAMapKit 到Pod/AMap3DMap里，原因是原sdk不支持arm64

有下载链接吗？ 我找到的是V10.0.700，替换进去地图显示不了了。
https://lbs.amap.com/api/ios-sdk/download
@Cyx1994

**Comment by qilovehua** [comment]
<img width="816" alt="image" src="https://github.com/qiuxiang/react-native-amap3d/assets/12076175/a28a8ca0-899f-4e64-99f9-97d01884e441">
之前是13.4会提示这样的错误，改成12.4就ok了

**Comment by Cyx1994** [comment]
@qilovehua 基础包里面，找MAMapKit, 替换项目pods中的MAMapKit

**Comment by LuckyYunPeng** [comment]
@qilovehua 请问搞定了么？

**Comment by LuckyYunPeng** [comment]
@Cyx1994 我提示这个，请问大佬有什么建议吗？


Pointer not aligned in '_dbl_lnds_data_TileDataRespMsg_fields'+0x32 (/Users/xiaohei/Documents/freelancer/李杰/ydbapp/ios/Pods/AMap3DMap/MAMapKit.framework/MAMapKit[arm64][2](MAMapKit-arm64-master.o))

**Comment by qilovehua** [comment]
> @qilovehua 请问搞定了么？

按上面的截图试试

**Comment by LuckyYunPeng** [comment]
@qilovehua 请问可以看下你expo和react-native版本号分别是多少吗？

**Comment by LuckyYunPeng** [comment]
> .0 MAMapKit 到Pod/AMap3DMap里，原因是原sdk不支持arm64

@Cyx1994 请问有下载链接吗？我按从官方下载丢进去还是报错

<img width="664" alt="Image" src="https://github.com/user-attachments/assets/c484fc02-020f-4f71-bd52-a8db5891bea9" />

**Comment by qilovehua** [comment]
> [@qilovehua](https://github.com/qilovehua) 请问可以看下你expo和react-native版本号分别是多少吗？

RN 0.74.1, 没用expo

**Comment by scc02** [comment]
> > .0 MAMapKit 到Pod/AMap3DMap里，原因是原sdk不支持arm64
> 
> [@Cyx1994](https://github.com/Cyx1994) 请问有下载链接吗？我按从官方下载丢进去还是报错
> 
> <img alt="Image" width="664" src="https://private-user-images.githubusercontent.com/165190905/404681527-c484fc02-020f-4f71-bd52-a8db5891bea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwMjA1NzIsIm5iZiI6MTc0MDAyMDI3MiwicGF0aCI6Ii8xNjUxOTA5MDUvNDA0NjgxNTI3LWM0ODRmYzAyLTAyMGYtNGY3MS1iZDUyLWE4ZGI1ODkxYmVhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIyMFQwMjU3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTg5NDM1MDJhYTRjNDAxMGQ2NDY1NTgzNDFlZTQxNzkxNmUyNDI1MWE3Njg0M2Y4NTVmYjczN2QzZTY3NWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rIyihITHej4XIm6jvHGPrPhtT3U6G8FHcc_XjcvuXrM">

哥们你解决了吗

**Comment by cutpictureboy** [comment]
把IPHONEOS_DEPLOYMENT_TARGET编译版本改为13.0
然后在pod里面把所有的依赖版本的IPHONEOS_DEPLOYMENT_TARGET改为13.0（否则 expo 安装不了 ）
post_install do |installer| installer.pods_project.targets.each do |t| t.build_configurations.each do |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0' end end end

**Comment by yumez11** [comment]
Xcode 16 报
Pointer not aligned in '_landmark_data_LandmarkTileRequest_fields'+0x15 (/userpath/app/example/ios/Pods/AMap3DMap/MAMapKit.framework/MAMapKit[arm64][2](MAMapKit-arm64-master.o))

 1. other linker flags 添加-ld64
报错
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

2. podfile 添加
 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
3. pod 'AMap3DMap', '~> 10.0.600'
后通过 
 有缘人看到可以试试
