### ISSUE TITLE
missing 'version' at /variants[6]/dependencies[0]/requestedCapabilities[0]这个是网不好？终端都设置代理了，build.gradle也加阿里云maven镜像了[捂脸]

### ISSUE THREAD

**Issue by inkcrazy666** [qiuxiang/react-native-amap3d#793]
problem occurred configuring project ':react-native-amap3d'.
> Could not resolve all artifacts for configuration ':react-native-amap3d:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.21.
     Required by:
         project :react-native-amap3d
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.21.
         > Could not parse module metadata https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.7.21/kotlin-gradle-plugin-1.7.21.module
            > missing 'version' at /variants[6]/dependencies[0]/requestedCapabilities[0]
            
![image](https://user-images.githubusercontent.com/130324703/233557603-351147f2-8d8e-41e4-8077-4defcd7cb4ba.png)
![image](https://user-images.githubusercontent.com/130324703/233557623-bf87702e-bfd6-4dc3-b102-8bcddc0fb05d.png)
注释掉一些库也不行
![image](https://user-images.githubusercontent.com/130324703/233557686-0ac6aeac-c05e-4b50-bea8-04f051e08d76.png)
![image](https://user-images.githubusercontent.com/130324703/233557697-b428c4f6-8815-4823-9300-4e0d1d97c0ab.png)

            
![image](https://user-images.githubusercontent.com/130324703/233561581-535a180c-46a2-410c-b79d-f7331ef24254.png)
react-native-amap3d这个库里面我改掉了，镜像地址成功了，运行还是失败的。

**Comment by rao555** [comment]
I have the same problem. Have you solved it？

**Comment by rao555** [comment]
> I have the same problem. Have you solved it？

别用公司网络，用自己手机数据翻墙装

**Comment by inkcrazy666** [comment]
> > I have the same problem. Have you solved it？
> 
> 别用公司网络，用自己手机数据翻墙装

那我七月份再试试，我们又要百度地图换高德地图，上次失败了，再试试😂

**Comment by raochenghui** [comment]
> 

我切回[react-native-amap-geolocation](https://github.com/qiuxiang/react-native-amap-geolocation)这个库了，没用这个

**Comment by inkcrazy666** [comment]
> 

这个库没地图啊，只有定位

**Comment by inkcrazy666** [comment]
```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

def getExt(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

buildscript {
    // ext.kotlin_version = '1.7.21'
    ext.kotlin_version = '1.5.32'
    // ext.kotlin_version = '1.7.0'
    // ext.kotlin_version = '1.6.21' //xhe current Gradle version 6.0.1 is not compatible with the Kotlin Gradle plugin. Please use Gradle 6.1.1 or newer, or the previous version of the Kotlin plugin.
    // ext.kotlin_version = '1.3.72' //x
    repositories {
        maven {url 'https://maven.aliyun.com/repository/google'}
        maven {url 'https://maven.aliyun.com/repository/public'}
        maven {url 'https://maven.aliyun.com/repository/jcenter'}
        // mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

android {
    compileSdkVersion getExt('compileSdkVersion', 33)
    buildToolsVersion getExt('buildToolsVersion', '33.0.0')

    defaultConfig {
        minSdkVersion getExt('minSdkVersion', 21)
        targetSdkVersion getExt('targetSdkVersion', 33)
    }
}

dependencies {
    compileOnly 'com.facebook.react:react-native:+'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.amap.api:3dmap:9.6.0'
}

```
