### ISSUE TITLE
新手入坑RN，请问还不支持定位吗

### ISSUE THREAD

**Issue by hawind** [qiuxiang/react-native-amap3d#80]
请问还不支持定位吗

**Comment by qiuxiang** [comment]
定位是早就支持的 https://github.com/qiuxiang/react-native-amap3d/blob/v0.7.1/components/maps/MapView.js#L169

**Comment by hawind** [comment]
我有时候可能只想获取定位的json，并不想显示地图，怎么用呢

**Comment by qiuxiang** [comment]
目前暂时不打算做定位模块，因为已经有其他库在做这件事，比如 https://github.com/react-native-component/react-native-smart-amap-location

**Comment by hawind** [comment]
确实可以使用react-native-smart-amap-location，谢谢。本来也打算用react-native-smart-amap的，可是地图不显示，折腾人啊
