### ISSUE TITLE
地图同时创建已达上限，请检查地图使用

### ISSUE THREAD

**Issue by wangzhi17** [qiuxiang/react-native-amap3d#804]
在iOS平台上，一个界面使用地图组件，然后频繁从别的界面到使用地图组件的界面，会提示“地图同时创建已达上限，请检查地图使用”，是不是没有做对象销毁操作呢，
react native 版本0.70.7
react native amap3d版本3.2.3

**Comment by 18911131970** [comment]
从地图返回到原生会有不销毁的情况，有解决吗？
如果从地图页返回的是上一个rn，地图可以正常销毁
![image](https://github.com/qiuxiang/react-native-amap3d/assets/12705578/0ef2d60f-ae3b-472d-bfae-1465dbbbf092)

**Comment by CoderBQ** [comment]
我这边是rn页面相互跳转也不释放地图。  3.2.3大佬们怎么解决的啊

**Comment by wangzhi17** [comment]
我后来是通过修改react native screen库版本解决的

**Comment by 18911131970** [comment]
> 我后来是通过修改react native screen库版本解决的

哪个版本呢？

**Comment by Wanghs830** [comment]
> 我后来是通过修改react native screen库版本解决的

同问

**Comment by Wanghs830** [comment]
> 从地图返回到原生会有不销毁的情况，有解决吗？ 如果从地图页返回的是上一个rn，地图可以正常销毁 ![image](https://private-user-images.githubusercontent.com/12705578/262212389-0ef2d60f-ae3b-472d-bfae-1465dbbbf092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMjA5OTUsIm5iZiI6MTczNzAyMDY5NSwicGF0aCI6Ii8xMjcwNTU3OC8yNjIyMTIzODktMGVmMmQ2MGYtYWUzYi00NzJkLWJmYWUtMTQ2NWRiYmJmMDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDA5NDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YmU0MThjMGYwZjI2ODZkODE3NjE2NDUzNmFjYzVmNWMzMWQ3ZWQyMWIxY2Y3NTg0OTU5MjNhNjcwOGYyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9BdNpGDhPJw9Vxw_5vqN2eeKozBgeHazKsF2L4z9POM)

大佬   你解决了么
