### ISSUE TITLE
错误library not found for -lreact-native-amap3

### ISSUE THREAD

**Issue by flyinghawker** [qiuxiang/react-native-amap3d#81]
在xcode 9.0上面，用rn 0.48.1尝试安装，但是出现上面这个错误

**Comment by flyinghawker** [comment]
啊，因为用了pod，所以应该用.xcworkspace打开。但是再次构建，又出现错误
<img width="1130" alt="screen shot 2017-10-02 at 4 39 14 pm" src="https://user-images.githubusercontent.com/13193798/31069798-90cadc96-a723-11e7-911b-e449ddf6469e.png">

**Comment by flyinghawker** [comment]
不过如果react-native run-ios, 依然同开始一样报错library not found for -lreact-native-amap3

**Comment by qiuxiang** [comment]
这个错误看起来是因为这个库编译失败引起的，但为什么 radius 是 readonly 我就不确定了

**Comment by qiuxiang** [comment]
想起来这个问题我好像遇到过，但不记得怎么解决了，你只能自己想办法，顺着现在的错误提示。
