### ISSUE TITLE
安装APP 在安卓系统下第一次打开地图不展示，重启app正常显示

### ISSUE THREAD

**Issue by qimengfeidiao** [qiuxiang/react-native-amap3d#814]
各位大佬 我使用的rn0.63.5  react-native-amap3d版本3.1.3第一次打开应用地图不显示，重进app 地图就正常了，麻烦问一下这种怎么排查和解决，谢谢了

**Comment by whr810012** [comment]
请问解决了吗，我也碰到了这个问题

**Comment by qimengfeidiao** [comment]
地图初始化的问题

**Comment by whr810012** [comment]
有什么办法可以解决吗

**Comment by qimengfeidiao** [comment]
应该是你的写法问题，需要提前初始化地图，你可以在对照文档检查一遍

**Comment by zjjjjjjjjjjd** [comment]
我也是0.64.2,amap是3.1.3,为啥死活空白呢？宽高都是加了的

**Comment by qimengfeidiao** [comment]
AMapSdk.init(
  Platform.select({
    android:xxxx,
    ios: xxxx,
  })
);
<MapView style={{ ...StyleSheet.absoluteFill, height: '75%' }}
          ref={(ref) => {this.mapView = ref }}
          mapType={MapType.Standard}
          compassEnabled={false}
          myLocationEnabled={true}
          rotateGesturesEnabled={false}
          zoomControlsEnabled={false}
          tiltGesturesEnabled={false}
          initialCameraPosition={{
            target: {
              latitude: this.state.latitude,
              longitude: this.state.longitude, //注意数据类型
              // latitude: 39.91095,
              // longitude:116.37296,
            },
            zoom: this.zoom,
          }}
          
          onCameraIdle={(event) => {
           
          }}
        />   目前我这样写是可以正常显示的，你可以参考排查一下
