### ISSUE TITLE
:react-native-amap3d:compileReleaseKotlin 报错

### ISSUE THREAD

**Issue by my4piano** [qiuxiang/react-native-amap3d#82]
RN版本： ^0.44.3
react-native-amap3d版本：^0.7.3

:react-native-amap3d:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-amap3d:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 6.034 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by qiuxiang** [comment]
这些信息没有指出任何问题，我需要更多的信息

**Comment by my4piano** [comment]
\node_modules\react-native-amap3d\android\src\main\java\cn\qiuxiang\react\amap3d\AMap3DPackage.kt: (12, 1): Class 'AMap3DPackage' is not abstra
ct and does not implement abstract member public abstract fun createJSModules(): (Mutable)List<Class<out JavaScriptModule!>!>! defined in com.facebook.react.ReactPackage
:react-native-amap3d:compileReleaseKotlin FAILED

**Comment by qiuxiang** [comment]
RN 低于 0.47，已经不支持了，你只能自己改。

https://github.com/qiuxiang/react-native-amap3d/commit/7972eb4112843554f42c092aa8ab9eefc6852775#diff-956fab68d13a3f80e0d0a5061fc0a725 这里删掉的 createJSModules 方法，自己加回去。

**Comment by dragon-eight** [comment]
@qiuxiang   版主你好，我自己按你给的指示修改了，但还是出现了下面的问题
RN版本： ^0.46.4
react-native-amap3d版本：^0.7.3

\node_modules\react-native-amap3d\android\src\main\java\cn\qiuxiang\react\amap3d\AMap3DPackage.kt: (13, 37): Return type of 'createJSModules' is not a subtype of the return type of the overridden member 'public abstract fun createJSModules(): (Mutable)List<Class<out JavaScriptModule!>!>! defined in com.facebook.react.ReactPackage'
\node_modules\react-native-amap3d\android\src\main\java\cn\qiuxiang\react\amap3d\AMap3DPackage.kt: (13, 52): Unresolved reference: JavaScriptModule
:react-native-amap3d:compileReleaseKotlin FAILED

![2017-12-18_191534](https://user-images.githubusercontent.com/28556227/34103627-5ebc63a4-e428-11e7-9d56-ecd4f53a30ef.png)

**Comment by qiuxiang** [comment]
不支持 RN 0.47 以下版本

**Comment by qiuxiang** [comment]
倒也不是不能用，但要自己改点东西

**Comment by dragon-eight** [comment]
我贴的图中已经将createJSModules 加入了 ，但是并不理想。

**Comment by dragon-eight** [comment]
由于项目问题，暂时不方便更新RN版本。是否还有其他要改动的地方呢，我看那个更新日志并没有找到amap3d/AMap3DPackage.java这个文件

**Comment by qiuxiang** [comment]
原来的版本是支持的，你看看以前的版本

**Comment by HelenChenVIP** [comment]
你好：我也出现这个问题：
* What went wrong:
Execution failed for task ':react-native-amap3d:compileReleaseKotlin'.
> Compilation error. See log for more details
但是我的reactnative 版本是："react-native": {
			"version": "0.49.3",
所以，我想请问下，怎么解决呢？
谢谢！

**Comment by qiuxiang** [comment]
@HelenChenVIP 你这不是同一个问题，你得提供更详细的 error log

**Comment by InitialSugar** [comment]
楼主   我的
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-amap3d": "^0.10.1",
还是会有这个问题
* What went wrong:
Execution failed for task ':react-native-amap3d:compileReleaseKotlin'.
> Internal compiler error. See log for more details
我该怎么解决呢？求解，谢谢楼主大大。

**Comment by qiuxiang** [comment]
@InitialSugar 需要更多信息，你的问题未必与这里有关

**Comment by InitialSugar** [comment]
那楼主我需要给你提供些什么呢

**Comment by qiuxiang** [comment]
就是详细的错误信息，你可能需要 android studio
