### ISSUE TITLE
需要rn最低版本多少

### ISSUE THREAD

**Issue by sharingjingang050241** [qiuxiang/react-native-amap3d#83]
rn：0.33

**Comment by qiuxiang** [comment]
只支持最新的 RN，之所以不支持低版本是因为一些原生接口的改动。我是从 v0.44 开始开发的，就我所知，RN v0.47 有个接口被删掉了，导致无法再兼容之前的版本，但只要把那方法加上，就可以适配 v0.44 ~ v0.47。

至于更低的版本，我没有测试过。

**Comment by sharingjingang050241** [comment]
好的 ，谢谢哦。
