### ISSUE TITLE
运行黑屏

### ISSUE THREAD

**Issue by see-more** [qiuxiang/react-native-amap3d#830]
<code>
"react-native": "0.74.3",
"react-native-amap3d": "^3.2.4"
</code>
代码
![image](https://github.com/qiuxiang/react-native-amap3d/assets/107225647/fe6f3233-eb01-427b-a9fb-46ad951f18a3)
截图
![image](https://github.com/qiuxiang/react-native-amap3d/assets/107225647/dd2f6345-bb55-4201-98c4-e7848b14c19f)

**Comment by Jhh910** [comment]
> ` "react-native": "0.74.3", "react-native-amap3d": "^3.2.4" ` 代码 ![image](https://github.com/qiuxiang/react-native-amap3d/assets/107225647/fe6f3233-eb01-427b-a9fb-46ad951f18a3) 截图 ![image](https://github.com/qiuxiang/react-native-amap3d/assets/107225647/dd2f6345-bb55-4201-98c4-e7848b14c19f)

你好  你解决了嘛  地图黑屏的问题

**Comment by see-more** [comment]
换腾讯地图了

**Comment by Jhh910** [comment]
> 换腾讯地图了

可以分享下链接吗

**Comment by see-more** [comment]
https://lbs.qq.com/location/
