### ISSUE TITLE
iOS debug模式下地图正常，打包的时候编译通不过

### ISSUE THREAD

**Issue by chenKunyang** [qiuxiang/react-native-amap3d#84]
您好，我使用的是amap3d的0.7.1的版本，RN的版本是0.47。iOS配置是采用的cocoapods进行配置的，在项目debug模式下可以正常使用。但是打包的时候编译通不过。
错误信息为：error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by qiuxiang** [comment]
我需要更详细的错误信息

**Comment by chenKunyang** [comment]
不好意思，没有更详细的信息了，打包的时候xocde直接报出clang: error: linker command failed with exit code 1 (use -v to see invocation)。关于错误信息我也一头雾水，debug模式下是可以正常使用了。

**Comment by qiuxiang** [comment]
你怎么打包的？

**Comment by chenKunyang** [comment]
就是走的xcode正常的打包流程，iOS device设备下archive

**Comment by yy0608** [comment]
同样遇到了

**Comment by yy0608** [comment]
解决了吗？

**Comment by qiuxiang** [comment]
我没有可以打包的开发者账号，这个问题没法自己重现，如果能提供具体的错误信息，而不是 `error: linker command failed with exit code 1` 这种相当于什么都没说的错误信息，或许还能提供点意见。

**Comment by MinzhangWei** [comment]
同样遇到这个问题，使用react-native run-ios 没有问题，但打包时候就出现问题。
![9c32f1c8-d4c1-4553-b4f7-862f02797555](https://user-images.githubusercontent.com/4898303/33660012-5a4514e8-dabd-11e7-831d-20d7f74e0de7.png)

**Comment by MinzhangWei** [comment]
下载example的代码，按照readme操作完之后，跑react-native run-ios 可以正常显示，但用xcoce 9.0 中的Product -> Archive 打包时候，出现跟上面类似的问题。如图所示
![632ed432-0790-42fc-8046-ce720b00e929](https://user-images.githubusercontent.com/4898303/33660964-c9399e48-dac0-11e7-94c3-01c410b19e06.png)

**Comment by qiuxiang** [comment]
总算有人提供些有价值的错误信息了，`Undefined symbols` 大概是因为某些库没有引入，尝试改下 Podfile：
```
pod 'React', path: '../node_modules/react-native/', :subspecs => [
  'jschelpers',
  'cxxreact',
]
```
然后重新 `pod install`。

**Comment by MinzhangWei** [comment]
我怀疑是react native 的问题，正在试，有了解决办法分享给大家

**Comment by qiuxiang** [comment]
@MinzhangWei 我说的方法试过了？

**Comment by MinzhangWei** [comment]
@qiuxiang 刚刚验证了，example的ios/Podfile需要更改为：

`
platform :ios, '8.0'

target 'RNAMap3D' do
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'BatchedBridge',
  ]
  pod 'react-native-amap3d', path: '../../ios/'
end
`

**Comment by MinzhangWei** [comment]
react native 在0.45版本以后，如果使用 Cocoapods, 必须更新Podfile ，给其中的 React subspec 添加 ‘BatchedBridge’ 或 ‘CxxBridge’ 的依赖。

**Comment by pentakill666** [comment]
最新的react-native,ios按照readme的podfile这么设置确实会报错，楼上说的太正确了，希望作者可以改一下readme，我今天弄一天，就是这个CxxBridge有问题,改成BatchedBridge就没问题了

**Comment by qiuxiang** [comment]
@pentakill666 有错误信息吗，按理说 `CxxBridge` 应该是可以的

**Comment by pentakill666** [comment]
就是pod install会报错，我现在已经改好了，没法重现了，可能是react-native版本的问题，我现在用的版本是"react-native": "0.49.3"

**Comment by zhaochu0821** [comment]
It's useless for me to add BatchedBridge

**Comment by qiuxiang** [comment]
BatchedBridge 已经废弃了

**Comment by zhaochu0821** [comment]
Where to use what

**Comment by zhaochu0821** [comment]
"react": "16.0.0-alpha.12",
		"react-native": "0.46.3",

**Comment by zhaochu0821** [comment]
platform :ios, '8.0'

target 'RNAMap3D' do
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspaces => [
    
    'jschelpers_legacy',
    'BatchedBridge', 
  
    
  ]
 pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'
  
end

**Comment by zhaochu0821** [comment]
![qq20180614-0](https://user-images.githubusercontent.com/27795580/41405712-fd7cf52a-6ffc-11e8-8aa4-8bb2a6cf4f6a.png)

**Comment by zhaochu0821** [comment]
@qiuxiang What's the solution

**Comment by qiuxiang** [comment]
@zhaochu0821 低版本不再提供支持，自己看 https://facebook.github.io/react-native/docs/0.46/integration-with-existing-apps.html#configuring-cocoapods-dependencies 解决不了我也没办法

**Comment by zhaochu0821** [comment]
@pentakill666  24/5000  
Why use pod ipa to appear white ah after the start page

**Comment by zhaochu0821** [comment]
@pentakill666 [
![835ee13bc62471ada43f63f0e0336059](https://user-images.githubusercontent.com/27795580/41841691-894c122e-789b-11e8-810e-b70517b9c3ad.jpg)

**Comment by zhaochu0821** [comment]
@pentakill666 	
                "react": "16.0.0-beta.5",
		"react-native": "0.49.3",
