### ISSUE TITLE
启用定位后，会出现这个错误，虽然不影响使用，但是大神能看看吗

### ISSUE THREAD

**Issue by xyj0922** [qiuxiang/react-native-amap3d#85]
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err: com.amap.api.col.n3.ih: IO 操作异常 - IOException
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at com.amap.api.col.n3.kl.a(HttpUrlUtil.java:440)
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at com.amap.api.col.n3.kl.a(HttpUrlUtil.java:273)
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at com.amap.api.col.n3.ki.a(BaseNetManager.java:222)
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at com.amap.api.col.n3.lt.a(LocNetManager.java)
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at com.amap.api.col.n3.lk.d(MapNetLocation.java)
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at com.amap.api.col.n3.lk.a(MapNetLocation.java)
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at com.amap.api.col.n3.lj.b(MapLocationService.java)
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at com.amap.api.col.n3.lj$a.handleMessage(MapLocationService.java)
10-16 02:25:04.313 3498-14268/com.dev2assistant W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 02:25:04.314 3498-14268/com.dev2assistant W/System.err:     at android.os.Looper.loop(Looper.java:154)
10-16 02:25:04.314 3498-14268/com.dev2assistant W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by qiuxiang** [comment]
因为我们不知道 SDK 内部的细节，就这些信息不能知道到底发生了什么
