### ISSUE TITLE
升级到最新版本以后，地图显示速度缓慢。操作延迟很大

### ISSUE THREAD

**Issue by blackkey520** [qiuxiang/react-native-amap3d#86]
amap3D版本：0.7.3
RN版本:0.47.2

运行 example 也是一样，在模拟器中，地图显示速度缓慢，操作延迟非常大。

**Comment by qiuxiang** [comment]
是 ios 吧？

**Comment by blackkey520** [comment]
是的。模拟器很慢，但是我刚才连真机试了一下，真机上没有这个问题

**Comment by qiuxiang** [comment]
这是一个已知的 bug，这个 bug 是从 xcode9.0 beta4 开始的，与 opengl 有关，内置的地图应用也是一样的卡。

这里有讨论：https://forums.developer.apple.com/thread/83570?start=45&tstart=0#discussion-262626 。

最简单的解决办法是用最新的 xcode9.1 beta2。

**Comment by blackkey520** [comment]
好的，谢谢
