### ISSUE TITLE
大神，有计划加入导航功能吗？

### ISSUE THREAD

**Issue by xyj0922** [qiuxiang/react-native-amap3d#87]
项目里需要有导航功能，不知道大神们什么时候能加入

**Comment by qiuxiang** [comment]
我是想做导航的，已经简单实现了，这里有个 [Example](https://github.com/qiuxiang/react-native-amap3d/blob/master/example/src/examples/navigation.js)，但 android 有个 bug，导致某些导航控件不显示，我暂时没法解决，所以就搁置了。

**Comment by xyj0922** [comment]
我去试试。。主要是对kotlin不熟悉，在直接修改这个库

**Comment by xyj0922** [comment]
还有你说的，android 上有bug。。是指哪个控件显示不了吗？

**Comment by qiuxiang** [comment]
正常来说应该是这样的：
<img src="https://user-images.githubusercontent.com/1709072/31756280-ce0f629c-b4d5-11e7-9e8b-01891ad60f52.png" width=300>

但实际上是这样：
<img src="https://user-images.githubusercontent.com/1709072/31756289-d5c902f4-b4d5-11e7-9f7a-a0c0eefce4c1.png" width=300>

我用 UI 调试工具发现，控件是存在的，但不知道为什么不显示。现在用的这是魅族手机，切出应用再切回来，不显示的控件就又显示了，但另一台 Nexus 6 就不行。

我只能大概估计是 ReactView 的问题，因为我测试新 Activity 不使用 ReactView 的情况是没问题的。我不是专业的 Android 开发，暂时没有找到突破口，只能以后有空了再慢慢研究 ReactView 以及 Android View 的机制。

**Comment by xyj0922** [comment]
主要是kotlin我不会，如果用的是JAVA还能看看。。一下子转变语言有点麻烦

**Comment by qiuxiang** [comment]
语言我觉得都差不多，选择 kotlin 基本只是个人的喜好，再稍微权衡下是不是可持续，就现在来看，kotlin 是可以作为主力开发语言来用了。

真要解决这个问题，语言不是问题，就算重新用 java 写一个简单的导航封装也就一下子的事。

**Comment by xyj0922** [comment]
就是改起来比较麻烦，重新写也是。。

**Comment by xyj0922** [comment]
建议android 可以通过RN调用原生的Activity进行导航，目前我的项目就这样做的，能解决这个bug。IOS仍然使用了你的组件。

**Comment by xyj0922** [comment]
暂时先用这种方式替代，不过我还是希望大神，能把这个bug完善一下，看看有没有解决方案。顺便加入语音功能。

**Comment by qiuxiang** [comment]
再看

**Comment by 594904020** [comment]
请问大神，目前rn最新版本ios导入后报错了
![image](https://user-images.githubusercontent.com/32348909/32555111-80c79bb2-c461-11e7-97d8-be50b6f3fc50.png)

**Comment by qiuxiang** [comment]
@594904020 #39

**Comment by wq13718048209** [comment]
不是专业的安卓开发都能写这些,羡慕!

**Comment by ys5678** [comment]
你好，可以把导航箭头方向转变加一下吗？现在导航的时候，箭头方向不会跟着人的方向转。

**Comment by qiuxiang** [comment]
暂时不打算更新导航组件，本来最近时间不多，我打算先完善地图组件
