### ISSUE TITLE
安卓开启混淆后编译不通过

### ISSUE THREAD

**Issue by ismjt** [qiuxiang/react-native-amap3d#89]
RN: 0.49.3
OS: windows 10
问题重现：
1.react-native init AMap  
2.安装react-native-amap3d、link 
3.修改代码混淆def enableProguardInReleaseBuilds = true   
4.编译./gradlew build

编译的时候，终端会抛出一堆混淆相关的错误，不开启混淆，编译都没什么问题。
大佬，这个要怎么处理？
尝试按照http://lbs.amap.com/api/android-sdk/guide/create-project/dev-attention#obfuscated-code
这里的说明添加混淆配置，不过也好像是没用

**Comment by qiuxiang** [comment]
我试了，确实会出错，不过这错误我不是很能看懂，只能猜测是出现的 warning 触发了某个异常导致的。只要不出现 warning 就没问题了。最终我加的配置是：
```pro
-keep class com.amap.**{*;}
-keep class com.autonavi.**{*;}
-dontwarn com.amap.**
```

**Comment by ismjt** [comment]
多谢大佬指点！这个代码混淆问题我自己再深入了解看看
