### ISSUE TITLE
我想点击“定位按钮”的时候才得到坐标数据

### ISSUE THREAD

**Issue by my4piano** [qiuxiang/react-native-amap3d#90]
RT，怎么操作?

如果我将 locationInterval 设置为1分钟，那么点击 定位按钮 并不会立即触发，要等到1分钟给你后才会 从 onLocation 中取得。我想点击即取得，不需要间隔。

基于 最新的 react-native-amap3d 和 react native 版本

**Comment by my4piano** [comment]
基于 最新的 react-native-amap3d 和 react native 版本

**Comment by qiuxiang** [comment]
你需要的是 getLocation 方法，我应该说过，ios 是没有定位按钮的。

**Comment by my4piano** [comment]
好吧 
1、能否在地图上自定义按钮？
2、有 getLocation  方法嘛？

**Comment by qiuxiang** [comment]
1. absolute position view 不就可以做到的吗，就像这样：
<p align=center>
  <img src="https://user-images.githubusercontent.com/1709072/31770830-2cbca4cc-b50c-11e7-8312-54288436b4c1.png" width=300>
</p>
2. getLocation 的接口我是想加的，但暂时没时间

如果是只需要一次定位，我会先启用定位，等得到 location 之后再禁用定位，点击定位按钮的时候就 animateTo 定位到的座标。

**Comment by my4piano** [comment]
“就像这样：”？后面还有文字图片？没看见

**Comment by qiuxiang** [comment]
有个图片

**Comment by my4piano** [comment]
你说得对，我采用你的建议了
