### ISSUE TITLE
点击地图获取经纬度

### ISSUE THREAD

**Issue by starsion** [qiuxiang/react-native-amap3d#91]
我想通过点击地图事件获取点击点经纬度，请问下大神有提供接口么，或者有什么解决办法？

**Comment by qiuxiang** [comment]
你不看接口文档的吗，虽然只是注释文档 https://github.com/qiuxiang/react-native-amap3d/blob/v0.7.3/components/maps/MapView.js#L160 。

时间传递的参数在 `event.nativeEvent`。

**Comment by starsion** [comment]
onPress事件我知道，之前这样（nativeEvent）=>传参数了，应该这样（{nativeEvent}）=>，哈哈？

**Comment by qiuxiang** [comment]
对，你自己试不就知道了

**Comment by hsl5315156** [comment]
这里 坐标转换怎么转？比如 转成高德坐标系
