### ISSUE TITLE
坐标转换问题 

### ISSUE THREAD

**Issue by hsl5315156** [qiuxiang/react-native-amap3d#92]
比如硬件设备上传了坐标上过来   但是要转换成高德系 坐标 有方法么

**Comment by starsion** [comment]
你是gps坐标的话，需要自己写算法转火星坐标系，百度上也有

**Comment by hsl5315156** [comment]
@starsion 能给个链接么 因为我也百度找了好久 不懂哪个才适用，谢谢。

**Comment by hsl5315156** [comment]
@starsion  谢谢，能给个链接么  因为我也找了好久  不懂哪个才适用。

**Comment by starsion** [comment]
http://blog.csdn.net/admin_yi/article/details/70160875,试试这个

**Comment by starsion** [comment]
[](http://blog.csdn.net/admin_yi/article/details/70160875)
试试这个

**Comment by starsion** [comment]
[http://blog.csdn.net/admin_yi/article/details/70160875](url)
试试这个

**Comment by hsl5315156** [comment]
@starsion 好的 谢谢 等会试试

**Comment by qiuxiang** [comment]
高德的 Web Service 有提供接口：http://lbs.amap.com/api/webservice/guide/api/convert 。

**Comment by hsl5315156** [comment]
@qiuxiang 好的 谢谢
