### ISSUE TITLE
android真机调试，onLocation事件获取的位置信息都为0

### ISSUE THREAD

**Issue by unionTime** [qiuxiang/react-native-amap3d#93]
一、细节信息：
react-native 0.48.3
react-native-amap3d: "^0.7.0"
二、问题描述：
我是在使用onLocation事件获取实时位置（已开启locationEnabled），在ios模拟器下运行时，可以获取经纬度和速度数据，而且与模拟器设置的模拟位置数据一致。当我用android真机调试的时候，返回的经纬度、速度数据都是为0 （onLocation每次触发都是一样的结果）
有这个问题吗，请问我应该怎么样解决！谢谢～

**Comment by qiuxiang** [comment]
确定高德 key 配置正确？

**Comment by unionTime** [comment]
@qiuxiang 嗯嗯，应该正确。其它的地图显示，点击获取位置等都可以成功的。我还是添代码，你看看：
`<meta-data
      android:name="com.amap.api.v2.apikey"
      android:value="我的密钥"/>`
放置在AndroidManifest.XML文件下 <manifest>标签下的<application>标签下

这么一说，不是大众问题。这个有点尴尬，难道没有权限吗，数据都是0

**Comment by qiuxiang** [comment]
你要看看 android logcat，最好用 android-studio，如果 key 不正确的话，会有 error 的。

**Comment by my4piano** [comment]
![tim 20171022175544](https://user-images.githubusercontent.com/17940455/31860759-3fdbfe0c-b752-11e7-8699-a04b9c268815.png)
点击SEND后 才不会是 0，但是过几秒后又变为零了，而且坐标会自动变

**Comment by my4piano** [comment]
链接: https://pan.baidu.com/s/1mixcyaW 密码: bf3p

**Comment by qiuxiang** [comment]
@my4piano 基本上可以认为是 android 模拟器的行为。
