### ISSUE TITLE
地图不显示，与wix的react-native-navigation不兼容

### ISSUE THREAD

**Issue by laiyifeng77** [qiuxiang/react-native-amap3d#94]
进行问题反馈之前：
  - RN 版本: 0.47.1
  - android平台
  - 运行时问题

描述：
使用wix的react-native-navigation作为APP的router，在使用amap3d的时候，配置完成，在A页面显示地图，使用react-native-navigation提供的跳转页面的api（push），进行页面跳转到B，此时back返回到A页面，A页面地图空白不显示；

可能原因：
没有处理好amap的生命周期，因为react-native-navigation处理每个rn页面的时候处理方式不一样，可能会和amap的生命周期有关联，如果没有很好的处理生命周期的问题，那么就可能出现地图不绘制的问题。

希望作者关注一下这个问题，特别是与地图生命周期相关的问题。

**Comment by laiyifeng77** [comment]
进行问题反馈之前：
  - RN 版本: 0.47.1
  - android平台
  - 运行时问题

描述：
使用wix的react-native-navigation作为APP的router，在使用amap3d的时候，配置完成，在A页面显示地图，使用react-native-navigation提供的跳转页面的api（push），进行页面跳转到B，此时back返回到A页面，A页面地图空白不显示；

可能原因：
没有处理好amap的生命周期，因为react-native-navigation处理每个rn页面的时候处理方式不一样，可能会和amap的生命周期有关联，如果没有很好的处理生命周期的问题，那么就可能出现地图不绘制的问题。

希望作者关注一下这个问题，特别是与地图生命周期相关的问题。

**Comment by qiuxiang** [comment]
最好能提供一个 demo
