### ISSUE TITLE
ios release 打包，启动应用空白

### ISSUE THREAD

**Issue by 563803119** [qiuxiang/react-native-amap3d#97]
真机调试，debug调试都正常显示，打包之后安装应用到手机上，可以看到启动页，之后显示空白，不添加react-native-amap3d 打包可以正常显示运行。
没有任何报错信息。

react-native 0.47.2
react-native-amap3d 0.7.3  （pod install 安装）
xcode 9.0.1

请问这是什么问题，是不是哪里配置问题？

**Comment by qiuxiang** [comment]
错误日志呢？

**Comment by 563803119** [comment]
没有呀

**Comment by qiuxiang** [comment]
不晓得

**Comment by xuepx** [comment]
是不是mapview的高度宽度为0

**Comment by qiuxiang** [comment]
#84
