### ISSUE TITLE
我想问一个题外话 你在开发组件的时候怎么调试原生的代码

### ISSUE THREAD

**Issue by jsshizhan** [qiuxiang/react-native-amap3d#99]
谢谢 大神

**Comment by qiuxiang** [comment]
简单来说是用 `UIManager.dispatchViewManagerCommand`，这个项目调用原生方法的代码在这里：

https://github.com/qiuxiang/react-native-amap3d/blob/4f11c531abb0c1a84f37d1e920a08f3b30f0c2d4/components/BaseComponent.js#L17

我有写过一篇关于这一主题的文章：[React Native 原生组件封装：js 调用原生组件方法](http://www.jianshu.com/p/b3351cf4ad02)。

**Comment by jsshizhan** [comment]
调用我知道一些，但是怎么DEBUG原生代码

**Comment by qiuxiang** [comment]
原来是调试。。看成调用。。

调试的话肯定就用 android-studio。

**Comment by qiuxiang** [comment]
iOS 用 xcode，因为是原生代码，原生该怎么调试就怎么调试，这没什么好说的。

**Comment by jsshizhan** [comment]
android studio启动react native项目是没办法加载js的，页面都没有怎么调试啊

**Comment by qiuxiang** [comment]
android-studio 启动 react-native 和一般的启动有什么区别？如果你的意思不依赖一个完整的 RN App，直接就像运行组件项目，那你只能写测试，在测试里调试。
